import { useId, useLayoutEffect, useRef, useState, type ReactNode, type RefObject } from 'react'
import { useClientPreferences } from '../client-preferences'
import { accountActivityText } from '../client-account-activity-copy'
import { accountPlanText } from '../client-account-plan-copy'
import { billingText } from '../client-billing-copy'
import { clientTerminalText } from '../client-terminal-copy'
import type { AccountAlertsFilter, AccountAlertsPresentation, AccountBotPresentation, AccountPeriodicPresentation, AccountPlanPresentation, AccountPresentationActions, AccountReviewPresentation, AccountViewAction, AccountViewHero, AccountViewMetric, AccountViewRow } from '../client-account-presentation'
import '../client-account-activity.css'
import '../client-user-strategy.css'

import { ClientAccountIcon as Icon } from './ClientAccountIcon'
function Badge({ children, tone = '' }: { children?: ReactNode; tone?: string }) { return children ? <span className={`nfx-badge ${tone}`}>{children}</span> : null }
const labels = {
  failed: ['요청을 완료하지 못했어요. 다시 시도해 주세요.', 'Could not complete the request. Please try again.', 'リクエストを完了できませんでした。再試行してください。', '未能完成请求，请重试。', '未能完成請求，請重試。', 'No se pudo completar la solicitud. Inténtalo de nuevo.', 'La demande a échoué. Réessayez.'],
  empty: ['제공된 기록이 없습니다.', 'No records supplied.', '提供された記録はありません。', '没有提供记录。', '沒有提供記錄。', 'No hay registros proporcionados.', 'Aucun enregistrement fourni.'],
  returns: ['검증 수익률', 'Validation return', '検証リターン', '验证收益率', '驗證收益率', 'Rentabilidad validada', 'Rendement validé'],
  drawdown: ['최대 낙폭 (MDD)', 'Maximum drawdown (MDD)', '最大ドローダウン (MDD)', '最大回撤 (MDD)', '最大回撤 (MDD)', 'Caída máxima (MDD)', 'Drawdown maximal (MDD)'],
  equity: ['검증 수익 곡선', 'Validation equity curve', '検証資産曲線', '验证收益曲线', '驗證收益曲線', 'Curva de capital validada', 'Courbe de capital validée'],
  environment: ['전략 실행 환경', 'Strategy execution environment', '戦略実行環境', '策略执行环境', '策略執行環境', 'Entorno de ejecución', "Environnement d’exécution"],
  log: ['AI 행동 로그', 'AI activity log', 'AI行動ログ', 'AI 行为日志', 'AI 行為日誌', 'Registro de actividad de IA', "Journal d’activité IA"],
  fillsOnly: ['체결만', 'Fills only', '約定のみ', '仅成交', '僅成交', 'Solo ejecuciones', 'Exécutions uniquement'],
  older: ['이전 14개 보기', 'Show 14 older records', '以前の14件を表示', '查看前14条', '查看前14筆', 'Ver 14 registros anteriores', 'Voir 14 enregistrements précédents'],
} as const
function useCopy() {
  const { language } = useClientPreferences()
  const column = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const
  return { language, local: (key: keyof typeof labels) => labels[key][column[language]], t: (key: Parameters<typeof accountActivityText>[1]) => accountActivityText(language, key), p: (key: Parameters<typeof accountPlanText>[1]) => accountPlanText(language, key) }
}
function Empty({ known = false }: { known?: boolean }) { const { p, local } = useCopy(); return <div className="nfx-empty" role="status"><div className="nfx-eicon"><Icon /></div><div className="nfx-etit">{known ? local('empty') : p('unavailable')}</div></div> }
function Frame({ children, bot = false }: { children: ReactNode; bot?: boolean }) { const { language } = useCopy(); return <div className={`client-account-activity${bot ? ' client-user-strategy' : ''}`} lang={language}><div className="nfx-page"><div className="nfx-glow" />{children}</div></div> }
function useDelivery() {
  const [pending, setPending] = useState(false), [failed, setFailed] = useState(false)
  const lock = useRef(false), alive = useRef(false)
  useLayoutEffect(() => { alive.current = true; return () => { alive.current = false } }, [])
  const invoke = async (action: (() => void | Promise<void>) | undefined) => {
    if (!action || lock.current || !alive.current) return
    lock.current = true; setPending(true); setFailed(false)
    try { await action() } catch { if (alive.current) setFailed(true) }
    finally { lock.current = false; if (alive.current) setPending(false) }
  }
  return { pending, failed, invoke, isCurrent: () => alive.current }
}
type Delivery = ReturnType<typeof useDelivery>
function ErrorNotice({ delivery }: { delivery: Delivery }) { const { local } = useCopy(); return delivery.failed ? <p role="alert" className="user-error">{local('failed')}</p> : null }
type Navigation = Pick<AccountPresentationActions, 'onNavigate' | 'canNavigate'>
function routeAvailable(callbacks: Navigation, route: string) { return !!callbacks.onNavigate && callbacks.canNavigate?.(route) !== false }
function navigate(callbacks: Navigation, route: string) { if (routeAvailable(callbacks, route)) callbacks.onNavigate?.(route) }
function Action({ action, callbacks, delivery }: { action: AccountViewAction; callbacks: AccountPresentationActions; delivery: Delivery }) {
  const callback = action.route ? routeAvailable(callbacks, action.route) ? (() => navigate(callbacks, action.route!)) : undefined : callbacks.onAction && callbacks.isActionAvailable?.(action.id) !== false ? (() => callbacks.onAction!(action.id)) : undefined
  return <button type="button" className={`nfx-btn ${action.tone ?? 'out'}`} disabled={delivery.pending || !callback} onClick={() => void delivery.invoke(callback)}>{action.label}</button>
}
function Actions({ actions, callbacks, delivery }: { actions: readonly AccountViewAction[]; callbacks: AccountPresentationActions; delivery: Delivery }) { return <div className="nfx-cta">{actions.map(action => <Action key={action.id} action={action} callbacks={callbacks} delivery={delivery} />)}</div> }
function Rows({ rows, callbacks }: { rows: readonly AccountViewRow[] | null; callbacks: Navigation }) {
  if (rows === null || !rows.length) return <Empty known={rows !== null} />
  return <div className="nfx-rows">{rows.map((row, index) => {
    const content = <><span className="nfx-rl"><span className={`nfx-ric ${row.tone === 'gain' ? 'gg' : row.tone === 'loss' ? 'gr' : ''}`}><Icon name={row.icon} /></span><span className="nfx-rtx"><span className="nfx-rlb">{row.label}</span>{row.description && <span className="nfx-rds">{row.description}</span>}</span></span><span className="nfx-rr"><span className={`nfx-rval ${row.tone ?? ''}`}>{row.value}</span>{row.route && <svg aria-hidden="true" className="nfx-arrow" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m9 18 6-6-6-6" /></svg>}</span></>
    const className = `nfx-row nfx-stag s${Math.min(index + 1, 8)}${row.route ? ' lk' : ''}`
    return row.route ? <button type="button" className={className} key={row.id} disabled={!routeAvailable(callbacks, row.route)} onClick={() => navigate(callbacks, row.route!)}>{content}</button> : <div className={className} key={row.id}>{content}</div>
  })}</div>
}
function HeroBody({ hero }: { hero: AccountViewHero }) { return <div><div className="nfx-hero-label">{hero.label}</div><div className={`nfx-hero ${hero.tone === 'gain' ? 'cg' : hero.tone === 'loss' ? 'cr' : ''}`}><span>{hero.value}</span>{hero.unit && <span className="nfx-hero-sub"> {hero.unit}</span>}</div>{hero.description && <div className="nfx-hero-desc">{hero.description}</div>}</div> }
function Metrics({ metrics }: { metrics: readonly AccountViewMetric[] }) { return <>{metrics.map((metric, index) => <div className="nfx-mbox" key={index}><span className="nfx-mtit">{metric.label}</span><span className={`nfx-mval nfx-text-value ${metric.tone ?? ''}`}>{metric.value}</span></div>)}</> }
const percent = (value: number) => Number.isFinite(value) ? Math.max(0, Math.min(100, value)) : 0
function Ring({ value, label, score = false }: { value: number; label: string; score?: boolean }) {
  const circumference = score ? 251.3 : 163.4
  return <div className={score ? 'nfxb-ring' : 'nfxr-ring'}><svg viewBox={score ? '0 0 100 100' : '0 0 60 60'} aria-hidden="true"><circle className="bg" cx={score ? 50 : 30} cy={score ? 50 : 30} r={score ? 40 : 26} /><circle className="fg" cx={score ? 50 : 30} cy={score ? 50 : 30} r={score ? 40 : 26} style={{ strokeDashoffset: circumference * (1 - percent(value) / 100) }} /></svg><span className="val">{label}</span></div>
}
function Breadcrumb({ title, callbacks }: { title: string; callbacks: Navigation }) { const { t } = useCopy(); return <nav className="nfx-bc" aria-label={t('location')}><button type="button" className="account-link lk" disabled={!routeAvailable(callbacks, '#/trade')} onClick={() => navigate(callbacks, '#/trade')}>{t('myTrading')}</button><span>/</span><span>{title}</span></nav> }

export function ClientAccountPlanPresentation({ view, tab, headingRef, ...callbacks }: AccountPresentationActions & { view: AccountPlanPresentation; tab: 'plan' | 'rebates' | 'alerts'; headingRef?: RefObject<HTMLHeadingElement | null> }) {
  const { p, language } = useCopy(), delivery = useDelivery(), status = view.status, rebate = view.rebates
  return <Frame><header className="nfx-head"><h1 ref={headingRef} tabIndex={-1} className="nfx-title">{view.title}</h1><div className="nfx-sub">{p('description')}</div><nav className="nfx-tabs" aria-label={p('navigation')}>{(['plan', 'rebates', 'alerts'] as const).map(key => <button type="button" key={key} className={`nfx-tab${tab === key ? ' on' : ''}`} aria-current={tab === key ? 'page' : undefined} disabled={!routeAvailable(callbacks, `#/plan${key === 'plan' ? '' : `/${key}`}`)} onClick={() => navigate(callbacks, `#/plan${key === 'plan' ? '' : `/${key}`}`)}>{p(key)}</button>)}</nav></header>
    {view.sourceLabel && <p className="nfx-foot" data-plan-source><Icon name="doc" /><span>{view.sourceLabel}</span></p>}
    {tab === 'plan' ? <div className="nfx-grid2"><section className="nfx-card nfx-card-hero nfx-glowonce"><div className="nfx-chead"><span className="nfx-ctitle">{status?.hero.title ?? p('level')}</span><Badge tone={status?.badgeTone}>{status?.hero.badge}</Badge></div>{status ? <><HeroBody hero={status.hero} /><div className="nfx-gauge">{status.gauge ? <><div className="nfx-gtrack"><div className={`nfx-gfill ${status.gauge.style ?? ''}`} style={{ width: `${percent(status.gauge.percent)}%` }} /></div><div className="nfx-glabels"><span>{status.gauge.left}</span><span>{status.gauge.right}</span></div></> : <Empty />}</div><Actions actions={status.actions} callbacks={callbacks} delivery={delivery} />{status.footer && <div className="nfx-foot"><Icon name="doc" /><span>{status.footer}</span></div>}</> : <Empty />}</section><section className="nfx-card"><div className="nfx-sechead"><h2 className="nfx-sectit">{p('details')}</h2></div><Rows rows={status?.details ?? null} callbacks={callbacks} /></section></div>
      : tab === 'rebates' ? <div className="nfx-grid2"><section className="nfx-card nfx-card-hero"><div className="nfx-chead"><span className="nfx-ctitle">{rebate?.hero.title ?? p('rebateTotal')}<Badge>{rebate?.hero.badge}</Badge></span></div>{rebate ? <><HeroBody hero={rebate.hero} /><div className="nfx-metrics"><Metrics metrics={rebate.metrics} /></div><Actions actions={rebate.actions} callbacks={callbacks} delivery={delivery} /></> : <Empty />}</section><section className="nfx-card"><div className="nfx-sechead"><h2 className="nfx-sectit">{p('rebateHistory')}</h2><Badge>{rebate?.historyLabel}</Badge></div><Rows rows={rebate?.history ?? null} callbacks={callbacks} /></section></div>
        : <div className="nfx-grid2 nfx-preferences" lang={language}>{view.preferences === null ? <>{['notificationKinds', 'channels'].map(key => <section className="nfx-card" key={key}><h2 className="nfx-sectit">{p(key as 'channels' | 'notificationKinds')}</h2><Empty /></section>)}</> : view.preferences.map(group => <section className="nfx-card" key={group.id}><div className="nfx-sechead"><h2 className="nfx-sectit">{group.title}</h2><Badge>{group.badge}</Badge></div><div className="nfx-rows">{group.rows.map((row, index) => <div className={`nfx-row nfx-stag s${Math.min(index + 1, 8)}`} key={row.id}><span className="nfx-rl"><span className="nfx-ric"><Icon name={row.icon} /></span><span className="nfx-rtx"><span className="nfx-rlb">{row.label}</span><span className="nfx-rds">{row.description}</span></span></span><span className="nfx-rr"><Badge>{row.badge}</Badge>{row.checked === null ? <span>{p('unavailable')}</span> : <label className="nfx-sw"><input type="checkbox" role="switch" aria-label={row.label} checked={row.checked} disabled={row.disabled || delivery.pending || !callbacks.onPreference} onChange={event => { const checked = event.target.checked; void delivery.invoke(() => callbacks.onPreference?.(row.id, checked)) }} /><span className={row.switchTone === 'green' ? 'nfx-slider grn' : 'nfx-slider'} /></label>}</span></div>)}</div>{group.footer && <div className="nfx-foot"><Icon /><span>{group.footer}</span></div>}</section>)}</div>}
    <ErrorNotice delivery={delivery} />
  </Frame>
}

export function ClientAccountReviewPresentation({ view, ...callbacks }: AccountPresentationActions & { view: AccountReviewPresentation }) {
  const { t } = useCopy(), delivery = useDelivery()
  return <Frame><Breadcrumb title={t('review')} callbacks={callbacks} /><section className={`nfx-card nfx-card-hero nfxr-hero ${view.hero.tone === 'gain' ? 'win' : view.hero.tone === 'loss' ? 'loss' : ''}`}><div className="nfx-chead"><span className="nfx-ctitle">{view.hero.title}<Badge>{view.hero.badge}</Badge></span>{view.reportAction && <Action action={view.reportAction} callbacks={callbacks} delivery={delivery} />}</div><HeroBody hero={view.hero} /><div className="nfxr-chiprow">{view.chips.map((chip, index) => <span className="nfxr-chip" key={index}>{chip.label} <b className={chip.tone}>{chip.value}</b></span>)}</div><p className="nfx-foot">{view.sourceLabel}</p></section><section className="nfx-card"><div className="nfx-sechead"><h2 className="nfx-sectit">{t('causality')}</h2><Badge>{view.evidenceLabel}</Badge></div><div className="nfxr-steps">{view.causes === null || !view.causes.length ? <Empty known={view.causes !== null} /> : view.causes.map((cause, index) => <div className={`nfxr-step nfx-stag s${Math.min(index + 1, 8)}`} key={cause.id}><div className={`nfxr-sic ${cause.tone ?? ''}`}><Icon name={cause.icon} /></div><div className="account-step-body"><div><span className="nfxr-stag">{String(index + 1).padStart(2, '0')} {cause.tag}</span><span className="nfxr-stit">{cause.title}</span></div><div className="nfxr-sbody">{cause.text}</div></div></div>)}</div></section><Actions actions={view.actions} callbacks={callbacks} delivery={delivery} /><ErrorNotice delivery={delivery} /></Frame>
}
export function ClientAccountPeriodicPresentation({ view, ...callbacks }: AccountPresentationActions & { view: AccountPeriodicPresentation }) {
  const { t } = useCopy(), delivery = useDelivery()
  return <Frame><Breadcrumb title={view.hero.title} callbacks={callbacks} /><section className={`nfx-card nfx-card-hero nfxr-hero ${view.hero.tone === 'gain' ? 'win' : view.hero.tone === 'loss' ? 'loss' : ''}`}><div className="nfx-chead"><span className="nfx-ctitle">{view.hero.title}<Badge>{view.hero.badge}</Badge></span><Badge>{view.dateLabel}</Badge></div><HeroBody hero={view.hero} /><div className="nfxr-stats">{view.ring ? <Ring value={view.ring.percent} label={view.ring.label} /> : <Empty />}<Metrics metrics={view.metrics} /></div><p className="nfx-foot">{view.sourceLabel}</p></section><section className="nfx-card"><div className="nfx-sechead"><h2 className="nfx-sectit">{t('periodReviews')}</h2><Badge>{view.reviewsLabel}</Badge></div><Rows rows={view.reviews} callbacks={callbacks} /></section><Actions actions={view.actions} callbacks={callbacks} delivery={delivery} /><ErrorNotice delivery={delivery} /></Frame>
}

export function ClientAccountAlertsPresentation({ view, onRead, onReadAll, onNavigate, filter: suppliedFilter, onFilterChange }: { view: AccountAlertsPresentation; onRead?: (id: string) => void | Promise<void>; onReadAll?: () => void | Promise<void>; onNavigate?: (route: string) => void; filter?: AccountAlertsFilter; onFilterChange?: (filter: AccountAlertsFilter) => void }) {
  const { t, language } = useCopy(), delivery = useDelivery(), [localFilter, setLocalFilter] = useState<AccountAlertsFilter>('all')
  const filter = suppliedFilter ?? localFilter
  const setFilter = (next: AccountAlertsFilter) => { setLocalFilter(next); onFilterChange?.(next) }
  const tabs = [['all', 'all'], ['pos', 'position'], ['bot', 'strategy'], ['review', 'review'], ['rebate', 'rebates']] as const
  const matches = (type: string, tab: string) => tab === 'all' || tab === type || tab === 'pos' && type === 'bot'
  const unread = view.rows?.filter(row => !row.read).length
  const rows = view.rows?.filter(row => matches(row.type, filter))
  const tags = { credit: 'credits', pos: 'position', bot: 'strategy', review: 'review', rebate: 'rebates', report: 'reports' } as const
  return <div className="client-account-activity" lang={language}><div className="nfx-sechead"><h2 className="nfx-sectit">{t('alerts')} {!!unread && <Badge tone="blue">{accountActivityText(language, 'unread', { count: unread.toLocaleString(language) })}</Badge>}</h2><div className="account-alert-actions"><button type="button" className="nfxu-later" disabled={!onReadAll || delivery.pending || !unread} onClick={() => void delivery.invoke(onReadAll)}>{t('readAll')}</button><button type="button" className="nfx-btn out" disabled={!onNavigate} onClick={() => onNavigate?.('#/plan/alerts')}>{t('preferences')}</button></div></div><div className="nfxh-fchips" role="group" aria-label={t('categories')}>{tabs.map(([key, label]) => { const count = view.rows?.filter(row => matches(row.type, key)).length; return <button type="button" key={key} className={`nfxh-fchip${filter === key ? ' on' : ''}`} aria-pressed={filter === key} onClick={() => setFilter(key)}>{t(label)}{!!count && <span className="c2">{count.toLocaleString(language)}</span>}</button> })}</div><div className="nfxh-alerts-list">{rows === undefined || !rows.length ? <Empty known={rows !== undefined} /> : rows.map(row => <button type="button" key={row.id} className={`nf-item${row.read ? ' read' : ''}`} disabled={!onRead || delivery.pending} onClick={() => void delivery.invoke(async () => { await onRead?.(row.id); if (row.route && delivery.isCurrent()) onNavigate?.(row.route) })}><span className="ic" /><span className="account-sr">{t(row.read ? 'read' : 'notRead')} </span><span className="bx"><span className="tt"><span className="account-alert-title"><span className={`tg t-${row.type}`}>{row.type === 'bill' ? billingText(language, 'billingTag') : t(tags[row.type])}</span>{row.title}</span>{row.move && <span className={`mv ${row.move.tone === 'gain' ? 'up' : row.move.tone === 'loss' ? 'dn' : ''}`}>{row.move.label}</span>}</span>{row.body && <span className="bd2">{row.body}</span>}<span className="tm num">{row.timeLabel}</span></span></button>)}</div><ErrorNotice delivery={delivery} /></div>
}

function Equity({ view }: { view: AccountBotPresentation['equity'] }) {
  const id = useId().replace(/:/g, ''), { local } = useCopy()
  const points = view?.points ?? []
  const valid = points.length > 1 && points.every(point => Number.isFinite(point.value))
  // Only SVG coordinates are derived. Return, drawdown, win rate and labels are
  // never calculated from the equity points or inferred from their sign.
  const low = valid ? Math.min(...points.map(point => point.value)) : 0
  const high = valid ? Math.max(...points.map(point => point.value)) : 0
  const path = valid ? points.map((point, index) => `${index ? 'L' : 'M'} ${index / (points.length - 1) * 800} ${high === low ? 70 : 130 - (point.value - low) / (high - low) * 115}`).join(' ') : ''
  const color = view?.tone === 'loss' ? '#e0604b' : '#4ec08d'
  return <section className="nfxb-chart"><div className="nfxb-chd"><h2 className="nfxb-ctit">{view?.title ?? local('equity')}<span className="nfxb-cbadge">{view?.sourceLabel}</span></h2><div className="nfxb-cstats">{view?.description}</div></div>{valid ? <div className="nfxb-spark"><svg role="img" aria-label={view!.description} viewBox="0 0 800 140" preserveAspectRatio="none"><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity=".32" /><stop offset="60%" stopColor={color} stopOpacity=".08" /><stop offset="100%" stopColor={color} stopOpacity="0" /></linearGradient></defs>{[20, 70, 120].map(y => <line className="nfxb-grid" key={y} x1="0" y1={y} x2="800" y2={y} />)}<path className="nfxb-area" fill={`url(#${id})`} d={`${path} L800 140 L0 140 Z`} /><path className={`nfxb-line${view?.tone === 'loss' ? ' dn' : ''}`} d={path} /></svg></div> : <Empty known={view !== null && points.length === 0} />}</section>
}
function BotMetric({ metric, title }: { metric: AccountViewMetric | null; title: string }) { return <div className="nfxb-mcard"><div className="nfxb-mhd"><span className="nfxb-mlb">{metric?.label ?? title}</span><Badge>{metric?.badge}</Badge></div>{metric ? <><div><div className={`nfxb-bigval ${metric.tone === 'gain' ? 'up' : metric.tone === 'loss' ? 'dn' : ''}`}>{metric.value}</div><div className="nfxb-subtx">{metric.description}</div></div>{metric.barPercent !== undefined && <div className="nfxb-rbar"><i style={{ width: `${percent(metric.barPercent)}%`, background: metric.tone === 'loss' ? 'var(--gr)' : 'var(--gg)' }} /></div>}</> : <Empty />}</div> }
function BotLog({ log }: { log: AccountBotPresentation['log'] }) {
  const { local, t } = useCopy(), [filter, setFilter] = useState<'all' | 'fills'>('all'), [limit, setLimit] = useState(14)
  const anchor = useRef<HTMLButtonElement>(null), previousTop = useRef<number | null>(null)
  const rows = log?.rows.filter(row => filter === 'all' || row.type !== 'watch'), shown = rows?.slice(-limit)
  useLayoutEffect(() => { if (previousTop.current !== null && anchor.current) { const delta = anchor.current.getBoundingClientRect().top - previousTop.current; let parent = anchor.current.parentElement; while (parent && !/(auto|scroll|overlay)/.test(getComputedStyle(parent).overflowY)) parent = parent.parentElement; if (parent) parent.scrollTop += delta; else window.scrollBy(0, delta); previousTop.current = null } }, [limit])
  return <section className="nfxb-scard user-log"><div className="nfx-sechead"><h2 className="nfx-sectit">{local('log')}</h2><Badge>{log?.sourceLabel}</Badge></div><div className="nfxl-sum">{log?.summary.map((item, index) => <span key={index}>{item.label} <b>{item.value}</b></span>)}</div><div className="nfxh-fchips" role="group" aria-label={local('log')}>{(['all', 'fills'] as const).map(key => <button type="button" className={`nfxh-fchip${filter === key ? ' on' : ''}`} aria-pressed={filter === key} key={key} onClick={() => { setFilter(key); setLimit(14) }}>{key === 'all' ? t('all') : local('fillsOnly')}</button>)}</div><div className="nfxl-tl">{shown === undefined || !shown.length ? <Empty known={shown !== undefined} /> : shown.map(row => <div className={`nfxl-ev ${row.type}`} key={row.id}><time className="tm2">{row.timeLabel}</time><span className="node"><span className="dt" /><span className="ln" /></span><div className="card"><span className="tp2">{row.tag}</span>{row.text}</div></div>)}</div><button type="button" className="nfx-btn out user-log-more" ref={anchor} disabled={!rows || rows.length <= limit} onClick={() => { previousTop.current = anchor.current?.getBoundingClientRect().top ?? null; setLimit(limit + 14) }}>{local('older')}</button></section>
}
export function ClientAccountBotPresentation({ view, ...callbacks }: AccountPresentationActions & { view: AccountBotPresentation }) {
  const { local, t, language } = useCopy(), delivery = useDelivery()
  return <Frame bot><Breadcrumb title={view.title} callbacks={callbacks} /><section className="nfxb-hero"><div className="nfxb-toprow"><div className="user-min"><div className="nfxb-tline"><h1 className="nfxb-title">{view.title}</h1><span className={`nfxb-st ${view.environment.key === 'off' ? 'stop' : view.environment.key ?? ''}`}><span className="nfx-dot" />{view.environment.label}</span><Badge>{view.sourceLabel}</Badge></div>{view.origin && <span className="nfxb-origin">{view.origin}</span>}</div><div className="nfxb-actions" aria-busy={delivery.pending}>{view.actions.map(action => <Action key={action.id} action={action} callbacks={callbacks} delivery={delivery} />)}</div></div>{view.notice && <div className="nfxb-notice"><Icon /><span>{view.notice}</span></div>}<ErrorNotice delivery={delivery} /></section><section className="nfxb-mgrid"><div className="nfxb-mcard score"><div className="nfxb-mhd"><span className="nfxb-mlb">TETH Score</span><span className="nfxb-chipp">{view.score?.badge}</span></div>{view.score ? <div className="nfxb-scorebody"><Ring score value={view.score.percent} label={view.score.value} /><div className="nfxb-smeta"><span className="nfxb-srank">{view.score.rank}</span><span className="nfxb-sdesc">{view.score.description}</span></div></div> : <Empty />}</div><BotMetric metric={view.returnMetric} title={local('returns')} /><BotMetric metric={view.drawdownMetric} title={local('drawdown')} /></section><Equity view={view.equity} /><div className="nfxb-grid2"><section className="nfxb-scard"><div className="nfx-sechead"><h2 className="nfx-sectit">{clientTerminalText(language, 'orders')}</h2><span className="nfxb-fee">{view.ordersLabel}</span></div><Rows rows={view.orders} callbacks={callbacks} /></section><div className="user-side"><section className="nfxb-scard"><div className="nfx-sechead"><h2 className="nfx-sectit">{t('position')}</h2><span className="nfxb-pill-amber">{view.position?.badge}</span></div><div className="nfxb-posbox">{view.position ? <><div><div className="nfxb-postit">{view.position.title}</div><div className="nfxb-posdesc">{view.position.description}</div></div>{view.position.checks.map((check, index) => <div className="nfxb-check" key={index}><span className="d" /><span>{check}</span></div>)}</> : <Empty />}</div></section><section className="nfxb-scard"><div className="nfx-sechead"><h2 className="nfx-sectit">{local('environment')}</h2></div><div className="nfxb-specs">{view.execution === null ? <Empty /> : view.execution.map(item => <div className="nfxb-spec" key={item.id}><span className="k">{item.label}</span><span className="v">{item.value}</span></div>)}</div></section></div></div><BotLog log={view.log} /></Frame>
}
