import { expect, test, type Page } from '@playwright/test'

async function openPlan(page: Page) {
  await page.clock.install()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const input = page.locator('.client-home-content textarea')
  await input.fill('비트코인 과매도 반등 전략을 검증하고 싶어요')
  await input.press('Enter')
  await page.clock.fastForward(12_000)
  for (const choice of ['1시간', '−3% (표준)', '익절 +8% 설정']) {
    await page.getByRole('button', { name: choice, exact: true }).click()
    await page.clock.fastForward(12_000)
  }
  await page.getByRole('button', { name: /Research Plan.*연구 계획 확인/ }).click()
  await expect(page.getByRole('heading', { name: 'Research Plan', exact: true })).toBeVisible()
}
async function artifact(page: Page, title: string) {
  const trigger = page.getByRole('button', { name: 'Artifacts 열기', exact: true })
  if (await trigger.isVisible()) await trigger.click()
  await page.locator('.rw-artifact').filter({ hasText: new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(검토 필요)?$`) }).click()
}

test('95초 연구에서 문서가 순차 생성되고 완료 후 최종 보고서로 이어진다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openPlan(page)
  await expect(page.locator('.rw-artifact')).toHaveCount(1)
  await expect(page.locator('.rw-team')).toHaveCount(7)
  await expect(page.locator('.rw-team small')).toHaveText(Array(7).fill('대기'))
  await expect(page.locator('.rw-artifact svg path').first()).toHaveAttribute('d', 'M6 3h8l5 5v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await expect(page.locator('.rw-title')).toContainText('연구 진행 중')
  await expect(page.locator('.rw-composer')).toHaveCount(0)
  await page.clock.fastForward(39_000)
  await expect(page.locator('.g-finding > div')).toHaveCount(5)
  await expect(page.locator('.g-finding')).toContainText('저변동성 구간 과잉 거래')
  await expect(page.locator('.rw-artifact')).toHaveCount(5)
  await artifact(page, 'Critic Review')
  await expect(page.locator('.research-critic-document')).toHaveAttribute('data-version', '1')
  await expect(page.locator('.research-critic-document')).not.toContainText('필터로 수정됨')
  await page.clock.fastForward(15_000)
  await expect(page.locator('.research-critic-document')).toHaveAttribute('data-version', '2')
  await expect(page.locator('.research-critic-document')).toContainText('수익의 72%')
  await page.getByRole('tab', { name: 'Activity', exact: true }).click()
  await page.clock.fastForward(41_000)
  await expect(page.getByRole('button', { name: '최종 보고서 열기', exact: true })).toBeVisible()
  await page.clock.fastForward(1_300)
  await expect(page.getByRole('heading', { name: 'Research Integrity' })).toBeVisible()
  await expect(page.locator('.rw-artifact')).toHaveCount(10)
  await expect(page.locator('.rw-workspace')).not.toContainText(/MOCK|샘플 데이터|95초/)
  await expect(page.locator('.rw-preview-tools')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('인라인 코멘트·문서별 초안·질문 맥락과 최대 5개 열린 탭을 보존한다', async ({ page }) => {
  await openPlan(page)
  await page.getByRole('button', { name: '손절 수정 요청', exact: true }).click()
  await page.getByLabel('손절 코멘트').fill('-2%로')
  await page.getByRole('button', { name: '적용', exact: true }).click()
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^손절$/ }) })).toContainText('−2%')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(96_000)
  await artifact(page, 'Critic Review')
  await page.getByLabel('Critic Review에 질문').fill('집중도와 손절의 관계를 알고 싶어요')
  await artifact(page, 'Backtest v2')
  await page.getByLabel('Backtest v2에 질문').fill('2025년 손익은 왜 약해졌나요?')
  await artifact(page, 'Critic Review')
  await expect(page.getByLabel('Critic Review에 질문')).toHaveValue('집중도와 손절의 관계를 알고 싶어요')
  for (const title of ['Hypothesis', 'Strategy v1', 'Strategy v2', 'Stress Test', 'Holdout Test', 'Final Report']) await artifact(page, title)
  await expect(page.getByRole('tab')).toHaveCount(5)
  await expect(page.getByRole('tab').first()).toHaveText('Activity')
  await artifact(page, 'Backtest v2')
  await expect(page.getByLabel('Backtest v2에 질문')).toHaveValue('2025년 손익은 왜 약해졌나요?')
  await page.getByRole('button', { name: '문서 질문 보내기', exact: true }).click()
  await expect(page.locator('.rw-user-message')).toHaveText('2025년 손익은 왜 약해졌나요?')
  await expect(page.locator('.rw-answer')).toContainText('v2는 10회 거래')
  await expect(page.getByRole('slider', { name: 'Backtest v2 가격과 매수·매도 시점' })).toBeVisible()
  await expect(page.locator('.rw-price svg title')).toHaveCount(20)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Backtest v2', exact: true })).toBeVisible()
  await expect(page.locator('.rw-user-message')).toHaveText('2025년 손익은 왜 약해졌나요?')
})

test('320~1440px에서 문서·차트가 넘치지 않고 모바일 탐색과 Paper 준비 경계를 지킨다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openPlan(page)
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(96_000)
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 820 })
    await artifact(page, 'Backtest v2')
    await expect(page.locator('.rw-price')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await artifact(page, 'Stress Test')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 820 })
  await page.getByRole('button', { name: 'Artifacts 열기' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Artifacts 열기' })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Artifacts 열기' })).toHaveAttribute('aria-expanded', 'false')
  await artifact(page, 'Final Report')
  await page.getByRole('button', { name: '거래소 연결', exact: true }).click()
  await page.getByRole('button', { name: 'Binance로 간편 연결', exact: true }).click()
  await expect(page.locator('.rw-notice')).toContainText('계정 연결이나 권한 요청을 실행하지 않았습니다')
  await page.getByRole('button', { name: '실행 확인 화면 보기', exact: true }).click()
  await expect(page.getByRole('button', { name: '실제 자금으로 시작', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Paper 시뮬레이션 시작', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reality Check', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '일시 정지', exact: true }).click()
  await expect(page.locator('article .meta')).toContainText('일시 정지됨')
  await page.getByRole('button', { name: '재개', exact: true }).click()
  await page.getByRole('button', { name: '전략 종료', exact: true }).click()
  await page.getByRole('button', { name: '정말 종료할까요?', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Research Integrity' })).toBeVisible()
  expect(errors).toEqual([])
})

test('선택한 ETH 추세·1시간·손절·익절 없음은 계획에만 연결하고 고정 결과와 구분한다', async ({ page }) => {
  await page.clock.install()
  await page.goto('/?ui-debug=1')
  const input = page.locator('.client-home-content textarea')
  await input.fill('이더리움 추세 전략을 만들고 싶어요')
  await input.press('Enter')
  await page.clock.fastForward(12_000)
  await expect(page.getByRole('button', { name: /Research Plan.*연구 계획 확인/ })).toHaveCount(0)
  for (const choice of ['1시간', '−2%', '익절 없이 진행']) {
    await page.getByRole('button', { name: choice, exact: true }).click()
    await page.clock.fastForward(12_000)
  }
  await page.getByRole('button', { name: /Research Plan.*연구 계획 확인/ }).click()
  await expect(page.locator('article .meta')).toContainText('ETH/USDT, 1시간봉')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^진입$/ }) })).toContainText('20일 이동평균 상향 돌파 + 거래량 확인')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^손절$/ }) })).toContainText('−2%')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^익절$/ }) })).toContainText('미설정')
  await page.locator('.rw-preview-tools summary').click()
  await expect(page.locator('.rw-preview-tools')).toContainText('선택한 계획: ETH/USDT · 1시간봉 · 추세 추종 · 손절 −2% · 익절 미설정')
  await expect(page.locator('.rw-preview-tools')).toContainText('고정 원본 재생 사례: BTC/USDT · 1일봉 · RSI 40 반등 · 손절 −3% · 익절 +8%')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(2_000)
  await artifact(page, 'Hypothesis')
  await expect(page.locator('article')).toContainText('Momentum continuation following volume-confirmed breakouts within established uptrends.')
  await expect(page.locator('article')).toContainText('거래가 몰리며 상승 흐름이 확인될 때')
  await page.getByRole('button', { name: '샘플 재생 완료', exact: true }).click()
  await artifact(page, 'Strategy v2')
  await expect(page.locator('article')).toContainText('RSI(14) < 40')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^손절$/ }) })).toContainText('−3%')
})
