import { expect, test, type Page } from '@playwright/test'
import { fixture } from '../src/dev/chart-workspace-fixture'

async function open(page: Page, reduced = true) {
  await page.emulateMedia({ reducedMotion: reduced ? 'reduce' : 'no-preference' })
  await page.goto('/?chart-workspace-preview=1')
  await page.getByRole('button', { name: '차트 작업 공간 열기' }).click()
  await expect(page.locator('.cp-surface canvas').first()).toBeVisible()
}

test('60초 재생·Skip·같은 캔버스에서 차트와 대화로 전환', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.clock.install()
  await open(page, false)
  await expect(page.locator('.bw-workspace')).toHaveClass(/is-replaying/)
  await expect(page.locator('.bw-ledger-section')).toBeHidden()
  await expect(page.locator('.bw-conversation')).toBeHidden()
  await expect(page.getByRole('button', { name: '차트 이미지 저장', exact: true })).toBeDisabled()
  await page.clock.fastForward(10_000)
  await page.screenshot({ path: info.outputPath('workspace-replay.png') })
  const canvas = await page.locator('.cp-surface canvas').first().elementHandle()
  await page.getByRole('button', { name: 'Skip · 결과 보기' }).click()
  await expect(page.locator('.bw-workspace')).not.toHaveClass(/is-replaying/)
  expect(await canvas!.evaluate(node => node === document.querySelector('.cp-surface canvas'))).toBe(true)
  await expect(page.locator('.bw-ledger>button')).toHaveCount(3)
  expect(errors).toEqual([])
})

test('체결·차트·질문 연결, 초안 보존과 검색', async ({ page }, info) => {
  await open(page)
  await page.locator('.bw-ledger>button').nth(1).click()
  await expect(page.locator('.cp-quote')).toContainText('104')
  await page.getByRole('button', { name: '선택한 체결에 질문하기' }).click()
  const field = page.getByRole('textbox', { name: '전략 연구에 질문', exact: true })
  await expect(field).toBeFocused()
  await field.fill('이 진입 조건을')
  await field.press('Shift+Enter'); await page.keyboard.insertText('가')
  await expect(field).toHaveValue('이 진입 조건을\n가')
  await page.getByRole('button', { name: '차트 질문 보내기' }).click()
  await expect(page.locator('.bw-thread .rw-user-message')).toContainText('buy-2')
  await page.screenshot({ path: info.outputPath('workspace-conversation.png') })
  await expect(field).toBeEmpty()
  await field.fill('보존할 초안')
  await page.getByRole('button', { name: '전략 연구로 돌아가기' }).click()
  await expect(page.getByText('보존된 초안: 보존할 초안')).toBeVisible()
  await page.getByRole('button', { name: '차트 작업 공간 열기' }).click()
  await page.getByRole('searchbox').fill('없는 거래')
  await expect(page.getByText('검색 조건에 맞는 체결이 없습니다.')).toBeVisible()
  await page.getByRole('searchbox').fill('trade-a')
  await expect(page.locator('.bw-ledger>button')).toHaveCount(2)
  await page.getByRole('button', { name: 'SELL', exact: true }).click()
  await expect(page.locator('.bw-ledger>button')).toHaveCount(1)
  await page.locator('.bw-ledger>button').click()
  await expect(page.getByRole('button', { name: 'SELL', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('searchbox')).toHaveValue('trade-a')
})

test('320~1440px·짧은 화면 정렬, 대화 입력과 접근성', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await open(page)
  for (const width of [320, 390, 768, 860, 861, 1100, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(() => page.locator('.bw-workspace').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await expect.poll(() => page.locator('.bw-market').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    if (width <= 860) {
      await page.getByRole('button', { name: '대화 이어가기', exact: true }).click()
      await expect(page.getByRole('textbox', { name: '전략 연구에 질문', exact: true })).toBeVisible()
      await page.getByRole('button', { name: '차트·체결', exact: true }).click()
    }
    if ([390, 1440].includes(width)) await page.screenshot({ path: info.outputPath(`workspace-${width}.png`) })
  }
  await page.setViewportSize({ width: 390, height: 360 })
  await page.getByRole('button', { name: '대화 이어가기', exact: true }).click()
  const field = page.getByRole('textbox', { name: '전략 연구에 질문', exact: true })
  await field.fill('긴 초안\n'.repeat(40))
  await page.getByRole('button', { name: '차트 질문 보내기' }).click()
  await expect(field).toBeEmpty()
  expect(errors).toEqual([])
})

test('타이머 지연 후 자동 완료와 재생 중 닫기', async ({ page }) => {
  await page.clock.install()
  await open(page, false)
  await page.clock.fastForward(61_000)
  await expect(page.locator('.bw-workspace')).not.toHaveClass(/is-replaying/)
  await expect(page.locator('.bw-ledger>button')).toHaveCount(3)
  await page.getByRole('button', { name: '전략 연구로 돌아가기' }).click()
  await page.getByRole('button', { name: '차트 작업 공간 열기' }).click()
  await expect(page.locator('.bw-workspace')).toHaveClass(/is-replaying/)
  await page.getByRole('button', { name: '전략 연구로 돌아가기' }).click()
  await page.clock.fastForward(70_000)
  await expect(page.locator('.cp-surface canvas')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '차트 작업 공간 열기' })).toBeFocused()
})

test('StrictMode·재생 중 잘못된 입력 교체는 대화를 숨긴 채 남지 않는다', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/?chart-workspace-preview=1')
  await page.evaluate(async view => {
    const path = '/tests/fixtures/backtest-workspace-host.tsx'
    const module = await import(/* @vite-ignore */ path)
    Object.assign(window, { backtestHost: module.mount(view) })
  }, fixture)
  await expect(page.locator('.bw-workspace')).toHaveClass(/is-replaying/)
  await page.evaluate(view => (window as unknown as { backtestHost: { render: (value: unknown) => void } }).backtestHost.render({ ...view, bars: [] }), fixture)
  await expect(page.locator('.bw-workspace')).not.toHaveClass(/is-replaying/)
  const nav = page.getByRole('button', { name: '대화 이어가기', exact: true })
  if (await nav.isVisible()) await nav.click()
  await expect(page.locator('.bw-composer textarea')).toHaveValue('확인할 조건')
  await expect(page.getByText('보존되는 원래 대화')).toBeVisible()
  await page.evaluate(() => (window as unknown as { backtestHost: { unmount: () => void } }).backtestHost.unmount())
  expect(errors).toEqual([])
})

test('재생 도중 모션 감소 설정은 같은 차트의 전체 결과로 전환한다', async ({ page }) => {
  await open(page, false)
  await expect(page.locator('.bw-workspace')).toHaveClass(/is-replaying/)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.bw-workspace')).not.toHaveClass(/is-replaying/)
  await expect(page.locator('.bw-ledger>button')).toHaveCount(3)
  await page.getByRole('button', { name: '체결 순서 재생', exact: true }).click()
  await expect(page.locator('.bw-workspace')).not.toHaveClass(/is-replaying/)
})

test('데스크톱 대화 입력 중 폭 축소는 현재 대화와 포커스를 보존한다', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await open(page)
  const field = page.locator('.bw-composer textarea')
  await field.fill('계속 입력할 초안')
  await page.setViewportSize({ width: 390, height: 800 })
  await expect(field).toBeVisible()
  await expect(field).toBeFocused()
  await expect(field).toHaveValue('계속 입력할 초안')
  await page.getByRole('button', { name: '차트·체결', exact: true }).click()
  await expect(page.locator('.bw-market')).toBeVisible()
})
