import { expect, test, type Page } from '@playwright/test'

// A real Vite fixture resolves React without relying on optimizer internals.
async function fixture(page: Page) {
  await page.goto('/tests/fixtures/client-account-ui.html')
  await expect(page.getByRole('button', { name: 'signup', exact: true })).toBeVisible()
}

test('이메일 가입의 비밀번호·코드·성명·연령을 보존하고 자격증명을 저장하지 않는다', async ({ page }) => {
  const sent: string[] = []
  page.on('request', request => { if (request.method() !== 'GET') sent.push(request.url()) })
  await fixture(page)
  await page.getByRole('button', { name: 'signup', exact: true }).click()
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('올바른 이메일')
  await page.getByRole('textbox', { name: '이메일 주소' }).fill('research@example.test')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await expect(page.getByRole('heading', { name: '비밀번호 생성하기' })).toBeVisible()
  await page.getByLabel('비밀번호', { exact: true }).fill('sample-password-42!')
  await expect(page.locator('.rq.ok')).toHaveCount(3)
  await page.getByRole('button', { name: '비밀번호 표시' }).click()
  await expect(page.getByLabel('비밀번호', { exact: true })).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await expect(page.getByRole('heading', { name: '받은 편지함을 확인하세요' })).toBeVisible()
  await expect(page.getByRole('button', { name: '비밀번호로 계속하기' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /다시 보내기/ })).toBeDisabled()
  await page.getByRole('textbox', { name: '코드', exact: true }).fill('123456')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('textbox', { name: '성명', exact: true }).fill('연구 사용자')
  await page.getByRole('textbox', { name: '연령', exact: true }).fill('121')
  await page.getByRole('button', { name: '시장에 입장하기' }).click()
  await expect(page.getByRole('alert')).toContainText('연령을 숫자로')
  await page.getByRole('textbox', { name: '연령', exact: true }).fill('28')
  await page.getByRole('button', { name: '시장에 입장하기' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('output')).toHaveText('연구 사용자 research@example.test')
  expect(await page.evaluate(() => ({ local: { ...localStorage }, session: { ...sessionStorage } }))).toEqual({ local: {}, session: {} })
  expect(sent).toEqual([])
})

test('로그인은 코드에서 비밀번호로 전환하고 재인증 없이 끝나며 Escape 포커스를 돌려준다', async ({ page }) => {
  await fixture(page)
  const opener = page.getByRole('button', { name: 'login', exact: true })
  await opener.click()
  await page.keyboard.press('Escape')
  await expect(opener).toBeFocused()
  await opener.click()
  await page.getByRole('textbox', { name: '이메일 주소' }).fill('reader@example.test')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('button', { name: '비밀번호로 계속하기' }).click()
  await page.getByLabel('비밀번호', { exact: true }).fill('fixture-only-password')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await expect(page.locator('output')).toHaveText('reader reader@example.test')
  await page.getByRole('button', { name: 'profile', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '프로필' })).toContainText('reader@example.test')
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  await expect(page.locator('output')).toHaveText('')
})

test('설정 계층과 모바일 시트는 원본 메뉴와 언어/통화 동선을 유지한다', async ({ page }) => {
  await fixture(page)
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 800 })
    await page.getByRole('button', { name: 'settings', exact: true }).click()
    await page.getByRole('button', { name: '설정', exact: true }).click()
    await expect(page.getByRole('button', { name: /언어 및 통화/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /테마/ })).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const box = await page.locator('.gm-sub').boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(width)
    await page.getByRole('button', { name: /언어 및 통화/ }).click()
    await expect(page.getByText('locale selected', { exact: true })).toBeVisible()
  }
})

test('피드백 첨부·제거·형식오류·완료 화면은 로컬 상태만 사용한다', async ({ page }) => {
  await fixture(page)
  await page.getByRole('button', { name: 'feedback', exact: true }).click()
  await page.getByRole('button', { name: '보내기', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('의견 내용을 입력')
  await page.locator('input[type=file]').setInputFiles({ name: 'wrong.txt', mimeType: 'text/plain', buffer: Buffer.from('fixture') })
  await expect(page.getByRole('alert')).toContainText('이미지 파일만')
  await page.locator('input[type=file]').setInputFiles({ name: 'chart.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jG1sAAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByAltText('첨부된 스크린샷')).toBeVisible()
  await page.getByRole('button', { name: '첨부 제거' }).click()
  await expect(page.getByAltText('첨부된 스크린샷')).toHaveCount(0)
  await page.getByRole('textbox', { name: '의견을 설명해 주세요. (필수)' }).fill('화면 구성이 일관되어서 좋습니다.')
  await page.getByRole('button', { name: '보내기', exact: true }).click()
  await expect(page.getByRole('heading', { name: '의견이 제출되었습니다. 감사합니다' })).toBeVisible()
  await expect(page.getByRole('button', { name: '닫기', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '닫기', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('가입 미리보기 처리 중 취소하면 지연 완료가 계정 상태를 바꾸지 않는다', async ({ page }) => {
  await page.clock.install()
  await fixture(page)
  await page.getByRole('button', { name: 'signup', exact: true }).click()
  await page.locator('.au-btns button').first().click()
  await page.getByRole('textbox', { name: '연령', exact: true }).fill('28')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  await page.getByRole('button', { name: '시장에 입장하기' }).click()
  await expect(page.locator('.au-spin')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.clock.fastForward(2000)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('output')).toHaveText('')
  await expect(page.getByRole('button', { name: 'signup', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'signup', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '이메일 주소' })).toHaveValue('')
})
