import { expect, test, type Page } from '@playwright/test'
import { fixture } from '../src/dev/chart-workspace-fixture'
import type { PriceChartView } from '../src/chart/price-chart-view'

type Host = { calls: number; settle(fail: boolean): void; render(view: PriceChartView, messages?: string[]): void; unmount(): void }
declare global { interface Window { hardeningHost: Host } }
async function mount(page: Page, view = fixture, asyncSend = false) {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?chart-workspace-preview=1')
  await page.evaluate(async args => {
    const path = '/tests/fixtures/backtest-workspace-host.tsx'
    const module = await import(/* @vite-ignore */ path)
    window.hardeningHost = module.mount(args.view, { asyncSend: args.asyncSend })
  }, { view, asyncSend })
  await expect(page.locator('.bw-composer textarea')).toBeVisible()
}

test('중복 전송 차단·실패 초안 보존·재시도·늦은 응답 정리', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await mount(page, fixture, true)
  await page.locator('.bw-composer').evaluate(form => { (form as HTMLFormElement).requestSubmit(); (form as HTMLFormElement).requestSubmit() })
  await expect(page.locator('.bw-composer')).toHaveAttribute('aria-busy', 'true')
  expect(await page.evaluate(() => window.hardeningHost.calls)).toBe(1)
  await expect(page.getByRole('button', { name: '차트 질문 보내기' })).toBeDisabled()
  await page.evaluate(view => window.hardeningHost.render({ ...view, identity: 'NEXT_RESULT_SAME_CONVERSATION' }), fixture)
  await expect(page.getByRole('button', { name: '차트 질문 보내기' })).toBeDisabled()
  await page.locator('.bw-composer').evaluate(form => (form as HTMLFormElement).requestSubmit())
  expect(await page.evaluate(() => window.hardeningHost.calls)).toBe(1)
  await page.evaluate(() => window.hardeningHost.settle(true))
  await expect(page.getByRole('alert')).toContainText('입력 내용은 유지')
  await expect(page.getByRole('alert')).not.toContainText('TEST_ONLY_PRIVATE_ERROR')
  await expect(page.locator('.bw-composer textarea')).toHaveValue('확인할 조건')
  await page.screenshot({ path: info.outputPath('send-error.png') })
  await page.getByRole('button', { name: '차트 질문 보내기' }).click()
  expect(await page.evaluate(() => window.hardeningHost.calls)).toBe(2)
  await page.evaluate(() => window.hardeningHost.settle(false))
  await expect(page.locator('.bw-composer textarea')).toBeEmpty()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.locator('.bw-composer textarea').fill('다음 질문')
  await page.getByRole('button', { name: '차트 질문 보내기' }).click()
  await page.evaluate(() => { window.hardeningHost.unmount(); window.hardeningHost.settle(true) })
  await expect(page.locator('.bw-workspace')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('실제 메시지 변경만 자동 따라가고 이전 대화 읽는 위치는 보존', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await mount(page)
  const messages = Array.from({ length: 80 }, (_, i) => `이전 대화 ${i} · 검수용 본문입니다.`)
  const update = (items: string[]) => page.evaluate(({ view, items }) => window.hardeningHost.render(view, items), { view: fixture, items })
  await update(messages)
  const thread = page.locator('.bw-thread')
  const distance = () => thread.evaluate(node => node.clientHeight ? node.scrollHeight - node.clientHeight - node.scrollTop : Infinity)
  await expect.poll(distance).toBeLessThan(5)
  await thread.evaluate(node => { node.scrollTop = 0 })
  await expect.poll(() => thread.evaluate(node => node.scrollTop)).toBe(0)
  await page.locator('.bw-composer textarea').fill('초안을 쓰는 것만으로 새 메시지가 생기지 않음')
  await expect(page.getByRole('button', { name: '새 메시지 보기' })).toHaveCount(0)
  await update([...messages, '새로 도착한 메시지'])
  await expect(page.getByRole('button', { name: '새 메시지 보기' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('unread-message.png') })
  expect(await thread.evaluate(node => node.scrollTop)).toBe(0)
  await page.getByRole('button', { name: '새 메시지 보기' }).click()
  await expect.poll(distance).toBeLessThan(5)
  await expect(thread).toBeFocused()
  await update([...messages, '새로 도착한 메시지', '스트리밍으로 이어지는 내용'])
  await expect.poll(distance).toBeLessThan(5)
  await expect(page.getByRole('button', { name: '새 메시지 보기' })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 800 })
  await page.getByRole('button', { name: '차트·체결', exact: true }).click()
  await update([...messages, '숨겨진 대화에도 도착한 메시지'])
  await page.getByRole('button', { name: '대화 이어가기', exact: true }).click()
  await expect.poll(distance).toBeLessThan(5)
  await thread.evaluate(node => { node.scrollTop = 200 })
  await expect.poll(() => thread.evaluate(node => node.scrollTop)).toBe(200)
  await page.getByRole('button', { name: '차트·체결', exact: true }).click()
  await update([...messages, '추가 도착'])
  await page.getByRole('button', { name: '대화 이어가기', exact: true }).click()
  await expect.poll(() => thread.evaluate(node => node.scrollTop)).toBe(200)
  await expect(page.getByRole('button', { name: '새 메시지 보기' })).toBeVisible()
  await thread.focus(); await thread.press('Home')
  await expect.poll(() => thread.evaluate(node => node.scrollTop)).toBe(0)
  await update([...messages, '키보드로 이전 대화를 읽는 중'])
  await expect.poll(() => thread.evaluate(node => node.scrollTop)).toBe(0)
  expect(errors).toEqual([])
})

test('10000체결도 50행만 mount하고 마지막 페이지·검색·질문 연결', async ({ page }, info) => {
  const large = { ...fixture, fills: Array.from({ length: 10000 }, (_, i) => ({ ...fixture.fills[0], id: `fill-${String(i).padStart(5, '0')}`, tradeId: `trade-${i}` })) }
  await mount(page, large)
  const rows = page.locator('.bw-ledger>button')
  await expect(rows).toHaveCount(50)
  await page.getByRole('button', { name: '체결 마지막 페이지' }).click()
  await expect(rows).toHaveCount(50)
  await expect(rows.last()).toContainText('trade-9999')
  await rows.last().click()
  await expect.poll(() => page.locator('.bw-ledger').evaluate(node => node.scrollTop)).toBeGreaterThan(500)
  await page.getByRole('button', { name: '선택한 체결에 질문하기' }).click()
  await expect(page.locator('.bw-reference')).toContainText('trade-9999')
  await page.getByRole('searchbox').fill('fill-00000')
  await expect(rows).toHaveCount(1)
  await expect(rows.first()).toContainText('trade-0')
  await page.getByRole('searchbox').fill('')
  await expect(rows).toHaveCount(50)
  await expect(rows.first()).toContainText('trade-0')
  for (const width of [320, 390, 861]) {
    await page.setViewportSize({ width, height: 900 })
    const nav = page.getByRole('button', { name: '차트·체결', exact: true })
    if (await nav.isVisible()) await nav.click()
    await expect.poll(() => page.locator('.bw-market').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    if (width === 320) { await page.locator('.bw-pagination').scrollIntoViewIfNeeded(); await page.screenshot({ path: info.outputPath('ledger-320.png') }) }
  }
})
