import { expect, test } from '@playwright/test'

test('정보와 다운로드는 같은 앱 안에서 열리고 왕복해도 입력 초안이 유지된다', async ({ page }, testInfo) => {
  await page.goto('/')
  const input = page.getByRole('textbox', { name: '시장이나 전략에 대해 물어보세요' })
  await input.fill('아직 보내지 않은 투자 아이디어')
  await page.evaluate(() => { Object.assign(window, { tethNavigationSentinel: 123 }) })
  const mobile = testInfo.project.name === 'mobile'
  if (mobile) await page.getByRole('button', { name: '메뉴', exact: true }).click()
  await page.getByRole('link', { name: 'TETH 정보', exact: true }).filter({ visible: true }).first().click()
  await expect(page).toHaveURL(/\/about\/$/)
  await expect(page.locator('.client-info-about h1')).toContainText('당신 편에서 시장과 싸우는')
  await expect(page.locator('.client-public-page a[href*="github"]')).toHaveCount(0)
  await page.locator('.client-info-about .ft').getByRole('link', { name: '앱 다운로드', exact: true }).click()
  await expect(page).toHaveURL(/\/download\/$/)
  await expect(page.getByRole('heading', { name: 'TETH를 다운로드하세요' })).toBeVisible()
  await page.goBack()
  await expect(page.locator('.client-info-about')).toBeVisible()
  await page.goBack()
  await expect(input).toHaveValue('아직 보내지 않은 투자 아이디어')
  expect(await page.evaluate(() => Reflect.get(window, 'tethNavigationSentinel'))).toBe(123)
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
  await input.fill('왕복 후에도 계속 입력할 수 있어요')
  await expect(input).toBeFocused()
})

test('원본 정보 페이지의 제품 섹션·요금제·FAQ를 내부에서 사용할 수 있다', async ({ page }) => {
  await page.goto('/about/')
  await expect(page.locator('.feat')).toHaveCount(4)
  await expect(page.locator('.feat .vis')).toHaveCount(4)
  await expect(page.getByRole('heading', { name: 'TETH Direct' })).toBeAttached()
  await expect(page.getByRole('heading', { name: 'TETH Partner' })).toBeAttached()
  await expect(page.locator('.pricing-preview')).toContainText('결제·파트너 가입은 진행되지 않습니다')
  const question = page.locator('summary').filter({ hasText: '모바일 앱이 있나요?' })
  await question.click()
  await expect(page.locator('details[open]')).toHaveCount(1)
  await page.locator('details[open]').getByRole('link', { name: '앱 다운로드 페이지' }).click()
  await expect(page).toHaveURL(/\/download\/$/)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'TETH를 다운로드하세요' })).toBeVisible()
})

test('다운로드 캐러셀은 선택·일시 정지가 되고 가짜 스토어·QR 요청이 없다', async ({ page }) => {
  const external: string[] = []
  page.on('request', request => { if (/qrserver|apps\.apple|play\.google|github\.io/.test(request.url())) external.push(request.url()) })
  await page.goto('/download/')
  await expect(page.locator('.qr.todo')).toHaveCount(2)
  await expect(page.locator('.count')).toHaveText('1 / 3')
  await page.getByRole('button', { name: '자동 재생 일시 정지' }).click()
  await page.getByRole('button', { name: '다음 앱 화면' }).click()
  await expect(page.locator('.count')).toHaveText('2 / 3')
  await expect(page.locator('.slide.on')).toHaveAttribute('data-screen', 'report')
  await page.getByRole('button', { name: '모니터링 화면 보기' }).click()
  await expect(page.locator('.count')).toHaveText('3 / 3')
  await page.waitForTimeout(6200)
  await expect(page.locator('.count')).toHaveText('3 / 3')
  await page.getByRole('button', { name: '자동 재생 시작' }).click()
  await page.getByRole('button', { name: '대화 화면 보기' }).focus()
  await page.mouse.move(0, 0)
  await page.waitForTimeout(6200)
  await expect(page.locator('.count')).toHaveText('3 / 3')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.getByRole('button', { name: '자동 재생 시작' })).toHaveCount(0)
  expect(external).toEqual([])
})

test('정책의 탭·조항 링크·새로고침·뒤로가기가 일치한다', async ({ page }, testInfo) => {
  await page.goto('/policies/#privacy')
  await expect(page.locator('#v-privacy')).toBeVisible()
  await page.locator('.site-skip').focus()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/\/policies\/#privacy$/)
  await expect(page.locator('#site-main')).toBeFocused()
  await expect(page.locator('#v-privacy')).toBeVisible()
  await expect(page.locator('.prototype-notice')).toContainText('검토용 초안')
  await page.locator('.tabs').getByRole('link', { name: '서비스 약관', exact: true }).click()
  await expect(page.locator('#v-terms')).toBeVisible()
  const risk = page.locator('#v-terms .lnk').filter({ hasText: '투자 위험 고지' })
  await risk.click()
  await expect(page).toHaveURL(/\/policies\/#t-risk$/)
  await expect(page.locator('#t-risk')).toBeInViewport()
  if (testInfo.project.name === 'desktop') await expect(page.locator('.view.on .toc a.on')).toHaveText('투자 위험 고지')
  await page.reload()
  await expect(page.locator('#v-terms')).toBeVisible()
  await expect(page.locator('#t-risk')).toBeInViewport()
  await page.locator('.tabs').getByRole('link', { name: 'FAQ', exact: true }).click()
  await expect(page.locator('#v-faq')).toBeVisible()
  await page.goBack()
  await expect(page.locator('#t-risk')).toBeInViewport()
})

test('도움말은 내부 FAQ로 이동하며 Escape로 닫고 포커스를 복구한다', async ({ page }) => {
  await page.goto('/download/')
  const help = page.getByRole('button', { name: 'TETH 도움말', exact: true })
  await help.click()
  await expect(page.locator('.site-help-pop')).toContainText('실시간 채팅은 곧 제공돼요')
  await page.keyboard.press('Escape')
  await expect(page.locator('.site-help-pop')).toHaveCount(0)
  await expect(help).toBeFocused()
  await help.click()
  await page.getByRole('link', { name: '자주 묻는 질문 →' }).click()
  await expect(page).toHaveURL(/\/about\/#faq$/)
  await expect(page.locator('#faq')).toBeInViewport()
})

test('안내 페이지는 320·390·768·1440px에서 가로 넘침·중복 ID·이미지 오류가 없다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  for (const route of ['about', 'download', 'policies']) {
    await page.goto(`/${route}/`)
    await expect(page.locator('#site-main')).toBeVisible()
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 })
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
    }
    expect(await page.evaluate(() => {
      const ids = Array.from(document.querySelectorAll('[id]')).map(el => el.id)
      return ids.filter((id, i) => ids.indexOf(id) !== i)
    })).toEqual([])
    await expect.poll(() => page.locator('img:not([loading="lazy"])').evaluateAll(images => images.every(image => (image as HTMLImageElement).complete && (image as HTMLImageElement).naturalWidth > 0))).toBeTruthy()
  }
  expect(errors).toEqual([])
})
