import { expect, test, type Page } from '@playwright/test'

async function openDelegation(page: Page) {
  await page.goto('/')
  await page.getByLabel('시장이나 전략에 대해 물어보세요').fill('비트코인 전략 만들어줘')
  await page.getByRole('button', { name: '대화 시작', exact: true }).click()
  await page.getByRole('button', { name: /^전략 맡기기/ }).click()
  await expect(page.getByRole('heading', { name: '어떤 자산으로 할까요?' })).toBeVisible()
}

async function report(page: Page) {
  await openDelegation(page)
  for (const name of ['비트코인', '중립적으로', '500만원', '최근 2년', '-5%까지']) await page.getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('heading', { name: '전략 계약서' })).toBeVisible()
  await page.getByRole('button', { name: '전략 검증 시작', exact: true }).click()
  await expect(page.getByRole('heading', { name: '검증 진행' })).toBeVisible()
  await page.getByRole('button', { name: '추천 설정으로 다시 검증', exact: true }).click()
  await page.getByRole('button', { name: '리포트 보기', exact: true }).click()
}

async function expectNoSensitiveStorage(page: Page) {
  const values = await page.evaluate(() => Object.values({ ...localStorage, ...sessionStorage }).join('\n'))
  expect(values).not.toMatch(/SAFE_FAKE|BAD_FAKE|42424242|1212345678|1234567890|테스트카드/)
  const records = await page.evaluate(() => Object.entries(sessionStorage).filter(([key]) => key.startsWith('teth:client-delegation:')).map(([, value]) => JSON.parse(value)))
  for (const record of records) expect(Object.keys(record).sort()).toEqual(['answers', 'attempt', 'chartInterval', 'expert', 'page', 'questionIndex', 'workStartedAt', 'workStep'])
}

test('전략 위임은 원본 5문항과 계약서, 개선 결과, 리포트로 이어진다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await report(page)
  await expect(page.locator('.tf-scorebox')).toHaveCount(0)
  await expect(page.locator('.tf-ez').first()).toContainText('100번 중 63번')
  await page.getByRole('button', { name: '전문가 보기', exact: true }).click()
  await expect(page.locator('.tf-ez').first()).toContainText('Profit Factor 2.01')
  await page.reload()
  await expect(page.getByRole('button', { name: '쉬운 말 보기', exact: true })).toBeVisible()
  await expect(page.locator('.tf-ez').first()).toContainText('Profit Factor 2.01')
  await page.locator('.client-delegation .bk').click()
  const daily = await page.locator('.tf-chart svg rect').count()
  await page.getByRole('button', { name: '1W', exact: true }).click()
  expect(await page.locator('.tf-chart svg rect').count()).toBeLessThan(daily)
  await page.getByRole('button', { name: '1M', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '1M', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.client-delegation')).toHaveAttribute('data-source', 'client-ui-fixture')
  expect(errors).toEqual([])
})

test('질문 선택은 세션별 복원되고 다시 답하기는 계약서 전체를 초기화한다', async ({ page }) => {
  await openDelegation(page)
  await page.getByRole('button', { name: '이더리움', exact: true }).click()
  await page.getByRole('button', { name: '안전하게', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: '어느 정도 예산으로 시작할까요?' })).toBeVisible()
  await expect(page.locator('.tf-intake-done')).toHaveCount(2)
  await expect(page.locator('.tf-intake-done').first()).toContainText('이더리움')
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: '잘 모르겠어요, AI가 추천해주세요' }).click()
  await page.getByRole('button', { name: '다시 답하기', exact: true }).click()
  await expect(page.locator('.tf-intake-done')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '어떤 자산으로 할까요?' })).toBeVisible()
})

test('무료 연결은 UID 오류와 가이드, API 오류 재시도를 지원하고 민감값은 저장하지 않는다', async ({ page }) => {
  await report(page)
  await page.getByRole('button', { name: '이 전략 실행하기' }).click()
  await page.getByRole('button', { name: '무료로 시작' }).click()
  await page.getByRole('button', { name: '추천 Binance', exact: true }).click()
  await page.getByRole('button', { name: '가입 완료했어요' }).click()
  await page.getByRole('button', { name: '연동 확인하기' }).click()
  await expect(page.getByLabel('Binance UID')).toBeFocused()
  await page.getByLabel('Binance UID').fill('000000')
  await page.getByRole('button', { name: '연동 확인하기' }).click()
  await expect(page.getByRole('alert')).toContainText('가입 내역을 찾지 못했어요')
  await page.getByLabel('Binance UID').fill('1212345678')
  await page.getByRole('button', { name: 'UID가 어디 있어요?' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('.tf-guide .g')).toHaveCount(3)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'UID가 어디 있어요?' })).toBeFocused()
  await expect(page.getByLabel('Binance UID')).toHaveValue('1212345678')
  await page.getByRole('button', { name: '연동 확인하기' }).click()
  await page.getByLabel('API Key', { exact: true }).fill('BAD_FAKE_KEY')
  await page.getByLabel('Secret Key', { exact: true }).fill('SAFE_FAKE_SECRET')
  await page.getByRole('button', { name: '권한 확인하고 연결하기' }).click()
  await expect(page.getByRole('alert')).toContainText('API Key 권한 확인에 실패')
  await expect(page.getByRole('alert')).toBeFocused()
  await page.getByLabel('API Key', { exact: true }).fill('SAFE_FAKE_KEY')
  await page.getByRole('button', { name: '권한 확인하고 연결하기' }).click()
  await page.getByRole('button', { name: '전략 시작', exact: true }).click()
  await page.getByRole('button', { name: '중지', exact: true }).click()
  await expect(page.getByText('중지됨', { exact: true })).toBeVisible()
  await expectNoSensitiveStorage(page)
})

test('유료 결제는 검증·거절·재시도를 지원하고 새로고침 시 민감 입력 단계로 복귀하지 않는다', async ({ page }) => {
  await report(page)
  await page.getByRole('button', { name: '이 전략 실행하기' }).click()
  await page.getByRole('button', { name: '기존 계정 연결' }).click()
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await expect(page.getByLabel('카드 번호', { exact: true })).toBeFocused()
  await page.getByLabel('카드 번호', { exact: true }).fill('0000000000000000')
  await page.getByLabel('유효기간').fill('12/29')
  await page.getByLabel('CVC').fill('123')
  await page.getByLabel('카드 소유자 이름').fill('테스트카드')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('button', { name: '₩5,000,000 결제하기' }).click()
  await expect(page.getByRole('alert')).toContainText('카드사 승인이 거절')
  await page.getByLabel('카드 번호', { exact: true }).fill('4242424242424242')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('button', { name: '₩5,000,000 결제하기' }).click()
  await page.getByRole('button', { name: 'OKX', exact: true }).click()
  await page.getByLabel('API Key', { exact: true }).fill('SAFE_FAKE_KEY')
  await page.getByLabel('Secret Key', { exact: true }).fill('SAFE_FAKE_SECRET')
  await expectNoSensitiveStorage(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: '어떻게 실행할까요?' })).toBeVisible()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveCount(0)
  await expectNoSensitiveStorage(page)
})

test('위임 리포트의 모바일 축과 단계, 드로어가 화면 폭을 넘지 않는다', async ({ page }) => {
  await report(page)
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(() => page.locator('.tf-chart svg').evaluate(el => Math.abs(el.viewBox.baseVal.width - el.getBoundingClientRect().width))).toBeLessThan(2)
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
    await expect(page.getByRole('button', { name: '이 전략 실행하기' })).toBeVisible()
  }
  await page.setViewportSize({ width: 320, height: 740 })
  await page.getByRole('button', { name: '이 전략 실행하기' }).click()
  await page.getByRole('button', { name: '무료로 시작' }).click()
  await page.getByRole('button', { name: '추천 Binance', exact: true }).click()
  await page.getByRole('button', { name: '가입 완료했어요' }).click()
  await page.getByRole('button', { name: 'UID가 어디 있어요?' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
})
