import { expect, test, type Page } from '@playwright/test'

async function menu(page: Page) {
  await page.locator((page.viewportSize()?.width ?? 0) <= 860 ? '.client-hamburger' : '.client-rail-logo-row button').click()
}
async function healthy(page: Page) {
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  expect(await page.evaluate(() => {
    const ids = Array.from(document.querySelectorAll('[id]')).map(el => el.id)
    return ids.filter((id, i) => ids.indexOf(id) !== i)
  })).toEqual([])
  expect(await page.evaluate(() => Boolean(document.activeElement?.closest('[inert],[hidden]')))).toBe(false)
}
async function document(page: Page, title: string) {
  if (title === 'Activity') { await page.getByRole('tab', { name: 'Activity', exact: true }).click(); return }
  const trigger = page.getByRole('button', { name: 'Artifacts 열기', exact: true })
  if (await trigger.isVisible()) await trigger.click()
  await page.locator('.rw-artifact').filter({ has: page.locator('span', { hasText: new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`) }) }).click()
}

test('빈 계정에서 두 대화·연구·공개 페이지·문서·랭킹을 왕복해도 상태가 섞이지 않는다', async ({ page }) => {
  page.setDefaultTimeout(15_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.install()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  await page.locator('.client-home-content textarea').fill('비트코인 하락 후 반등 전략 🔍')
  await page.getByRole('button', { name: '대화 시작', exact: true }).click()
  await page.locator('.g-composer textarea').fill('첫 대화에 보존할 초안')
  await page.locator('.g-composer textarea').press('Enter')
  await expect(page.locator('.g-urow')).toHaveCount(1)
  await expect(page.locator('.g-composer textarea')).toHaveValue('첫 대화에 보존할 초안')
  await page.clock.resume()
  // Local presentation-only login, no OAuth or network authentication.
  await menu(page)
  await page.locator('[data-sidebar-action="account"]').click()
  await page.locator('.au-btns button').first().click()
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await menu(page)
  await page.locator('.client-new-strategy').click()
  await page.locator('.client-home-content textarea').fill('이더리움 추세 전략')
  await page.getByRole('button', { name: '대화 시작', exact: true }).click()
  await page.getByRole('button', { name: '대화 제목 수정', exact: true }).click()
  await page.getByRole('textbox', { name: '대화 제목 수정', exact: true }).fill('두 번째 연구 🔍')
  await page.getByRole('textbox', { name: '대화 제목 수정', exact: true }).press('Enter')
  await page.locator('.g-composer textarea').fill('두 번째 독립 초안')
  await menu(page)
  await page.locator('.client-session').nth(1).click()
  await page.clock.fastForward(15_000)
  await expect(page.locator('.g-composer textarea')).toHaveValue('첫 대화에 보존할 초안')
  await page.locator('.g-composer textarea').fill('')
  for (const choice of ['1시간', '−3% (표준)', '익절 +8% 설정']) {
    await page.getByRole('button', { name: choice, exact: true }).click()
    await page.clock.fastForward(12_000)
  }
  await page.getByRole('button', { name: /Research Plan.*연구 계획/ }).click()
  await page.locator('.rw-composer textarea').fill('계획 문서의 독립 초안')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(18_000)
  await menu(page)
  await page.locator('.client-sidebar .client-drawer-links').getByRole('link', { name: 'TETH 앱 다운로드', exact: true }).click()
  await expect(page.locator('.client-info-download')).toBeVisible()
  await page.clock.fastForward(90_000)
  await page.locator('a.web-start').click()
  await document(page, 'Activity')
  await expect(page.locator('.g-act-row')).toHaveCount(19)
  await document(page, 'Research Plan')
  await expect(page.locator('.rw-composer textarea')).toHaveValue('계획 문서의 독립 초안')
  const labels = await page.locator('.rw-artifact > span').allTextContents()
  expect(labels.length).toBeGreaterThanOrEqual(10)
  for (let i = 0; i < labels.length; i++) {
    await page.setViewportSize({ width: [320, 768, 1440][i % 3], height: 900 })
    await document(page, labels[i])
    await expect(page.locator('.rw-scroll article')).toHaveAttribute('aria-label', `${labels[i]} 문서`)
    await expect(page.locator('.rw-tabs [aria-selected="true"]')).toHaveCount(1)
    expect(await page.locator('.rw-tabs button').count()).toBeLessThanOrEqual(5)
    expect(await page.locator('.rw-scroll svg').evaluateAll(elements => elements.some(el => /NaN|Infinity/.test(el.outerHTML)))).toBe(false)
    await healthy(page)
  }
  await document(page, 'Final Report')
  await page.getByRole('button', { name: '거래소 연결', exact: true }).click()
  await page.getByRole('button', { name: 'Binance로 간편 연결', exact: true }).click()
  await page.getByRole('button', { name: '실행 확인 화면 보기', exact: true }).click()
  await expect(page.getByRole('button', { name: '실제 자금으로 시작', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Paper 시뮬레이션 시작', exact: true }).click()
  await page.getByRole('button', { name: '일시 정지', exact: true }).click()
  await menu(page)
  await page.locator('.client-sidebar').getByRole('button', { name: '연구 기록', exact: true }).click()
  await page.locator('.hub-history button').filter({ hasText: 'BTC Pullback Strategy' }).click()
  await expect(page.getByRole('button', { name: '재개', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '전략 종료', exact: true }).click()
  await page.getByRole('button', { name: '정말 종료할까요?', exact: true }).click()
  await menu(page)
  await page.locator('.client-sidebar').getByRole('button', { name: '연구 기록', exact: true }).click()
  await expect(page.locator('.hub-history li')).toHaveCount(2)
  await expect(page.locator('.hub-history li').filter({ hasText: 'BTC Pullback Strategy' })).toContainText('검토 필요')
  await page.locator('.hub-history button').filter({ hasText: '두 번째 연구 🔍' }).click()
  await expect(page.locator('.g-composer textarea')).toHaveValue('두 번째 독립 초안')
  await expect(page.locator('.g-title')).toContainText('두 번째 연구 🔍')
  await expect(page.locator('.g-urow')).toHaveCount(1)
  await menu(page)
  await page.locator('.client-sidebar').getByRole('button', { name: '랭킹', exact: true }).click()
  await page.getByRole('button', { name: /전략 따라하기/ }).first().click()
  await expect(page.locator('.client-home-content textarea')).toHaveValue(/전략을 검토하고 싶어요/)
  await expect(page.locator('.client-conversation-frame')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.client-home-content textarea')).toHaveValue(/전략을 검토하고 싶어요/)
  await menu(page)
  await expect(page.locator('.client-session')).toHaveCount(2)
  await page.keyboard.press('Escape')
  await healthy(page)
  expect(errors).toEqual([])
})

test('공개 페이지 언어·정책·설정·피드백을 교차 사용해도 입력과 조작이 유지된다', async ({ page }) => {
  page.setDefaultTimeout(15_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const draft = '줄바꿈 보존\n<script>테스트 문자열</script> 🔍'.repeat(5)
  await page.locator('.client-home-content textarea').fill(draft)
  await menu(page)
  await page.locator('.client-sidebar .client-drawer-links').getByRole('link', { name: 'TETH 정보', exact: true }).click()
  await page.locator('.public-language-trigger').click()
  await page.getByRole('button', { name: 'Français', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'fr')
  await healthy(page)
  await page.locator('.public-language-trigger').click()
  await page.getByRole('button', { name: '한국어', exact: true }).click()
  await page.locator('.ft').getByRole('link', { name: '앱 다운로드', exact: true }).click()
  await page.getByRole('button', { name: '다음 앱 화면', exact: true }).click()
  await expect(page.locator('.count')).toHaveText('2 / 3')
  await page.getByRole('button', { name: 'TETH 도움말', exact: true }).click()
  await page.locator('.site-help-pop a[href="/policies/#overview"]').click()
  await page.locator('.tabs').getByRole('link', { name: '서비스 약관', exact: true }).click()
  await page.locator('#v-terms .lnk').filter({ hasText: '투자 위험 고지' }).click()
  await expect(page.locator('#t-risk')).toBeInViewport()
  await healthy(page)
  await page.goBack()
  await page.goBack()
  await page.goBack()
  await expect(page.locator('.client-info-download')).toBeVisible()
  await page.locator('a.web-start').click()
  await expect(page.locator('.client-home-content textarea')).toHaveValue(draft)
  await menu(page)
  await page.locator('[data-sidebar-action="settings"]').click()
  await page.locator('.ca-settings').getByRole('button', { name: '의견 보내기', exact: true }).click()
  await page.locator('.fb-send').click()
  await expect(page.locator('.ca-feedback textarea')).toBeFocused()
  await expect(page.locator('.ca-feedback [role="alert"]')).toBeVisible()
  await page.locator('.ca-feedback textarea').fill('검수용 의견입니다. 외부 전송 없음.')
  await page.locator('.fb-send').click()
  await expect(page.locator('.fb-done')).toBeVisible()
  await page.locator('.fb-done button').click()
  await expect(page.locator('.client-home-content textarea')).toHaveValue(draft)
  await healthy(page)
  expect(errors).toEqual([])
})
