// 전략 복사 창(ChatGPT 어휘): 겉모습, 레버리지 한 줄, 손실 알약, 확인 행, 복사 설정, 검증, 시작, 미연결 회원은 플랜 화면
// 사용: node qa/gpt-skin/copy/skc-check.mjs [url] [w] [h] [outDir]
import { newPage, closePage, goto, evala, viewport, shot, sleep } from 'file:///C:/Users/hyun1/AppData/Local/Temp/claude/C--Users-hyun1-OneDrive------/3eeecebb-9375-4ed0-850b-52929f00da99/scratchpad/pw/cdp.mjs';
import fs from 'fs';
const B=process.argv[2]||'http://127.0.0.1:8765/index.html', W=+(process.argv[3]||1440), H=+(process.argv[4]||900), M=W<700, sfx=M?'-m':'';
const DIR=process.argv[5]||decodeURIComponent(new URL('./s2/',import.meta.url).pathname).replace(/^\/([A-Za-z]:)/,'$1'); fs.mkdirSync(DIR,{recursive:true});
const out=[]; const ok=(n,c,i)=>{ out.push((c?'PASS':'FAIL')+' | '+n+(i!==undefined?' | '+JSON.stringify(i).slice(0,400):'')); console.log(out[out.length-1]); };
const p=await newPage(); await viewport(p,W,H,{mobile:M});
const ev=async(x)=>{ try{ return await evala(p,x); }catch(e){ return 'ERR '+String(e).slice(0,200); } };
const J=async(x)=>{ try{ return JSON.parse(await ev(`JSON.stringify(${x})`)); }catch(e){ return {}; } };
const snap=async(n)=>{ await sleep(350); await shot(p,DIR+n+sfx+'.png',{full:false}); };
const load=async(pr)=>{ await goto(p,B+'?v='+Date.now()); await sleep(500); await ev(`localStorage.clear(); sessionStorage.clear()`); await goto(p,B+'?v='+Date.now()); await sleep(3200);
  await ev(`window.__errs=window.__errs||[]; window.addEventListener('error',function(e){ __errs.push(String(e.message)+' @'+e.lineno); }); var s=document.createElement('style'); s.textContent='#tf-devbtn,#tf-devpanel{display:none!important}'; document.head.appendChild(s);`);
  await ev(`tfQaPreset('${pr}')`); await sleep(1200); };
await load('12');
const nick=await ev(`(function(){ var r=tfSSRows().filter(function(s){ return !s.me&&s.cfg&&s.cfg.fut&&s.cfg.lev>1; })[0]; return r.nick; })()`);
await ev(`location.hash='#/share/s/'+encodeURIComponent('${nick}')`); await sleep(1500);
await ev(`mkFollowSheet('${nick}')`); await sleep(600);
let s=await J(`(function(){ var d=document.querySelector('.mk-follow.skc'), cs=d?getComputedStyle(d):null, h=document.querySelector('.skc-hd h2'), hc=h?getComputedStyle(h):null, cta=document.getElementById('cps-cta'), cc=cta?getComputedStyle(cta):null, lime=[].filter.call(d?d.querySelectorAll('*'):[],function(e){ var c=getComputedStyle(e); return /200, 244, 60|200, 245, 66|197, 244, 59/.test(c.backgroundColor+c.color+c.borderColor); }).length;
  var r=d?d.getBoundingClientRect():{height:0}; return {bg:cs&&cs.backgroundColor,rad:cs&&cs.borderTopLeftRadius,h2:hc&&(hc.fontSize+' '+hc.fontWeight),ctaR:cc&&cc.borderTopLeftRadius,ctaDis:cta&&cta.disabled,lime:lime,h:Math.round(r.height),over:d?d.scrollHeight>d.clientHeight+1:null}; })()`);
ok('겉모습: #303030 반경 26, 제목 400, 흰 알약 단추(처음엔 꺼짐), 연두 없음',s.bg==='rgb(48, 48, 48)'&&s.rad==='26px'&&/ 400$/.test(s.h2)&&s.ctaR!=='0px'&&s.ctaDis===true&&s.lime===0,s);
if(!M) ok('데스크톱 900 높이에서 스크롤 없이 들어간다',s.over===false,s);
s=await J(`{lev:(document.querySelector('.skc-lev')||{}).innerText,pills:[].map.call(document.querySelectorAll('.skc-fld .skc-pills:not(.two) button'),function(b){ return b.innerText; }),on:(document.querySelector('.skc-pills button.on')||{}).innerText,sum:[].map.call(document.querySelectorAll('#mk-f-sum .r span'),function(x){ return x.innerText; }),adv:document.getElementById('skc-adv').hidden}`);
ok('레버리지 한 줄이 이름 바로 아래',/레버리지 변경도 원본을 따릅니다/.test(s.lev)&&/배/.test(s.lev),s);
ok('손실 중단 알약 10, 20, 30, 50 (기본 20)',s.pills.join()==='10%,20%,30%,50%'&&s.on==='20%',s);
ok('확인 행 4개, 복사 설정은 접힘',s.sum.join()==='복사 예산,손실 중단,시작 시점,주문당 예산 한도'&&s.adv===true,s);
await snap('K1-empty');
await ev(`(function(){ var e=document.getElementById('cps-amt'); e.value='50'; cpFormSync(); })()`); await sleep(200);
s=await J(`{err:document.getElementById('cps-amt-err').innerText,dis:document.getElementById('cps-cta').disabled,bad:document.getElementById('cps-amt-fld').classList.contains('bad')}`);
ok('최소 미달: 오류 한 줄, 단추 꺼짐',/최소/.test(s.err)&&s.dis&&s.bad,s); await snap('K2-under-min');
await ev(`(function(){ var e=document.getElementById('cps-amt'); e.value='800'; cpFormSync(); })()`); await sleep(200);
await ev(`skcLoss(-30,document.querySelectorAll('.skc-pills:not(.two) button')[2])`); await sleep(200);
s=await J(`{sum:[].map.call(document.querySelectorAll('#mk-f-sum .r b'),function(x){ return x.innerText; }),hint:document.getElementById('mk-f-lossh').innerText,dis:document.getElementById('cps-cta').disabled,loss:TF_MKF.loss}`);
ok('금액과 30% 선택 → 확인 행에 $800, $240 (30%), 단추 켜짐',s.sum[0]==='$800'&&/\$240 \(30%\)/.test(s.sum[1])&&!s.dis&&s.loss===-30,s);
await ev(`skcMore()`); await sleep(200); await ev(`skcEx('copy',document.querySelectorAll('#mk-f-ex button')[1])`); await sleep(200);
s=await J(`{adv:document.getElementById('skc-adv').hidden,sum:[].map.call(document.querySelectorAll('#mk-f-sum .r b'),function(x){ return x.innerText; }),ex:TF_MKF.existing}`);
ok('복사 설정 펼쳐 "현재 포지션부터" → 확인 행에 바로 반영',!s.adv&&s.sum[2]==='현재 포지션부터'&&s.ex==='copy',s); await snap('K3-filled-adv');
await ev(`window.AC_QA=null`); const before=await ev(`(cpState().copies||[]).length`);
await ev(`cpStart(TF_MKF.ne)`); await sleep(2200);
s=await J(`{n:(cpState().copies||[]).length,sheet:!!document.getElementById('mk-follow'),kyc:!!document.getElementById('ac-cf')}`);
ok('전략 복사 시작 → 복사가 하나 생기거나 본인 확인 관문',(s.n===before+1)||s.kyc,s);
await ev(`acConfirmClose(); mkFollowClose(true)`);
// 미연결 회원: 창 대신 플랜 화면
await load('02');
const nk2=await ev(`tfSSRows().filter(function(s){ return !s.me; })[0].nick`);
await ev(`mkFollowSheet('${nk2}')`); await sleep(1200);
s=await J(`{sheet:!!document.getElementById('mk-follow'),plan:!!document.getElementById('pl-root'),h1:(document.querySelector('#pl-root h1')||{}).innerText}`);
ok('거래소 미연결 회원: 복사 창 대신 플랜 화면',!s.sheet&&s.plan,s);
s=await J(`window.__errs`); ok('콘솔 오류 없음',Array.isArray(s)&&s.length===0,s);
const pass=out.filter(x=>x.startsWith('PASS')).length; out.push('','TOTAL '+pass+' / '+out.length); console.log(out[out.length-1]);
fs.writeFileSync(DIR+'skc-check'+sfx+'.txt',out.join('\n'));
await closePage(p);
