/* Source SVG output is frozen from 412fd60, not generated by the React renderer. */
import { createRoot } from 'react-dom/client'
import { ClientStrategyGlyph } from '../../src/components/ClientStrategyGlyph'
import { ClientStrategyListCard } from '../../src/components/ClientStrategyListCard'
import type { StrategyKind } from '../../src/client-strategy-classification'
import type { StrategyGlyphEvidence, StrategyVenue } from '../../src/client-strategy-identity'
import golden from './strategy-glyph-source.json'
import '../../src/client-strategy-sharing.css'

function host() {
  document.getElementById('root')?.remove()
  const root = document.createElement('main'); root.id = 'identity-test-root'; root.className = 'client-strategy-sharing'
  document.body.append(root); return createRoot(root)
}
export function mountGlyphs() {
  host().render(<div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 24, padding: 24 }}>
    {golden.cases.map(item => <section key={item.id} data-case={item.id}>
      <p>{item.kind} {item.id}{item.correctedOverlap ? ' · 겹침 교정' : ''}</p>
      <div style={{ display: 'flex', gap: 24, alignItems: 'center' }}>
        <div className="source" dangerouslySetInnerHTML={{ __html: item.svg }}/>
        <div className="react"><ClientStrategyGlyph kind={item.kind as StrategyKind} evidence={item.evidence as StrategyGlyphEvidence | undefined}/></div>
      </div>
    </section>)}
  </div>)
}
export function mountIdentityCards() {
  const evidence: StrategyGlyphEvidence[] = [
    { kind: 'rule', shape: 'diamond', rsiThreshold: 26, targetPercent: 20, trendFilter: true },
    { kind: 'agent', shape: 'square', universeSize: 8, selectedCount: 3 },
    { kind: 'mix', shape: 'diamond', universeSize: 3, rsiThreshold: 50, targetPercent: 5, trendFilter: false },
  ]
  host().render(<div className="strategy-list-container"><div className="strategy-list-grid">
    {evidence.map((glyph, index) => <ClientStrategyListCard key={index} title={`공급된 원문 ${index}`} asset="BTC / USDT" kind={glyph.kind} glyph={glyph}
      venue={index === 0 ? { name: 'Binance', logo: 'binance' } : index === 1 ? { name: '사용자가 지정한 아주 긴 거래소 이름 '.repeat(5), logo: 'okx' } : { name: '<img src=x onerror=alert(1)> $& {venue}', logo: 'https://example.invalid/tracker' as StrategyVenue['logo'] }}
      followers={0} performance={null} location={{ nick: String(index), period: 'all' }} onNavigate={() => {}}/>)}
  </div></div>)
}
