import type { ClientLanguage } from './client-preferences'

type Translations = readonly [string, string, string, string, string, string, string]
const column = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const satisfies Record<ClientLanguage, number>
export const accountPlanCopy = {
  freeLow: ["얼마 남지 않음","Running low","残りわずか","即将用尽","即將用盡","Queda poco","Presque épuisé"],
  freeValue: ["무료","Free","無料","免费","免費","Gratis","Gratuit"],
  trialInUse: ["체험 중","In trial","トライアル中","试用中","試用中","En prueba","En essai"],
  freeStatus: ["이용 상태: 무료 체험","Status: Free trial","利用状況: 無料トライアル","使用状态: 免费试用","使用狀態: 免費試用","Estado: prueba gratuita","Statut : Essai gratuit"],
  uidAlwaysFree: ["UID 연동 시 상시 무료","Always free with UID link","UID連携で常時無料","绑定 UID 始终免费","綁定 UID 始終免費","Siempre gratis vinculando tu UID","Toujours gratuit en associant l'UID"],
  spentValue: ["소진","Exhausted","消費済み","已用尽","已用盡","Agotado","Épuisé"],
  trialExhausted: ["무료 체험 소진","Free trial exhausted","無料トライアル終了","免费试用已用尽","免費試用已用盡","Prueba gratuita agotada","Essai gratuit épuisé"],
  continueLinkOrSubscribe: ["연동 또는 구독으로 계속","Continue with link or subscribe","連携またはサブスクで継続","绑定或订阅以继续","綁定或訂閱以繼續","Continúa vinculando o suscribiéndote","Continuer avec liaison ou abonnement"],
  rebateTotal: ["누적 적립","Accumulated Rebates","累計還元","累计返佣","累計返佣","Reembolsos acumulados","Remboursements cumulés"],
  simulation: ["시뮬레이션","Simulation","シミュレーション","模拟","模擬","Simulación","Simulation"],
  rebateLabel: ["현재까지 누적된 거래 수수료 적립","Trading fee rebates accumulated to date","現在までに累積された取引手数料還元","截至目前累计的交易手续费返佣","截至目前累計的交易手續費返佣","Reembolsos de comisiones acumulados hasta la fecha","Remboursements de frais cumulés à ce jour"],
  rebateAmount: ["수수료 적립 금액","Fee Rebate Amount","手数料還元額","手续费返佣金额","手續費返佣金額","Importe del reembolso de comisiones","Montant du remboursement des frais"],
  rebateDescription: ["체결 건별로 적립되며, 적립금은 이용료 차감에 사용될 예정이에요. 시뮬레이션 체결 기준이며 실제 정산이 아니에요.","Credited per filled order; rebates will be used to offset service fees. Based on simulated fills, not actual settlement.","約定ごとに還元され、積立金は利用料の控除に使用される予定です。シミュレーション約定に基づくもので、実際の精算ではありません。","按每笔成交累积，返佣将用于抵扣服务费。基于模拟成交计算，并非实际结算。","按每筆成交累積，返佣將用於抵扣服務費。基於模擬成交計算，並非實際結算。","Se acumula por operación ejecutada y se usará para deducir tarifas del servicio. Basado en ejecuciones simuladas, no es una liquidación real.","Crédité par exécution et destiné à déduire les frais de service. Basé sur des exécutions simulées, il ne s'agit pas d'un règlement réel."],
  rebateCount: ["적립 건수","Rebate Count","還元件数","返佣笔数","返佣筆數","Número de reembolsos","Nombre de remboursements"],
  recordCount: ["{count}건","{count} records","{count}件","{count} 条","{count} 筆","{count} registros","{count} enregistrements"],
  recordCountOne: ["{count}건","{count} record","{count}件","{count} 条","{count} 筆","{count} registro","{count} enregistrement"],
  rebateRate: ["적립률","Rebate Rate","還元率","返佣率","返佣率","Tasa de reembolso","Taux de remboursement"],
  rebateRateValue: ["수수료(0.2%)의 10%","10% of fee (0.2%)","手数料(0.2%)の10%","手续费(0.2%)的 10%","手續費(0.2%)的 10%","10% de la comisión (0,2%)","10 % des frais (0,2 %)"],
  goTrading: ["내 트레이딩으로 이동","Go to My Trading","マイトレードへ移動","前往我的交易","前往我的交易","Ir a Mis operaciones","Aller à Mes transactions"],
  rebateHistory: ["적립 내역","Rebate History","還元履歴","返佣明细","返佣明細","Historial de reembolsos","Historique des remboursements"],
  recentRecords: ["최근 {count}건 표시","Showing {count} recent records","直近{count}件を表示","显示最近 {count} 条","顯示最近 {count} 筆","Mostrando {count} registros recientes","Affichage de {count} enregistrements récents"],
  recentRecordOne: ["최근 {count}건 표시","Showing {count} recent record","直近{count}件を表示","显示最近 {count} 条","顯示最近 {count} 筆","Mostrando {count} registro reciente","Affichage de {count} enregistrement récent"],
  noHistory: ["내역 없음","No history","履歴なし","暂无记录","暫無紀錄","Sin historial","Aucun historique"],
  fill: ["체결 {id}","Fill {id}","約定 {id}","成交 {id}","成交 {id}","Ejecución {id}","Exécution {id}"],
  fillConfirmed: ["{date}, 체결 확정","{date}, fill confirmed","{date}、約定確定","{date}，成交已确认","{date}，成交已確認","{date}, ejecución confirmada","{date}, exécution confirmée"],
  rebateEmpty: ["아직 적립된 내역이 없어요","No rebates accumulated yet","まだ還元の履歴がありません","暂无返佣记录","暫無返佣記錄","Aún no hay reembolsos acumulados","Aucun remboursement pour le moment"],
  rebateEmptyDescription: ["전략 거래가 체결되면 파트너 거래 수수료의 10%가 이곳에 자동으로 적립돼요.","When a strategy trade is filled, 10% of partner trading fees will be automatically credited here.","戦略取引が約定すると、提携取引所の手数料の10%がここに自動で還元されます。","策略交易成交后，合作方交易手续费的 10% 将自动累积在此处。","策略交易成交後，合作方交易手續費的 10% 將自動累積在此處。","Cuando se ejecute una operación de estrategia, el 10% de las comisiones del socio se acreditará aquí automáticamente.","Lorsqu'une transaction de stratégie est exécutée, 10 % des frais de trading partenaires sont automatiquement crédités ici."],
  goTradingEmpty: ["내 트레이딩으로 이동하기","Go to My Trading","マイトレードへ移動する","前往我的交易","前往我的交易","Ir a Mis operaciones","Aller à Mes transactions"],
  reviewExpired: ["연결된 복기가 보관 기간을 지나 정리됐어요","The linked review has expired and was cleaned up","関連する取引振り返りは保管期間を過ぎたため整理されました","关联的复盘记录已过保留期限并已被清理","關聯的複盤紀錄已過保留期限並已被清理","La revisión vinculada superó el período de retención y se ha eliminado","Le compte-rendu lié a dépassé la période de conservation et a été purgé"],
  positionPreference: ["포지션 진입/청산","Position Entry/Exit","ポジションの新規建て/決済","持仓建仓/平仓","持倉開倉/平倉","Entrada/Cierre de posición","Entrée/Sortie de position"],
  positionDescription: ["전략의 체결이 확정될 때","When a strategy fill is confirmed","戦略の約定が確定したとき","策略成交确认时","策略成交確認時","Cuando se confirma la ejecución de una estrategia","Lorsqu'une exécution de stratégie est confirmée"],
  lossPreference: ["손실 단계 경고","Loss Threshold Alert","損失段階の警告","亏损阶梯预警","虧損階梯預警","Alerta de nivel de pérdidas","Alerte de seuil de perte"],
  lossDescription: ["평가 손실이 단계에 진입할 때","When unrealized loss enters a threshold level","評価損が設定段階に入ったとき","浮动亏损达到预警阶梯时","浮動虧損達到預警階梯時","Cuando las pérdidas no realizadas alcanzan un nivel","Lorsque la perte latente atteint un palier"],
  reviewPreference: ["거래복기 리포트","Trade Review Report","取引振り返りレポート","交易复盘报告","交易複盤報告","Informe de revisión de operaciones","Rapport de revue de transaction"],
  reviewDescription: ["체결 복기가 생성될 때","When a fill review is generated","約定振り返りが作成されたとき","生成成交复盘时","生成成交覆盤時","Cuando se genera una revisión de ejecución","Lorsqu'un compte-rendu d'exécution est généré"],
  rebatePreference: ["수수료 적립","Fee Rebates","手数料還元","手续费返佣","手續費返佣","Reembolso de comisiones","Remboursement des frais"],
  rebatePreferenceDescription: ["적립이 확정될 때","When a rebate is confirmed","還元が確定したとき","返佣确认时","返佣確認時","Cuando se confirma un reembolso","Lorsqu'un remboursement est confirmé"],
  watchPreference: ["관심 종목 소식","Watchlist Updates","お気に入り銘柄の更新","自选标的动态","自選標的動態","Novedades de favoritos","Actualités des favoris"],
  watchDescription: ["데모에서는 실행 이벤트만 수신해요","In demo mode, only execution events are received","デモモードでは実行イベントのみ受信します","演示模式下仅接收执行事件","示範模式下僅接收執行事件","En el modo demo, solo se reciben eventos de ejecución","En mode démo, seuls les événements d'exécution sont reçus"],
  inboxPreference: ["앱 내 수신함","In-App Inbox","アプリ内受信トレイ","站内收件箱","站內收件箱","Buzón en la app","Boîte de réception intégrée"],
  inboxDescription: ["기본 채널이라 항상 동작해요","Default channel, always active","デフォルトのチャンネルのため常に動作します","默认渠道，始终可用","預設渠道，始終可用","Canal predeterminado, siempre activo","Canal par défaut, toujours actif"],
  kakaoPreference: ["카카오톡","KakaoTalk","カカオトーク","KakaoTalk","KakaoTalk","KakaoTalk","KakaoTalk"],
  channelDescription: ["데모에서는 설정만 저장돼요","In demo mode, only settings are saved","デモモードでは設定のみ保存されます","演示模式下仅保存设置","示範模式下僅保存設定","En el modo demo, solo se guarda la configuración","En mode démo, seuls les paramètres sont enregistrés"],
  telegramPreference: ["텔레그램","Telegram","Telegram","Telegram","Telegram","Telegram","Telegram"],
  emailPreference: ["이메일 리포트","Email Report","メールレポート","邮件报告","郵件報告","Informe por correo electrónico","Rapport par e-mail"],
  channels: ["수신 채널","Notification Channels","通知チャンネル","接收渠道","接收渠道","Canales de recepción","Canaux de notification"],
  notificationKinds: ["어떤 알림을 받을까요","Notifications to Receive","受信する通知","接收哪些通知","接收哪些通知","¿Qué notificaciones quieres recibir?","Quelles notifications recevoir ?"],
  channelCount: ["4개 채널","4 channels","4つのチャンネル","4 个渠道","4 個渠道","4 canales","4 canaux"],
  kindCount: ["5개 항목","5 items","5項目","5 个项目","5 個項目","5 elementos","5 éléments"],
  defaultChannel: ["기본","Default","デフォルト","默认","預設","Predeterminado","Par défaut"],
  preferenceFooter: ["체험 모드에서는 외부 채널 발송이 일어나지 않아요. 설정은 저장돼요.","In trial mode, notifications are not sent to external channels. Settings are saved.","体験モードでは外部チャンネルへの送信は行われません。設定は保存されます。","体验模式下不会向外部渠道发送通知。设置将被保存。","體驗模式下不會向外部渠道發送通知。設定將被保存。","En el modo de prueba no se envían notificaciones a canales externos. La configuración se guardará.","En mode d'essai, aucun envoi vers des canaux externes n'est effectué. Les paramètres sont enregistrés."],
  planUnavailable: ["플랜 상태를 확인할 수 없어요","Unable to check plan status","プランの状態を確認できません","无法确认方案状态","無法確認方案狀態","No se puede verificar el estado del plan","Impossible de vérifier le statut du forfait"],
  invalidSource: ["원본 체험 상태 또는 기준 시간을 확인할 수 없어요.","Unable to verify the original trial status or reference time.","元の体験状態または基準時間を確認できません。","无法确认原始体验状态或基准时间。","無法確認原始體驗狀態或基準時間。","No se puede verificar el estado de prueba original ni la hora de referencia.","Impossible de vérifier le statut d'essai d'origine ou l'heure de référence."],
  invalidValues: ["플랜 표시를 위한 체험 수치가 유효하지 않아요.","The trial metrics for displaying the plan are invalid.","プラン表示のための体験数値が無効です。","用于显示方案的体验数值无效。","用於顯示方案的體驗數值無效。","Los valores de prueba para mostrar el plan no son válidos.","Les valeurs d'essai pour afficher le forfait ne sont pas valides."],
  basic: ["기본 분석","Basic Analysis","基本分析","基础分析","基礎分析","Análisis básico","Analyse de base"],
  guestDescription: ["로그인 후 PLAN 및 크레딧을 확인할 수 있어요.","Log in to check your PLAN and credits.","ログイン後にPLANおよびクレジットを確認できます。","登录后即可查看 PLAN 及额度。","登入後即可查看 PLAN 及額度。","Inicia sesión para consultar el PLAN y los créditos.","Connectez-vous pour consulter le PLAN et les crédits."],
  membership: ["PRO 멤버십","PRO Membership","PROメンバーシップ","PRO会员","PRO會員","Membresía PRO","Adhésion PRO"],
  unlimited: ["무제한","Unlimited","無制限","无限制","無限制","Ilimitado","Illimité"],
  memberActive: ["멤버십: 구독 중","Membership: Subscribed","メンバーシップ: 購読中","会员：订阅中","會員：訂閱中","Membresía: Suscrita","Adhésion : Abonné"],
  unlimitedUse: ["무제한 이용","Unlimited Use","無制限利用","无限制使用","無限制使用","Uso ilimitado","Utilisation illimitée"],
  paidDescription: ["구독 중이라 PRO 분석이 무제한이에요.","PRO analysis is unlimited with your subscription.","購読中のためPRO分析が無制限です。","由于处于订阅中，PRO分析无限制使用。","由於處於訂閱中，PRO分析無限制使用。","El análisis PRO es ilimitado gracias a tu suscripción.","L'analyse PRO est illimitée grâce à votre abonnement."],
  tradeBadge: ["PRO 활성 (무제한)","PRO Active (Unlimited)","PROアクティブ（無制限）","PRO已激活（无限制）","PRO已啟用（無限制）","PRO Activo (Ilimitado)","PRO Actif (Illimité)"],
  tradeActive: ["이용 상태: 무제한 활성","Usage Status: Unlimited Active","利用状態: 無制限アクティブ","使用状态：无限制激活","使用狀態：無限制啟用","Estado de uso: Activo ilimitado","Statut d'utilisation : Actif illimité"],
  expires: ["만료일 {date}","Expires {date}","有効期限 {date}","到期日 {date}","到期日 {date}","Vencimiento {date}","Expiration {date}"],
  tradeDescription: ["파트너 거래소 거래가 활성 상태라 PRO 분석이 무제한이에요. (거래 인정 기간 {days}일)","Partner exchange trading is active, making PRO analysis unlimited. (Trade recognition period: {days} days)","提携取引所の取引がアクティブなためPRO分析が無制限です。（取引認定期間: {days}日）","合作交易所交易处于活跃状态，PRO分析无限制使用。（交易认定有效期 {days} 天）","合作交易所交易處於活躍狀態，PRO分析無限制使用。（交易認定有效期 {days} 天）","El trading en el exchange asociado está activo, por lo que el análisis PRO es ilimitado. (Período de reconocimiento de trading: {days} días)","Le trading sur l'exchange partenaire est actif, l'analyse PRO est donc illimitée. (Période de reconnaissance du trading : {days} jours)"],
  inUse: ["이용 중","In Use","利用中","使用中","使用中","En uso","En cours d'utilisation"],
  normal: ["이용 상태: 정상","Usage Status: Normal","利用状態: 正常","使用状态：正常","使用狀態：正常","Estado de uso: Normal","Statut d'utilisation : Normal"],
  volumeRecharge: ["거래량 연동 자동 충전","Volume-Linked Auto Recharge","取引量連動の自動チャージ","交易量联动自动充值","交易量連動自動加值","Recarga automática vinculada al volumen","Recharge automatique liée au volume"],
  creditDescription: ["UID 연동으로 PRO 분석을 사용 중이에요. 거래량에 따라 자동으로 충전돼요.","You are using PRO analysis with UID linking. It recharges automatically based on trading volume.","UID連携によりPRO分析をご利用中です。取引量に応じて自動的にチャージされます。","已通过 UID 绑定使用 PRO 分析。将根据交易量自动充值。","已透過 UID 綁定使用 PRO 分析。將根據交易量自動加值。","Estás utilizando el análisis PRO mediante la vinculación de UID. Se recarga automáticamente según el volumen de trading.","Vous utilisez l'analyse PRO via la liaison UID. Elle se recharge automatiquement selon le volume de trading."],
  freeTrial: ["무료 체험","Free Trial","無料体験","免费体验","免費體驗","Prueba gratuita","Essai gratuit"],
  freeDescription: ["로그인 무료 체험으로 고급 분석을 사용 중이에요. UID 를 연동하면 AI 이용 크레딧 $100 혜택을 받아요.","You are using advanced analysis with the login free trial. Link your UID to receive $100 in AI usage credits.","ログイン無料体験で高度分析をご利用中です。UIDを連携するとAI利用クレジット$100の特典を受け取れます。","正在通过登录免费体验使用高级分析。绑定 UID 即可享受 $100 AI使用额度福利。","正在透過登入免費體驗使用進階分析。綁定 UID 即可享有 $100 AI使用額度福利。","Estás utilizando el análisis avanzado con la prueba gratuita de inicio de sesión. Vincula tu UID para recibir un beneficio de $100 en créditos de uso de IA.","Vous utilisez l'analyse avancée grâce à l'essai gratuit de connexion. Associez votre UID pour recevoir un avantage de $100 en crédits d'utilisation de l'IA."],
  upgradeRequired: ["업그레이드 필요","Upgrade Required","アップグレードが必要","需要升级","需要升級","Actualización requerida","Mise à niveau requise"],
  exhaustedDescription: ["무료 분석 사용량을 모두 썼어요. UID 연동(무료) 또는 구독으로 계속 사용할 수 있어요.","You have used all of your free analyses. You can continue with UID linking (free) or a subscription.","無料分析の利用枠をすべて使い切りました。UID連携（無料）または購読で引き続きご利用いただけます。","免费分析额度已全部用尽。可通过 UID 绑定（免费）或订阅继续使用。","免費分析額度已全部用盡。可透過 UID 綁定（免費）或訂閱繼續使用。","Has usado todos tus análisis gratuitos. Puedes continuar con la vinculación de UID (gratis) o una suscripción.","Vous avez utilisé toutes vos analyses gratuites. Vous pouvez continuer avec la liaison UID (gratuit) ou un abonnement."],
  level: ["현재 AI 수준","Current AI Level","現在のAIレベル","当前 AI 等级","當前 AI 等級","Nivel actual de IA","Niveau actuel de l'IA"],
  usageStatus: ["이용 상태","Usage Status","利用状態","使用状态","使用狀態","Estado de uso","Statut d'utilisation"],
  linkFree: ["무료로 UID 연동하기 (Fast API)","Link UID for Free (Fast API)","無料でUIDを連携する（Fast API）","免费绑定 UID（Fast API）","免費綁定 UID（Fast API）","Vincular UID gratis (Fast API)","Lier gratuitement l'UID (Fast API)"],
  upgrade: ["구독으로 업그레이드","Upgrade to Subscription","購読にアップグレード","升级为订阅","升級為訂閱","Actualizar a suscripción","Passer à l'abonnement"],
  previewFooter: ["체험 모드에서는 응답 모델이 동일하며 크레딧 차감만 재현돼요. 크레딧 정책 v{version}.","In trial mode, the response model is identical and only credit deductions are simulated. Credit policy v{version}.","体験モードでは応答モデルは同一であり、クレジット消費のみが再現されます。クレジットポリシー v{version}。","在体验模式下，响应模型相同，仅模拟额度扣除。额度政策 v{version}。","在體驗模式下，回應模型相同，僅模擬額度扣除。額度政策 v{version}。","En el modo de prueba, el modelo de respuesta es idéntico y solo se simula la deducción de créditos. Política de créditos v{version}.","En mode d'essai, le modèle de réponse est identique et seule la déduction de crédits est simulée. Politique de crédits v{version}."],
  details: ["상태 및 연동 상세","Status and Linking Details","状態および連携の詳細","状态与绑定详情","狀態與綁定詳情","Detalles de estado y vinculación","Détails du statut et de la liaison"],
  uidLink: ["UID 연동","UID Linking","UID連携","UID绑定","UID綁定","Vinculación de UID","Liaison UID"],
  partnerAccount: ["거래소 파트너 연동 계정","Exchange Partner Linked Account","取引所パートナー連携アカウント","交易所合作绑定账户","交易所合作綁定帳戶","Cuenta vinculada de exchange asociado","Compte lié de l'exchange partenaire"],
  linkedFree: ["연동됨 (무료)","Linked (Free)","連携済み（無料）","已绑定（免费）","已綁定（免費）","Vinculado (Gratis)","Lié (Gratuit)"],
  unlinked: ["미연동","Unlinked","未連携","未绑定","未綁定","No vinculado","Non lié"],
  partnerActivity: ["파트너 거래 활성","Partner Trading Active","パートナートレード有効","合作交易活跃","合作交易活躍","Trading asociado activo","Trading partenaire actif"],
  activityDescription: ["체결 1회 시 {days}일 무제한 적용","Unlimited access applied for {days} days upon 1 executed trade","約定1回につき{days}日間無制限適用","成交 1 笔即享 {days} 天无限制","成交 1 筆即享 {days} 天無限制","Acceso ilimitado durante {days} días por 1 operación ejecutada","Accès illimité pendant {days} jours pour 1 transaction exécutée"],
  activeUntil: ["{date} 까지 활성","Active until {date}","{date}までアクティブ","活跃至 {date}","啟用至 {date}","Activo hasta el {date}","Actif jusqu'au {date}"],
  none: ["없음","None","なし","无","無","Ninguno","Aucun"],
  subscription: ["구독 멤버십","Subscription Membership","サブスクリプションメンバーシップ","订阅会员","訂閱會員","Membresía de suscripción","Abonnement de membre"],
  monthlyPlan: ["월간 PRO 정기 결제 플랜","Monthly PRO Recurring Plan","月額PRO定期決済プラン","月度 PRO 定期续费方案","月度 PRO 定期續費方案","Plan mensual recurrente PRO","Forfait mensuel récurrent PRO"],
  subscribed: ["구독 중","Subscribed","購読中","订阅中","訂閱中","Suscrito","Abonné"],
  responseCost: ["고급 응답 비용","Advanced Response Cost","高度応答コスト","高级响应费用","進階回應費用","Costo de respuesta avanzada","Coût de réponse avancée"],
  responseUsage: ["PRO 심층 분석 사용량 기반","Based on PRO Deep Analysis Usage","PRO深層分析の使用量に基づく","基于 PRO 深度分析使用量","基於 PRO 深度分析使用量","Basado en el uso de análisis profundo PRO","Basé sur l'utilisation de l'analyse approfondie PRO"],
  noDebit: ["차감 없음","No deduction","消費なし","不扣除","不扣除","Sin deducción","Aucune déduction"],
  usageDebit: ["이용량 기반 차감","Usage-based deduction","利用量に基づく消費","按使用量扣除","按使用量扣除","Deducción según el uso","Déduction basée sur l'utilisation"],
  description: ['AI 수준, 수수료 적립, 알림 수신을 관리해요', 'Manage your AI level, fee rebates, and notifications', 'AIのレベル、手数料の還元、通知の受信を管理できます', '管理 AI 级别、手续费返还和通知接收', '管理 AI 等級、手續費回饋與通知接收', 'Gestiona el nivel de IA, los reembolsos de comisiones y las notificaciones', 'Gérez le niveau d’IA, les remises de frais et la réception des notifications'],
  navigation: ['PLAN 화면', 'PLAN screen', 'PLAN 画面', 'PLAN 界面', 'PLAN 畫面', 'Pantalla PLAN', 'Écran PLAN'],
  plan: ['플랜', 'Plan', 'プラン', '方案', '方案', 'Plan', 'Formule'],
  rebates: ['정산', 'Settlement', '精算', '结算', '結算', 'Liquidación', 'Règlement'],
  alerts: ['알림 설정', 'Alert settings', '通知設定', '通知设置', '通知設定', 'Ajustes de alertas', 'Paramètres d’alertes'],
  unavailable: ['계정 상태를 확인할 수 없어요', 'We can’t check your account status', 'アカウントの状態を確認できません', '无法确认账户状态', '無法確認帳戶狀態', 'No se puede comprobar el estado de la cuenta', 'Impossible de vérifier l’état du compte'],
} as const satisfies Record<string, Translations>
export function accountPlanText(language: ClientLanguage, key: keyof typeof accountPlanCopy, values: Readonly<Record<string, string>> = {}): string {
  return accountPlanCopy[key][column[language]].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? values[name] : token)
}
