import type { ClientLanguage } from './client-preferences'

// Korean source copy is unchanged; AGY supplied bounded UI translations.
const rows = {
  excludedConditions: ['검증에서 뺀 조건', 'Excluded conditions', '検証から除外した条件', '验证排除条件', '驗證排除條件', 'Condiciones excluidas', 'Conditions exclues'],
  rsiRebound: ['RSI가 {rsi} 아래로 내려갔다가 하루 0.5% 넘게 반등한 날', 'Days when RSI is below {rsi} and the price rebounds by more than 0.5% in a day', 'RSIが{rsi}を下回り、価格が1日で0.5%超反発した日', 'RSI低于{rsi}且价格单日反弹超过0.5%的日子', 'RSI低於{rsi}且價格單日反彈超過0.5%的日子', 'Días con RSI por debajo de {rsi} y un rebote del precio de más del 0,5% en un día', 'Jours avec un RSI inférieur à {rsi} et un rebond du prix de plus de 0,5 % en une journée'],
  summaryTitle: ["전략 계약서","Strategy Agreement","戦略契約書","策略协议","策略協議","Contrato de estrategia","Contrat de stratégie"],
  asset: ["자산","Asset","資産","资产","資產","Activo","Actif"],
  buyWhen: ["사는 때","When to buy","買い時","买入时机","買入時機","Cuándo comprar","Quand acheter"],
  sellWhen: ["파는 때","When to sell","売り時","卖出时机","賣出時機","Cuándo vender","Quand vendre"],
  testPeriod: ["돌려 볼 기간","Test period","テスト期間","测试期间","測試期間","Período de prueba","Période de test"],
  requestedFrame: ["대화에서 고른 주기","Timeframe chosen in conversation","会話で選択した周期","对话中选择的周期","對話中選擇的週期","Intervalo elegido en la conversación","Période choisie dans la conversation"],
  frameHour: ["1시간봉","1-hour candle","1時間足","1小时K线","1小時K線","Vela de 1 hora","Bougie de 1 heure"],
  revise: ["다시 답하기","Answer again","もう一度答える","重新回答","重新回答","Responder de nuevo","Répondre à nouveau"],
  resume: ["이어서 보기","Resume","続きを見る","继续查看","繼續查看","Continuar viendo","Continuer"],
  verifying: ["전략 검증","Strategy verification","戦略検証","策略验证","策略驗證","Verificación de estrategia","Vérification de la stratégie"],
  rebound: ["적당히 밀렸다가 하루 0.5% 넘게 반등한 날","Days with a moderate pullback followed by a rebound of over 0.5% in a day","適度に下落した後、1日で0.5%超反発した日","适度回调后单日反弹超过0.5%的日子","適度回調後單日反彈超過0.5%之日","Día con retroceso moderado y posterior rebote de más del 0.5% en un día","Jour de repli modéré suivi d'un rebond de plus de 0.5% en une journée"],
  clearTrend: ["방향이 뚜렷할 때만","Only when the direction is clear","方向性が明確なときのみ","仅在方向明确时","僅在方向明確時","Solo cuando la dirección sea clara","Uniquement lorsque la direction est claire"],
  exitRule: ["{stop}% 내리면, 또는 25일이 지나면","If it drops by {stop}%, or after 25 days","{stop}%下落した場合、または25日が経過した場合","下跌{stop}%，或过去25天后","下跌{stop}%，或過去25天後","Si cae un {stop}%, o pasados 25 días","En cas de baisse de {stop}%, ou après 25 jours"],
  takeRule: ["+{take}% 오르거나","+{take}% rise, or","+{take}%上昇するか、","上涨+{take}%，或","上漲+{take}%，或","Sube un +{take}%, o","Hausse de +{take}%, ou"],
  summaryPreview: ["합성 일별 자료로 계산하는 미리보기입니다. 실제 시세나 실제 거래 체결이 아니며, 완료된 거래마다 0.2% 비용을 반영합니다.","This is a preview calculated using synthetic daily data. It is not actual market quotes or real trade execution, and reflects a 0.2% fee for each completed trade.","合成日次データで計算されたプレビューです。実際の相場や実際の約定ではなく、完了した取引ごとに0.2%のコストを反映しています。","这是使用合成日度数据计算的预览。并非实际行情或真实交易成交，每笔已完成的交易均计入0.2%的费用。","這是使用合成日度數據計算的預覽。並非實際行情或真實交易成交，每筆已完成的交易均計入0.2%的費用。","Esta es una vista previa calculada con datos diarios sintéticos. No corresponde a cotizaciones reales ni a ejecuciones reales, y refleja un costo del 0.2% por cada operación completada.","Il s'agit d'un aperçu calculé à partir de données quotidiennes synthétiques. Il ne s'agit pas de cours réels ni d'exécutions réelles, et un coût de 0.2% est appliqué à chaque transaction terminée."],
  months: ["월별 수익률", 'Monthly breakdown', '月ごとの推移', '每月表现', '每月表現', 'Mes a mes', 'Mois par mois'],
  partial: ['일부', 'Partial', '一部', '部分', '部分', 'Parcial', 'Partiel'],
  monthSummary: ["한 달 전체를 계산한 {total}개월 중 {up}개월에 수익이 났습니다","Out of {total} full months calculated, {up} were profitable.","1か月全体を計算した{total}か月のうち、{up}か月で利益が出ました。","按整月计算的{total}个月中，有{up}个月实现盈利。","按整月計算的{total}個月中，有{up}個月實現盈利。","De los {total} meses completos calculados, {up} fueron rentables.","Sur les {total} mois complets calculés, {up} ont été rentables."],
  chartKeys: ["방향키로 날짜를 살펴보고 Enter를 누르면 판단 근거가 열립니다. Home과 End는 처음과 마지막 날짜로 이동합니다.","Use the arrow keys to browse dates and press Enter to open the decision rationale. Home and End move to the first and last dates.","方向キーで日付を確認し、Enterを押すと判断根拠が開きます。HomeとEndで最初と最後の日付に移動します。","使用方向键浏览日期，按 Enter 打开判断依据。Home 和 End 移动至起始和最后日期。","使用方向鍵瀏覽日期，按 Enter 開啟判斷依據。Home 和 End 移動至起始與最後日期。","Use las teclas de flecha para explorar las fechas y presione Enter para abrir los fundamentos de la decisión. Home y End se desplazan a la primera y última fecha.","Utilisez les touches fléchées pour parcourir les dates et appuyez sur Entrée pour ouvrir les motifs de décision. Home et End permettent d'accéder à la première et à la dernière date."],
  openDecision: ["판단 근거 보기","View decision rationale","判断根拠を見る","查看判断依据","查看判斷依據","Ver fundamentos de la decisión","Afficher les motifs de décision"],
  chartBalance: ["그날의 잔고","Balance on that day","その日の残高","当日余额","當日餘額","Saldo de ese día","Solde du jour"],
  sort: ["정렬","Sort","並び替え","排序","排序","Ordenar","Trier"],
  new: ["최신순","Newest first","新しい順","最新优先","最新優先","Más recientes primero","Plus récents d'abord"],
  old: ["오래된순","Oldest first","古い順","最早优先","最舊優先","Más antiguos primero","Plus anciens d'abord"],
  big: ["결과가 큰 순","Largest result first","結果が大きい順","结果最大优先","結果最大優先","Mayor resultado primero","Plus grand résultat d'abord"],
  kinds: ["판단 종류","Decision types","判断の種類","决策类型","決策類型","Tipos de decisión","Types de décision"],
  allRecords: ["전체 기록","All records","すべての記録","全部记录","全部紀錄","Todos los registros","Tous les enregistrements"],
  watch: ["관망","Observe","様子見","观望","觀望","Observar","Observer"],
  holdingDecision: ["그대로 유지","Hold position","保有継続","继续持有","繼續持有","Mantener posición","Conserver la position"],
  holdGroup: ['그대로 유지 {count}번', 'Position held: {count} times', '保有継続 {count}回', '继续持有 {count}次', '繼續持有 {count}次', 'Posición mantenida {count} veces', 'Position conservée {count} fois'],
  holdRange: ['{from}부터 {to}까지 조건에 맞아 그대로 뒀습니다', 'Held from {from} to {to} as conditions were met', '{from}から{to}まで条件に従い保有を継続しました', '从{from}到{to}符合条件，继续持有', '從{from}到{to}符合條件，繼續持有', 'Se mantuvo la posición del {from} al {to} al cumplirse las condiciones', 'Position conservée du {from} au {to} (conditions remplies)'],
  year: ['연도', 'Year', '年', '年份', '年份', 'Año', 'Année'],
  annual: ['연간', 'Annual', '年間', '年度', '年度', 'Anual', 'Annuel'],
  noMonth: ['관측 없음', 'No observations', '観測なし', '无观测', '無觀測', 'Sin observaciones', 'Aucune observation'],
  moreDecisions: ["이전 판단 더 보기","View earlier decisions","以前の判断をさらに表示","查看更早的决策","查看更早的決策","Ver decisiones anteriores","Voir les décisions antérieures"],
  noDecisions: ["이 종류의 판단은 없었습니다","No decisions of this type were found.","この種類の判断はありませんでした。","未找到此类决策记录。","未找到此類決策紀錄。","No se encontraron decisiones de este tipo.","Aucune décision de ce type n'a été trouvée."],
  allViewed: ["모든 판단을 확인했습니다","All decisions have been viewed.","すべての判断を確認しました。","已查看全部决策。","已查看全部決策。","Se han revisado todas las decisiones.","Toutes les décisions ont été consultées."],
  facts: ["그날 확인한 값","Observed values for the day","その日に確認した数値","当日观察指标","當日觀察指標","Valores observados del día","Valeurs observées ce jour-là"],
  price: ["그날의 가격","Price on that day","その日の価格","当日价格","當日價格","Precio de ese día","Prix ce jour-là"],
  previousRsi: ["전봉 RSI","Previous bar RSI","前足RSI","前一根K线RSI","前一根K線RSI","RSI de la vela anterior","RSI du chandelier précédent"],
  dailyChange: ["하루 가격 변화","Daily price change","1日の価格変動","单日价格变动","單日價格變動","Variación diaria de precio","Variation quotidienne du prix"],
  trendGap: ["이평 괴리","MA disparity","移動平均乖離","均线乖离率","均線乖離率","Disparidad respecto a la media móvil","Écart à la moyenne mobile"],
  outcome: ["이 거래의 결과","Trade outcome","この取引の結果","本笔交易结果","本筆交易結果","Resultado de esta operación","Résultat de cette transaction"],
  decisionRule: ["확인한 규칙","Evaluated rule","適用されたルール","触发规则","觸發規則","Regla evaluada","Règle évaluée"],
  waiting: ["청산 조건 대기","Awaiting exit condition","決済条件の待機中","等待平仓条件","等待平倉條件","Esperando condición de cierre","En attente de la condition de clôture"],
  holding: ['보유 기간', 'Holding period', '保有期間', '持仓时间', '持倉時間', 'Período de tenencia', 'Durée de détention'],
  title: ["백테스트","Backtest","バックテスト","回测","回測","Backtest","Backtest"],
  open: ["과거로 돌려 보기","Replay Past","過去データを再生","回放历史","重放歷史","Reproducir histórico","Rejouer l'historique"],
  ready: ["돌려 볼 조건","Test Parameters","テスト条件","回测条件","回測條件","Condiciones de prueba","Conditions de test"],
  period: ["기간","Period","期間","周期","期間","Período","Période"],
  amount: ["시작 금액","Initial Capital","初期資金","初始金额","初始金額","Capital inicial","Capital initial"],
  p90: ["최근 3개월","Last 3 Months","直近3ヶ月","最近3个月","最近3個月","Últimos 3 meses","3 derniers mois"],
  p365: ["최근 1년","Last 1 Year","直近1年","最近1年","最近1年","Último año","Dernière année"],
  p730: ["최근 2년","Last 2 Years","直近2年","最近2年","最近2年","Últimos 2 años","2 dernières années"],
  p0: ["전체 기간","All Time","全期間","全部期间","全部期間","Todo el período","Toute la période"],
  run: ["과거를 다시 돌려 보기","Run Backtest","過去検証を実行","重新回放历史","重新重放歷史","Repetir simulación","Relancer la simulation"],
  rules: ["이 전략의 규칙","Strategy Rules","戦略ルール","策略规则","策略規則","Reglas de la estrategia","Règles de la stratégie"],
  terms: ["계산 기준","Backtest Conditions","バックテスト条件","回测条件","回測條件","Condiciones de backtest","Conditions du backtest"],
  strategy: ["이 전략","This Strategy","対象の戦略","当前策略","當前策略","Esta estrategia","Cette stratégie"],
  benchmarkPnl: ["현물 보유 손익","Spot Holding PnL","現物保有損益","现货持有盈亏","現貨持有損益","PnL de tenencia spot","PnL de détention spot"],
  benchmark: ["현물 보유","Buy & Hold","保有継続（バイ＆ホールド）","基准持有","基準持有","Comprar y mantener","Achat et conservation"],
  buy: ["매수","Buy","買い","买入","買入","Compra","Achat"],
  sell: ["매도","Sell","売り","卖出","賣出","Venta","Vente"],
  back: ["대화로 돌아가기","Back to Chat","チャットに戻る","返回对话","返回對話","Volver al chat","Retour au chat"],
  backToSettings: ['설정으로 돌아가기', 'Back to settings', '設定に戻る', '返回设置', '返回設定', 'Volver a la configuración', 'Retour aux paramètres'],
  skip: ["바로 결과 보기","Skip to Results","結果をすぐ見る","直接看结果","直接看結果","Ver resultados","Voir les résultats"],
  rerun: ["조건을 바꿔 다시 돌리기","Adjust and Rerun","条件を変更して再実行","调整条件并重跑","調整條件並重跑","Cambiar condiciones y repetir","Modifier et relancer"],
  current: ["지금 하는 일","Current Step","現在の処理","当前步骤","當前步驟","Paso actual","Étape en cours"],
  prepare: ["가격 자료 준비","Preparing Price Data","価格データの準備","准备价格数据","準備價格數據","Preparando datos de precios","Préparation des données de prix"],
  replay: ["하루씩 다시 돌리기","Replaying Day by Day","日次でシミュレーション","逐日回放","逐日重放","Reproducción diaria","Relecture jour par jour"],
  check: ["사는 조건 확인","Checking Entry Conditions","買い条件の判定","检查买入条件","檢查買入條件","Comprobando condiciones de compra","Vérification des conditions d'achat"],
  wrap: ["결과 정리","Compiling Results","結果の集計","整理结果","整理結果","Resumiendo resultados","Synthèse des résultats"],
  decisions: ["판단 기록","Decision Log","判断の推移","判断依据","判斷依據","Lógica de decisiones","Historique des décisions"],
  trades: ["거래 내역","Trade History","取引履歴","交易记录","交易記錄","Historial de operaciones","Historique des transactions"],
  all: ["전체","All","すべて","全部","全部","Todos","Tous"],
  win: ["수익 거래","Winning Trades","勝ち取引","盈利交易","盈利交易","Operaciones ganadoras","Trades gagnants"],
  loss: ["손실 거래","Losing Trades","負け取引","亏损交易","虧損交易","Operaciones perdedoras","Trades perdants"],
  mdd: ["최대 하락률","Max Drawdown","最大下落幅 (MDD)","最大回撤","最大回撤","Caída máxima","Perte maximale (MDD)"],
  hold: ["평균 보유 기간","Avg Holding Period","平均保有期間","平均持仓","平均持倉","Tenencia media","Détention moyenne"],
  final: ["남은 금액","Final Balance","最終残高","最终金额","最終金額","Balance final","Solde final"],
  execute: ["이 전략 실행하기","Deploy Strategy","この戦略を実行","执行该策略","執行該策略","Ejecutar estrategia","Exécuter cette stratégie"],
  unconnected: ["실행 연결은 준비 중입니다. 실제 주문은 전송되지 않습니다.","Live execution is in development. No real orders are sent.","本番連携は準備中です。実際の注文は発注されません。","实盘连接正在准备中，不会发送真实订单。","實盤連接正在準備中，不會發送真實訂單。","La conexión en vivo está en desarrollo. No se envían órdenes reales.","La connexion en direct est en préparation. Aucun ordre réel n'est envoyé."],
  preview: ["공통 합성 일별 자료로 재생하는 디자인 미리보기입니다. 실제 시장 데이터나 서비스 백테스트 결과가 아닙니다.","This is a design preview replayed with synthetic daily data, not real market data or live backtest results.","合成の日次データを用いたデザインプレビューです。実際の市場データや検証結果ではありません。","这是使用通用合成日线数据回放的设计预览，并非真实市场数据或正式回测结果。","這是使用通用合成日線數據重放的設計預覽，並非真實市場數據或正式回測結果。","Vista previa de diseño basada en datos sintéticos diarios; no representa datos de mercado reales ni resultados de backtest en vivo.","Aperçu de conception basé sur des données journalières synthétiques ; ne constitue pas des données de marché réelles ni un résultat de backtest en ligne."],
  readyNote: ["진입 조건이 맞으면 여기에 표시합니다.","Displayed here when entry conditions are met.","エントリー条件を満たすとここに表示されます。","满足入场条件时将在此显示。","滿足進場條件時將在此顯示。","Se mostrará aquí cuando se cumplan las condiciones de entrada.","S'affichera ici lorsque les conditions d'entrée seront remplies."],
  empty: ["완료된 거래가 없습니다.","No completed trades.","完了した取引はありません。","没有已完成的交易。","沒有已完成的交易。","No hay operaciones completadas.","Aucune transaction terminée."],
  missing: ["대화에서 백테스트할 전략을 먼저 선택해주세요.","Please select a strategy to backtest from the chat first.","チャットでバックテストする戦略を先に選択してください。","请先在对话中选择要回测的策略。","請先在對話中選擇要回測的策略。","Selecciona primero una estrategia para el backtest en el chat.","Veuillez d'abord sélectionner une stratégie à tester dans le chat."],
  chart: ["전략과 단순 보유 비교","Strategy vs. Buy & Hold","戦略とバイ＆ホールドの比較","策略与基准持有对比","策略與基準持有對比","Comparación: Estrategia vs. Mantener","Comparaison : Stratégie vs Achat-Conservation"],
  chartError: ["차트를 표시할 수 없습니다. 거래 기록과 결과 숫자는 그대로 확인할 수 있습니다.","Unable to display chart. Trade records and performance metrics remain available.","チャートを表示できません。取引履歴と集計数値はそのままご確認いただけます。","无法显示图表，交易记录和结果数据仍可正常查看。","無法顯示圖表，交易記錄與結果數據仍可正常查看。","No se puede mostrar el gráfico. Los registros de operaciones y métricas siguen disponibles.","Impossible d'afficher le graphique. Les transactions et indicateurs restent consultables."],
  more: ["더 보기","View More","もっと見る","查看更多","查看更多","Ver más","Voir plus"],
  stop: ["손절","Stop Loss","損切り","止损","止損","Stop loss","Stop loss"],
  take: ["익절","Take Profit","利確","止盈","止盈","Take profit","Prise de bénéfice"],
  filter: ["추세 필터","Trend Filter","トレンドフィルター","趋势过滤","趨勢過濾","Filtro de tendencia","Filtre de tendance"],
  on: ["사용","Enabled","オン","开启","開啟","Activado","Activé"],
  off: ["사용 안 함","Disabled","オフ","关闭","關閉","Desactivado","Désactivé"],
  noTake: ["미설정","Not Set","未設定","未设置","未設置","No definido","Non défini"],
  timeframe: ["계산 단위","Interval","計算単位","计算单位","計算單位","Unidad de cálculo","Unité de calcul"],
  daily: ["일별 종가","Daily Close","日足終値","日收盘价","日收盤價","Cierre diario","Clôture quotidienne"],
  fees: ["거래 비용","Trading Fees","取引コスト","交易费用","交易費用","Comisiones","Frais de transaction"],
  previewRule: ["합성 규칙 체결, 다음 거래일 체결 아님","Synthetic fill rule, not next-day execution","合成ルールによる約定、翌営業日約定ではありません","按合成规则成交，非下一交易日成交","按合成規則成交，非下一交易日成交","Ejecución por regla sintética, no al día hábil siguiente","Exécution par règle synthétique, non au jour de bourse suivant"],
  entry: ["진입","Entry","エントリー","入场","進場","Entrada","Entrée"],
  exit: ["청산","Exit","イグジット","离场","出場","Salida","Sortie"],
  pnl: ["손익","P&L","損益","盈亏","盈虧","P/L","P&L"],
  days: ["일","days","日","天","天","días","j"],
  savingError: ["조건을 저장하지 못했습니다. 기존 선택은 유지됩니다.","Failed to save parameters. Existing settings remain unchanged.","条件を保存できませんでした。以前の設定が維持されます。","保存条件失败，已保留原先设置。","儲存條件失敗，已保留原先設置。","No se pudieron guardar las condiciones. Se mantiene la selección anterior.","Échec de l'enregistrement des conditions. La sélection précédente est conservée."],
  checked: ['확인한 가격', 'Price points checked', '確認した価格データ数', '已检查的价格数据数', '已檢查的價格資料數', 'Precios comprobados', 'Points de prix vérifiés'],
  notice: ["계산된 규칙 근거","Rule Evaluation Basis","計算根拠","规则计算依据","規則計算依據","Base de la regla calculada","Base du calcul de la règle"],
  same: ["같음","Equal","同等","持平","持平","Igual","Égal"],
  compare: ["단순 보유와 차이","Difference vs. Buy & Hold","バイ＆ホールドとの差","与基准持有的差异","與基準持有的差異","Diferencia frente a mantener","Écart par rapport à l'achat-conservation"],
} as const
const languages: readonly ClientLanguage[] = ['ko', 'en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr']
export function commonBacktestText(language: ClientLanguage, key: keyof typeof rows): string {
  return rows[key][languages.indexOf(language)] ?? rows[key][0]
}
