import type { ClientLanguage } from './client-preferences'

/** Source 501053b public-preview copy. Translation never creates publishing,
 * reward, payment, eligibility or backend authority. Korean stays unchanged. */
const ko = {
  "{nick} 크리에이터 센터": "{nick} 크리에이터 센터",
  "전략 공개 과정": "전략 공개 과정",
  "공개 설정 단계": "공개 설정 단계",
  "전략 만들기": "전략 만들기",
  "TETH 80점 검증 통과": "TETH 80점 검증 통과",
  "공개하고 보상 받기": "공개하고 보상 받기",
  "전략 선택": "전략 선택",
  "보상, 공개 범위": "보상, 공개 범위",
  "검토, 공개": "검토, 공개",
  "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.": "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.",
  "다시 불러오기": "다시 불러오기",
  "내 전략을 공유해보세요": "내 전략을 공유해보세요",
  "검증을 통과한 전략을 닉네임으로 공개하면,": "검증을 통과한 전략을 닉네임으로 공개하면,",
  "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.": "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.",
  "내 전략 공유하기": "내 전략 공유하기",
  "채팅에서 전략 만들기": "채팅에서 전략 만들기",
  "공개 전략 요약": "공개 전략 요약",
  "팔로워": "팔로워",
  "팔로워 정보 미제공": "팔로워 정보 미제공",
  "누적 정산 보상": "누적 정산 보상",
  "누적 정산 보상 정보 미제공": "누적 정산 보상 정보 미제공",
  "공개 전략 검증 수익": "공개 전략 검증 수익",
  "TETH 점수": "TETH 점수",
  "{score}점": "{score}점",
  "랭킹 공개": "랭킹 공개",
  "랭킹에 공개 중": "랭킹에 공개 중",
  "비공개 상태": "비공개 상태",
  "보상 요율": "보상 요율",
  "팔로워 요금의 20%": "팔로워 요금의 20%",
  "공개 등록일": "공개 등록일",
  "소개": "소개",
  "설정 수정": "설정 수정",
  "비공개로 전환": "비공개로 전환",
  "전략 찾기에 이렇게 노출돼요": "전략 찾기에 이렇게 노출돼요",
  "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.": "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.",
  "공개할 전략 선택": "공개할 전략 선택",
  "전략 ID": "전략 ID",
  "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}": "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}",
  "기준 미달로 공개 불가": "기준 미달로 공개 불가",
  "보상 구조": "보상 구조",
  "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.": "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.",
  "공개 범위": "공개 범위",
  "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.": "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.",
  "전략 소개 (선택, 100자)": "전략 소개 (선택, 100자)",
  "예: 하락 후 반등 구간만 노리는 전략이에요": "예: 하락 후 반등 구간만 노리는 전략이에요",
  "공개되면 전략 찾기에 이렇게 노출돼요": "공개되면 전략 찾기에 이렇게 노출돼요",
  "취소": "취소",
  "이전": "이전",
  "다음 단계": "다음 단계",
  "공개하고 랭킹 등록하기": "공개하고 랭킹 등록하기",
  "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요": "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요",
  "비공개로 전환했어요. 스냅샷은 보관돼요": "비공개로 전환했어요. 스냅샷은 보관돼요",
  "전략이 공개됐어요": "전략이 공개됐어요",
  "전략 공개를 껐어요": "전략 공개를 껐어요",
  "공개 상태를 저장하지 못했어요. 다시 시도해주세요.": "공개 상태를 저장하지 못했어요. 다시 시도해주세요.",
  "공개 기록을 다시 불러오지 못했어요.": "공개 기록을 다시 불러오지 못했어요.",
  "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.": "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.",
  "검증을 통과한 전략을 선택해주세요": "검증을 통과한 전략을 선택해주세요",
  "검증을 통과한 전략을 다시 선택해주세요.": "검증을 통과한 전략을 다시 선택해주세요.",
  "공개 설정을 저장하지 못했어요. 다시 시도해주세요.": "공개 설정을 저장하지 못했어요. 다시 시도해주세요.",
  "TETH 80점 이상 전략만 공개할 수 있어요.": "TETH 80점 이상 전략만 공개할 수 있어요.",
  "저장된 검증 수치를 다시 확인해주세요.": "저장된 검증 수치를 다시 확인해주세요.",
  "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.": "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.",
  "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.": "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.",
  "저장된 전략 정보를 다시 확인해주세요.": "저장된 전략 정보를 다시 확인해주세요.",
  "로그인 후 다시 시도해주세요.": "로그인 후 다시 시도해주세요.",
  "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.": "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.",
  "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.": "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.",
  "공개할 전략과 소개를 다시 확인해주세요.": "공개할 전략과 소개를 다시 확인해주세요.",
  "공개할 전략을 다시 불러와주세요.": "공개할 전략을 다시 불러와주세요.",
  "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.": "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.",
  "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.": "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.",
  "공개할 전략 정보를 다시 확인해주세요.": "공개할 전략 정보를 다시 확인해주세요.",
  "공개할 전략 스냅샷이 없어요.": "공개할 전략 스냅샷이 없어요."
} as const
export type CreatorCopyKey = keyof typeof ko
const translations: Record<Exclude<ClientLanguage, 'ko'>, Record<CreatorCopyKey, string>> = {
  "en": {
    "{nick} 크리에이터 센터": "{nick} Creator Center",
    "전략 공개 과정": "Strategy publishing process",
    "공개 설정 단계": "Publishing setup steps",
    "전략 만들기": "Create a strategy",
    "TETH 80점 검증 통과": "Pass verification with TETH 80",
    "공개하고 보상 받기": "Publish and earn rewards",
    "전략 선택": "Select strategy",
    "보상, 공개 범위": "Rewards, disclosure scope",
    "검토, 공개": "Review, publish",
    "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.": "We couldn't load your publishing record. Your existing record will not be overwritten.",
    "다시 불러오기": "Reload",
    "내 전략을 공유해보세요": "Share your strategy",
    "검증을 통과한 전략을 닉네임으로 공개하면,": "When you publish a verified strategy under your nickname,",
    "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.": "you earn 20% of the usage fee as a reward each time another user follows it.",
    "내 전략 공유하기": "Share my strategy",
    "채팅에서 전략 만들기": "Create a strategy in chat",
    "공개 전략 요약": "Published strategy summary",
    "팔로워": "Followers",
    "팔로워 정보 미제공": "Follower data not provided",
    "누적 정산 보상": "Cumulative settled rewards",
    "누적 정산 보상 정보 미제공": "Cumulative settled reward data not provided",
    "공개 전략 검증 수익": "Published strategy verified return",
    "TETH 점수": "TETH score",
    "{score}점": "{score} pts",
    "랭킹 공개": "Publish to ranking",
    "랭킹에 공개 중": "Published to ranking",
    "비공개 상태": "Private",
    "보상 요율": "Reward rate",
    "팔로워 요금의 20%": "20% of follower fees",
    "공개 등록일": "Published on",
    "소개": "Description",
    "설정 수정": "Edit settings",
    "비공개로 전환": "Switch to private",
    "전략 찾기에 이렇게 노출돼요": "This is how it appears in Find Strategies",
    "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.": "Only strategies with a TETH score of 80 or higher can be listed in the public ranking.",
    "공개할 전략 선택": "Select a strategy to publish",
    "전략 ID": "Strategy ID",
    "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}": "TETH {score} pts, verified return {return}, max drawdown {mdd}",
    "기준 미달로 공개 불가": "Below the threshold, can't be published",
    "보상 구조": "Reward structure",
    "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.": "20% of the TETH usage fee paid by users who follow your strategy is settled monthly as a creator reward.",
    "공개 범위": "Disclosure scope",
    "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.": "The original strategy parameters are not disclosed. Only the verified performance metrics (return, score, drawdown, win rate) and the equity curve are published under your nickname.",
    "전략 소개 (선택, 100자)": "Strategy description (optional, 100 characters)",
    "예: 하락 후 반등 구간만 노리는 전략이에요": "e.g. A strategy that targets only rebounds after a drop",
    "공개되면 전략 찾기에 이렇게 노출돼요": "Once published, this is how it appears in Find Strategies",
    "취소": "Cancel",
    "이전": "Previous",
    "다음 단계": "Next step",
    "공개하고 랭킹 등록하기": "Publish and list in the ranking",
    "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요": "Your strategy is published. You can find it in Find Strategies",
    "비공개로 전환했어요. 스냅샷은 보관돼요": "Switched to private. The snapshot is kept",
    "전략이 공개됐어요": "Your strategy is published",
    "전략 공개를 껐어요": "Strategy publishing is turned off",
    "공개 상태를 저장하지 못했어요. 다시 시도해주세요.": "We couldn't save the publishing status. Please try again.",
    "공개 기록을 다시 불러오지 못했어요.": "We couldn't reload the publishing record.",
    "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.": "Please check your account and storage status, then try again.",
    "검증을 통과한 전략을 선택해주세요": "Please select a strategy that passed verification",
    "검증을 통과한 전략을 다시 선택해주세요.": "Please select a verified strategy again.",
    "공개 설정을 저장하지 못했어요. 다시 시도해주세요.": "We couldn't save the publishing settings. Please try again.",
    "TETH 80점 이상 전략만 공개할 수 있어요.": "Only strategies with TETH 80 or higher can be published.",
    "저장된 검증 수치를 다시 확인해주세요.": "Please check the saved verification figures again.",
    "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.": "The saved verification figures don't match the current calculation settings. Please verify the strategy again.",
    "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.": "We can't check the saved calculation settings. Please verify the strategy again.",
    "저장된 전략 정보를 다시 확인해주세요.": "Please check the saved strategy information again.",
    "로그인 후 다시 시도해주세요.": "Please sign in and try again.",
    "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.": "We couldn't load the saved publishing settings. Please reload and try again.",
    "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.": "We couldn't save the publishing settings. Please check what you entered and try again.",
    "공개할 전략과 소개를 다시 확인해주세요.": "Please check the strategy and description you want to publish.",
    "공개할 전략을 다시 불러와주세요.": "Please reload the strategy you want to publish.",
    "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.": "There's no strategy to publish, or its identifying information can't be confirmed.",
    "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.": "The strategy conditions have changed. Please reopen the settings window and check.",
    "공개할 전략 정보를 다시 확인해주세요.": "Please check the information of the strategy you want to publish.",
    "공개할 전략 스냅샷이 없어요.": "There's no strategy snapshot to publish."
  },
  "ja": {
    "{nick} 크리에이터 센터": "{nick} クリエイターセンター",
    "전략 공개 과정": "戦略公開の流れ",
    "공개 설정 단계": "公開設定のステップ",
    "전략 만들기": "戦略を作る",
    "TETH 80점 검증 통과": "TETH 80点の検証を通過",
    "공개하고 보상 받기": "公開して報酬を受け取る",
    "전략 선택": "戦略を選択",
    "보상, 공개 범위": "報酬・公開範囲",
    "검토, 공개": "確認・公開",
    "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.": "公開記録を読み込めませんでした。既存の記録は上書きされません。",
    "다시 불러오기": "再読み込み",
    "내 전략을 공유해보세요": "自分の戦略を共有してみましょう",
    "검증을 통과한 전략을 닉네임으로 공개하면,": "検証を通過した戦略をニックネームで公開すると、",
    "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.": "他のユーザーがフォローするたびに利用料金の20%が報酬として貯まります。",
    "내 전략 공유하기": "自分の戦略を共有する",
    "채팅에서 전략 만들기": "チャットで戦略を作る",
    "공개 전략 요약": "公開戦略の概要",
    "팔로워": "フォロワー",
    "팔로워 정보 미제공": "フォロワー情報は未提供",
    "누적 정산 보상": "累計精算報酬",
    "누적 정산 보상 정보 미제공": "累計精算報酬の情報は未提供",
    "공개 전략 검증 수익": "公開戦略の検証リターン",
    "TETH 점수": "TETHスコア",
    "{score}점": "{score}点",
    "랭킹 공개": "ランキング公開",
    "랭킹에 공개 중": "ランキングに公開中",
    "비공개 상태": "非公開の状態",
    "보상 요율": "報酬レート",
    "팔로워 요금의 20%": "フォロワー料金の20%",
    "공개 등록일": "公開登録日",
    "소개": "紹介",
    "설정 수정": "設定を変更",
    "비공개로 전환": "非公開に切り替え",
    "전략 찾기에 이렇게 노출돼요": "戦略検索ではこのように表示されます",
    "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.": "TETHスコア80点以上を獲得した戦略のみ、公開ランキングに登録できます。",
    "공개할 전략 선택": "公開する戦略を選択",
    "전략 ID": "戦略ID",
    "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}": "TETH {score}点、検証リターン {return}、最大ドローダウン {mdd}",
    "기준 미달로 공개 불가": "基準未達のため公開できません",
    "보상 구조": "報酬の仕組み",
    "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.": "自分の戦略をフォローするユーザーが支払うTETH利用料の20%が、クリエイター報酬として毎月精算されます。",
    "공개 범위": "公開範囲",
    "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.": "戦略パラメータの原本は公開されません。検証パフォーマンス指標（リターン、スコア、ドローダウン、勝率）とエクイティカーブのみがニックネームで公開されます。",
    "전략 소개 (선택, 100자)": "戦略の紹介（任意、100文字）",
    "예: 하락 후 반등 구간만 노리는 전략이에요": "例：下落後の反発局面だけを狙う戦略です",
    "공개되면 전략 찾기에 이렇게 노출돼요": "公開すると戦略検索でこのように表示されます",
    "취소": "キャンセル",
    "이전": "戻る",
    "다음 단계": "次のステップ",
    "공개하고 랭킹 등록하기": "公開してランキングに登録する",
    "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요": "戦略を公開しました。戦略検索で確認できます",
    "비공개로 전환했어요. 스냅샷은 보관돼요": "非公開に切り替えました。スナップショットは保管されます",
    "전략이 공개됐어요": "戦略を公開しました",
    "전략 공개를 껐어요": "戦略の公開をオフにしました",
    "공개 상태를 저장하지 못했어요. 다시 시도해주세요.": "公開状態を保存できませんでした。もう一度お試しください。",
    "공개 기록을 다시 불러오지 못했어요.": "公開記録を再読み込みできませんでした。",
    "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.": "アカウントと保存状態を確認してから、もう一度お試しください。",
    "검증을 통과한 전략을 선택해주세요": "検証を通過した戦略を選択してください",
    "검증을 통과한 전략을 다시 선택해주세요.": "検証を通過した戦略をもう一度選択してください。",
    "공개 설정을 저장하지 못했어요. 다시 시도해주세요.": "公開設定を保存できませんでした。もう一度お試しください。",
    "TETH 80점 이상 전략만 공개할 수 있어요.": "TETH 80点以上の戦略のみ公開できます。",
    "저장된 검증 수치를 다시 확인해주세요.": "保存された検証数値をもう一度ご確認ください。",
    "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.": "保存された検証数値が現在の計算設定と一致しません。戦略をもう一度検証してください。",
    "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.": "保存された計算設定を確認できません。戦略をもう一度検証してください。",
    "저장된 전략 정보를 다시 확인해주세요.": "保存された戦略情報をもう一度ご確認ください。",
    "로그인 후 다시 시도해주세요.": "ログイン後、もう一度お試しください。",
    "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.": "保存された公開設定を読み込めませんでした。再読み込みしてからお試しください。",
    "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.": "公開設定を保存できませんでした。入力内容を確認して、もう一度お試しください。",
    "공개할 전략과 소개를 다시 확인해주세요.": "公開する戦略と紹介文をもう一度ご確認ください。",
    "공개할 전략을 다시 불러와주세요.": "公開する戦略をもう一度読み込んでください。",
    "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.": "公開する戦略がないか、識別情報を確認できません。",
    "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.": "戦略の条件が変わりました。設定ウィンドウを開き直してご確認ください。",
    "공개할 전략 정보를 다시 확인해주세요.": "公開する戦略情報をもう一度ご確認ください。",
    "공개할 전략 스냅샷이 없어요.": "公開する戦略のスナップショットがありません。"
  },
  "zh-CN": {
    "{nick} 크리에이터 센터": "{nick} 创作者中心",
    "전략 공개 과정": "策略公开流程",
    "공개 설정 단계": "公开设置步骤",
    "전략 만들기": "创建策略",
    "TETH 80점 검증 통과": "通过 TETH 80 分验证",
    "공개하고 보상 받기": "公开并获得奖励",
    "전략 선택": "选择策略",
    "보상, 공개 범위": "奖励、公开范围",
    "검토, 공개": "确认、公开",
    "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.": "未能加载公开记录。现有记录不会被覆盖。",
    "다시 불러오기": "重新加载",
    "내 전략을 공유해보세요": "分享你的策略吧",
    "검증을 통과한 전략을 닉네임으로 공개하면,": "将通过验证的策略以昵称公开后，",
    "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.": "其他用户每次跟单时，使用费的 20% 就会累积为奖励。",
    "내 전략 공유하기": "分享我的策略",
    "채팅에서 전략 만들기": "在聊天中创建策略",
    "공개 전략 요약": "公开策略摘要",
    "팔로워": "关注者",
    "팔로워 정보 미제공": "未提供关注者信息",
    "누적 정산 보상": "累计结算奖励",
    "누적 정산 보상 정보 미제공": "未提供累计结算奖励信息",
    "공개 전략 검증 수익": "公开策略验证收益",
    "TETH 점수": "TETH 分数",
    "{score}점": "{score} 分",
    "랭킹 공개": "在排行榜公开",
    "랭킹에 공개 중": "已在排行榜公开",
    "비공개 상태": "未公开状态",
    "보상 요율": "奖励费率",
    "팔로워 요금의 20%": "关注者费用的 20%",
    "공개 등록일": "公开登记日",
    "소개": "简介",
    "설정 수정": "修改设置",
    "비공개로 전환": "切换为不公开",
    "전략 찾기에 이렇게 노출돼요": "在策略发现中会这样展示",
    "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.": "只有 TETH 分数达到 80 分以上的策略才能登记到公开排行榜。",
    "공개할 전략 선택": "选择要公开的策略",
    "전략 ID": "策略 ID",
    "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}": "TETH {score} 分，验证收益 {return}，最大回撤 {mdd}",
    "기준 미달로 공개 불가": "未达标准，无法公开",
    "보상 구조": "奖励结构",
    "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.": "跟单你策略的用户所支付的 TETH 使用费的 20%，将作为创作者奖励按月结算。",
    "공개 범위": "公开范围",
    "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.": "策略参数原文不会公开。仅验证绩效指标（收益率、分数、回撤、胜率）与净值曲线会以昵称公开。",
    "전략 소개 (선택, 100자)": "策略简介（选填，100 字）",
    "예: 하락 후 반등 구간만 노리는 전략이에요": "例：只捕捉下跌后反弹区间的策略",
    "공개되면 전략 찾기에 이렇게 노출돼요": "公开后在策略发现中会这样展示",
    "취소": "取消",
    "이전": "上一步",
    "다음 단계": "下一步",
    "공개하고 랭킹 등록하기": "公开并登记到排行榜",
    "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요": "策略已公开，可在策略发现中查看",
    "비공개로 전환했어요. 스냅샷은 보관돼요": "已切换为不公开，快照会保留",
    "전략이 공개됐어요": "策略已公开",
    "전략 공개를 껐어요": "已关闭策略公开",
    "공개 상태를 저장하지 못했어요. 다시 시도해주세요.": "未能保存公开状态，请重试。",
    "공개 기록을 다시 불러오지 못했어요.": "未能重新加载公开记录。",
    "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.": "请确认账号与保存状态后重试。",
    "검증을 통과한 전략을 선택해주세요": "请选择通过验证的策略",
    "검증을 통과한 전략을 다시 선택해주세요.": "请重新选择通过验证的策略。",
    "공개 설정을 저장하지 못했어요. 다시 시도해주세요.": "未能保存公开设置，请重试。",
    "TETH 80점 이상 전략만 공개할 수 있어요.": "只有 TETH 80 分以上的策略才能公开。",
    "저장된 검증 수치를 다시 확인해주세요.": "请重新确认已保存的验证数值。",
    "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.": "已保存的验证数值与当前计算设置不一致，请重新验证策略。",
    "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.": "无法确认已保存的计算设置，请重新验证策略。",
    "저장된 전략 정보를 다시 확인해주세요.": "请重新确认已保存的策略信息。",
    "로그인 후 다시 시도해주세요.": "请登录后重试。",
    "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.": "未能加载已保存的公开设置，请重新加载后再试。",
    "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.": "未能保存公开设置，请确认输入内容后重试。",
    "공개할 전략과 소개를 다시 확인해주세요.": "请重新确认要公开的策略与简介。",
    "공개할 전략을 다시 불러와주세요.": "请重新加载要公开的策略。",
    "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.": "没有可公开的策略，或无法确认其识别信息。",
    "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.": "策略条件已变更，请重新打开设置窗口确认。",
    "공개할 전략 정보를 다시 확인해주세요.": "请重新确认要公开的策略信息。",
    "공개할 전략 스냅샷이 없어요.": "没有可公开的策略快照。"
  },
  "zh-TW": {
    "{nick} 크리에이터 센터": "{nick} 創作者中心",
    "전략 공개 과정": "策略公開流程",
    "공개 설정 단계": "公開設定步驟",
    "전략 만들기": "建立策略",
    "TETH 80점 검증 통과": "通過 TETH 80 分驗證",
    "공개하고 보상 받기": "公開並獲得獎勵",
    "전략 선택": "選擇策略",
    "보상, 공개 범위": "獎勵、公開範圍",
    "검토, 공개": "確認、公開",
    "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.": "未能載入公開紀錄。現有紀錄不會被覆寫。",
    "다시 불러오기": "重新載入",
    "내 전략을 공유해보세요": "分享你的策略吧",
    "검증을 통과한 전략을 닉네임으로 공개하면,": "將通過驗證的策略以暱稱公開後，",
    "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.": "其他使用者每次跟單時，使用費的 20% 就會累積為獎勵。",
    "내 전략 공유하기": "分享我的策略",
    "채팅에서 전략 만들기": "在聊天中建立策略",
    "공개 전략 요약": "公開策略摘要",
    "팔로워": "追蹤者",
    "팔로워 정보 미제공": "未提供追蹤者資訊",
    "누적 정산 보상": "累計結算獎勵",
    "누적 정산 보상 정보 미제공": "未提供累計結算獎勵資訊",
    "공개 전략 검증 수익": "公開策略驗證報酬",
    "TETH 점수": "TETH 分數",
    "{score}점": "{score} 分",
    "랭킹 공개": "在排行榜公開",
    "랭킹에 공개 중": "已在排行榜公開",
    "비공개 상태": "未公開狀態",
    "보상 요율": "獎勵費率",
    "팔로워 요금의 20%": "追蹤者費用的 20%",
    "공개 등록일": "公開登錄日",
    "소개": "簡介",
    "설정 수정": "修改設定",
    "비공개로 전환": "切換為不公開",
    "전략 찾기에 이렇게 노출돼요": "在策略發現中會這樣顯示",
    "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.": "只有 TETH 分數達 80 分以上的策略才能登錄至公開排行榜。",
    "공개할 전략 선택": "選擇要公開的策略",
    "전략 ID": "策略 ID",
    "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}": "TETH {score} 分，驗證報酬 {return}，最大回撤 {mdd}",
    "기준 미달로 공개 불가": "未達標準，無法公開",
    "보상 구조": "獎勵結構",
    "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.": "跟單你策略的使用者所支付的 TETH 使用費的 20%，將作為創作者獎勵按月結算。",
    "공개 범위": "公開範圍",
    "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.": "策略參數原文不會公開。僅驗證績效指標（報酬率、分數、回撤、勝率）與淨值曲線會以暱稱公開。",
    "전략 소개 (선택, 100자)": "策略簡介（選填，100 字）",
    "예: 하락 후 반등 구간만 노리는 전략이에요": "例：只鎖定下跌後反彈區間的策略",
    "공개되면 전략 찾기에 이렇게 노출돼요": "公開後在策略發現中會這樣顯示",
    "취소": "取消",
    "이전": "上一步",
    "다음 단계": "下一步",
    "공개하고 랭킹 등록하기": "公開並登錄至排行榜",
    "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요": "策略已公開，可在策略發現中查看",
    "비공개로 전환했어요. 스냅샷은 보관돼요": "已切換為不公開，快照會保留",
    "전략이 공개됐어요": "策略已公開",
    "전략 공개를 껐어요": "已關閉策略公開",
    "공개 상태를 저장하지 못했어요. 다시 시도해주세요.": "未能儲存公開狀態，請再試一次。",
    "공개 기록을 다시 불러오지 못했어요.": "未能重新載入公開紀錄。",
    "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.": "請確認帳號與儲存狀態後再試一次。",
    "검증을 통과한 전략을 선택해주세요": "請選擇通過驗證的策略",
    "검증을 통과한 전략을 다시 선택해주세요.": "請重新選擇通過驗證的策略。",
    "공개 설정을 저장하지 못했어요. 다시 시도해주세요.": "未能儲存公開設定，請再試一次。",
    "TETH 80점 이상 전략만 공개할 수 있어요.": "只有 TETH 80 分以上的策略才能公開。",
    "저장된 검증 수치를 다시 확인해주세요.": "請重新確認已儲存的驗證數值。",
    "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.": "已儲存的驗證數值與目前的計算設定不一致，請重新驗證策略。",
    "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.": "無法確認已儲存的計算設定，請重新驗證策略。",
    "저장된 전략 정보를 다시 확인해주세요.": "請重新確認已儲存的策略資訊。",
    "로그인 후 다시 시도해주세요.": "請登入後再試一次。",
    "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.": "未能載入已儲存的公開設定，請重新載入後再試。",
    "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.": "未能儲存公開設定，請確認輸入內容後再試一次。",
    "공개할 전략과 소개를 다시 확인해주세요.": "請重新確認要公開的策略與簡介。",
    "공개할 전략을 다시 불러와주세요.": "請重新載入要公開的策略。",
    "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.": "沒有可公開的策略，或無法確認其識別資訊。",
    "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.": "策略條件已變更，請重新開啟設定視窗確認。",
    "공개할 전략 정보를 다시 확인해주세요.": "請重新確認要公開的策略資訊。",
    "공개할 전략 스냅샷이 없어요.": "沒有可公開的策略快照。"
  },
  "es": {
    "{nick} 크리에이터 센터": "Centro de creador de {nick}",
    "전략 공개 과정": "Proceso de publicación de la estrategia",
    "공개 설정 단계": "Pasos de configuración de publicación",
    "전략 만들기": "Crear estrategia",
    "TETH 80점 검증 통과": "Superar la verificación con TETH 80",
    "공개하고 보상 받기": "Publicar y recibir recompensas",
    "전략 선택": "Elegir estrategia",
    "보상, 공개 범위": "Recompensas y alcance de publicación",
    "검토, 공개": "Revisar y publicar",
    "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.": "No pudimos cargar el registro de publicación. El registro existente no se sobrescribe.",
    "다시 불러오기": "Volver a cargar",
    "내 전략을 공유해보세요": "Comparte tu estrategia",
    "검증을 통과한 전략을 닉네임으로 공개하면,": "Si publicas con tu apodo una estrategia que ha superado la verificación,",
    "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.": "acumulas como recompensa el 20 % de la tarifa de uso cada vez que otro usuario la sigue.",
    "내 전략 공유하기": "Compartir mi estrategia",
    "채팅에서 전략 만들기": "Crear una estrategia en el chat",
    "공개 전략 요약": "Resumen de la estrategia publicada",
    "팔로워": "Seguidores",
    "팔로워 정보 미제공": "Información de seguidores no disponible",
    "누적 정산 보상": "Recompensas liquidadas acumuladas",
    "누적 정산 보상 정보 미제공": "Información de recompensas liquidadas acumuladas no disponible",
    "공개 전략 검증 수익": "Rentabilidad verificada de la estrategia publicada",
    "TETH 점수": "Puntuación TETH",
    "{score}점": "{score} ptos",
    "랭킹 공개": "Publicar en el ranking",
    "랭킹에 공개 중": "Publicada en el ranking",
    "비공개 상태": "Estado privado",
    "보상 요율": "Tasa de recompensa",
    "팔로워 요금의 20%": "20 % de la tarifa de los seguidores",
    "공개 등록일": "Fecha de publicación",
    "소개": "Descripción",
    "설정 수정": "Editar ajustes",
    "비공개로 전환": "Cambiar a privada",
    "전략 찾기에 이렇게 노출돼요": "Así se muestra en Buscar estrategias",
    "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.": "Solo las estrategias con una puntuación TETH de 80 o más pueden registrarse en el ranking público.",
    "공개할 전략 선택": "Selecciona la estrategia que quieres publicar",
    "전략 ID": "ID de la estrategia",
    "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}": "TETH {score} ptos, rentabilidad verificada {return}, caída máxima {mdd}",
    "기준 미달로 공개 불가": "No alcanza el criterio, no se puede publicar",
    "보상 구조": "Estructura de recompensas",
    "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.": "El 20 % de la tarifa de uso de TETH que pagan los usuarios que siguen tu estrategia se liquida cada mes como recompensa de creador.",
    "공개 범위": "Alcance de la publicación",
    "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.": "Los parámetros originales de la estrategia no se publican. Solo se publican con tu apodo las métricas de rendimiento verificadas (rentabilidad, puntuación, caída, tasa de acierto) y la curva de capital.",
    "전략 소개 (선택, 100자)": "Descripción de la estrategia (opcional, 100 caracteres)",
    "예: 하락 후 반등 구간만 노리는 전략이에요": "Ej.: es una estrategia que solo busca los rebotes tras una caída",
    "공개되면 전략 찾기에 이렇게 노출돼요": "Una vez publicada, así se muestra en Buscar estrategias",
    "취소": "Cancelar",
    "이전": "Anterior",
    "다음 단계": "Siguiente paso",
    "공개하고 랭킹 등록하기": "Publicar y registrar en el ranking",
    "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요": "Tu estrategia se ha publicado. Puedes verla en Buscar estrategias",
    "비공개로 전환했어요. 스냅샷은 보관돼요": "Se ha cambiado a privada. La instantánea se conserva",
    "전략이 공개됐어요": "Tu estrategia se ha publicado",
    "전략 공개를 껐어요": "Has desactivado la publicación de la estrategia",
    "공개 상태를 저장하지 못했어요. 다시 시도해주세요.": "No pudimos guardar el estado de publicación. Inténtalo de nuevo.",
    "공개 기록을 다시 불러오지 못했어요.": "No pudimos volver a cargar el registro de publicación.",
    "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.": "Comprueba tu cuenta y el estado de guardado, y vuelve a intentarlo.",
    "검증을 통과한 전략을 선택해주세요": "Selecciona una estrategia que haya superado la verificación",
    "검증을 통과한 전략을 다시 선택해주세요.": "Vuelve a seleccionar una estrategia que haya superado la verificación.",
    "공개 설정을 저장하지 못했어요. 다시 시도해주세요.": "No pudimos guardar los ajustes de publicación. Inténtalo de nuevo.",
    "TETH 80점 이상 전략만 공개할 수 있어요.": "Solo se pueden publicar estrategias con TETH 80 o más.",
    "저장된 검증 수치를 다시 확인해주세요.": "Revisa de nuevo los valores de verificación guardados.",
    "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.": "Los valores de verificación guardados no coinciden con los ajustes de cálculo actuales. Vuelve a verificar la estrategia.",
    "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.": "No podemos comprobar los ajustes de cálculo guardados. Vuelve a verificar la estrategia.",
    "저장된 전략 정보를 다시 확인해주세요.": "Revisa de nuevo la información de la estrategia guardada.",
    "로그인 후 다시 시도해주세요.": "Inicia sesión y vuelve a intentarlo.",
    "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.": "No pudimos cargar los ajustes de publicación guardados. Vuelve a cargarlos e inténtalo de nuevo.",
    "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.": "No pudimos guardar los ajustes de publicación. Revisa lo que has introducido e inténtalo de nuevo.",
    "공개할 전략과 소개를 다시 확인해주세요.": "Revisa de nuevo la estrategia y la descripción que quieres publicar.",
    "공개할 전략을 다시 불러와주세요.": "Vuelve a cargar la estrategia que quieres publicar.",
    "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.": "No hay ninguna estrategia que publicar o no se puede comprobar su información de identificación.",
    "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.": "Las condiciones de la estrategia han cambiado. Vuelve a abrir la ventana de ajustes y compruébalo.",
    "공개할 전략 정보를 다시 확인해주세요.": "Revisa de nuevo la información de la estrategia que quieres publicar.",
    "공개할 전략 스냅샷이 없어요.": "No hay ninguna instantánea de estrategia que publicar."
  },
  "fr": {
    "{nick} 크리에이터 센터": "Espace créateur de {nick}",
    "전략 공개 과정": "Étapes de publication de la stratégie",
    "공개 설정 단계": "Étapes de configuration de la publication",
    "전략 만들기": "Créer une stratégie",
    "TETH 80점 검증 통과": "Réussir la vérification avec TETH 80",
    "공개하고 보상 받기": "Publier et recevoir des récompenses",
    "전략 선택": "Choisir la stratégie",
    "보상, 공개 범위": "Récompenses, portée de la publication",
    "검토, 공개": "Vérification, publication",
    "공개 기록을 불러오지 못했어요. 기존 기록은 덮어쓰지 않습니다.": "Impossible de charger l'historique de publication. L'historique existant n'est pas écrasé.",
    "다시 불러오기": "Recharger",
    "내 전략을 공유해보세요": "Partagez votre stratégie",
    "검증을 통과한 전략을 닉네임으로 공개하면,": "Si vous publiez sous votre pseudo une stratégie ayant passé la vérification,",
    "다른 사용자가 따라할 때마다 이용 요금의 20%가 보상으로 쌓여요.": "vous accumulez 20 % des frais d'utilisation en récompense chaque fois qu'un autre utilisateur la suit.",
    "내 전략 공유하기": "Partager ma stratégie",
    "채팅에서 전략 만들기": "Créer une stratégie dans le chat",
    "공개 전략 요약": "Résumé de la stratégie publiée",
    "팔로워": "Abonnés",
    "팔로워 정보 미제공": "Informations sur les abonnés non fournies",
    "누적 정산 보상": "Récompenses réglées cumulées",
    "누적 정산 보상 정보 미제공": "Informations sur les récompenses réglées cumulées non fournies",
    "공개 전략 검증 수익": "Rendement vérifié de la stratégie publiée",
    "TETH 점수": "Score TETH",
    "{score}점": "{score} pts",
    "랭킹 공개": "Publier dans le classement",
    "랭킹에 공개 중": "Publiée dans le classement",
    "비공개 상태": "Statut privé",
    "보상 요율": "Taux de récompense",
    "팔로워 요금의 20%": "20 % des frais des abonnés",
    "공개 등록일": "Date de publication",
    "소개": "Présentation",
    "설정 수정": "Modifier les réglages",
    "비공개로 전환": "Passer en privé",
    "전략 찾기에 이렇게 노출돼요": "Voici comment elle apparaît dans Recherche de stratégies",
    "TETH 점수 80점 이상을 획득한 전략만 공개 랭킹에 등록할 수 있어요.": "Seules les stratégies ayant obtenu un score TETH d'au moins 80 peuvent être inscrites au classement public.",
    "공개할 전략 선택": "Sélectionnez la stratégie à publier",
    "전략 ID": "ID de la stratégie",
    "TETH {score}점, 검증 수익 {return}, 최대 낙폭 {mdd}": "TETH {score} pts, rendement vérifié {return}, perte maximale {mdd}",
    "기준 미달로 공개 불가": "Critère non atteint, publication impossible",
    "보상 구조": "Structure des récompenses",
    "내 전략을 따라하는 사용자가 지불하는 TETH 이용료의 20%가 크리에이터 보상으로 매월 정산돼요.": "20 % des frais d'utilisation TETH payés par les utilisateurs qui suivent votre stratégie sont réglés chaque mois en récompense de créateur.",
    "공개 범위": "Portée de la publication",
    "전략 파라미터 원본은 공개되지 않아요. 검증 성과 지표(수익률, 점수, 낙폭, 승률)와 에쿼티 곡선만 닉네임으로 공개됩니다.": "Les paramètres d'origine de la stratégie ne sont pas publiés. Seuls les indicateurs de performance vérifiés (rendement, score, perte maximale, taux de réussite) et la courbe de capital sont publiés sous votre pseudo.",
    "전략 소개 (선택, 100자)": "Présentation de la stratégie (facultatif, 100 caractères)",
    "예: 하락 후 반등 구간만 노리는 전략이에요": "Ex. : une stratégie qui vise uniquement les rebonds après une baisse",
    "공개되면 전략 찾기에 이렇게 노출돼요": "Une fois publiée, voici comment elle apparaît dans Recherche de stratégies",
    "취소": "Annuler",
    "이전": "Précédent",
    "다음 단계": "Étape suivante",
    "공개하고 랭킹 등록하기": "Publier et inscrire au classement",
    "전략이 공개됐어요. 전략 찾기에서 확인할 수 있어요": "Votre stratégie est publiée. Vous pouvez la voir dans Recherche de stratégies",
    "비공개로 전환했어요. 스냅샷은 보관돼요": "Passée en privé. L'instantané est conservé",
    "전략이 공개됐어요": "Votre stratégie est publiée",
    "전략 공개를 껐어요": "Vous avez désactivé la publication de la stratégie",
    "공개 상태를 저장하지 못했어요. 다시 시도해주세요.": "Impossible d'enregistrer le statut de publication. Veuillez réessayer.",
    "공개 기록을 다시 불러오지 못했어요.": "Impossible de recharger l'historique de publication.",
    "계정과 저장 상태를 확인한 뒤 다시 시도해주세요.": "Vérifiez votre compte et l'état de l'enregistrement, puis réessayez.",
    "검증을 통과한 전략을 선택해주세요": "Veuillez sélectionner une stratégie ayant passé la vérification",
    "검증을 통과한 전략을 다시 선택해주세요.": "Veuillez sélectionner à nouveau une stratégie ayant passé la vérification.",
    "공개 설정을 저장하지 못했어요. 다시 시도해주세요.": "Impossible d'enregistrer les réglages de publication. Veuillez réessayer.",
    "TETH 80점 이상 전략만 공개할 수 있어요.": "Seules les stratégies avec un score TETH d'au moins 80 peuvent être publiées.",
    "저장된 검증 수치를 다시 확인해주세요.": "Veuillez vérifier à nouveau les valeurs de vérification enregistrées.",
    "저장된 검증 수치가 현재 계산 설정과 일치하지 않아요. 전략을 다시 검증해주세요.": "Les valeurs de vérification enregistrées ne correspondent pas aux réglages de calcul actuels. Veuillez vérifier à nouveau la stratégie.",
    "저장된 계산 설정을 확인할 수 없어요. 전략을 다시 검증해주세요.": "Impossible de vérifier les réglages de calcul enregistrés. Veuillez vérifier à nouveau la stratégie.",
    "저장된 전략 정보를 다시 확인해주세요.": "Veuillez vérifier à nouveau les informations de la stratégie enregistrée.",
    "로그인 후 다시 시도해주세요.": "Veuillez vous connecter puis réessayer.",
    "저장된 공개 설정을 불러오지 못했어요. 다시 불러온 뒤 시도해주세요.": "Impossible de charger les réglages de publication enregistrés. Rechargez-les puis réessayez.",
    "공개 설정을 저장하지 못했어요. 입력한 내용을 확인하고 다시 시도해주세요.": "Impossible d'enregistrer les réglages de publication. Vérifiez ce que vous avez saisi puis réessayez.",
    "공개할 전략과 소개를 다시 확인해주세요.": "Veuillez vérifier à nouveau la stratégie et la présentation à publier.",
    "공개할 전략을 다시 불러와주세요.": "Veuillez recharger la stratégie à publier.",
    "공개할 전략이 없거나 식별 정보를 확인할 수 없어요.": "Il n'y a aucune stratégie à publier ou ses informations d'identification ne peuvent pas être vérifiées.",
    "전략 조건이 바뀌었어요. 설정 창을 다시 열어 확인해주세요.": "Les conditions de la stratégie ont changé. Rouvrez la fenêtre de réglages pour vérifier.",
    "공개할 전략 정보를 다시 확인해주세요.": "Veuillez vérifier à nouveau les informations de la stratégie à publier.",
    "공개할 전략 스냅샷이 없어요.": "Il n'y a aucun instantané de stratégie à publier."
  }
}
export const creatorCopyKeys = Object.freeze(Object.keys(ko) as CreatorCopyKey[])
export const isCreatorCopyKey = (value: string): value is CreatorCopyKey => Object.prototype.hasOwnProperty.call(ko, value)
export function creatorCopy(language: ClientLanguage, key: CreatorCopyKey, values: Record<string, string | number> = {}): string {
  const text = language === 'ko' ? ko[key] : translations[language][key]
  return text.replace(/\{([a-zA-Z]+)\}/g, (match, name: string) => Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : match)
}

/** Keep the source Korean civil date; localized display must not shift day,
 * mutate stored bytes or normalize invalid producer input into a different date. */
export function creatorDate(value: string, language: ClientLanguage): string {
  if (language === 'ko' || !/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(value) || value.startsWith('0000')) return value
  const date = new Date(value + 'T00:00:00.000Z')
  if (!Number.isFinite(date.getTime()) || date.toISOString().slice(0, 10) !== value) return value
  return new Intl.DateTimeFormat(language, { year: 'numeric', month: 'short', day: 'numeric', calendar: 'gregory', timeZone: 'UTC' }).format(date)
}

