import type { ClientLanguage } from './client-preferences'

// Presentation only. Korean source copy and supplied USDT values are preserved.
const copy = {
  pos: ['포지션', 'Positions', 'ポジション', '持仓', '持倉', 'Posiciones', 'Positions'],
  hist: ['청산 이력', 'Closed trades', '決済履歴', '平仓历史', '平倉歷史', 'Operaciones cerradas', 'Positions clôturées'],
  share: ['수익 분배', 'Profit sharing', '利益分配', '利润分成', '利潤分成', 'Reparto de beneficios', 'Partage des bénéfices'],
  bal: ['자금 이동', 'Fund transfers', '資金移動', '资金划转', '資金劃轉', 'Transferencias', 'Transferts de fonds'],
  tx: ['거래 내역', 'Transactions', '取引明細', '交易记录', '交易紀錄', 'Transacciones', 'Transactions'],
  tabs: ['카피 상세 정보', 'Copy details', 'コピー詳細情報', '跟单详情', '跟單詳情', 'Detalles de la copia', 'Détails de la copie'],
  pair: ['페어', 'Pair', 'ペア', '交易对', '交易對', 'Par', 'Paire'],
  direction: ['방향', 'Direction', '方向', '方向', '方向', 'Dirección', 'Sens'],
  entryPrice: ['진입가', 'Entry price', 'エントリー価格', '开仓价', '開倉價', 'Precio de entrada', "Prix d’entrée"],
  exitPrice: ['청산가', 'Exit price', '決済価格', '平仓价', '平倉價', 'Precio de salida', 'Prix de sortie'],
  pnl: ['손익', 'P&L', '損益', '盈亏', '損益', 'Ganancias/pérdidas', 'Gains/pertes'],
  return: ['수익률', 'Return', '収益率', '收益率', '報酬率', 'Rentabilidad', 'Rendement'],
  reason: ['청산 사유', 'Exit reason', '決済理由', '平仓原因', '平倉原因', 'Motivo del cierre', 'Motif de clôture'],
  exitTime: ['청산 시각', 'Exit time', '決済日時', '平仓时间', '平倉時間', 'Fecha de cierre', 'Date de clôture'],
  long: ['롱', 'Long', 'ロング', '做多', '做多', 'Largo', 'Long'],
  sl: ['손절 규칙', 'Stop-loss rule', '損切りルール', '止损规则', '停損規則', 'Regla de stop-loss', 'Règle de stop-loss'],
  tp: ['목표가 도달', 'Target reached', '目標価格到達', '达到目标价', '達到目標價', 'Objetivo alcanzado', 'Objectif atteint'],
  timeExit: ['기간 청산', 'Time-based exit', '期間終了による決済', '到期平仓', '到期平倉', 'Cierre por plazo', 'Clôture à échéance'],
  ruleExit: ['규칙 청산', 'Rule-based exit', 'ルールによる決済', '按规则平仓', '依規則平倉', 'Cierre por regla', 'Clôture selon une règle'],
  period: ['기간', 'Period', '期間', '期间', '期間', 'Periodo', 'Période'],
  realized: ['실현 손익', 'Realized P&L', '実現損益', '已实现盈亏', '已實現損益', 'Ganancias/pérdidas realizadas', 'Gains/pertes réalisés'],
  settled: ['정산 완료', 'Settled', '精算済み', '已结算', '已結算', 'Liquidado', 'Réglé'],
  pending: ['정산 대기', 'Pending settlement', '精算待ち', '待结算', '待結算', 'Pendiente de liquidación', 'En attente de règlement'],
  ratio: ['분배율', 'Share ratio', '分配率', '分成比例', '分成比例', 'Porcentaje de reparto', 'Taux de partage'],
  ratioHint: ['수익 분배 비율', 'Profit share ratio', '利益分配率', '利润分成比例', '利潤分成比例', 'Porcentaje de reparto de beneficios', 'Taux de partage des bénéfices'],
  shareAmount: ['분배 금액', 'Shared amount', '分配額', '分成金额', '分成金額', 'Importe repartido', 'Montant partagé'],
  present: ['현재', 'Present', '現在', '当前', '目前', 'Actualidad', 'Aujourd’hui'],
  at: ['시각', 'Time', '日時', '时间', '時間', 'Fecha', 'Date'],
  type: ['유형', 'Type', '種類', '类型', '類型', 'Tipo', 'Type'],
  amount: ['금액', 'Amount', '金額', '金额', '金額', 'Importe', 'Montant'],
  asset: ['자산', 'Asset', '資産', '资产', '資產', 'Activo', 'Actif'],
  deposit: ['입금', 'Deposit', '入金', '存入', '存入', 'Ingreso', 'Dépôt'],
  withdraw: ['출금', 'Withdrawal', '出金', '转出', '轉出', 'Retirada', 'Retrait'],
  toCopy: ['스팟 → 카피', 'Spot → Copy', '現物 → コピー', '现货 → 跟单', '現貨 → 跟單', 'Spot → Copia', 'Spot → Copie'],
  toSpot: ['카피 → 스팟', 'Copy → Spot', 'コピー → 現物', '跟单 → 现货', '跟單 → 現貨', 'Copia → Spot', 'Copie → Spot'],
  entry: ['진입', 'Entry', 'エントリー', '开仓', '開倉', 'Entrada', 'Entrée'],
  exit: ['청산', 'Exit', '決済', '平仓', '平倉', 'Cierre', 'Clôture'],
  transferIn: ['이체 입금', 'Transfer in', '振替入金', '划转转入', '劃轉轉入', 'Transferencia entrante', 'Transfert entrant'],
  transferOut: ['이체 출금', 'Transfer out', '振替出金', '划转转出', '劃轉轉出', 'Transferencia saliente', 'Transfert sortant'],
  raw: ['원본 거래 내역', 'Raw transaction details', '元の取引明細', '原始交易明细', '原始交易明細', 'Detalle original de transacciones', 'Détail original des transactions'],
  category: ['구분', 'Category', '区分', '类别', '類別', 'Categoría', 'Catégorie'],
  quantity: ['수량', 'Quantity', '数量', '数量', '數量', 'Cantidad', 'Quantité'],
  fee: ['수수료', 'Fee', '手数料', '手续费', '手續費', 'Comisión', 'Frais'],
  balanceChange: ['잔고 변화', 'Balance change', '残高変動', '余额变动', '餘額變動', 'Cambio de saldo', 'Variation du solde'],
  emptyTitle: ['아직 청산된 카피 거래가 없어요', 'No closed copy trades yet', '決済済みのコピー取引はまだありません', '暂无已平仓的跟单交易', '尚無已平倉的跟單交易', 'Aún no hay operaciones de copia cerradas', 'Aucune opération de copie clôturée'],
  emptyBody: ['첫 거래가 청산되면 진입가, 청산가, 손익이 여기에 쌓여요.', 'Entry prices, exit prices and P&L appear here after the first trade closes.', '最初の取引が決済されると、エントリー価格・決済価格・損益がここに表示されます。', '第一笔交易平仓后，开仓价、平仓价和盈亏会显示在这里。', '第一筆交易平倉後，開倉價、平倉價與損益會顯示在這裡。', 'Los precios de entrada, salida y las ganancias o pérdidas aparecerán tras el primer cierre.', 'Les prix d’entrée, de sortie et les gains ou pertes apparaîtront après la première clôture.'],
  summary: ['청산 {count}회, 그중 {wins}회 수익. 합계 {sum}.', '{count} closed trades, {wins} profitable. Total {sum}.', '決済{count}回、うち利益{wins}回。合計{sum}。', '已平仓{count}笔，其中{wins}笔盈利。合计{sum}。', '已平倉{count}筆，其中{wins}筆獲利。合計{sum}。', '{count} operaciones cerradas, {wins} con beneficio. Total: {sum}.', '{count} opérations clôturées, dont {wins} bénéficiaires. Total : {sum}.'],
  noShareTitle: ['아직 지급된 수익 분배가 없어요', 'No profit share paid yet', '支払済みの利益分配はまだありません', '暂无已支付的利润分成', '尚無已支付的利潤分成', 'Aún no se han repartido beneficios', 'Aucun bénéfice partagé pour le moment'],
  noShareBody: ['실현 수익이 나면 그중 {share}%가 트레이더에게 분배되고 내역이 여기에 남아요.', '{share}% of realized profit is shared with the trader and recorded here.', '実現利益の{share}%がトレーダーに分配され、ここに記録されます。', '产生已实现利润后，其中{share}%分配给交易员，明细记录在这里。', '產生已實現利潤後，其中{share}%分配給交易員，明細記錄在這裡。', 'El {share}% del beneficio realizado se reparte al trader y se registra aquí.', '{share}% des bénéfices réalisés sont partagés avec le trader et consignés ici.'],
  noShareHint: ['미실현 수익에는 분배가 붙지 않아요. 손실에는 당연히 없어요.', 'No profit sharing is charged on unrealized profits or on losses.', '未実現利益や損失には利益分配は発生しません。', '未实现利润不收取分成，亏损也不收取。', '未實現利潤不收取分成，虧損也不收取。', 'No se cobra reparto sobre beneficios no realizados ni sobre pérdidas.', 'Aucun partage n’est prélevé sur les bénéfices latents ni sur les pertes.'],
  shareSummary: ['분배는 실현 수익에서만 차감돼요. 지금까지 실현 수익 {profit} 중 {share}%가 분배됐어요.', 'Profit sharing is deducted only from realized profits. {share}% of {profit} in realized profits has been shared.', '分配は実現利益からのみ差し引かれます。これまでの実現利益{profit}のうち{share}%が分配されました。', '分成仅从已实现利润中扣除。目前已实现利润{profit}中，{share}%已分配。', '分成僅從已實現利潤中扣除。目前已實現利潤{profit}中，{share}%已分配。', 'El reparto solo se descuenta de los beneficios realizados. Se ha repartido el {share}% de {profit}.', 'Le partage est prélevé uniquement sur les bénéfices réalisés. {share}% de {profit} ont été partagés.'],
  depositsWarning: ['손실 구간에서 입금이 {count}회 반복됐어요. 반복 충전은 수익률을 실제보다 부풀려 보이게 해요. 금액을 늘리기 전에 전략 자체를 다시 점검해보세요.', 'There have been {count} deposits during a losing period. Repeated top-ups can make returns look better than they are. Review the strategy before adding funds.', '損失期間中に入金が{count}回繰り返されています。追加入金は収益率を実際より高く見せることがあります。増額前に戦略を見直してください。', '亏损期间已重复存入{count}次。反复追加资金可能让收益率看起来高于实际情况。增加资金前，请重新检查策略。', '虧損期間已重複存入{count}次。反覆追加資金可能讓報酬率看起來高於實際情況。增加資金前，請重新檢查策略。', 'Se han realizado {count} ingresos durante un periodo de pérdidas. Las recargas repetidas pueden aparentar una rentabilidad mayor. Revisa la estrategia antes de aportar más.', 'Il y a eu {count} dépôts pendant une période de pertes. Les apports répétés peuvent embellir le rendement apparent. Réexaminez la stratégie avant d’ajouter des fonds.'],
  transfersSummary: ['입출금 {count}건. 모든 이동은 스팟 계좌와 카피 계좌 사이에서 일어나요 (최근 180일).', '{count} transfers, all between the spot and copy accounts (last 180 days).', '入出金{count}件。すべて現物口座とコピー口座の間の移動です（直近180日）。', '共{count}笔存取，均在现货账户与跟单账户之间划转（最近180天）。', '共{count}筆存取，均在現貨帳戶與跟單帳戶之間劃轉（最近180天）。', '{count} movimientos entre las cuentas spot y de copia (últimos 180 días).', '{count} mouvements entre les comptes spot et de copie (180 derniers jours).'],
  fillsCount: ['체결 {count}건', '{count} fills', '約定{count}件', '{count}笔成交', '{count}筆成交', '{count} ejecuciones', '{count} exécutions'],
  transactionsSummary: ['이 카피에서 지금까지 {fills}이 있었고, 수수료로 약 {fee}, 펀딩비로 약 {funding}를 지출했어요.', 'This copy has had {fills}, with approximately {fee} in fees and {funding} in funding costs.', 'このコピーではこれまで{fills}があり、手数料は約{fee}、資金調達料は約{funding}です。', '该跟单目前有{fills}，手续费约{fee}，资金费约{funding}。', '該跟單目前有{fills}，手續費約{fee}，資金費約{funding}。', 'Esta copia ha tenido {fills}, con unos {fee} en comisiones y {funding} en financiación.', 'Cette copie compte {fills}, avec environ {fee} de frais et {funding} de financement.'],
  fundingHint: ['펀딩비는 포지션을 들고 있는 동안 주기적으로 오가는 비용이에요. 트레이더가 포지션을 오래 들수록 커져요.', 'Funding is exchanged periodically while a position is held. It grows with the holding period.', '資金調達料はポジション保有中に定期的にやり取りされる費用です。保有期間が長いほど増えます。', '资金费是持仓期间定期交换的费用，持仓越久，累计费用越大。', '資金費是持倉期間定期交換的費用，持倉越久，累計費用越大。', 'La financiación se intercambia periódicamente mientras se mantiene una posición. Aumenta con el tiempo de tenencia.', 'Le financement est échangé périodiquement pendant la détention d’une position. Il augmente avec la durée de détention.'],
  expand: ['원본 거래 내역 표 펼치기 ({count}건)', 'Expand raw transactions ({count})', '元の取引明細表を開く（{count}件）', '展开原始交易明细（{count}笔）', '展開原始交易明細（{count}筆）', 'Ver transacciones originales ({count})', 'Afficher les transactions originales ({count})'],
} as const satisfies Record<string, readonly [string, string, string, string, string, string, string]>

const languages: readonly ClientLanguage[] = ['ko', 'en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr']
export type CopyHistoryKey = keyof typeof copy
export function copyHistoryText(language: ClientLanguage, key: CopyHistoryKey, values: Record<string, string | number> = {}): string {
  return copy[key][Math.max(0, languages.indexOf(language))].replace(/\{(\w+)\}/g, (match, name: string) => Object.hasOwn(values, name) ? String(values[name]) : match)
}
