// Renderer copy; reduced-motion notices describe presentation, not result completeness.
export const professionalChartKo = {
  waiting: '검증된 가격 데이터를 기다리고 있습니다.', chart: '백테스트 가격 차트',
  source: '데이터 출처를 확인할 수 없습니다.', resolution: '표시 주기를 확인할 수 없습니다.',
  precision: '가격 표시 정밀도를 확인할 수 없습니다.', empty: '표시할 가격 데이터가 없습니다.',
  narrow: '조회 범위를 좁혀 주세요.', invalidBars: '가격 데이터의 순서와 범위를 확인할 수 없습니다.', invalidFills: '체결 데이터를 확인할 수 없습니다.',
  reduced: '모션 줄이기 설정에 따라 애니메이션 재생을 건너뛰었습니다.',
  inspection: '{time} UTC · 시가 {open} · 고가 {high} · 저가 {low} · 종가 {close}',
  executionAnnouncement: '조회된 체결 {index}/{total}: {side}, 가격 {price}, 시각 {time} UTC',
  currentWindow: '현재 조회 화면', display: '{resolution} 표시', fit: '차트 전체 맞춤', save: '차트 이미지 저장',
  candle: '조회 캔들', scale: '가격 눈금', normal: '일반', log: '로그', volume: '거래량',
  skip: 'Skip · 결과 보기', replay: '체결 순서 재생', progress: '결과 설명 재생',
  replayNote: '완료된 결과 재생 · 지표 변경은 Skip 후 가능합니다',
  keyboard: '가격 캔들 및 BUY·SELL 체결. 좌우 방향키 1봉, Shift와 방향키 10봉, Home·End 처음·마지막, R 전체 맞춤, Escape 선택 해제.',
  failure: '차트를 표시하지 못했습니다. 데이터를 바꾸지 않고 다시 시도할 수 있습니다.', retry: '차트 다시 표시',
  legend: 'BUY 매수 · SELL 매도', count: '{count}개 봉 · UTC',
  emaNote: 'EMA는 현재 조회 구간의 종가로 계산한 보조선입니다. 전략의 진입 신호가 아닙니다.',
  movingAverages: '단순이동평균',
  maNote: 'MA는 각 선에 표시된 개수(7·25·99)의 연속된 봉 종가 평균입니다. 데이터가 끊기면 다시 필요한 봉이 모일 때까지 비워둡니다. 전략 신호가 아닙니다.',
  studies: '조회 봉 보조지표', studyEmpty: '계산값 없음',
  vwapNote: 'VWAP은 조회 봉의 평균가(HLC3)를 거래량으로 가중한 보조선입니다. 시간 공백 뒤 다시 시작하며, 세션 전체 VWAP이나 전략 신호가 아닙니다.',
  studiesNote: 'RSI·BB는 현재 조회 구간의 종가 기준 계산값이며 실제 전략 신호가 아닙니다. 준비·결측 등 계산 불가 구간은 빈 값으로 표시합니다.',
  unplaced: '현재 가격 봉에 연결할 수 없는 체결 {count}건은 마커로 표시하지 않았습니다.',
  fills: '조회 구간 체결', more: '체결 더 보기 ({shown}/{total})',
  days: '{count}일', hours: '{count}시간', minutes: '{count}분', seconds: '{count}초',
} as const
