import type { ClientLanguage } from './client-preferences'

/** Display labels only. User-authored text and server content are not translated. */
const ko = {
  "전략 찾기": "전략 찾기",
  "따라가는 중": "따라가는 중",
  "내 전략": "내 전략",
  "정렬 기준": "정렬 기준",
  "검증 수익순": "검증 수익순",
  "(역순)": "(역순)",
  "전체 자산군": "전체 자산군",
  "전략 또는 작성자 검색": "전략 또는 작성자 검색",
  "자세히": "자세히",
  "따라하기": "따라하기",
  "TETH 점수순": "TETH 점수순",
  "최대 낙폭 낮은순": "최대 낙폭 낮은순",
  "승률순": "승률순",
  "팔로워순": "팔로워순",
  "자산군": "자산군",
  "전략 검색": "전략 검색",
  "TETH 점수": "TETH 점수",
  "최대 낙폭": "최대 낙폭",
  "승률 ({count}회)": "승률 ({count}회)",
  "누적 백테스트 성과": "누적 백테스트 성과",
  "검증 곡선 없음": "검증 곡선 없음",
  "현재 위치": "현재 위치",
  "내가 공유한 전략": "내가 공유한 전략",
  "전략 링크 복사": "전략 링크 복사",
  "TETH에게 분석시키기": "TETH에게 분석시키기",
  "관심 전략 해제": "관심 전략 해제",
  "관심 전략": "관심 전략",
  "조건에 맞는 전략이 없어요": "조건에 맞는 전략이 없어요",
  "필터 초기화": "필터 초기화",
  "전략을 찾을 수 없어요": "전략을 찾을 수 없어요",
  "(나)": "(나)",
  "검증 완료 전략, 거래 비용 0.2% 반영 백테스트": "검증 완료 전략, 거래 비용 0.2% 반영 백테스트",
  "{nick} 검증 구간 누적 수익 곡선": "{nick} 검증 구간 누적 수익 곡선"
} as const

export type SharingCopyKey = keyof typeof ko
export const CLIENT_SHARING_COPY: Record<ClientLanguage, Record<SharingCopyKey, string>> = {
  ko,
"en": {
  "전략 찾기": "Explore strategies",
  "따라가는 중": "Following",
  "내 전략": "My strategies",
  "정렬 기준": "Sort by",
  "검증 수익순": "By validation return",
  "(역순)": "(Reverse)",
  "전체 자산군": "All asset classes",
  "전략 또는 작성자 검색": "Search strategy or author",
  "자세히": "Details",
  "따라하기": "Follow",
  "TETH 점수순": "By TETH score",
  "최대 낙폭 낮은순": "Lowest max drawdown",
  "승률순": "By win rate",
  "팔로워순": "By followers",
  "자산군": "Asset class",
  "전략 검색": "Search strategies",
  "TETH 점수": "TETH score",
  "최대 낙폭": "Max drawdown",
  "승률 ({count}회)": "Win rate ({count} trades)",
  "누적 백테스트 성과": "Cumulative backtest performance",
  "검증 곡선 없음": "No validation curve",
  "현재 위치": "Current location",
  "내가 공유한 전략": "My shared strategy",
  "전략 링크 복사": "Copy strategy link",
  "TETH에게 분석시키기": "Ask TETH to analyze",
  "관심 전략 해제": "Remove from watchlist",
  "관심 전략": "Watchlist",
  "조건에 맞는 전략이 없어요": "No matching strategies found",
  "필터 초기화": "Reset filters",
  "전략을 찾을 수 없어요": "Strategy not found",
  "(나)": "(You)",
  "검증 완료 전략, 거래 비용 0.2% 반영 백테스트": "Validated strategy, backtest with 0.2% transaction costs",
  "{nick} 검증 구간 누적 수익 곡선": "Cumulative return curve of {nick}’s validation period"
},
"ja": {
  "전략 찾기": "戦略を探す",
  "따라가는 중": "フォロー中",
  "내 전략": "マイ戦略",
  "정렬 기준": "並び替え",
  "검증 수익순": "検証リターン順",
  "(역순)": "(逆順)",
  "전체 자산군": "全資産クラス",
  "전략 또는 작성자 검색": "戦略または作成者を検索",
  "자세히": "詳細",
  "따라하기": "フォロー",
  "TETH 점수순": "TETHスコア順",
  "최대 낙폭 낮은순": "最大ドローダウンが低い順",
  "승률순": "勝率順",
  "팔로워순": "フォロワー順",
  "자산군": "資産クラス",
  "전략 검색": "戦略を検索",
  "TETH 점수": "TETHスコア",
  "최대 낙폭": "最大ドローダウン",
  "승률 ({count}회)": "勝率（{count}回）",
  "누적 백테스트 성과": "累積バックテスト実績",
  "검증 곡선 없음": "検証曲線なし",
  "현재 위치": "現在位置",
  "내가 공유한 전략": "自分が共有した戦略",
  "전략 링크 복사": "戦略リンクをコピー",
  "TETH에게 분석시키기": "TETHに分析を依頼",
  "관심 전략 해제": "お気に入り解除",
  "관심 전략": "お気に入り戦略",
  "조건에 맞는 전략이 없어요": "条件に一致する戦略がありません",
  "필터 초기화": "フィルターをリセット",
  "전략을 찾을 수 없어요": "戦略が見つかりません",
  "(나)": "(自分)",
  "검증 완료 전략, 거래 비용 0.2% 반영 백테스트": "検証済み戦略、取引コスト0.2%反映バックテスト",
  "{nick} 검증 구간 누적 수익 곡선": "{nick}検証区間の累積リターン曲線"
},
"zh-CN": {
  "전략 찾기": "发现策略",
  "따라가는 중": "正在跟随",
  "내 전략": "我的策略",
  "정렬 기준": "排序方式",
  "검증 수익순": "按验证收益",
  "(역순)": "(倒序)",
  "전체 자산군": "全部资产类别",
  "전략 또는 작성자 검색": "搜索策略或作者",
  "자세히": "详情",
  "따라하기": "跟随",
  "TETH 점수순": "按TETH评分",
  "최대 낙폭 낮은순": "最低最大回撤",
  "승률순": "按胜率",
  "팔로워순": "按关注者数",
  "자산군": "资产类别",
  "전략 검색": "搜索策略",
  "TETH 점수": "TETH评分",
  "최대 낙폭": "最大回撤",
  "승률 ({count}회)": "胜率（{count}次）",
  "누적 백테스트 성과": "累计回测表现",
  "검증 곡선 없음": "无验证曲线",
  "현재 위치": "当前位置",
  "내가 공유한 전략": "我分享的策略",
  "전략 링크 복사": "复制策略链接",
  "TETH에게 분석시키기": "让TETH分析",
  "관심 전략 해제": "取消关注策略",
  "관심 전략": "关注策略",
  "조건에 맞는 전략이 없어요": "没有符合条件的策略",
  "필터 초기화": "重置筛选",
  "전략을 찾을 수 없어요": "未找到策略",
  "(나)": "(我)",
  "검증 완료 전략, 거래 비용 0.2% 반영 백테스트": "已验证策略，计入0.2%交易成本的回测",
  "{nick} 검증 구간 누적 수익 곡선": "{nick}验证区间累计收益曲线"
},
"zh-TW": {
  "전략 찾기": "探索策略",
  "따라가는 중": "正在跟隨",
  "내 전략": "我的策略",
  "정렬 기준": "排序依據",
  "검증 수익순": "依驗證收益",
  "(역순)": "(反向)",
  "전체 자산군": "全部資產類別",
  "전략 또는 작성자 검색": "搜尋策略或作者",
  "자세히": "詳細資訊",
  "따라하기": "跟隨",
  "TETH 점수순": "按TETH評分",
  "최대 낙폭 낮은순": "最低最大回撤",
  "승률순": "按勝率",
  "팔로워순": "按追蹤者數",
  "자산군": "資產類別",
  "전략 검색": "搜尋策略",
  "TETH 점수": "TETH評分",
  "최대 낙폭": "最大回撤",
  "승률 ({count}회)": "勝率（{count}次）",
  "누적 백테스트 성과": "累積回測表現",
  "검증 곡선 없음": "無驗證曲線",
  "현재 위치": "目前位置",
  "내가 공유한 전략": "我分享的策略",
  "전략 링크 복사": "複製策略連結",
  "TETH에게 분석시키기": "讓TETH分析",
  "관심 전략 해제": "取消關注策略",
  "관심 전략": "關注策略",
  "조건에 맞는 전략이 없어요": "沒有符合條件的策略",
  "필터 초기화": "重設篩選",
  "전략을 찾을 수 없어요": "找不到策略",
  "(나)": "(我)",
  "검증 완료 전략, 거래 비용 0.2% 반영 백테스트": "已驗證策略，計入0.2%交易成本的回測",
  "{nick} 검증 구간 누적 수익 곡선": "{nick}驗證區間累計收益曲線"
},
"es": {
  "전략 찾기": "Explorar estrategias",
  "따라가는 중": "Siguiendo",
  "내 전략": "Mis estrategias",
  "정렬 기준": "Ordenar por",
  "검증 수익순": "Por rentabilidad de validación",
  "(역순)": "(Inverso)",
  "전체 자산군": "Todas las clases de activos",
  "전략 또는 작성자 검색": "Buscar estrategia o autor",
  "자세히": "Detalles",
  "따라하기": "Seguir",
  "TETH 점수순": "Por puntuación TETH",
  "최대 낙폭 낮은순": "Menor drawdown máximo",
  "승률순": "Por tasa de acierto",
  "팔로워순": "Por seguidores",
  "자산군": "Clase de activo",
  "전략 검색": "Buscar estrategias",
  "TETH 점수": "Puntuación TETH",
  "최대 낙폭": "Drawdown máximo",
  "승률 ({count}회)": "Tasa de acierto ({count} operaciones)",
  "누적 백테스트 성과": "Rendimiento acumulado de backtest",
  "검증 곡선 없음": "Sin curva de validación",
  "현재 위치": "Ubicación actual",
  "내가 공유한 전략": "Mi estrategia compartida",
  "전략 링크 복사": "Copiar enlace de la estrategia",
  "TETH에게 분석시키기": "Pedir análisis a TETH",
  "관심 전략 해제": "Quitar de favoritos",
  "관심 전략": "Estrategias favoritas",
  "조건에 맞는 전략이 없어요": "No se encontraron estrategias que coincidan",
  "필터 초기화": "Restablecer filtros",
  "전략을 찾을 수 없어요": "No se encontró la estrategia",
  "(나)": "(Tú)",
  "검증 완료 전략, 거래 비용 0.2% 반영 백테스트": "Estrategia validada, backtest con costos de transacción del 0,2%",
  "{nick} 검증 구간 누적 수익 곡선": "Curva de rentabilidad acumulada del período de validación de {nick}"
},
"fr": {
  "전략 찾기": "Explorer les stratégies",
  "따라가는 중": "Suivis",
  "내 전략": "Mes stratégies",
  "정렬 기준": "Trier par",
  "검증 수익순": "Par rendement de validation",
  "(역순)": "(Inversé)",
  "전체 자산군": "Toutes les classes d’actifs",
  "전략 또는 작성자 검색": "Rechercher une stratégie ou un auteur",
  "자세히": "Détails",
  "따라하기": "Suivre",
  "TETH 점수순": "Par score TETH",
  "최대 낙폭 낮은순": "Drawdown maximal le plus faible",
  "승률순": "Par taux de réussite",
  "팔로워순": "Par abonnés",
  "자산군": "Classe d’actifs",
  "전략 검색": "Rechercher des stratégies",
  "TETH 점수": "Score TETH",
  "최대 낙폭": "Drawdown maximal",
  "승률 ({count}회)": "Taux de réussite ({count} opérations)",
  "누적 백테스트 성과": "Performance cumulée du backtest",
  "검증 곡선 없음": "Aucune courbe de validation",
  "현재 위치": "Emplacement actuel",
  "내가 공유한 전략": "Ma stratégie partagée",
  "전략 링크 복사": "Copier le lien de la stratégie",
  "TETH에게 분석시키기": "Demander une analyse à TETH",
  "관심 전략 해제": "Retirer des favoris",
  "관심 전략": "Stratégies favorites",
  "조건에 맞는 전략이 없어요": "Aucune stratégie ne correspond aux critères",
  "필터 초기화": "Réinitialiser les filtres",
  "전략을 찾을 수 없어요": "Stratégie introuvable",
  "(나)": "(Vous)",
  "검증 완료 전략, 거래 비용 0.2% 반영 백테스트": "Stratégie validée, backtest intégrant 0,2 % de frais de transaction",
  "{nick} 검증 구간 누적 수익 곡선": "Courbe de rendement cumulé de la période de validation de {nick}"
}
}

export function sharingCopy(language: ClientLanguage, key: SharingCopyKey, values: Record<string, string | number> = {}) {
  return CLIENT_SHARING_COPY[language][key].replace(/\{(\w+)\}/g, (token, name: string) => String(values[name] ?? token))
}
