import type { ClientLanguage } from './client-preferences'
const rows = {
  addShort: ['추가', 'Add', '追加', '添加', '新增', 'Añadir', 'Ajouter'],
  planSection: ['구독', 'Subscription', 'サブスクリプション', '订阅', '訂閱', 'Suscripción', 'Abonnement'],
  manageSubscription: ['구독 관리', 'Manage subscription', 'サブスクリプションを管理', '管理订阅', '管理訂閱', 'Gestionar suscripción', 'Gérer l’abonnement'],
  manage: ['관리', 'Manage', '管理', '管理', '管理', 'Gestionar', 'Gérer'],
  information: ['청구 정보', 'Billing information', '請求先情報', '账单信息', '帳單資訊', 'Datos de facturación', 'Informations de facturation'],
  change: ['변경', 'Change', '変更', '更改', '變更', 'Cambiar', 'Modifier'],
  fee: ['요금', 'Price', '料金', '费用', '費用', 'Precio', 'Tarif'],
  subscription: ['TETH 구독', 'TETH Subscription', 'TETH サブスクリプション', 'TETH 订阅', 'TETH 訂閱', 'Suscripción TETH', 'Abonnement TETH'],
  invited: ['TETH 초대 계정', 'TETH Invited Account', 'TETH 招待アカウント', 'TETH 邀请账号', 'TETH 邀請帳戶', 'Cuenta invitada TETH', 'Compte invité TETH'],
  expired: ['구독이 종료되었습니다', 'Subscription expired', 'サブスクリプションが終了しました', '订阅已到期', '訂閱已到期', 'La suscripción ha expirado', 'L’abonnement a expiré'],
  none: ['이용 중인 플랜이 없습니다', 'No active plan', '利用中のプランはありません', '无正在使用的方案', '無使用中的方案', 'No hay ningún plan en uso', 'Aucun forfait actif'],
  resume: ['다시 시작', 'Resume subscription', 'サブスクリプションを再開', '恢复订阅', '恢復訂閱', 'Reanudar suscripción', 'Reprendre l’abonnement'],
  subscribe: ['다시 구독', 'Resubscribe', '再登録', '重新订阅', '重新訂閱', 'Volver a suscribirse', 'Se réabonner'],
  connect: ['거래소 연결', 'Connect exchange', '取引所を接続', '连接交易所', '連接交易所', 'Conectar exchange', 'Connecter une plateforme d’échange'],
  cancel: ['구독 해지', 'Cancel subscription', 'サブスクリプションを解約', '取消订阅', '取消訂閱', 'Cancelar suscripción', 'Résilier l’abonnement'],
  cancelShort: ['해지', 'Cancel', '解約', '取消', '取消', 'Cancelar', 'Résilier'],
  noInvitedInvoices: ['TETH 초대 계정은 결제 내역이 없습니다', 'TETH invited accounts do not have billing history.', 'TETH 招待アカウントには請求履歴がありません。', 'TETH 邀请账号没有账单记录。', 'TETH 邀請帳戶沒有帳單紀錄。', 'Las cuentas invitadas de TETH no tienen historial de facturación.', 'Les comptes invités TETH n’ont aucun historique de facturation.'],
  all: ['전체 보기', 'View all', 'すべて表示', '查看全部', '查看全部', 'Ver todo', 'Tout afficher'],
  less: ['접기', 'Show less', '折りたたむ', '收起', '收合', 'Ver menos', 'Réduire'],
  noInvoices: ['아직 결제 내역이 없습니다', 'No payment history yet', '支払い履歴はまだありません', '暂无付款记录', '尚無付款紀錄', 'Aún no hay historial de pagos', 'Aucun historique de paiement'],
  noMethods: ['등록한 결제 수단이 없습니다', 'No payment methods added', '登録済みの支払い方法はありません', '未添加付款方式', '尚未新增付款方式', 'No hay métodos de pago registrados', 'Aucun moyen de paiement enregistré'],
  receipt: ['영수증', 'Receipt', '領収書', '收据', '收據', 'Recibo', 'Reçu'],
  failedReceipt: ['결제 실패 내역', 'Failed payment details', '支払い失敗の詳細', '付款失败详情', '付款失敗詳情', 'Detalles del pago fallido', 'Détails du paiement échoué'],
  refundedReceipt: ['환불 내역', 'Refund details', '返金の詳細', '退款详情', '退款詳情', 'Detalles del reembolso', 'Détails du remboursement'],
  content: ['내용', 'Description', '内容', '内容', '內容', 'Descripción', 'Description'],
  date: ['날짜', 'Date', '日付', '日期', '日期', 'Fecha', 'Date'],
  amount: ['금액', 'Amount', '金額', '金额', '金額', 'Importe', 'Montant'],
  method: ['결제 수단', 'Payment method', '支払い方法', '付款方式', '付款方式', 'Método de pago', 'Moyen de paiement'],
  number: ['번호', 'Number', '番号', '编号', '編號', 'Número', 'Numéro'],
  recipient: ['받는 사람', 'Recipient', '受取人', '收件人', '收件人', 'Destinatario', 'Destinataire'],
  close: ['닫기', 'Close', '閉じる', '关闭', '關閉', 'Cerrar', 'Fermer'],
  edit: ['편집', 'Edit', '編集', '编辑', '編輯', 'Editar', 'Modifier'],
  email: ['결제 이메일', 'Billing email', '請求先メールアドレス', '账单邮箱', '帳單電子郵件', 'Correo de facturación', 'E-mail de facturation'],
  address: ['청구지 주소', 'Billing address', '請求先住所', '账单地址', '帳單地址', 'Dirección de facturación', 'Adresse de facturation'],
  addressHint: ['도로명 주소, 도시, 우편번호, 국가', 'Street, city, postal code, country', '住所、市区町村、郵便番号、国', '街道、城市、邮编、国家', '街道、城市、郵遞區號、國家', 'Calle, ciudad, código postal, país', 'Rue, ville, code postal, pays'],
  emailInvalid: ['결제 이메일을 확인해 주십시오', 'Check your billing email.', '請求先メールアドレスをご確認ください', '请检查账单邮箱', '請檢查帳單電子郵件', 'Compruebe el correo de facturación.', 'Vérifiez l’e-mail de facturation.'],
  nameRequired: ['이름을 입력해 주십시오', 'Enter a name.', '名前を入力してください', '请输入姓名', '請輸入姓名', 'Introduzca un nombre.', 'Saisissez un nom.'],
  add: ['새로 추가', 'Add new', '新しく追加', '新增', '新增', 'Añadir nuevo', 'Ajouter'],
  default: ['기본 결제 수단', 'Default', '既定', '默认', '預設', 'Predeterminado', 'Par défaut'],
  makeDefault: ['기본으로 설정', 'Set as default', '既定にする', '设为默认', '設為預設', 'Establecer por defecto', 'Définir par défaut'],
  remove: ['삭제', 'Delete', '削除', '删除', '刪除', 'Eliminar', 'Supprimer'],
  removeTitle: ['결제 수단을 삭제하시겠습니까?', 'Delete this payment method?', 'この支払い方法を削除しますか？', '删除此付款方式？', '刪除此付款方式？', '¿Eliminar este método de pago?', 'Supprimer ce moyen de paiement ?'],
  defaultTitle: ['기본 결제 수단으로 설정하시겠습니까?', 'Set as the default payment method?', '既定の支払い方法に設定しますか？', '设为默认付款方式？', '設為預設付款方式？', '¿Establecer como método de pago predeterminado?', 'Définir comme moyen de paiement par défaut ?'],
  addTitle: ['결제 수단 추가', 'Add a payment method', '支払い方法の追加', '添加付款方式', '新增付款方式', 'Añadir un método de pago', 'Ajouter un moyen de paiement'],
  providerHint: ['카드 정보는 연결된 결제 서비스에서 입력합니다.', 'Enter card details in the connected payment service.', 'カード情報は連携先の決済サービスで入力します。', '请在已连接的支付服务中输入卡片信息。', '請在已連接的付款服務中輸入卡片資訊。', 'Introduzca los datos de la tarjeta en el servicio de pago conectado.', 'Saisissez les informations de carte dans le service de paiement connecté.'],
} as const
const languages: readonly ClientLanguage[] = ['ko', 'en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr']
export function billingText(language: ClientLanguage, key: keyof typeof rows): string {
  return rows[key][languages.indexOf(language)] ?? rows[key][0]
}
