import { useClientPreferences, type ClientLanguage } from './client-preferences'

// UI chrome only. User messages, saved titles, AI prose and artifact contents
// retain their original language. Columns are checked for all seven locales.
type Translations = readonly [ko: string, en: string, ja: string, zhCN: string, zhTW: string, es: string, fr: string]
const languageColumn = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const satisfies Record<ClientLanguage, number>
export const conversationCopy = {
  retry: ['요청을 완료하지 못했습니다. 다시 시도해주세요.', 'Could not complete the request. Please try again.', '処理を完了できませんでした。再試行してください。', '未能完成请求，请重试。', '無法完成要求，請重試。', 'No se pudo completar. Inténtalo de nuevo.', 'Impossible de terminer. Réessayez.'],
  archive: ['목록에서 보관', 'Archive from list', '一覧から保管', '从列表归档', '從清單封存', 'Archivar de la lista', 'Archiver de la liste'],
  archiveDetail: ['이 대화를 목록에서 보관합니다. 실행 중인 연구, 전략, 거래는 중단하거나 삭제하지 않습니다.', 'Archive this conversation from the list. Running research, strategies and trades are not stopped or deleted.', 'この会話を一覧から保管します。実行中の研究・戦略・取引は停止・削除しません。', '将此对话归档。不会停止或删除正在运行的研究、策略或交易。', '封存此對話。不會停止或刪除執行中的研究、策略或交易。', 'Archiva esta conversación. No detiene ni elimina investigaciones, estrategias ni operaciones.', 'Archive cette conversation sans arrêter ni supprimer les recherches, stratégies ou transactions.'],
  loadRecords: ['기록 불러오기', 'Load history', '履歴を読み込む', '加载记录', '載入紀錄', 'Cargar historial', 'Charger l’historique'],
  moreRecords: ['기록 더 보기', 'Load more history', '履歴をさらに読み込む', '加载更多记录', '載入更多紀錄', 'Cargar más historial', 'Charger plus d’historique'],
  copyCode: ['코드 복사', 'Copy code', 'コードをコピー', '复制代码', '複製程式碼', 'Copiar código', 'Copier le code'],
  copyCodeShort: ['복사', 'Copy', 'コピー', '复制', '複製', 'Copiar', 'Copier'],
  codeCopied: ['✓ 복사됨', '✓ Copied', '✓ コピー済み', '✓ 已复制', '✓ 已複製', '✓ Copiado', '✓ Copié'],
  codeBlock: ['코드 블록', 'Code block', 'コードブロック', '代码块', '程式碼區塊', 'Bloque de código', 'Bloc de code'],
  responseTable: ['답변 표', 'Response table', '回答の表', '回答表格', '回答表格', 'Tabla de la respuesta', 'Tableau de la réponse'],
  clarificationNeeded: ['입력이 필요합니다, 아래 카드에서 답해주세요', 'Your input is needed. Please answer below.', '入力が必要です。下のカードで回答してください', '需要补充信息，请在下方卡片中回答', '需要補充資訊，請在下方卡片中回答', 'Necesitamos tu respuesta. Responde en la tarjeta.', 'Votre réponse est nécessaire. Répondez ci-dessous.'],
  clarificationQuestion: ['질문', 'Question', '質問', '问题', '問題', 'Pregunta', 'Question'],
  clarificationSkip: ['이 질문 건너뛰기 (추천값으로 진행)', 'Skip this question (use the suggested value)', 'この質問をスキップ（推奨値を使用）', '跳过此问题（使用建议值）', '跳過此問題（使用建議值）', 'Omitir esta pregunta (usar el valor sugerido)', 'Passer cette question (utiliser la valeur suggérée)'],
  clarificationFree: ['직접 답변 작성', 'Write your own answer', '自分で回答を入力', '自行输入回答', '自行輸入回答', 'Escribe tu respuesta', 'Rédiger votre réponse'],
  activityRegion: ['TETH 작업 과정', 'TETH activity', 'TETHの作業過程', 'TETH任务过程', 'TETH工作過程', 'Actividad de TETH', 'Activité de TETH'],
  activityDescription: ['작업 설명', 'Activity description', '作業の説明', '任务说明', '工作說明', 'Descripción de la actividad', 'Description de l’activité'],
  elapsedSeconds: ['{seconds}초', '{seconds}s', '{seconds}秒', '{seconds}秒', '{seconds}秒', '{seconds} s', '{seconds} s'],
  elapsedTime: ['경과 시간 {duration}', 'Elapsed time {duration}', '経過時間 {duration}', '已用时间 {duration}', '經過時間 {duration}', 'Tiempo transcurrido {duration}', 'Temps écoulé {duration}'],
  failed: ['실패', 'Failed', '失敗', '失败', '失敗', 'Fallido', 'Échec'],
  stopped: ['중지됨', 'Stopped', '停止済み', '已停止', '已停止', 'Detenido', 'Arrêté'],
  goodAnswer: ['좋은 답변', 'Good answer', '良い回答', '回答不错', '回答不錯', 'Buena respuesta', 'Bonne réponse'],
  poorAnswer: ['아쉬운 답변', 'Poor answer', '不十分な回答', '回答欠佳', '回答欠佳', 'Respuesta mejorable', 'Réponse insatisfaisante'],
  copyAnswer: ['답변 복사', 'Copy answer', '回答をコピー', '复制回答', '複製回答', 'Copiar respuesta', 'Copier la réponse'],
  copiedAnswer: ['답변 복사 완료', 'Answer copied', '回答をコピーしました', '回答已复制', '回答已複製', 'Respuesta copiada', 'Réponse copiée'],
  copyError: ['복사 권한을 확인해주세요.', 'Please check clipboard permissions.', 'コピーの権限を確認してください。', '请检查剪贴板权限。', '請檢查剪貼簿權限。', 'Revisa los permisos del portapapeles.', 'Vérifiez les autorisations du presse-papiers.'],
  thinkingSummary: ['생각을 정리하는 중', 'Organizing thoughts', '考えを整理中', '正在整理思路', '正在整理思路', 'Organizando ideas', 'Organisation des idées'],
  workStopped: ['작업 중단, 1단계', 'Work stopped, 1 step', '作業中断、1ステップ', '任务已停止，1个步骤', '工作已停止，1個步驟', 'Trabajo detenido, 1 paso', 'Travail arrêté, 1 étape'],
  workDone: ['작업 완료, 1단계', 'Work complete, 1 step', '作業完了、1ステップ', '任务完成，1个步骤', '工作完成，1個步驟', 'Trabajo completado, 1 paso', 'Travail terminé, 1 étape'],
  thinking: ['생각하는 중', 'Thinking', '思考中', '正在思考', '正在思考', 'Pensando', 'Réflexion en cours'],
  thoughtDone: ['생각 완료', 'Thinking complete', '思考完了', '思考完成', '思考完成', 'Reflexión completada', 'Réflexion terminée'],
  tethThinking: ['TETH가 생각 중입니다', 'TETH is thinking', 'TETHが思考中です', 'TETH正在思考', 'TETH正在思考', 'TETH está pensando', 'TETH réfléchit'],
  responseStopped: ['응답이 중지되었습니다.', 'The response was stopped.', '応答を停止しました。', '回答已停止。', '回答已停止。', 'La respuesta se ha detenido.', 'La réponse a été arrêtée.'],
  conversationMenu: ['대화 메뉴', 'Conversation menu', '会話メニュー', '对话菜单', '對話選單', 'Menú de conversación', 'Menu de conversation'],
  manageConversation: ['대화 관리', 'Manage conversation', '会話の管理', '管理对话', '管理對話', 'Gestionar conversación', 'Gérer la conversation'],
  strategyName: ['전략 이름', 'Strategy name', '戦略名', '策略名称', '策略名稱', 'Nombre de la estrategia', 'Nom de la stratégie'],
  save: ['저장', 'Save', '保存', '保存', '儲存', 'Guardar', 'Enregistrer'],
  rename: ['이름 변경', 'Rename', '名前を変更', '重命名', '重新命名', 'Cambiar nombre', 'Renommer'],
  delete: ['삭제', 'Delete', '削除', '删除', '刪除', 'Eliminar', 'Supprimer'],
  confirmDelete: ['정말 삭제할까요? 되돌릴 수 없어요', 'Delete permanently? This cannot be undone.', '削除しますか？元に戻せません', '确定删除吗？此操作无法撤销', '確定刪除嗎？此操作無法復原', '¿Eliminar? No se puede deshacer.', 'Supprimer ? Cette action est irréversible.'],
  editMessage: ['메시지 수정', 'Edit message', 'メッセージを編集', '编辑消息', '編輯訊息', 'Editar mensaje', 'Modifier le message'],
  copyMessage: ['메시지 복사', 'Copy message', 'メッセージをコピー', '复制消息', '複製訊息', 'Copiar mensaje', 'Copier le message'],
  copiedMessage: ['메시지 복사 완료', 'Message copied', 'メッセージをコピーしました', '消息已复制', '訊息已複製', 'Mensaje copiado', 'Message copié'],
  newStrategy: ['새 전략', 'New strategy', '新しい戦略', '新策略', '新策略', 'Nueva estrategia', 'Nouvelle stratégie'],
  conversationRegion: ['TETH AI 대화', 'TETH AI conversation', 'TETH AIの会話', 'TETH AI对话', 'TETH AI對話', 'Conversación con TETH AI', 'Conversation TETH AI'],
  editTitle: ['대화 제목 수정', 'Edit conversation title', '会話のタイトルを編集', '编辑对话标题', '編輯對話標題', 'Editar título de conversación', 'Modifier le titre de la conversation'],
  conversationDocuments: ['대화 문서', 'Conversation documents', '会話ドキュメント', '对话文档', '對話文件', 'Documentos de la conversación', 'Documents de la conversation'],
  chat: ['대화', 'Chat', '会話', '对话', '對話', 'Conversación', 'Conversation'],
  researchRunning: ['연구 진행 중', 'Research in progress', '研究進行中', '研究进行中', '研究進行中', 'Investigación en curso', 'Recherche en cours'],
  newResponse: ['새 응답', 'New response', '新しい応答', '新回答', '新回答', 'Nueva respuesta', 'Nouvelle réponse'],
  placeholder: ['시장에 대해 무엇이든 물어보세요', 'Ask anything about the markets', '市場について何でも聞いてください', '关于市场，想问什么都可以', '關於市場，想問什麼都可以', 'Pregunta lo que quieras sobre los mercados', 'Posez vos questions sur les marchés'],
  stop: ['응답 중지', 'Stop response', '応答を停止', '停止回答', '停止回答', 'Detener respuesta', 'Arrêter la réponse'],
  waiting: ['응답 기다리는 중', 'Waiting for response', '応答を待っています', '正在等待回答', '正在等待回答', 'Esperando respuesta', 'En attente de réponse'],
  openPlan: ['연구 계획 문서 열기', 'Open Research Plan document', 'Research Planを開く', '打开Research Plan文档', '開啟Research Plan文件', 'Abrir el documento Research Plan', 'Ouvrir le document Research Plan'],
  openCritic: ['비판 검토 기록 문서 열기', 'Open Critic Review document', 'Critic Reviewを開く', '打开Critic Review文档', '開啟Critic Review文件', 'Abrir el documento Critic Review', 'Ouvrir le document Critic Review'],
  working: ['작업 중', 'Working', '作業中', '工作中', '工作中', 'Trabajando', 'En cours'],
  done: ['완료', 'Complete', '完了', '完成', '完成', 'Completado', 'Terminé'],
  pending: ['대기', 'Waiting', '待機', '等待', '等待', 'En espera', 'En attente'],
  pinned: ['고정됨', 'Pinned', '固定済み', '已置顶', '已釘選', 'Fijado', 'Épinglé'],
  manage: ['관리', 'Manage', '管理', '管理', '管理', 'Gestionar', 'Gérer'],
  manageResearch: ['연구 관리', 'Manage research', '研究の管理', '管理研究', '管理研究', 'Gestionar investigación', 'Gérer la recherche'],
  pin: ['고정', 'Pin', '固定', '置顶', '釘選', 'Fijar', 'Épingler'],
  unpin: ['고정 해제', 'Unpin', '固定を解除', '取消置顶', '取消釘選', 'Desfijar', 'Désépingler'],
  renameResearch: ['연구 이름 변경', 'Rename research', '研究名を変更', '重命名研究', '重新命名研究', 'Cambiar nombre de investigación', 'Renommer la recherche'],
  deleteResearch: ['연구를 삭제하시겠습니까?', 'Delete this research?', 'この研究を削除しますか？', '要删除此研究吗？', '要刪除此研究嗎？', '¿Eliminar esta investigación?', 'Supprimer cette recherche ?'],
  researchName: ['연구 이름', 'Research name', '研究名', '研究名称', '研究名稱', 'Nombre de la investigación', 'Nom de la recherche'],
  researchDeleteDetail: ['이 연구의 대화, 검증 기록, 아티팩트가 함께 삭제되며 되돌릴 수 없습니다.', 'This research’s conversation, validation history and artifacts will be deleted. This cannot be undone.', 'この研究の会話、検証履歴、アーティファクトが削除されます。元に戻せません。', '此研究的对话、验证记录和产出文件将一并删除，且无法撤销。', '此研究的對話、驗證記錄和產出檔案將一併刪除，且無法復原。', 'Se eliminarán la conversación, el historial de validación y los archivos de esta investigación. No se puede deshacer.', 'La conversation, l’historique de validation et les documents de cette recherche seront supprimés. Cette action est irréversible.'],
  cancel: ['취소', 'Cancel', 'キャンセル', '取消', '取消', 'Cancelar', 'Annuler'],
  draft: ['초안', 'Draft', '下書き', '草稿', '草稿', 'Borrador', 'Brouillon'],
  inProgress: ['진행 중', 'In progress', '進行中', '进行中', '進行中', 'En curso', 'En cours'],
  reviewNeeded: ['검토 필요', 'Review needed', '確認が必要', '需要审核', '需要審核', 'Requiere revisión', 'À vérifier'],
  paperRunning: ['가상 검증 중', 'Paper running', 'Paper実行中', 'Paper运行中', 'Paper執行中', 'Paper en ejecución', 'Paper en cours'],
  askTeth: ['TETH에게 물어보세요', 'Ask TETH', 'TETHに聞いてください', '向TETH提问', '向TETH提問', 'Pregunta a TETH', 'Posez votre question à TETH'],
  send: ['메시지 보내기', 'Send message', 'メッセージを送信', '发送消息', '傳送訊息', 'Enviar mensaje', 'Envoyer le message'],
  title: ['대화 제목', 'Conversation title', '会話のタイトル', '对话标题', '對話標題', 'Título de la conversación', 'Titre de la conversation'],
  checkPlan: ['확인 →', 'View research plan →', '研究計画を確認 →', '查看研究计划 →', '查看研究計畫 →', 'Ver plan de investigación →', 'Voir le plan de recherche →'],
  delegate: ['전략 맡기기', 'Delegate strategy', '戦略を任せる', '委托策略', '委託策略', 'Delegar estrategia', 'Déléguer la stratégie'],
  configureAndValidate: ['조건을 정하고 검증하기 →', 'Set conditions and validate →', '条件を設定して検証 →', '设定条件并验证 →', '設定條件並驗證 →', 'Definir condiciones y validar →', 'Définir les conditions et valider →'],
  skipContent: ['본문으로 건너뛰기', 'Skip to content', '本文へスキップ', '跳转到正文', '跳至正文', 'Saltar al contenido', 'Aller au contenu'],
  deleted: ['전략을 삭제했어요', 'Strategy deleted', '戦略を削除しました', '策略已删除', '策略已刪除', 'Estrategia eliminada', 'Stratégie supprimée'],
  deletePartial: ['목록에서 제거했지만 저장소의 일부 기록을 삭제하지 못했습니다.', 'Removed from the list, but some stored records could not be deleted.', '一覧から削除しましたが、一部の保存記録を削除できませんでした。', '已从列表移除，但部分存储记录未能删除。', '已從清單移除，但部分儲存記錄未能刪除。', 'Se quitó de la lista, pero no se pudieron eliminar algunos registros guardados.', 'Retiré de la liste, mais certains enregistrements n’ont pas pu être supprimés.'],
  profileSaveError: ['계정 미리보기 상태를 이 탭에 저장하지 못했습니다.', 'The account preview could not be saved in this tab.', 'アカウントのプレビュー状態をこのタブに保存できませんでした。', '无法在此标签页保存账户预览状态。', '無法在此分頁儲存帳戶預覽狀態。', 'No se pudo guardar la vista previa de la cuenta en esta pestaña.', 'L’aperçu du compte n’a pas pu être enregistré dans cet onglet.'],
  storageError: ['이 탭에 변경 내용을 저장하지 못했습니다. 새로고침 전에 내용을 복사해주세요.', 'Changes could not be saved in this tab. Copy your content before refreshing.', 'このタブに変更を保存できませんでした。再読み込みの前に内容をコピーしてください。', '无法在此标签页保存更改。刷新前请复制内容。', '無法在此分頁儲存變更。重新整理前請複製內容。', 'No se pudieron guardar los cambios en esta pestaña. Copia el contenido antes de recargar.', 'Les modifications n’ont pas pu être enregistrées dans cet onglet. Copiez le contenu avant d’actualiser.'],
  recoveryWarning: ['일부 대화 기록을 복원하지 못했습니다. 나머지 대화와 초안은 유지했습니다.', 'Some conversation history could not be restored. Other conversations and drafts were preserved.', '一部の会話履歴を復元できませんでした。他の会話と下書きは保持されています。', '部分对话记录无法恢复。其他对话和草稿已保留。', '部分對話記錄無法復原。其他對話和草稿已保留。', 'No se pudo recuperar parte del historial. Se conservaron las demás conversaciones y borradores.', 'Une partie de l’historique n’a pas pu être restaurée. Les autres conversations et brouillons ont été conservés.'],
  closeNotice: ['알림 닫기', 'Dismiss notification', '通知を閉じる', '关闭通知', '關閉通知', 'Cerrar notificación', 'Fermer la notification'],
  busyError: ['이전 답변을 마무리하는 중이에요. 끝나면 다시 눌러주세요.', 'The previous response is still finishing. Try again when it is complete.', '前の回答を仕上げています。完了してからもう一度お試しください。', '上一条回答仍在生成。完成后请重试。', '上一則回答仍在產生。完成後請重試。', 'La respuesta anterior aún está terminando. Inténtalo de nuevo cuando acabe.', 'La réponse précédente est en cours de finalisation. Réessayez une fois terminée.'],
} as const satisfies Record<string, Translations>

export type ConversationCopyKey = keyof typeof conversationCopy
export function getConversationCopy(language: ClientLanguage, key: ConversationCopyKey): string {
  return conversationCopy[key][languageColumn[language]]
}
const statusKeys: Record<string, ConversationCopyKey> = {
  '초안': 'draft', '진행 중': 'inProgress', '검토 필요': 'reviewNeeded', '완료': 'done',
  'Paper 실행 중': 'paperRunning', '작업 중': 'working', '대기': 'pending',
}
export function useConversationCopy() {
  const { language } = useClientPreferences()
  return {
    language,
    c: (key: ConversationCopyKey) => getConversationCopy(language, key),
    statusLabel: (status: string) => Object.hasOwn(statusKeys, status) ? getConversationCopy(language, statusKeys[status]) : status,
  }
}
