import type { ClientLanguage } from './client-preferences'

/** Display-only source copy. Budget labels remain fixed KRW amounts, without conversion or execution authority. */
const ko = {
  "전략 따라하기": "전략 따라하기",
  "예상 결과 확인": "예상 결과 확인",
  "{nick} ({asset} 전략)": "{nick} ({asset} 전략)",
  "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%": "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%",
  "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.": "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.",
  "시작 예산": "시작 예산",
  "손절선": "손절선",
  "익절 목표": "익절 목표",
  "기간 청산": "기간 청산",
  "100만원": "100만원",
  "500만원": "500만원",
  "1,000만원": "1,000만원",
  "3,000만원 이상": "3,000만원 이상",
  "가볍게 시작": "가볍게 시작",
  "표준": "표준",
  "본격적으로": "본격적으로",
  "크게": "크게",
  "-3%까지": "-3%까지",
  "-5%까지": "-5%까지",
  "-8%까지": "-8%까지",
  "-12%까지": "-12%까지",
  "짧게 끊기": "짧게 끊기",
  "여유있게": "여유있게",
  "길게 버티기": "길게 버티기",
  "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.": "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.",
  "예상 TETH 점수": "예상 TETH 점수",
  "{score}점": "{score}점",
  "검증 수익": "검증 수익",
  "최대 낙폭": "최대 낙폭",
  "거래 수": "거래 수",
  "{count}회": "{count}회",
  "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.": "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.",
  "표본 {count}회가 적어 점수에 페널티가 있어요.": "표본 {count}회가 적어 점수에 페널티가 있어요.",
  "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.": "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.",
  "원본과 달라진 조건": "원본과 달라진 조건",
  "손절 {before}% → {after}%": "손절 {before}% → {after}%",
  "익절 {before} → {after}": "익절 {before} → {after}",
  "원본 전략": "원본 전략",
  "손절 / 익절": "손절 / 익절",
  "검증 구간": "검증 구간",
  "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.": "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.",
  "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.": "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.",
  "조건 설정": "조건 설정",
  "예상 결과": "예상 결과",
  "취소": "취소",
  "뒤로": "뒤로",
  "다음: 예상 결과 보기": "다음: 예상 결과 보기",
  "확정하고 검증 시작": "확정하고 검증 시작",
  "검증을 시작하지 못했어요. 다시 시도해주세요.": "검증을 시작하지 못했어요. 다시 시도해주세요.",
  "전체 기간": "전체 기간",
  "최근 2년": "최근 2년",
  "최근 1년": "최근 1년"
} as const

export type SharedCopyCopyKey = keyof typeof ko

export const CLIENT_SHARED_COPY_COPY: Record<ClientLanguage, Record<SharedCopyCopyKey, string>> = {
  ko,
  "en": {
  "전략 따라하기": "Follow strategy",
  "예상 결과 확인": "View expected results",
  "{nick} ({asset} 전략)": "{nick} ({asset} strategy)",
  "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%": "Validation return {return}, TETH score {score}, max drawdown {mdd}%",
  "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.": "Clone this strategy's settings, re-validate under your conditions, and then run it. This does not mirror accounts in real time; it only executes once validation passes.",
  "시작 예산": "Starting budget",
  "손절선": "Stop-loss",
  "익절 목표": "Take-profit target",
  "기간 청산": "Time-based exit",
  "100만원": "KRW 1,000,000",
  "500만원": "KRW 5,000,000",
  "1,000만원": "KRW 10,000,000",
  "3,000만원 이상": "KRW 30,000,000 or more",
  "가볍게 시작": "Light start",
  "표준": "Standard",
  "본격적으로": "Full-scale",
  "크게": "Large",
  "-3%까지": "Up to -3%",
  "-5%까지": "Up to -5%",
  "-8%까지": "Up to -8%",
  "-12%까지": "Up to -12%",
  "짧게 끊기": "Tight cut",
  "여유있게": "Moderate",
  "길게 버티기": "Hold longer",
  "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.": "These results recalculate the original rules over the same validation period using your chosen stop-loss ({stop}%) and take-profit ({takeProfit}) conditions. This is a simulation on historical data; confirming will run one more formal re-validation.",
  "예상 TETH 점수": "Expected TETH score",
  "{score}점": "{score} pts",
  "검증 수익": "Validation return",
  "최대 낙폭": "Max drawdown",
  "거래 수": "Trade count",
  "{count}회": "{count} trades",
  "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.": "The expected score under these conditions is below the execution threshold (80 pts).",
  "표본 {count}회가 적어 점수에 페널티가 있어요.": "A sample size of {count} trades is small, so a penalty applies to the score.",
  "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.": "You can still confirm, but conditions may need adjustment during formal validation.",
  "원본과 달라진 조건": "Conditions changed from original",
  "손절 {before}% → {after}%": "Stop-loss {before}% → {after}%",
  "익절 {before} → {after}": "Take-profit {before} → {after}",
  "원본 전략": "Original strategy",
  "손절 / 익절": "Stop-loss / take-profit",
  "검증 구간": "Validation period",
  "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.": "This is a local preview validated using original synthetic data. No real orders are executed.",
  "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.": "Strategy cloning and re-validation service is not yet connected. Current conditions will not be saved or executed.",
  "조건 설정": "Set conditions",
  "예상 결과": "Expected results",
  "취소": "Cancel",
  "뒤로": "Back",
  "다음: 예상 결과 보기": "Next: view expected results",
  "확정하고 검증 시작": "Confirm and start validation",
  "검증을 시작하지 못했어요. 다시 시도해주세요.": "Could not start validation. Please try again.",
  "전체 기간": "All time",
  "최근 2년": "Past 2 years",
  "최근 1년": "Past 1 year"
},
  "ja": {
  "전략 따라하기": "戦略をフォロー",
  "예상 결과 확인": "予想結果の確認",
  "{nick} ({asset} 전략)": "{nick} ({asset}戦略)",
  "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%": "検証リターン {return}、TETHスコア {score}点、最大ドローダウン {mdd}%",
  "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.": "この戦略の設定を複製し、自分の条件で再検証してから実行します。口座をリアルタイムでミラーリングする方式ではなく、検証を通過して初めて実行されます。",
  "시작 예산": "初期予算",
  "손절선": "ストップロス",
  "익절 목표": "利確目標",
  "기간 청산": "時間決済",
  "100만원": "KRW 1,000,000",
  "500만원": "KRW 5,000,000",
  "1,000만원": "KRW 10,000,000",
  "3,000만원 이상": "KRW 30,000,000以上",
  "가볍게 시작": "気軽にスタート",
  "표준": "標準",
  "본격적으로": "本格的",
  "크게": "大きめ",
  "-3%까지": "-3%まで",
  "-5%까지": "-5%まで",
  "-8%까지": "-8%まで",
  "-12%까지": "-12%まで",
  "짧게 끊기": "浅めにカット",
  "여유있게": "ゆとりを持たせる",
  "길게 버티기": "長めに維持",
  "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.": "選択したストップロス {stop}%、利確 {takeProfit} の条件で、元のルールを同一の検証期間で再計算した結果です。過去データのシミュレーションであり、確定すると正式な再検証がもう一度実行されます。",
  "예상 TETH 점수": "予想TETHスコア",
  "{score}점": "{score}点",
  "검증 수익": "検証リターン",
  "최대 낙폭": "最大ドローダウン",
  "거래 수": "取引数",
  "{count}회": "{count}回",
  "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.": "この条件では予想スコアが実行基準（80点）に達していません。",
  "표본 {count}회가 적어 점수에 페널티가 있어요.": "サンプル数（{count}回）が少ないため、スコアにペナルティが適用されています。",
  "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.": "確定は可能ですが、正式な検証時に条件の調整が必要になる場合があります。",
  "원본과 달라진 조건": "オリジナルから変更された条件",
  "손절 {before}% → {after}%": "ストップロス {before}% → {after}%",
  "익절 {before} → {after}": "利確 {before} → {after}",
  "원본 전략": "元の戦略",
  "손절 / 익절": "ストップロス / 利確",
  "검증 구간": "検証期間",
  "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.": "オリジナルの合成データで検証するローカルプレビューです。実際の注文は実行されません。",
  "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.": "戦略の複製・再検証サービスに接続する前です。現在の条件は保存も実行もされません。",
  "조건 설정": "条件設定",
  "예상 결과": "予想結果",
  "취소": "キャンセル",
  "뒤로": "戻る",
  "다음: 예상 결과 보기": "次へ: 予想結果を見る",
  "확정하고 검증 시작": "確定して検証を開始",
  "검증을 시작하지 못했어요. 다시 시도해주세요.": "検証を開始できませんでした。もう一度お試しください。",
  "전체 기간": "全期間",
  "최근 2년": "過去2年",
  "최근 1년": "過去1年"
},
  "zh-CN": {
  "전략 따라하기": "跟随策略",
  "예상 결과 확인": "查看预估结果",
  "{nick} ({asset} 전략)": "{nick} ({asset} 策略)",
  "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%": "验证收益 {return}，TETH评分 {score} 分，最大回撤 {mdd}%",
  "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.": "复制此策略的设置，根据您的条件重新验证后再执行。这并非实时镜像账户，必须通过验证后才会执行。",
  "시작 예산": "初始预算",
  "손절선": "止损线",
  "익절 목표": "止盈目标",
  "기간 청산": "时间平仓",
  "100만원": "KRW 1,000,000",
  "500만원": "KRW 5,000,000",
  "1,000만원": "KRW 10,000,000",
  "3,000만원 이상": "KRW 30,000,000 以上",
  "가볍게 시작": "轻松起步",
  "표준": "标准",
  "본격적으로": "进阶规模",
  "크게": "大额",
  "-3%까지": "至 -3%",
  "-5%까지": "至 -5%",
  "-8%까지": "至 -8%",
  "-12%까지": "至 -12%",
  "짧게 끊기": "窄幅止损",
  "여유있게": "适度宽容",
  "길게 버티기": "深度持有",
  "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.": "这是使用您选择的止损 {stop}%、止盈 {takeProfit} 条件，在同一验证区间内对原始规则重新计算的结果。此为历史数据模拟，确认后将再次执行正式重新验证。",
  "예상 TETH 점수": "预估 TETH评分",
  "{score}점": "{score} 分",
  "검증 수익": "验证收益",
  "최대 낙폭": "最大回撤",
  "거래 수": "交易次数",
  "{count}회": "{count} 次",
  "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.": "此条件下的预估得分未达到执行基准（80 分）。",
  "표본 {count}회가 적어 점수에 페널티가 있어요.": "样本量仅有 {count} 次，样本过少会对得分产生惩罚扣分。",
  "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.": "可以确认，但可能需要在正式验证中调整条件。",
  "원본과 달라진 조건": "与原始策略不同的条件",
  "손절 {before}% → {after}%": "止损 {before}% → {after}%",
  "익절 {before} → {after}": "止盈 {before} → {after}",
  "원본 전략": "原始策略",
  "손절 / 익절": "止损 / 止盈",
  "검증 구간": "验证区间",
  "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.": "这是使用原始合成数据进行验证的本地预览。不会执行实际订单。",
  "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.": "策略克隆与重新验证服务尚未连接。当前条件不会被保存或执行。",
  "조건 설정": "条件设置",
  "예상 결과": "预估结果",
  "취소": "取消",
  "뒤로": "返回",
  "다음: 예상 결과 보기": "下一步：查看预估结果",
  "확정하고 검증 시작": "确认并开始验证",
  "검증을 시작하지 못했어요. 다시 시도해주세요.": "无法启动验证，请重试。",
  "전체 기간": "全部期间",
  "최근 2년": "近2年",
  "최근 1년": "近1年"
},
  "zh-TW": {
  "전략 따라하기": "跟隨策略",
  "예상 결과 확인": "查看預估結果",
  "{nick} ({asset} 전략)": "{nick} ({asset} 策略)",
  "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%": "驗證收益 {return}，TETH評分 {score} 分，最大回撤 {mdd}%",
  "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.": "複製此策略的設定，根據您的條件重新驗證後再執行。這並非即時鏡像帳戶，必須通過驗證後才會執行。",
  "시작 예산": "初始預算",
  "손절선": "止損線",
  "익절 목표": "止盈目標",
  "기간 청산": "時間平倉",
  "100만원": "KRW 1,000,000",
  "500만원": "KRW 5,000,000",
  "1,000만원": "KRW 10,000,000",
  "3,000만원 이상": "KRW 30,000,000 以上",
  "가볍게 시작": "輕鬆起步",
  "표준": "標準",
  "본격적으로": "進階規模",
  "크게": "大額",
  "-3%까지": "至 -3%",
  "-5%까지": "至 -5%",
  "-8%까지": "至 -8%",
  "-12%까지": "至 -12%",
  "짧게 끊기": "窄幅止損",
  "여유있게": "適度寬容",
  "길게 버티기": "深度持有",
  "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.": "這是使用您選擇的止損 {stop}%、止盈 {takeProfit} 條件，在同一驗證區間內對原始規則重新計算的結果。此為歷史數據模擬，確認後將再次執行正式重新驗證。",
  "예상 TETH 점수": "預估 TETH評分",
  "{score}점": "{score} 分",
  "검증 수익": "驗證收益",
  "최대 낙폭": "最大回撤",
  "거래 수": "交易次數",
  "{count}회": "{count} 次",
  "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.": "此條件下的預估得分未達到執行基準（80 分）。",
  "표본 {count}회가 적어 점수에 페널티가 있어요.": "樣本數僅有 {count} 次，樣本過少會對得分產生懲罰扣分。",
  "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.": "可以確認，但可能需要在正式驗證中調整條件。",
  "원본과 달라진 조건": "與原始策略不同的條件",
  "손절 {before}% → {after}%": "止損 {before}% → {after}%",
  "익절 {before} → {after}": "止盈 {before} → {after}",
  "원본 전략": "原始策略",
  "손절 / 익절": "止損 / 止盈",
  "검증 구간": "驗證區間",
  "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.": "這是使用原始合成數據進行驗證的本地預覽。不會執行實際訂單。",
  "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.": "策略複製與重新驗證服務尚未連接。目前條件不會被儲存或執行。",
  "조건 설정": "條件設定",
  "예상 결과": "預估結果",
  "취소": "取消",
  "뒤로": "返回",
  "다음: 예상 결과 보기": "下一步：查看預估結果",
  "확정하고 검증 시작": "確認並開始驗證",
  "검증을 시작하지 못했어요. 다시 시도해주세요.": "無法啟動驗證，請重試。",
  "전체 기간": "全部期間",
  "최근 2년": "近2年",
  "최근 1년": "近1年"
},
  "es": {
  "전략 따라하기": "Seguir estrategia",
  "예상 결과 확인": "Ver resultados esperados",
  "{nick} ({asset} 전략)": "{nick} (estrategia {asset})",
  "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%": "Rentabilidad de validación {return}, puntuación TETH {score}, drawdown máximo {mdd}%",
  "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.": "Clona la configuración de esta estrategia, vuelve a validarla con tus condiciones y ejecútala. No refleja cuentas en tiempo real; solo se ejecuta tras superar la validación.",
  "시작 예산": "Presupuesto inicial",
  "손절선": "Stop-loss",
  "익절 목표": "Objetivo de take-profit",
  "기간 청산": "Salida basada en tiempo",
  "100만원": "KRW 1,000,000",
  "500만원": "KRW 5,000,000",
  "1,000만원": "KRW 10,000,000",
  "3,000만원 이상": "KRW 30,000,000 o más",
  "가볍게 시작": "Inicio ligero",
  "표준": "Estándar",
  "본격적으로": "Avanzado",
  "크게": "A gran escala",
  "-3%까지": "Hasta -3%",
  "-5%까지": "Hasta -5%",
  "-8%까지": "Hasta -8%",
  "-12%까지": "Hasta -12%",
  "짧게 끊기": "Corte ajustado",
  "여유있게": "Moderado",
  "길게 버티기": "Mantener más tiempo",
  "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.": "Estos resultados recalculan las reglas originales en el mismo período de validación según tus condiciones de stop-loss ({stop}%) y take-profit ({takeProfit}). Es una simulación con datos históricos; al confirmar se ejecutará una nueva validación formal.",
  "예상 TETH 점수": "Puntuación TETH esperada",
  "{score}점": "{score} pts",
  "검증 수익": "Rentabilidad de validación",
  "최대 낙폭": "Drawdown máximo",
  "거래 수": "Número de operaciones",
  "{count}회": "{count} operaciones",
  "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.": "La puntuación esperada con estas condiciones no alcanza el umbral de ejecución (80 pts).",
  "표본 {count}회가 적어 점수에 페널티가 있어요.": "La muestra de {count} operaciones es pequeña, por lo que se aplica una penalización a la puntuación.",
  "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.": "Puedes confirmar, pero es posible que se deban ajustar las condiciones durante la validación formal.",
  "원본과 달라진 조건": "Condiciones modificadas respecto al original",
  "손절 {before}% → {after}%": "Stop-loss {before}% → {after}%",
  "익절 {before} → {after}": "Take-profit {before} → {after}",
  "원본 전략": "Estrategia original",
  "손절 / 익절": "Stop-loss / Take-profit",
  "검증 구간": "Período de validación",
  "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.": "Esta es una vista previa local validada con datos sintéticos originales. No se ejecutan órdenes reales.",
  "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.": "El servicio de clonación y revalidación de estrategias aún no está conectado. Las condiciones actuales no se guardarán ni ejecutarán.",
  "조건 설정": "Configurar condiciones",
  "예상 결과": "Resultados esperados",
  "취소": "Cancelar",
  "뒤로": "Atrás",
  "다음: 예상 결과 보기": "Siguiente: Ver resultados esperados",
  "확정하고 검증 시작": "Confirmar e iniciar validación",
  "검증을 시작하지 못했어요. 다시 시도해주세요.": "No se pudo iniciar la validación. Inténtalo de nuevo.",
  "전체 기간": "Todo el período",
  "최근 2년": "Últimos 2 años",
  "최근 1년": "Último año"
},
  "fr": {
  "전략 따라하기": "Suivre la stratégie",
  "예상 결과 확인": "Voir les résultats attendus",
  "{nick} ({asset} 전략)": "{nick} (stratégie {asset})",
  "검증 수익 {return}, TETH {score}점, 최대 낙폭 {mdd}%": "Rendement de validation {return}, score TETH {score}, Drawdown maximal {mdd}%",
  "이 전략의 설정을 복제해 내 조건으로 다시 검증한 뒤 실행해요. 계좌를 실시간으로 미러링하는 방식이 아니라, 검증을 통과해야 실행됩니다.": "Dupliquez les paramètres de cette stratégie, revalidez-les selon vos conditions, puis exécutez-la. Il ne s'agit pas d'un miroir de compte en temps réel ; l'exécution n'a lieu qu'une fois la validation réussie.",
  "시작 예산": "Budget initial",
  "손절선": "Stop-loss",
  "익절 목표": "Objectif de take-profit",
  "기간 청산": "Sortie basée sur le temps",
  "100만원": "KRW 1,000,000",
  "500만원": "KRW 5,000,000",
  "1,000만원": "KRW 10,000,000",
  "3,000만원 이상": "KRW 30,000,000 ou plus",
  "가볍게 시작": "Démarrage léger",
  "표준": "Standard",
  "본격적으로": "Avancé",
  "크게": "Grande échelle",
  "-3%까지": "Jusqu'à -3%",
  "-5%까지": "Jusqu'à -5%",
  "-8%까지": "Jusqu'à -8%",
  "-12%까지": "Jusqu'à -12%",
  "짧게 끊기": "Coupure serrée",
  "여유있게": "Modéré",
  "길게 버티기": "Tenir plus longtemps",
  "내가 고른 손절 {stop}%, 익절 {takeProfit} 조건으로 원본 규칙을 같은 검증 구간에서 다시 계산한 결과예요. 과거 데이터 시뮬레이션이며, 확정하면 정식 재검증이 한 번 더 실행돼요.": "Ces résultats recalculent les règles d'origine sur la même période de validation avec vos conditions de stop-loss ({stop} %) et de take-profit ({takeProfit}). Il s'agit d'une simulation sur données historiques ; la confirmation lancera une nouvelle revalidation formelle.",
  "예상 TETH 점수": "Score TETH attendu",
  "{score}점": "{score} pts",
  "검증 수익": "Rendement de validation",
  "최대 낙폭": "Drawdown maximal",
  "거래 수": "Nombre de transactions",
  "{count}회": "{count} transactions",
  "이 조건은 예상 점수가 실행 기준(80점)에 못 미쳐요.": "Le score attendu dans ces conditions est inférieur au seuil d'exécution (80 pts).",
  "표본 {count}회가 적어 점수에 페널티가 있어요.": "L'échantillon de {count} opérations est faible, une pénalité est donc appliquée au score.",
  "확정은 가능하지만, 정식 검증에서 조건을 조정하게 될 수 있어요.": "Vous pouvez confirmer, mais les conditions devront peut-être être ajustées lors de la validation formelle.",
  "원본과 달라진 조건": "Conditions modifiées par rapport à l'original",
  "손절 {before}% → {after}%": "Stop-loss {before}% → {after}%",
  "익절 {before} → {after}": "Take-profit {before} → {after}",
  "원본 전략": "Stratégie originale",
  "손절 / 익절": "Stop-loss / Take-profit",
  "검증 구간": "Période de validation",
  "원본 합성 데이터로 검증하는 로컬 미리보기입니다. 실제 주문은 실행되지 않습니다.": "Il s'agit d'un aperçu local validé à partir de données synthétiques originales. Aucun ordre réel n'est exécuté.",
  "전략 복제·재검증 서비스 연결 전입니다. 현재 조건은 저장되거나 실행되지 않습니다.": "Le service de duplication et de revalidation de stratégie n'est pas encore connecté. Les conditions actuelles ne seront ni enregistrées ni exécutées.",
  "조건 설정": "Configurer les conditions",
  "예상 결과": "Résultats attendus",
  "취소": "Annuler",
  "뒤로": "Retour",
  "다음: 예상 결과 보기": "Suivant : Voir les résultats attendus",
  "확정하고 검증 시작": "Confirmer et lancer la validation",
  "검증을 시작하지 못했어요. 다시 시도해주세요.": "Impossible de lancer la validation. Veuillez réessayer.",
  "전체 기간": "Toute la période",
  "최근 2년": "2 dernières années",
  "최근 1년": "Dernière année"
},
}

export function sharedCopyCopy(language: ClientLanguage, key: SharedCopyCopyKey, values: Record<string, string | number> = {}) {
  return CLIENT_SHARED_COPY_COPY[language][key].replace(/\{(\w+)\}/g, (token, name: string) => String(values[name] ?? token))
}

