import type { ClientLanguage } from './client-preferences'

/** Display-only source follow copy. Archive and validation labels do not grant or stop execution. */
const ko = {
  "아직 따라가는 전략이 없어요": "아직 따라가는 전략이 없어요",
  "전략 찾기에서 마음에 드는 전략을 복제해보세요": "전략 찾기에서 마음에 드는 전략을 복제해보세요",
  "전략 찾기로 가기": "전략 찾기로 가기",
  "따라가는 전략 요약": "따라가는 전략 요약",
  "복제한 전략": "복제한 전략",
  "진행 중": "진행 중",
  "보관됨": "보관됨",
  "{count}개": "{count}개",
  "복제 설정:": "복제 설정:",
  "손절 {stop}%": "손절 {stop}%",
  "익절 미설정": "익절 미설정",
  "익절 +{target}%": "익절 +{target}%",
  "예산 {budget}": "예산 {budget}",
  "시작": "시작",
  "원 전략 검증 수익": "원 전략 검증 수익",
  "실행 현황 보기": "실행 현황 보기",
  "따라가기 중지": "따라가기 중지",
  "이어서 진행": "이어서 진행",
  "설정 변경": "설정 변경",
  "중지": "중지",
  "다시 검증": "다시 검증",
  "목록에서 삭제": "목록에서 삭제",
  "검증 확인 필요": "검증 확인 필요",
  "실행 중": "실행 중",
  "실행 꺼짐": "실행 꺼짐",
  "실행 준비": "실행 준비",
  "실행 오류": "실행 오류",
  "실행 상태 확인 필요": "실행 상태 확인 필요",
  "조건 입력 중": "조건 입력 중",
  "검증 중": "검증 중",
  "조정 중": "조정 중",
  "리포트 확인": "리포트 확인",
  "연결 단계": "연결 단계",
  "검증 통과": "검증 통과",
  "{nick} 전략 따라가기를 중지할까요?": "{nick} 전략 따라가기를 중지할까요?",
  "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.": "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.",
  "중지하고 보관": "중지하고 보관",
  "보관했어요": "보관했어요",
  "보관하지 못했어요. 다시 시도해주세요.": "보관하지 못했어요. 다시 시도해주세요.",
  "전략 기록을 다시 확인해주세요.": "전략 기록을 다시 확인해주세요.",
  "로그인 후 다시 시도해주세요.": "로그인 후 다시 시도해주세요.",
  "변경하지 못했어요. 다시 시도해주세요.": "변경하지 못했어요. 다시 시도해주세요.",
  "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.": "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.",
  "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.": "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.",
  "전략 링크를 복사했어요": "전략 링크를 복사했어요",
  "안내 상태를 저장하지 못했어요. 다시 시도해주세요.": "안내 상태를 저장하지 못했어요. 다시 시도해주세요.",
  "전략 기록이 바뀌었어요. 다시 선택해주세요.": "전략 기록이 바뀌었어요. 다시 선택해주세요.",
  "구독 안내를 열지 못했어요. 다시 시도해주세요.": "구독 안내를 열지 못했어요. 다시 시도해주세요.",
  "내가 공유한 전략이에요": "내가 공유한 전략이에요",
  "분석을 시작하지 못했어요. 다시 시도해주세요.": "분석을 시작하지 못했어요. 다시 시도해주세요.",
  "검증되면, 복제됩니다": "검증되면, 복제됩니다",
  "모의 검증으로 계산된 거래": "모의 검증으로 계산된 거래",
  "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요": "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요",
  "전략 공유 영역": "전략 공유 영역",
  "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.": "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.",
  "전략을 찾을 수 없어요": "전략을 찾을 수 없어요"
} as const

export type SharedFollowCopyKey = keyof typeof ko

export const CLIENT_SHARED_FOLLOW_COPY: Record<ClientLanguage, Record<SharedFollowCopyKey, string>> = {
  ko,
  "en": {
  "아직 따라가는 전략이 없어요": "No followed strategies yet",
  "전략 찾기에서 마음에 드는 전략을 복제해보세요": "Try cloning a strategy you like in Explore strategies",
  "전략 찾기로 가기": "Go to Explore strategies",
  "따라가는 전략 요약": "Followed strategy summary",
  "복제한 전략": "Cloned strategies",
  "진행 중": "In progress",
  "보관됨": "Archived",
  "{count}개": "{count}",
  "복제 설정:": "Clone settings:",
  "손절 {stop}%": "Stop-loss {stop}%",
  "익절 미설정": "Take-profit not set",
  "익절 +{target}%": "Take-profit +{target}%",
  "예산 {budget}": "Budget {budget}",
  "시작": "Started",
  "원 전략 검증 수익": "Original strategy validation return",
  "실행 현황 보기": "View running status",
  "따라가기 중지": "Stop following",
  "이어서 진행": "Continue",
  "설정 변경": "Change settings",
  "중지": "Stop",
  "다시 검증": "Validate again",
  "목록에서 삭제": "Remove from list",
  "검증 확인 필요": "Validation confirmation required",
  "실행 중": "Running",
  "실행 꺼짐": "Execution off",
  "실행 준비": "Ready to run",
  "실행 오류": "Execution error",
  "실행 상태 확인 필요": "Execution status check required",
  "조건 입력 중": "Entering conditions",
  "검증 중": "Validating",
  "조정 중": "Adjusting",
  "리포트 확인": "View report",
  "연결 단계": "Connection step",
  "검증 통과": "Validation passed",
  "{nick} 전략 따라가기를 중지할까요?": "Stop following the {nick} strategy?",
  "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.": "The item will be archived, and already running strategies can still be managed in My trading.",
  "중지하고 보관": "Stop and archive",
  "보관했어요": "Archived",
  "보관하지 못했어요. 다시 시도해주세요.": "Failed to archive. Please try again.",
  "전략 기록을 다시 확인해주세요.": "Please check the strategy record again.",
  "로그인 후 다시 시도해주세요.": "Please log in and try again.",
  "변경하지 못했어요. 다시 시도해주세요.": "Failed to change. Please try again.",
  "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.": "Removed from list. Conversations, validation results, and running strategies are kept.",
  "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.": "Failed to save favorite strategies to this browser. They are kept on the current screen.",
  "전략 링크를 복사했어요": "Copied strategy link",
  "안내 상태를 저장하지 못했어요. 다시 시도해주세요.": "Failed to save notice status. Please try again.",
  "전략 기록이 바뀌었어요. 다시 선택해주세요.": "The strategy record has changed. Please select again.",
  "구독 안내를 열지 못했어요. 다시 시도해주세요.": "Failed to open subscription info. Please try again.",
  "내가 공유한 전략이에요": "This is a strategy I shared",
  "분석을 시작하지 못했어요. 다시 시도해주세요.": "Failed to start analysis. Please try again.",
  "검증되면, 복제됩니다": "Once validated, it will be cloned",
  "모의 검증으로 계산된 거래": "Trades calculated by simulated validation",
  "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요": "Past validation performance does not guarantee future returns, and all validations reflect fees and slippage",
  "전략 공유 영역": "Strategy sharing area",
  "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.": "Client source preview · All assets are calculated using common synthetic daily bars and do not represent actual market performance.",
  "전략을 찾을 수 없어요": "Strategy not found"
},
  "ja": {
  "아직 따라가는 전략이 없어요": "まだフォローしている戦略はありません",
  "전략 찾기에서 마음에 드는 전략을 복제해보세요": "「戦略を探す」でお気に入りの戦略を複製してみましょう",
  "전략 찾기로 가기": "戦略を探すへ移動",
  "따라가는 전략 요약": "フォロー中戦略の概要",
  "복제한 전략": "複製した戦略",
  "진행 중": "進行中",
  "보관됨": "アーカイブ済み",
  "{count}개": "{count}件",
  "복제 설정:": "複製設定:",
  "손절 {stop}%": "ストップロス {stop}%",
  "익절 미설정": "利確未設定",
  "익절 +{target}%": "利確 +{target}%",
  "예산 {budget}": "予算 {budget}",
  "시작": "開始日",
  "원 전략 검증 수익": "元戦略の検証リターン",
  "실행 현황 보기": "実行状況を見る",
  "따라가기 중지": "フォローを停止",
  "이어서 진행": "続けて進める",
  "설정 변경": "設定変更",
  "중지": "停止",
  "다시 검증": "再検証",
  "목록에서 삭제": "リストから削除",
  "검증 확인 필요": "検証確認が必要",
  "실행 중": "実行中",
  "실행 꺼짐": "実行オフ",
  "실행 준비": "実行準備",
  "실행 오류": "実行エラー",
  "실행 상태 확인 필요": "実行状態の確認が必要",
  "조건 입력 중": "条件入力中",
  "검증 중": "検証中",
  "조정 중": "調整中",
  "리포트 확인": "レポート確認",
  "연결 단계": "接続ステップ",
  "검증 통과": "検証通過",
  "{nick} 전략 따라가기를 중지할까요?": "「{nick}」戦略のフォローを停止しますか？",
  "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.": "項目はアーカイブされ、すでに実行中の戦略はマイトレードで引き続き管理できます。",
  "중지하고 보관": "停止してアーカイブ",
  "보관했어요": "アーカイブしました",
  "보관하지 못했어요. 다시 시도해주세요.": "アーカイブできませんでした。もう一度お試しください。",
  "전략 기록을 다시 확인해주세요.": "戦略の記録をもう一度ご確認ください。",
  "로그인 후 다시 시도해주세요.": "ログイン後にもう一度お試しください。",
  "변경하지 못했어요. 다시 시도해주세요.": "変更できませんでした。もう一度お試しください。",
  "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.": "リストから削除しました。対話と検証結果、実行中の戦略は維持されます。",
  "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.": "お気に入り戦略をこのブラウザに保存できませんでした。現在の画面では保持されます。",
  "전략 링크를 복사했어요": "戦略リンクをコピーしました",
  "안내 상태를 저장하지 못했어요. 다시 시도해주세요.": "案内状態を保存できませんでした。もう一度お試しください。",
  "전략 기록이 바뀌었어요. 다시 선택해주세요.": "戦略の記録が変更されました。もう一度選択してください。",
  "구독 안내를 열지 못했어요. 다시 시도해주세요.": "購読案内を開けませんでした。もう一度お試しください。",
  "내가 공유한 전략이에요": "自分が共有した戦略です",
  "분석을 시작하지 못했어요. 다시 시도해주세요.": "分析を開始できませんでした。もう一度お試しください。",
  "검증되면, 복제됩니다": "検証完了後、複製されます",
  "모의 검증으로 계산된 거래": "模擬検証により計算された取引",
  "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요": "過去の検証実績は将来の利益を保証するものではなく、すべての検証には手数料とスリッページが反映されています",
  "전략 공유 영역": "戦略共有エリア",
  "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.": "クライアント原本プレビュー · すべての資産は共通の合成日足で計算されており、実際の市場パフォーマンスではありません。",
  "전략을 찾을 수 없어요": "戦略が見つかりません"
},
  "zh-CN": {
  "아직 따라가는 전략이 없어요": "还没有跟随的策略",
  "전략 찾기에서 마음에 드는 전략을 복제해보세요": "在“发现策略”中复制您喜欢的策略",
  "전략 찾기로 가기": "前往发现策略",
  "따라가는 전략 요약": "跟随策略摘要",
  "복제한 전략": "已复制的策略",
  "진행 중": "进行中",
  "보관됨": "已归档",
  "{count}개": "{count}个",
  "복제 설정:": "复制设置：",
  "손절 {stop}%": "止损 {stop}%",
  "익절 미설정": "未设置止盈",
  "익절 +{target}%": "止盈 +{target}%",
  "예산 {budget}": "预算 {budget}",
  "시작": "开始",
  "원 전략 검증 수익": "原策略验证收益",
  "실행 현황 보기": "查看运行状态",
  "따라가기 중지": "停止跟随",
  "이어서 진행": "继续进行",
  "설정 변경": "更改设置",
  "중지": "停止",
  "다시 검증": "重新验证",
  "목록에서 삭제": "从列表中删除",
  "검증 확인 필요": "需要确认验证",
  "실행 중": "运行中",
  "실행 꺼짐": "运行关闭",
  "실행 준비": "准备运行",
  "실행 오류": "运行错误",
  "실행 상태 확인 필요": "需要检查运行状态",
  "조건 입력 중": "正在输入条件",
  "검증 중": "验证中",
  "조정 중": "调整中",
  "리포트 확인": "查看报告",
  "연결 단계": "连接步骤",
  "검증 통과": "验证通过",
  "{nick} 전략 따라가기를 중지할까요?": "是否停止跟随 {nick} 策略？",
  "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.": "该项将被归档，已在运行中的策略仍可在我的交易中继续管理。",
  "중지하고 보관": "停止并归档",
  "보관했어요": "已归档",
  "보관하지 못했어요. 다시 시도해주세요.": "归档失败，请重试。",
  "전략 기록을 다시 확인해주세요.": "请重新检查策略记录。",
  "로그인 후 다시 시도해주세요.": "请登录后重试。",
  "변경하지 못했어요. 다시 시도해주세요.": "更改失败，请重试。",
  "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.": "已从列表中删除。对话、验证结果及运行中的策略将保留。",
  "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.": "未能将收藏的策略保存至此浏览器。当前画面中仍会保留。",
  "전략 링크를 복사했어요": "已复制策略链接",
  "안내 상태를 저장하지 못했어요. 다시 시도해주세요.": "未能保存提示状态，请重试。",
  "전략 기록이 바뀌었어요. 다시 선택해주세요.": "策略记录已变更，请重新选择。",
  "구독 안내를 열지 못했어요. 다시 시도해주세요.": "未能打开订阅说明，请重试。",
  "내가 공유한 전략이에요": "这是我分享的策略",
  "분석을 시작하지 못했어요. 다시 시도해주세요.": "未能开始分析，请重试。",
  "검증되면, 복제됩니다": "验证通过后将进行复制",
  "모의 검증으로 계산된 거래": "按模拟验证计算的交易",
  "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요": "过去的验证表现不保证未来的收益，所有验证均已计入手续费和滑点",
  "전략 공유 영역": "策略分享区域",
  "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.": "客户端原始预览 · 所有资产均按通用合成日K线计算，并非实际市场表现。",
  "전략을 찾을 수 없어요": "未找到策略"
},
  "zh-TW": {
  "아직 따라가는 전략이 없어요": "還沒有跟隨的策略",
  "전략 찾기에서 마음에 드는 전략을 복제해보세요": "在「探索策略」中複製您喜歡的策略",
  "전략 찾기로 가기": "前往探索策略",
  "따라가는 전략 요약": "跟隨策略摘要",
  "복제한 전략": "已複製的策略",
  "진행 중": "進行中",
  "보관됨": "已封存",
  "{count}개": "{count}個",
  "복제 설정:": "複製設定：",
  "손절 {stop}%": "止損 {stop}%",
  "익절 미설정": "未設定止盈",
  "익절 +{target}%": "止盈 +{target}%",
  "예산 {budget}": "預算 {budget}",
  "시작": "開始",
  "원 전략 검증 수익": "原策略驗證收益",
  "실행 현황 보기": "查看運行狀態",
  "따라가기 중지": "停止跟隨",
  "이어서 진행": "繼續進行",
  "설정 변경": "變更設定",
  "중지": "停止",
  "다시 검증": "重新驗證",
  "목록에서 삭제": "從清單中刪除",
  "검증 확인 필요": "需要確認驗證",
  "실행 중": "運行中",
  "실행 꺼짐": "運行關閉",
  "실행 준비": "準備運行",
  "실행 오류": "運行錯誤",
  "실행 상태 확인 필요": "需要檢查運行狀態",
  "조건 입력 중": "正在輸入條件",
  "검증 중": "驗證中",
  "조정 중": "調整中",
  "리포트 확인": "查看報告",
  "연결 단계": "連接步驟",
  "검증 통과": "驗證通過",
  "{nick} 전략 따라가기를 중지할까요?": "要停止跟隨 {nick} 策略嗎？",
  "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.": "該項將被封存，已在運行中的策略仍可在我的交易中繼續管理。",
  "중지하고 보관": "停止並封存",
  "보관했어요": "已封存",
  "보관하지 못했어요. 다시 시도해주세요.": "封存失敗，請再試一次。",
  "전략 기록을 다시 확인해주세요.": "請重新檢查策略記錄。",
  "로그인 후 다시 시도해주세요.": "請登入後再試一次。",
  "변경하지 못했어요. 다시 시도해주세요.": "變更失敗，請再試一次。",
  "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.": "已從清單中刪除。對話、驗證結果及運行中的策略將保留。",
  "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.": "未能將收藏的策略儲存至此瀏覽器。目前畫面中仍會保留。",
  "전략 링크를 복사했어요": "已複製策略連結",
  "안내 상태를 저장하지 못했어요. 다시 시도해주세요.": "未能儲存提示狀態，請再試一次。",
  "전략 기록이 바뀌었어요. 다시 선택해주세요.": "策略記錄已變更，請重新選擇。",
  "구독 안내를 열지 못했어요. 다시 시도해주세요.": "未能打開訂閱說明，請再試一次。",
  "내가 공유한 전략이에요": "這是我分享的策略",
  "분석을 시작하지 못했어요. 다시 시도해주세요.": "未能開始分析，請再試一次。",
  "검증되면, 복제됩니다": "驗證通過後將進行複製",
  "모의 검증으로 계산된 거래": "依模擬驗證計算的交易",
  "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요": "過去的驗證表現不保證未來的收益，所有驗證均已計入手續費和滑價",
  "전략 공유 영역": "策略分享區域",
  "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.": "客戶端原始預覽 · 所有資產均按通用合成日K線計算，並非實際市場表現。",
  "전략을 찾을 수 없어요": "找不到策略"
},
  "es": {
  "아직 따라가는 전략이 없어요": "Aún no sigues ninguna estrategia",
  "전략 찾기에서 마음에 드는 전략을 복제해보세요": "Prueba a clonar una estrategia que te guste en Explorar estrategias",
  "전략 찾기로 가기": "Ir a Explorar estrategias",
  "따라가는 전략 요약": "Resumen de estrategias seguidas",
  "복제한 전략": "Estrategias clonadas",
  "진행 중": "En curso",
  "보관됨": "Archivado",
  "{count}개": "{count}",
  "복제 설정:": "Ajustes de clonación:",
  "손절 {stop}%": "Stop-loss {stop}%",
  "익절 미설정": "Take-profit no establecido",
  "익절 +{target}%": "Take-profit +{target}%",
  "예산 {budget}": "Presupuesto {budget}",
  "시작": "Iniciado",
  "원 전략 검증 수익": "Rentabilidad de validación de la estrategia original",
  "실행 현황 보기": "Ver estado de ejecución",
  "따라가기 중지": "Dejar de seguir",
  "이어서 진행": "Continuar",
  "설정 변경": "Cambiar ajustes",
  "중지": "Detener",
  "다시 검증": "Validar de nuevo",
  "목록에서 삭제": "Eliminar de la lista",
  "검증 확인 필요": "Requiere confirmación de validación",
  "실행 중": "En ejecución",
  "실행 꺼짐": "Ejecución desactivada",
  "실행 준비": "Listo para ejecutar",
  "실행 오류": "Error de ejecución",
  "실행 상태 확인 필요": "Requiere verificar el estado de ejecución",
  "조건 입력 중": "Introduciendo condiciones",
  "검증 중": "Validando",
  "조정 중": "Ajustando",
  "리포트 확인": "Ver informe",
  "연결 단계": "Paso de conexión",
  "검증 통과": "Validación superada",
  "{nick} 전략 따라가기를 중지할까요?": "¿Dejar de seguir la estrategia {nick}?",
  "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.": "El elemento se archivará y las estrategias ya en ejecución se podrán seguir gestionando en Mis operaciones.",
  "중지하고 보관": "Detener y archivar",
  "보관했어요": "Archivado",
  "보관하지 못했어요. 다시 시도해주세요.": "No se pudo archivar. Inténtalo de nuevo.",
  "전략 기록을 다시 확인해주세요.": "Comprueba el registro de la estrategia de nuevo.",
  "로그인 후 다시 시도해주세요.": "Inicia sesión e inténtalo de nuevo.",
  "변경하지 못했어요. 다시 시도해주세요.": "No se pudo modificar. Inténtalo de nuevo.",
  "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.": "Eliminado de la lista. Las conversaciones, los resultados de validación y las estrategias en ejecución se mantendrán.",
  "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.": "No se pudieron guardar las estrategias favoritas en este navegador. Se mantendrán en la pantalla actual.",
  "전략 링크를 복사했어요": "Enlace de la estrategia copiado",
  "안내 상태를 저장하지 못했어요. 다시 시도해주세요.": "No se pudo guardar el estado de la guía. Inténtalo de nuevo.",
  "전략 기록이 바뀌었어요. 다시 선택해주세요.": "El registro de la estrategia ha cambiado. Selecciónalo de nuevo.",
  "구독 안내를 열지 못했어요. 다시 시도해주세요.": "No se pudo abrir la información de suscripción. Inténtalo de nuevo.",
  "내가 공유한 전략이에요": "Es una estrategia que he compartido",
  "분석을 시작하지 못했어요. 다시 시도해주세요.": "No se pudo iniciar el análisis. Inténtalo de nuevo.",
  "검증되면, 복제됩니다": "Una vez validada, se clonará",
  "모의 검증으로 계산된 거래": "Operaciones calculadas mediante validación simulada",
  "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요": "El rendimiento de validación pasado no garantiza rendimientos futuros, y todas las validaciones reflejan comisiones y deslizamiento",
  "전략 공유 영역": "Área para compartir estrategias",
  "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.": "Vista previa del cliente de origen · Todos los activos se calculan a partir de barras diarias sintéticas comunes y no representan el rendimiento real del mercado.",
  "전략을 찾을 수 없어요": "No se encontró la estrategia"
},
  "fr": {
  "아직 따라가는 전략이 없어요": "Aucune stratégie suivie pour l'instant",
  "전략 찾기에서 마음에 드는 전략을 복제해보세요": "Essayez de cloner une stratégie qui vous plaît dans Explorer les stratégies",
  "전략 찾기로 가기": "Aller à Explorer les stratégies",
  "따라가는 전략 요약": "Résumé des stratégies suivies",
  "복제한 전략": "Stratégies clonées",
  "진행 중": "En cours",
  "보관됨": "Archivé",
  "{count}개": "{count}",
  "복제 설정:": "Paramètres de clonage :",
  "손절 {stop}%": "Stop-loss {stop}%",
  "익절 미설정": "Take-profit non défini",
  "익절 +{target}%": "Take-profit +{target}%",
  "예산 {budget}": "Budget {budget}",
  "시작": "Démarré",
  "원 전략 검증 수익": "Rendement de validation de la stratégie originale",
  "실행 현황 보기": "Voir le statut d'exécution",
  "따라가기 중지": "Ne plus suivre",
  "이어서 진행": "Continuer",
  "설정 변경": "Modifier les paramètres",
  "중지": "Arrêter",
  "다시 검증": "Valider à nouveau",
  "목록에서 삭제": "Supprimer de la liste",
  "검증 확인 필요": "Confirmation de validation requise",
  "실행 중": "En cours d'exécution",
  "실행 꺼짐": "Exécution désactivée",
  "실행 준비": "Prêt à l'exécution",
  "실행 오류": "Erreur d'exécution",
  "실행 상태 확인 필요": "Vérification du statut d'exécution requise",
  "조건 입력 중": "Saisie des conditions en cours",
  "검증 중": "Validation en cours",
  "조정 중": "Ajustement en cours",
  "리포트 확인": "Consulter le rapport",
  "연결 단계": "Étape de connexion",
  "검증 통과": "Validation réussie",
  "{nick} 전략 따라가기를 중지할까요?": "Arrêter de suivre la stratégie {nick} ?",
  "항목은 보관 처리되고, 이미 실행 중인 전략은 내 트레이딩에서 계속 관리할 수 있어요.": "L'élément sera archivé et les stratégies déjà en cours d'exécution pourront toujours être gérées dans Mes opérations.",
  "중지하고 보관": "Arrêter et archiver",
  "보관했어요": "Archivé",
  "보관하지 못했어요. 다시 시도해주세요.": "Échec de l'archivage. Veuillez réessayer.",
  "전략 기록을 다시 확인해주세요.": "Veuillez vérifier à nouveau l'historique de la stratégie.",
  "로그인 후 다시 시도해주세요.": "Veuillez vous connecter et réessayer.",
  "변경하지 못했어요. 다시 시도해주세요.": "Échec de la modification. Veuillez réessayer.",
  "목록에서 삭제했어요. 대화와 검증 결과, 실행 중인 전략은 유지됩니다.": "Supprimé de la liste. Les conversations, les résultats de validation et les stratégies en cours d'exécution sont conservés.",
  "관심 전략을 이 브라우저에 저장하지 못했어요. 현재 화면에서는 유지됩니다.": "Échec de l'enregistrement des stratégies favorites dans ce navigateur. Elles sont conservées sur l'écran actuel.",
  "전략 링크를 복사했어요": "Lien de la stratégie copié",
  "안내 상태를 저장하지 못했어요. 다시 시도해주세요.": "Échec de l'enregistrement de l'état du guide. Veuillez réessayer.",
  "전략 기록이 바뀌었어요. 다시 선택해주세요.": "L'historique de la stratégie a changé. Veuillez sélectionner à nouveau.",
  "구독 안내를 열지 못했어요. 다시 시도해주세요.": "Échec de l'ouverture des informations d'abonnement. Veuillez réessayer.",
  "내가 공유한 전략이에요": "C'est une stratégie que j'ai partagée",
  "분석을 시작하지 못했어요. 다시 시도해주세요.": "Échec du démarrage de l'analyse. Veuillez réessayer.",
  "검증되면, 복제됩니다": "Une fois validée, elle sera clonée",
  "모의 검증으로 계산된 거래": "Transactions calculées par validation simulée",
  "과거 검증 성과가 미래 수익을 보장하지 않으며, 모든 검증은 수수료와 슬리피지를 반영해요": "Les performances de validation passées ne garantissent pas les rendements futurs, et toutes les validations prennent en compte les frais et le glissement",
  "전략 공유 영역": "Zone de partage de stratégie",
  "클라이언트 원본 미리보기 · 모든 자산은 공통 합성 일봉으로 계산되며 실제 시장 성과가 아닙니다.": "Aperçu source client · Tous les actifs sont calculés à l'aide de barres quotidiennes synthétiques communes et ne représentent pas les performances réelles du marché.",
  "전략을 찾을 수 없어요": "Stratégie introuvable"
},
}

export function isSharedFollowCopyKey(value: string): value is SharedFollowCopyKey {
  return Object.hasOwn(ko, value)
}

export function sharedFollowCopy(language: ClientLanguage, key: SharedFollowCopyKey, values: Record<string, string | number> = {}) {
  return CLIENT_SHARED_FOLLOW_COPY[language][key].replace(/\{(\w+)\}/g, (token, name: string) => String(values[name] ?? token))
}

