import { useClientPreferences, type ClientLanguage } from './client-preferences'
import { researchNavigationLabel } from './client-research-copy'

// Authored UI copy only. Korean keys retain source wording. Never pass provider
// descriptions, reviews, fees or user input through this display dictionary.
// Translations: bounded AGY 3.8 Flash High review, then placeholder/coverage audit.
const translations: Record<string, readonly [string,string,string,string,string,string]> = {
  "나": ["Me","自分","我","我","Yo","Moi"],
  "창을 닫아도 등록 요청은 계속 진행됩니다.": ["Your review submission will continue even if you close this window.","ウィンドウを閉じても、レビューの送信処理は続行されます。","即使关闭窗口，评价提交仍会继续处理。","即使關閉視窗，評價提交仍會繼續處理。","El envío de tu reseña continuará aunque cierres esta ventana.","L’envoi de votre avis se poursuivra même si vous fermez cette fenêtre."],
  "클라이언트 디자인 미리보기 · 평점은 원본 공개 평점 스냅샷이며 후기·연결 계정 수는 예시입니다.": ["Client design preview · Ratings are snapshots of original public ratings; review and connected account counts are illustrative.","クライアントデザインプレビュー・評価は元の公開評価のスナップショットであり、レビューおよび連携アカウント数はサンプルです。","客户端设计预览 · 评分是原始公开评分快照，评价和关联账户数量仅供示例。","客戶端設計預覽 · 評分是原始公開評分快照，評價和關聯帳戶數量僅供示例。","Vista previa del diseño del cliente · Las valoraciones son instantáneas de las valoraciones públicas originales; los recuentos de reseñas y cuentas conectadas son ilustrativos.","Aperçu de la conception client · Les notes sont des instantanés des notes publiques d'origine ; le nombre d'avis et de comptes connectés est donné à titre indicatif."],
  "TETH 초대코드로 가입하면 유동성 수수료 지원으로 TETH 이용료가 무료에요. 가입 즉시 자동 연결됩니다.": ["Sign up with a TETH invite code to get free TETH access with liquidity fee support. Automatically connected upon sign-up.","TETH招待コードで登録すると、流動性手数料のサポートによりTETHの利用料が無料になります。登録後すぐに自動連携されます。","使用TETH邀请码注册，即可通过流动性手续费支持免费使用TETH。注册后立即自动连接。","使用TETH邀請碼註冊，即可透過流動性手續費支援免費使用TETH。註冊後立即自動連接。","Regístrese con un código de invitación de TETH para obtener acceso gratuito a TETH con soporte de comisiones de liquidez. Se conecta automáticamente al registrarse.","Inscrivez-vous avec un code d'invitation TETH pour bénéficier de TETH gratuitement grâce au soutien sur les frais de liquidité. Connexion automatique dès l'inscription."],
  "닫기": ["Close","閉じる","关闭","關閉","Cerrar","Fermer"],
  "리뷰 등록 서비스가 아직 연결되지 않았습니다. 작성 내용은 전송되지 않았어요.": ["The review submission service is not connected yet. Your content was not sent.","レビュー投稿サービスはまだ連携されていません。入力内容は送信されていません。","评价提交服务尚未连接。您输入的内容未发送。","評價提交服務尚未連接。您輸入的內容未發送。","El servicio de envío de reseñas aún no está conectado. El contenido no se envió.","Le service de soumission d'avis n'est pas encore connecté. Le contenu rédigé n'a pas été envoyé."],
  "리뷰를 등록하지 못했습니다. 작성 내용은 유지됩니다. 잠시 후 다시 시도해주세요.": ["Failed to submit review. Your content has been retained. Please try again shortly.","レビューを投稿できませんでした。入力内容は保持されます。しばらくしてからもう一度お試しください。","未能提交评价。输入的内容已保留。请稍后再试。","未能提交評價。輸入的內容已保留。請稍後再試。","No se pudo enviar la reseña. Se conservó el contenido escrito. Inténtelo de nuevo más tarde.","Échec de l'envoi de l'avis. Le contenu saisi est conservé. Veuillez réessayer dans un instant."],
  "리뷰를 등록했습니다": ["Review submitted","レビューを投稿しました","已提交评价","已提交評價","Reseña enviada","Avis envoyé"],
  "솔직한 경험을 나눠주셔서 감사합니다.": ["Thank you for sharing your honest experience.","率直なご感想をお寄せいただき、ありがとうございます。","感谢分享您的真实体验。","感謝分享您的真實體驗。","Gracias por compartir su experiencia sincera.","Merci d'avoir partagé votre expérience sincère."],
  "개방적이고 투명한 커뮤니티를 위해 실제 계정 소유자의 리뷰만 남길 수 있어요. 솔직한 경험이 다른 사용자에게 큰 도움이 됩니다.": ["For an open and transparent community, only actual account holders can leave reviews. Your honest experience helps other users greatly.","オープンで透明性のあるコミュニティのため、実際の口座所有者のみがレビューを投稿できます。率直なご感想は他のユーザーの大きな助けになります。","为了保持社区开放透明，仅限真实账户持有者发表评价。您的真实体验将对其他用户大有帮助。","為了保持社群開放透明，僅限真實帳戶持有者發表評價。您的真實體驗將對其他使用者大有幫助。","Para una comunidad abierta y transparente, solo los titulares de cuentas reales pueden dejar reseñas. Su experiencia sincera es de gran ayuda para otros usuarios.","Pour une communauté ouverte et transparente, seuls les titulaires d'un compte réel peuvent laisser un avis. Votre retour sincère aide grandement les autres utilisateurs."],
  "별점 선택": ["Select rating","評価を選択","选择评分","選擇評分","Seleccionar calificación","Sélectionner une note"],
  "리뷰 내용": ["Review content","レビュー内容","评价内容","評價內容","Contenido de la reseña","Contenu de l'avis"],
  "먼저 별점을 선택해주세요": ["Please select a rating first","まず評価を選択してください","请先选择评分","請先選擇評分","Primero seleccione una calificación","Veuillez d'abord sélectionner une note"],
  "어떤 점이 불편했나요? 어떤 문제가 있었는지 알려주시면 개선에 도움이 돼요.": ["What was inconvenient? Letting us know what issues you faced helps us improve.","どのような点が不便でしたか？問題点をお知らせいただければ改善に役立ちます。","有哪些不便之处？告诉我们您遇到了什么问题有助于我们改进。","有哪些不便之處？告訴我們您遇到了什麼問題有助於我們改進。","¿Qué resultó incómodo? Contarnos los problemas que tuvo nos ayuda a mejorar.","Qu'est-ce qui n'a pas été pratique ? Faites-nous part des problèmes rencontrés pour nous aider à nous améliorer."],
  "어떤 점이 괜찮았고, 어떤 부분이 아쉬웠나요?": ["What was good, and what was disappointing?","良かった点と、物足りなかった点は何ですか？","哪些方面不错，哪些方面有所欠缺？","哪些方面不錯，哪些方面有所欠缺？","¿Qué estuvo bien y qué fue mejorable?","Qu'est-ce qui était bien et qu'est-ce qui était décevant ?"],
  "어떤 점이 특히 좋았나요? 다른 사용자에게 추천하고 싶은 기능이 있다면 함께 알려주세요.": ["What did you particularly like? Please let us know if there are features you would recommend to others.","特に良かった点は何ですか？他のユーザーにおすすめしたい機能があれば教えてください。","有哪些特别满意的点？如果有想向其他用户推荐的功能，请告诉我们。","有哪些特別滿意的點？如果有想向其他使用者推薦的功能，請告訴我們。","¿Qué le gustó especialmente? Cuéntenos si hay funciones que recomendaría a otros usuarios.","Qu'avez-vous particulièrement apprécié ? N'hésitez pas à mentionner les fonctionnalités que vous recommanderiez à d'autres utilisateurs."],
  "/ 600 · 최소 8자": ["/ 600 · Min 8 characters","/ 600 · 最低8文字","/ 600 · 至少8个字符","/ 600 · 至少8個字元","/ 600 · Mínimo 8 caracteres","/ 600 · 8 caractères minimum"],
  "취소": ["Cancel","キャンセル","取消","取消","Cancelar","Annuler"],
  "등록 중…": ["Submitting…","送信中…","正在提交…","正在提交…","Enviando…","Envoi en cours…"],
  "별점을 선택해주세요": ["Please select a rating","評価を選択してください","请选择评分","請選擇評分","Seleccione una calificación","Veuillez sélectionner une note"],
  "조금 더 알려주세요": ["Tell us a bit more","もう少し詳しく教えてください","请多告诉我们一些","請多告訴我們一些","Cuéntenos un poco más","Dites-nous-en un peu plus"],
  "리뷰 남기기": ["Leave a review","レビューを書く","撰写评价","撰寫評價","Dejar una reseña","Laisser un avis"],
  "작성 중인 리뷰를 지울까요?": ["Discard the review in progress?","作成中のレビューを削除しますか？","放弃正在撰写的评价吗？","放棄正在撰寫的評價嗎？","¿Descartar la reseña en curso?","Supprimer l'avis en cours de rédaction ?"],
  "지금 닫으면 별점과 내용이 저장되지 않아요.": ["Closing now will not save your rating and content.","今閉じると評価と内容が保存されません。","现在关闭将不会保存评分和内容。","現在關閉將不會儲存評分和內容。","Si cierra ahora, la calificación y el contenido no se guardarán.","Si vous fermez maintenant, la note et le contenu ne seront pas enregistrés."],
  "계속 작성": ["Continue writing","入力を続ける","继续编写","繼續編寫","Continuar escribiendo","Continuer à écrire"],
  "삭제": ["Delete","削除","删除","刪除","Eliminar","Supprimer"],
  "주문 유형": ["Order types","注文タイプ","订单类型","訂單類型","Tipos de orden","Types d'ordre"],
  "시장가 주문": ["Market order","成行注文","市价单","市價單","Orden a mercado","Ordre au marché"],
  "현재 가격으로 즉시 사고파는 주문이에요.": ["An order to buy or sell immediately at the current price.","現在の価格で即座に売買する注文です。","按当前价格立即买入或卖出的订单。","按當前價格立即買入或賣出的訂單。","Una orden para comprar o vender inmediatamente al precio actual.","Un ordre d'achat ou de vente immédiat au prix actuel."],
  "지정가 주문": ["Limit order","指値注文","限价单","限價單","Orden límite","Ordre à cours limité"],
  "정한 가격에 도달할 때만 체결되는 주문이에요.": ["An order executed only when the specified price is reached.","設定した価格に達したときのみ約定する注文です。","仅在达到指定价格时才成交的订单。","僅在達到指定價格時才成交的訂單。","Una orden que solo se ejecuta cuando se alcanza el precio fijado.","Un ordre exécuté uniquement lorsque le prix spécifié est atteint."],
  "스톱 주문": ["Stop order","ストップ注文","止损单","止損單","Orden stop","Ordre stop"],
  "가격이 기준선에 닿으면 실행되는 주문이에요.": ["An order executed when the price touches a trigger level.","価格がトリガー基準に達したときに実行される注文です。","价格达到触发基准线时执行的订单。","價格達到觸發基準線時執行的訂單。","Una orden que se ejecuta cuando el precio alcanza un nivel de referencia.","Un ordre exécuté lorsque le prix atteint un niveau de déclenchement."],
  "스톱 리밋 주문": ["Stop-limit order","ストップリミット注文","止损限价单","止損限價單","Orden stop-limit","Ordre stop-limit"],
  "기준선 도달 시 지정가 주문으로 걸리는 방식이에요.": ["Places a limit order once the trigger level is reached.","トリガー基準到達時に指値注文として出される方式です。","达到触发基准线时挂出限价单的方式。","達到觸發基準線時掛出限價單的方式。","Coloca una orden límite una vez alcanzado el nivel de referencia.","Place un ordre à cours limité lorsque le niveau de déclenchement est atteint."],
  "트레일링 스탑": ["Trailing stop","トレーリングストップ","追踪止损","追蹤止損","Trailing stop","Trailing stop"],
  "가격을 일정 거리로 따라가는 동적 손절이에요.": ["A dynamic stop-loss that follows the price at a set distance.","価格を一定の間隔で追従する動的な損切り注文です。","以设定距离跟随价格的动态止损。","以設定距離跟隨價格的動態止損。","Un stop-loss dinámico que sigue al precio a una distancia establecida.","Un stop-loss dynamique qui suit le prix à une distance définie."],
  "주문 기능": ["Order features","注文機能","订单功能","訂單功能","Funciones de orden","Fonctionnalités d'ordre"],
  "OCO 주문": ["OCO order","OCO注文","OCO订单","OCO訂單","Orden OCO","Ordre OCO"],
  "두 주문 중 하나가 체결되면 나머지가 취소돼요.": ["When one of the two orders is executed, the other is canceled.","2つの注文のうち一方が約定すると、もう一方はキャンセルされます。","两个订单中只要有一个成交，另一个便会被取消。","兩個訂單中只要有一個成交，另一個便會被取消。","Cuando una de las dos órdenes se ejecuta, la otra se cancela.","Lorsque l'un des deux ordres est exécuté, l'autre est annulé."],
  "포스트 온리": ["Post-only","ポストオンリー","只做Maker (Post-only)","只做Maker (Post-only)","Post-only","Post-only"],
  "메이커로만 체결되게 제한하는 옵션이에요.": ["An option restricting execution to maker orders only.","メイカーとしてのみ約定するように制限するオプションです。","限制仅作为挂单(Maker)成交的选项。","限制僅作為掛單(Maker)成交的選項。","Opción que restringe la ejecución únicamente como creador de mercado (maker).","Option limitant l'exécution aux ordres maker uniquement."],
  "리듀스 온리": ["Reduce-only","リデュースオンリー","只减仓 (Reduce-only)","只減倉 (Reduce-only)","Reduce-only","Reduce-only"],
  "포지션을 줄이는 방향으로만 체결돼요.": ["Executes only to reduce an existing position.","ポジションを減らす方向でのみ約定します。","仅在减小现有头寸的方向上成交。","僅在減小現有頭寸的方向上成交。","Se ejecuta únicamente para reducir la posición.","S'exécute uniquement pour réduire une position."],
  "기타": ["Other","その他","其他","其他","Otros","Autres"],
  "데모 계정": ["Demo account","デモ口座","模拟账户","模擬帳戶","Cuenta demo","Compte démo"],
  "실제 자금 없이 연습할 수 있는 환경이에요.": ["An environment to practice without real funds.","実際の資金なしで練習できる環境です。","无需实际资金即可进行练习的环境。","無需實際資金即可進行練習的環境。","Un entorno para practicar sin fondos reales.","Un environnement pour s'entraîner sans fonds réels."],
  "공개 API": ["Public API","公開API","公开API","公開API","API pública","API publique"],
  "외부 프로그램으로 조회와 주문이 가능해요.": ["Allows queries and orders through external programs.","外部プログラムを通じて照会や注文が可能です。","可通过外部程序进行查询和下单。","可透過外部程式進行查詢和下單。","Permite consultas y órdenes a través de programas externos.","Permet les consultations et les ordres via des programmes externes."],
  "호가 데이터": ["Order book data","気配値データ","订单簿深度数据","訂單簿深度數據","Datos del libro de órdenes","Données du carnet d'ordres"],
  "매수와 매도 호가 잔량을 볼 수 있어요.": ["View buy and sell order book quantities.","買い気配と売り気配の数量を確認できます。","可以查看买卖挂单数量。","可以查看買賣掛單數量。","Permite ver las cantidades de compra y venta del libro de órdenes.","Permet de visualiser les quantités d'ordres d'achat et de vente."],
  "전체": ["All","すべて","全部","全部","Todos","Tout"],
  "TETH로 연결": ["Connect to TETH","TETHに連携","连接到TETH","連接到TETH","Conectar a TETH","Se connecter à TETH"],
  "계정 연결 서비스가 아직 준비되지 않았습니다. 연결이나 결제는 실행되지 않았어요.": ["The account connection service is not ready yet. No connection or payment was executed.","アカウント連携サービスはまだ準備中です。連携や決済は実行されていません。","账户连接服务尚未就绪。未执行任何连接或付款。","帳戶連接服務尚未就緒。未執行任何連接或付款。","El servicio de conexión de cuentas aún no está listo. No se ejecutó ninguna conexión ni pago.","Le service de connexion de compte n'est pas encore prêt. Aucune connexion ni aucun paiement n'ont été effectués."],
  "계정 개설": ["Open account","口座開設","开户","開戶","Abrir cuenta","Ouvrir un compte"],
  "계정 개설 경로를 확인하고 있습니다. 새 계정이나 연결은 생성되지 않았어요.": ["Checking the account opening path. No new account or connection was created.","口座開設ルートを確認しています。新しい口座や連携は作成されていません。","正在确认开户路径。尚未创建新账户或连接。","正在確認開戶路徑。尚未建立新帳戶或連接。","Comprobando la ruta de apertura de cuenta. No se creó ninguna cuenta o conexión nueva.","Vérification du parcours d'ouverture de compte. Aucun nouveau compte ni connexion n'ont été créés."],
  "로그인이 필요합니다": ["Login required","ログインが必要です","需要登录","需要登入","Inicio de sesión requerido","Connexion requise"],
  "리뷰를 남기려면 로그인해주세요.": ["Please log in to leave a review.","レビューを投稿するにはログインしてください。","请登录后发表评价。","請登入後發表評價。","Inicie sesión para dejar una reseña.","Veuillez vous connecter pour laisser un avis."],
  "거래소 연결 상태와 거래 조건은 아직 제공되지 않았습니다.": ["Exchange connection status and trading terms are not provided yet.","取引所の連携状態および取引条件はまだ提供されていません。","交易所连接状态和交易条件尚未提供。","交易所連接狀態和交易條件尚未提供。","El estado de conexión del intercambio y las condiciones comerciales aún no se proporcionan.","L'état de connexion de la plateforme et les conditions de trading ne sont pas encore fournis."],
  "TETH 연결은 조회와 거래 권한만 사용하고 출금 권한은 요구하지 않아요.": ["TETH connection uses only read and trade permissions and never requests withdrawal permissions.","TETH連携は照会と取引の権限のみを使用し、出金権限を要求することはありません。","TETH连接仅使用查询和交易权限，不要求提现权限。","TETH連接僅使用查詢和交易權限，不要求提現權限。","La conexión TETH solo utiliza permisos de consulta y operación, y nunca requiere permisos de retiro.","La connexion TETH utilise uniquement les autorisations de consultation et de trading, et n'exige aucune autorisation de retrait."],
  "TETH 연결은 준비 중이며, 연결이 열리면 조회와 거래 권한만 사용하고 출금 권한은 요구하지 않아요.": ["TETH connection is under preparation; once open, it will only use read and trade permissions and never request withdrawal permissions.","TETH連携は準備中であり、連携開始時には照会と取引の権限のみを使用し、出金権限を要求することはありません。","TETH连接正在准备中，开放后将仅使用查询和交易权限，不要求提现权限。","TETH連接正在準備中，開放後將僅使用查詢和交易權限，不要求提現權限。","La conexión TETH está en preparación; una vez habilitada, solo utilizará permisos de consulta y operación, y no requerirá permisos de retiro.","La connexion TETH est en préparation ; une fois ouverte, elle n'utilisera que les autorisations de consultation et de trading, sans jamais exiger d'autorisation de retrait."],
  "현물 1:1": ["Spot 1:1","現物 1:1","现货 1:1","現貨 1:1","Spot 1:1","Spot 1:1"],
  "최대 레버리지": ["Max leverage","最大レバレッジ","最大杠杆","最大槓桿","Apalancamiento máximo","Effet de levier max"],
  "입금 수수료": ["Deposit fee","入金手数料","充值手续费","充值手續費","Comisión de depósito","Frais de dépôt"],
  "출금 수수료": ["Withdrawal fee","出金手数料","提现手续费","提現手續費","Comisión de retiro","Frais de retrait"],
  "휴면 수수료": ["Inactivity fee","休眠手数料","休眠账户费","休眠帳戶費","Comisión por inactividad","Frais d'inactivité"],
  "현물 Maker / Taker": ["Spot Maker / Taker","現物 Maker / Taker","现货 Maker / Taker","現貨 Maker / Taker","Spot Maker / Taker","Spot Maker / Taker"],
  "선물 Maker / Taker": ["Futures Maker / Taker","先物 Maker / Taker","合约 Maker / Taker","合約 Maker / Taker","Futuros Maker / Taker","Futures Maker / Taker"],
  "TETH와 어떻게 연결하나요?": ["How do I connect to TETH?","TETHとどのように連携しますか？","如何连接到TETH？","如何連接到TETH？","¿Cómo me conecto a TETH?","Comment se connecter à TETH ?"],
  "거래소 연결 서비스가 아직 제공되지 않았습니다. 이 화면에서는 계정 연결이나 주문을 실행하지 않습니다.": ["The exchange connection service is not provided yet. This screen does not execute account connections or orders.","取引所連携サービスはまだ提供されていません。この画面ではアカウント連携や注文は実行されません。","交易所连接服务尚未提供。本页面不执行账户连接或订单操作。","交易所連接服務尚未提供。本頁面不執行帳戶連接或訂單操作。","El servicio de conexión con el intercambio aún no se proporciona. Esta pantalla no ejecuta conexiones de cuenta ni órdenes.","Le service de connexion à la plateforme n'est pas encore proposé. Cet écran n'exécute aucune connexion de compte ni aucun ordre."],
  "출금 권한이 필요한가요?": ["Is withdrawal permission required?","出金権限は必要ですか？","需要提现权限吗？","需要提現權限嗎？","¿Se requiere permiso de retiro?","L'autorisation de retrait est-elle requise ?"],
  "출금 권한은 요구하지 않습니다. API 키 등 인증 정보를 이 화면에 입력하지 마세요.": ["Withdrawal permission is never requested. Do not enter authentication credentials such as API keys on this screen.","出金権限は要求しません。この画面にAPIキーなどの認証情報を入力しないでください。","不要求提现权限。请勿在此页面输入API密钥等认证信息。","不要求提現權限。請勿在此頁面輸入API密鑰等認證資訊。","No se requiere permiso de retiro. No introduzca credenciales como claves API en esta pantalla.","L'autorisation de retrait n'est jamais demandée. Ne saisissez aucune information d'authentification telle qu'une clé API sur cet écran."],
  "아직 준비 중이에요. 지원이 열리면 이 페이지와 알림으로 가장 먼저 알려드릴게요.": ["Currently under preparation. Once support opens, we will notify you first on this page and via notifications.","現在準備中です。サポートが開始され次第、このページと通知で最初にお知らせします。","目前正在准备中。支持上线后，我们将在此页面和通过通知第一时间告知。","目前正在準備中。支援上線後，我們將在此頁面和透過通知第一時間告知。","Actualmente en preparación. Le avisaremos en esta página y mediante notificaciones tan pronto como esté disponible.","Actuellement en préparation. Dès que le support sera ouvert, vous en serez informé en priorité sur cette page et par notification."],
  "어떤 권한이 필요한가요?": ["What permissions are required?","どのような権限が必要ですか？","需要哪些权限？","需要哪些權限？","¿Qué permisos se requieren?","Quelles autorisations sont requises ?"],
  "조회와 거래 권한만 사용해요. API 생성 시 출금 권한은 켜지 마세요.": ["Only read and trade permissions are used. Do not enable withdrawal permissions when creating your API key.","照会と取引の権限のみを使用します。API作成時に出金権限を有効にしないでください。","仅使用查询和交易权限。创建API时请勿开启提现权限。","僅使用查詢和交易權限。建立API時請勿開啟提現權限。","Solo se utilizan permisos de consulta y operación. No active los permisos de retiro al crear la API.","Seules les autorisations de consultation et de trading sont utilisées. N'activez pas l'autorisation de retrait lors de la création de la clé API."],
  "아니요. TETH는 자산을 옮길 수 없고, 출금 권한은 어떤 경우에도 요구하지 않아요.": ["No. TETH cannot transfer assets and never requests withdrawal permissions under any circumstances.","いいえ。TETHは資産を移動できず、いかなる場合も出金権限を要求しません。","不需要。TETH无法转移资产，在任何情况下均不要求提现权限。","不需要。TETH無法轉移資產，在任何情況下均不要求提現權限。","No. TETH no puede transferir activos y nunca solicita permisos de retiro bajo ninguna circunstancia.","Non. TETH ne peut pas transférer d'actifs et n'exige l'autorisation de retrait en aucun cas."],
  "기존 계정도 연결할 수 있나요?": ["Can I connect an existing account?","既存のアカウントも連携できますか？","可以连接已有账户吗？","可以連接已有帳戶嗎？","¿Puedo conectar una cuenta existente?","Puis-je connecter un compte existant ?"],
  "네. 이미 쓰던 계정 그대로 API 키만 만들어 연결할 수 있어요.": ["Yes. You can connect your existing account simply by creating an API key.","はい。すでにお使いのアカウントのまま、APIキーを作成するだけで連携できます。","可以。使用现有账户直接创建API密钥即可连接。","可以。使用現有帳戶直接建立API密鑰即可連接。","Sí. Puede usar su cuenta actual simplemente creando y conectando una clave API.","Oui. Vous pouvez connecter votre compte existant en créant simplement une clé API."],
  "지원이 열리면 기존 계정 그대로 API 키로 연결할 수 있도록 준비하고 있어요.": ["We are preparing so that once support opens, you can connect your existing account using an API key.","サポート開始後、既存のアカウントをそのままAPIキーで連携できるように準備を進めています。","我们正在做准备，以便支持上线后您可以使用现有账户的API密钥进行连接。","我們正在做準備，以便支援上線後您可以使用現有帳戶的API密鑰進行連接。","Nos estamos preparando para que pueda conectar su cuenta existente mediante una clave API cuando esté disponible.","Nous préparons l'intégration pour que vous puissiez connecter votre compte existant avec une clé API dès l'ouverture du service."],
  "계정 개설 혜택은 무엇인가요?": ["What are the benefits of opening an account?","口座開設の特典は何ですか？","开户有什么优惠？","開戶有什麼優惠？","¿Cuáles son los beneficios de abrir una cuenta?","Quels sont les avantages de l'ouverture d'un compte ?"],
  "파트너 링크로 가입하면 TETH 이용료가 영원히 ₩0이에요. 가입 즉시 자동 연결됩니다.": ["Sign up via the partner link to enjoy ₩0 TETH service fees forever. Automatically connected upon sign-up.","パートナーリンクから登録すると、TETHの利用料が永久に₩0になります。登録後すぐに自動連携されます。","通过合作伙伴链接注册，TETH使用费永久为₩0。注册后立即自动连接。","透過合作夥伴連結註冊，TETH使用費永久為₩0。註冊後立即自動連接。","Regístrese mediante el enlace de socio para disfrutar de una tarifa de servicio de TETH de ₩0 para siempre. Conexión automática al registrarse.","Inscrivez-vous via le lien partenaire pour bénéficier de frais de service TETH à 0 ₩ à vie. Connexion automatique dès l'inscription."],
  "현재 준비 중이에요. 지원이 열리면 이 페이지에 먼저 표시됩니다.": ["Currently under preparation. It will appear on this page first once support opens.","現在準備中です。サポートが開始され次第、まずこのページに表示されます。","目前正在准备中。支持上线后将首先显示在此页面。","目前正在準備中。支援上線後將首先顯示在此頁面。","Actualmente en preparación. Se mostrará en esta página en cuanto esté disponible.","Actuellement en préparation. Cela s'affichera en priorité sur cette page dès l'ouverture du service."],
  "연결을 해제하면 어떻게 되나요?": ["What happens if I disconnect?","連携を解除するとどうなりますか？","解除连接后会怎样？","解除連接後會怎樣？","¿Qué ocurre si me desconecto?","Que se passe-t-il si je me déconnecte ?"],
  "실행 중인 전략이 멈추고, TETH는 더 이상 계정에 접근할 수 없어요. 자산은 그대로 남습니다.": ["Active strategies will stop, and TETH will no longer be able to access your account. Your assets remain unaffected.","実行中の戦略が停止し、TETHはアカウントにアクセスできなくなります。資産はそのまま残ります。","正在运行的策略将停止，TETH将不再能访问您的账户。您的资产不受影响保留在原处。","正在運行的策略將停止，TETH將不再能訪問您的帳戶。您的資產不受影響保留在原處。","Las estrategias en ejecución se detendrán y TETH ya no tendrá acceso a su cuenta. Sus activos permanecerán intactos.","Les stratégies en cours s'arrêteront et TETH ne pourra plus accéder à votre compte. Vos actifs restent intacts."],
  "거래소 경로": ["Exchange route","取引所ルート","交易所路径","交易所路徑","Ruta de intercambio","Parcours de la plateforme"],
  "지원 거래소": ["Supported exchanges","対応取引所","支持的交易所","支援的交易所","Intercambios compatibles","Plateformes prises en charge"],
  "연결됨": ["Connected","連携済み","已连接","已連接","Conectado","Connecté"],
  "상태 미확인": ["Status unconfirmed","ステータス未確認","状态未确认","狀態未確認","Estado sin confirmar","Statut non confirmé"],
  "지원 예정": ["Coming soon","対応予定","即将支持","即將支援","Próximamente disponible","Bientôt disponible"],
  "평점 분포 보기": ["View rating distribution","評価分布を見る","查看评分分布","查看評分分佈","Ver distribución de calificaciones","Voir la répartition des notes"],
  "앱스토어 공개 평점 기준": ["Based on App Store public ratings","App Store公開評価基準","基于App Store公开评分","基於App Store公開評分","Basado en las calificaciones públicas de App Store","Basé sur les notes publiques de l'App Store"],
  "평가": ["Rating","評価","评分","評分","Calificación","Évaluation"],
  "연결 계정": ["Connected account","連携アカウント","已关联账户","已關聯帳戶","Cuenta conectada","Compte connecté"],
  "TETH에 연결됨": ["Connected to TETH","TETHに連携済み","已连接至TETH","已連接至TETH","Conectado a TETH","Connecté à TETH"],
  "연결 관리": ["Manage connection","連携の管理","管理连接","管理連接","Gestionar conexión","Gérer la connexion"],
  "계정 개설 ↗": ["Open account ↗","口座開設 ↗","立即开户 ↗","立即開戶 ↗","Abrir cuenta ↗","Ouvrir un compte ↗"],
  "거래소 상세": ["Exchange details","取引所の詳細","交易所详情","交易所詳情","Detalles del intercambio","Détails de la plateforme"],
  "개요": ["Overview","概要","概览","概覽","Resumen","Aperçu"],
  "리뷰": ["Reviews","レビュー","评价","評價","Reseñas","Avis"],
  "거래 가능 자산": ["Tradable assets","取引可能資産","可交易资产","可交易資產","Activos negociables","Actifs négociables"],
  "프로모션": ["Promotions","プロモーション","促销活动","促銷活動","Promociones","Promotions"],
  "파트너 혜택": ["Partner benefits","パートナー特典","合作伙伴福利","合作夥伴福利","Beneficios de socios","Avantages partenaires"],
  "혜택 조건은 승인된 서비스 정책과 거래소 안내를 확인한 뒤 적용됩니다. 현재 화면만으로 무료 자격이나 계정 연결이 생성되지 않습니다.": ["Benefit terms apply after reviewing approved service policies and exchange guidelines. This screen alone does not grant free eligibility or create account connections.","特典条件は承認されたサービスポリシーと取引所の案内を確認した上で適用されます。現在の画面のみで無料資格やアカウント連携が作成されることはありません。","福利条件将在确认已批准的服务政策和交易所指南后适用。仅凭当前页面不会产生免费资格或账户连接。","福利條件將在確認已批准的服務政策和交易所指南後適用。僅憑當前頁面不會產生免費資格或帳戶連接。","Las condiciones de los beneficios se aplican tras consultar las políticas de servicio aprobadas y las instrucciones del intercambio. Esta pantalla por sí sola no genera elegibilidad gratuita ni conexiones de cuenta.","Les conditions des avantages sont appliquées après examen des politiques de service approuvées et des consignes de la plateforme. Cet écran seul n'accorde aucune gratuité ni ne crée de connexion de compte."],
  "혜택 자세히": ["Benefit details","特典の詳細","福利详情","福利詳情","Detalles del beneficio","Détails des avantages"],
  "전체 보기": ["View all","すべて見る","查看全部","查看全部","Ver todo","Voir tout"],
  "리뷰 데이터가 아직 제공되지 않았습니다.": ["Review data is not provided yet.","レビューデータはまだ提供されていません。","评价数据尚未提供。","評價數據尚未提供。","Los datos de reseñas aún no están disponibles.","Les données d'avis ne sont pas encore fournies."],
  "아직 리뷰가 없어요.": ["There are no reviews yet.","まだレビューがありません。","暂无评价。","暫無評價。","Aún no hay reseñas.","Il n'y a pas encore d'avis."],
  "이전 리뷰": ["Previous review","前のレビュー","上一条评价","上一條評價","Reseña anterior","Avis précédent"],
  "다음 리뷰": ["Next review","次のレビュー","下一条评价","下一條評價","Siguiente reseña","Avis suivant"],
  "거래 조건, 수수료": ["Trading terms, fees","取引条件・手数料","交易条件与手续费","交易條件與手續費","Condiciones de negociación y comisiones","Conditions de trading et frais"],
  "수수료와 레버리지 데이터가 아직 제공되지 않았습니다.": ["Fee and leverage data are not provided yet.","手数料およびレバレッジデータはまだ提供されていません。","手续费和杠杆数据尚未提供。","手續費和槓桿數據尚未提供。","Los datos de comisiones y apalancamiento aún no están disponibles.","Les données sur les frais et l'effet de levier ne sont pas encore fournies."],
  "수수료와 레버리지는 기본 등급(VIP0) 공식 문서 기준,": ["Fees and leverage are based on standard tier (VIP0) official documentation,","手数料およびレバレッジは基本ランク（VIP0）の公式ドキュメント基準、","手续费与杠杆基于基础等级(VIP0)官方文档，","手續費與槓桿基於基礎等級(VIP0)官方文件，","Las comisiones y el apalancamiento se basan en la documentación oficial del nivel básico (VIP0),","Les frais et l'effet de levier sont basés sur la documentation officielle du niveau standard (VIP0),"],
  "기준 스냅샷이에요.": ["this is a baseline snapshot.","を基準としたスナップショットです。","为基准快照。","為基準快照。","es una instantánea de referencia.","constitue un instantané de référence."],
  "에 대하여": ["About","について","关于","關於","Acerca de","À propos de"],
  "설립": ["Founded","設立","创立","創立","Fundada","Fondation"],
  "본사": ["Headquarters","本社","总部","總部","Sede central","Siège social"],
  "문서": ["Documentation","ドキュメント","文档","文件","Documentación","Documentation"],
  "공식 문서 ↗": ["Official documentation ↗","公式ドキュメント ↗","官方文档 ↗","官方文件 ↗","Documentación oficial ↗","Documentation officielle ↗"],
  "웹사이트": ["Website","ウェブサイト","网站","網站","Sitio web","Site web"],
  "커뮤니티": ["Community","コミュニティ","社区","社群","Comunidad","Communauté"],
  "출금 권한": ["Withdrawal permission","出金権限","提现权限","提現權限","Permiso de retiro","Autorisation de retrait"],
  "연결 후에도 설정에서 언제든 끊을 수 있습니다.": ["You can disconnect anytime from settings even after connecting.","連携後も設定からいつでも解除できます。","连接后也可随时在设置中解除连接。","連接後也可隨時在設定中解除連接。","Puede desconectarse en cualquier momento desde la configuración incluso después de conectarse.","Vous pouvez vous déconnecter à tout moment dans les paramètres même après la connexion."],
  "도구 및 기능": ["Tools & features","ツールと機能","工具与功能","工具與功能","Herramientas y funciones","Outils et fonctionnalités"],
  "정보 미제공": ["Information not provided","情報未提供","未提供信息","未提供資訊","Información no disponible","Information non fournie"],
  "사업자 지원 정보": ["Provider support information","事業者サポート情報","服务商支持信息","服務商支援資訊","Información de soporte del proveedor","Informations de support du prestataire"],
  "원본 사업자 지원 정보": ["Original provider support information","元の事業者サポート情報","原始服务商支持信息","原始服務商支援資訊","Información original de soporte del proveedor","Informations de support originales du prestataire"],
  "지원하지 않음": ["Not supported","非対応","不支持","不支援","No compatible","Non pris en charge"],
  "TETH 연결 권한": ["TETH connection permissions","TETH連携権限","TETH连接权限","TETH連接權限","Permisos de conexión de TETH","Autorisations de connexion TETH"],
  "잔고, 시세 조회": ["Read balance & market prices","残高・相場の照会","查询余额与行情","查詢餘額與行情","Consulta de saldo y cotizaciones","Consulter les soldes et les cours"],
  "전략 계산과 리스크 확인에 사용해요.": ["Used for strategy calculations and risk assessment.","戦略の計算およびリスク確認に使用します。","用于策略计算和风险确认。","用於策略計算和風險確認。","Se utiliza para cálculos de estrategia y evaluación de riesgos.","Utilisé pour le calcul de stratégie et l'évaluation des risques."],
  "주문 실행": ["Order execution","注文実行","执行订单","執行訂單","Ejecución de órdenes","Exécution des ordres"],
  "전략 조건이 맞을 때 매수와 매도를 실행해요.": ["Executes buys and sells when strategy conditions are met.","戦略の条件が合致したときに買いと売りを実行します。","在满足策略条件时执行买入和卖出。","在滿足策略條件時執行買入和賣出。","Ejecuta compras y ventas cuando se cumplen las condiciones de la estrategia.","Exécute les achats et ventes lorsque les conditions de la stratégie sont remplies."],
  "출금": ["Withdrawal","出金","提现","提現","Retiro","Retrait"],
  "TETH는 자산을 옮길 수 없어요. 요구하지 않습니다.": ["TETH cannot move assets. It is never requested.","TETHは資産を移動できません。要求することはありません。","TETH无法转移资产，绝不提出此要求。","TETH無法轉移資產，絕不提出此要求。","TETH no puede mover activos. Nunca se solicita.","TETH ne peut pas déplacer d'actifs. Cela n'est jamais requis."],
  "자주 묻는 질문": ["Frequently asked questions","よくある質問","常见问题","常見問題","Preguntas frecuentes","Foire aux questions"],
  "평점 분포": ["Rating distribution","評価分布","评分分布","評分分佈","Distribución de calificaciones","Répartition des notes"],
  "리뷰 정렬": ["Sort reviews","レビューの並び替え","评价排序","評價排序","Ordenar reseñas","Trier les avis"],
  "별점 높은 순": ["Highest rating","評価が高い順","评分从高到低","評分從高到低","Calificación más alta","Note la plus élevée"],
  "최신순": ["Latest","最新順","最新","最新","Más recientes","Plus récents"],
  "리뷰 카테고리": ["Review category","レビューカテゴリー","评价分类","評價分類","Categoría de reseña","Catégorie d'avis"],
  "리뷰 데이터 미제공": ["Review data not provided","レビューデータ未提供","未提供评价数据","未提供評價數據","Datos de reseñas no proporcionados","Données d'avis non fournies"],
  "이 카테고리의 리뷰가 아직 없어요.": ["There are no reviews in this category yet.","このカテゴリーのレビューはまだありません。","该分类下暂无评价。","該分類下暫無評價。","Aún no hay reseñas en esta categoría.","Il n'y a pas encore d'avis dans cette catégorie."],
  "리뷰 페이지": ["Review page","レビューページ","评价页面","評價頁面","Página de reseñas","Page d'avis"],
  "이전 페이지": ["Previous page","前のページ","上一页","上一頁","Página anterior","Page précédente"],
  "다음 페이지": ["Next page","次のページ","下一页","下一頁","Página siguiente","Page suivante"],
  "수수료와 조건은 각 사업자 공지 기준으로 달라질 수 있습니다.": ["Fees and terms may vary based on each provider's official notices.","手数料および条件は各事業者の告知内容によって異なる場合があります。","手续费与条款可能会根据各服务商的公告而有所变动。","手續費與條款可能會根據各服務商的公告而有所變動。","Las comisiones y condiciones pueden variar según los avisos de cada proveedor.","Les frais et conditions peuvent varier selon les annonces de chaque prestataire."],
  "원본 사업자 목록입니다. 실제 지원·연결 상태와 평점·후기·수수료는 아직 제공되지 않았습니다.": ["This is an original provider list. Actual support and connection status, ratings, reviews, and fees are not provided yet.","元の事業者リストです。実際の対応・連携状態や評価・レビュー・手数料はまだ提供されていません。","这是原始服务商列表。实际支持/连接状态以及评分、评价和手续费尚未提供。","這是原始服務商列表。實際支援/連接狀態以及評分、評價和手續費尚未提供。","Esta es una lista original de proveedores. El estado real de compatibilidad y conexión, las valoraciones, reseñas y comisiones aún no están disponibles.","Il s'agit d'une liste originale de prestataires. L'état réel de prise en charge et de connexion, les notes, avis et frais ne sont pas encore fournis."],
  "제공된 사업자 정보입니다. 연결 상태는 확인된 응답으로만 갱신됩니다.": ["Provided provider information. Connection status is updated only through verified responses.","提供された事業者情報です。連携状態は確認された応答によってのみ更新されます。","已提供的服务商信息。连接状态仅根据已确认的响应进行更新。","已提供的服務商資訊。連接狀態僅根據已確認的響應進行更新。","Información del proveedor proporcionada. El estado de la conexión solo se actualiza mediante respuestas confirmadas.","Informations fournies sur le prestataire. L'état de connexion n'est mis à jour qu'avec des réponses confirmées."],
  "요청을 확인하지 못했습니다": ["Unable to verify request","リクエストを確認できませんでした","无法确认请求","無法確認請求","No se pudo verificar la solicitud","Impossible de vérifier la demande"],
  "요청을 완료하지 못했습니다. 연결이나 결제가 완료된 것으로 처리하지 않았습니다. 다시 시도해주세요.": ["Could not complete the request. No connection or payment was processed as completed. Please try again.","リクエストを完了できませんでした。連携や支払いが完了したものとして処理されていません。もう一度お試しください。","未能完成请求。未将连接或付款处理为已完成。请重试。","未能完成請求。未將連接或付款處理為已完成。請重試。","No se pudo completar la solicitud. No se ha procesado ninguna conexión o pago como completado. Inténtelo de nuevo.","Impossible de finaliser la demande. Aucune connexion ni aucun paiement n'ont été traités comme terminés. Veuillez réessayer."],
  "연결하면, 실행됩니다": ["Connect, and it runs","連携すれば、実行されます","连接即可运行","連接即可運行","Conecte y se ejecuta","Connectez, puis lancez"],
  "5분이면 준비 끝": ["Ready in 5 minutes","5分で準備完了","5分钟即可准备完毕","5分鐘即可準備完畢","Listo en 5 minutos","Prêt en 5 minutes"],
  "연결하고, TETH에게 거래를 맡기세요": ["Connect, and leave the trading to TETH","連携して、取引をTETHにお任せください","完成连接，让TETH为您执行交易","完成連接，讓TETH為您執行交易","Conéctese y deje las operaciones en manos de TETH","Connectez-vous et laissez TETH gérer le trading"],
  "출금 권한 필요 없음, 언제든 연결 해제": ["No withdrawal permission needed, disconnect anytime","出金権限不要、いつでも連携解除可能","无需提现权限，可随时解除连接","無需提現權限，可隨時解除連接","Sin permiso de retiro necesario, desconéctese en cualquier momento","Aucune autorisation de retrait requise, déconnexion à tout moment"],
  "거래소 정렬": ["Sort exchanges","取引所の並び替え","交易所排序","交易所排序","Ordenar intercambios","Trier les plateformes"],
  "기본 순서": ["Default order","デフォルト順","默认顺序","預設順序","Orden predeterminado","Ordre par défaut"],
  "최고 평점": ["Highest rating","最高評価","最高评分","最高評分","Mejor calificación","Meilleure note"],
  "최다 리뷰": ["Most reviews","レビュー最多","最多评价","最多評價","Más reseñas","Plus grand nombre d'avis"],
  "최다 사용자": ["Most users","ユーザー数最多","最多用户","最多使用者","Más usuarios","Plus grand nombre d'utilisateurs"],
  "연결 지원": ["Connection support","連携対応","支持连接","支援連接","Soporte de conexión","Support de connexion"],
  "자세히": ["Details","詳細","详情","詳情","Detalles","Détails"],
  "자세히 보기": ["View details","詳細を見る","查看详情","查看詳情","Ver detalles","Voir les détails"],
  "등록된 사업자가 없습니다.": ["No registered providers found.","登録された事業者はありません。","暂无已注册的服务商。","暫無已註冊的服務商。","No hay proveedores registrados.","Aucun prestataire enregistré."],
  "브로커는 준비 중이에요. 준비되는 대로 이곳에 먼저 표시됩니다.": ["Brokers are in preparation. They will appear here first once ready.","ブローカーは準備中です。準備ができ次第、まずここに表示されます。","经纪商正在准备中。准备就绪后将首先显示在此处。","經紀商正在準備中。準備就緒後將首先顯示在此處。","Los intermediarios están en preparación. Se mostrarán aquí primero en cuanto estén listos.","Les courtiers sont en préparation. Ils apparaîtront ici dès qu'ils seront disponibles."],
  "조건에 맞는 사업자가 없어요.": ["No providers match your criteria.","条件に一致する事業者がありません。","没有符合条件的服务商。","沒有符合條件的服務商。","No hay proveedores que coincidan con los criterios.","Aucun prestataire ne correspond aux critères."],
  "수수료는 각 사업자 공지 기준으로 달라질 수 있습니다.": ["Fees may vary based on each provider's official notices.","手数料は各事業者の告知内容によって異なる場合があります。","手续费可能会根据各服务商的公告而有所不同。","手續費可能會根據各服務商的公告而有所不同。","Las comisiones pueden variar según los avisos de cada proveedor.","Les frais peuvent varier selon les annonces de chaque prestataire."],
  "거래소": ["Exchange","取引所","交易所","交易所","Intercambio","Plateforme d'échange"],
  "증권사": ["Securities firm","証券会社","证券公司","證券公司","Sociedad de valores","Société de courtage"],
  "브로커": ["Broker","ブローカー","经纪商","經紀商","Bróker","Courtier"],
  "거래 조건": ["Trading terms","取引条件","交易条件","交易條件","Condiciones de negociación","Conditions de trading"],
  "플랫폼 사용성": ["Platform usability","プラットフォームの利便性","平台易用性","平台易用性","Facilidad de uso de la plataforma","Facilité d'utilisation de la plateforme"],
  "고객 지원": ["Customer support","カスタマーサポート","客户支持","客戶支援","Atención al cliente","Support client"],
  "거래 기능": ["Trading features","取引機能","交易功能","交易功能","Funciones de trading","Fonctionnalités de trading"],
  "계정 관리": ["Account management","アカウント管理","账户管理","帳戶管理","Gestión de cuenta","Gestion du compte"],
  "신뢰와 보안": ["Trust & security","信頼とセキュリティ","信任与安全","信任與安全","Confianza y seguridad","Confiance et sécurité"],
  "기술 안정성": ["Technical stability","技術的安定性","技术稳定性","技術穩定性","Estabilidad técnica","Stabilité technique"],
  "모바일": ["Mobile","モバイル","移动端","行動端","Móvil","Mobile"],
  "별점 {rating}": ["Rating: {rating}","評価 {rating}","评分 {rating}","評分 {rating}","Calificación {rating}","Note : {rating}"],
  "{name} 로고": ["{name} logo","{name}のロゴ","{name}徽标","{name}標誌","Logotipo de {name}","Logo {name}"],
  "{author} 리뷰 보기": ["View reviews by {author}","{author}のレビューを見る","查看 {author} 的评价","查看 {author} 的評價","Ver reseña de {author}","Voir l'avis de {author}"],
  "{name}에 대해 다른 사람들과 의견 나누기": ["Discuss {name} with others","{name}について他のユーザーと意見交換する","与他人讨论关于 {name} 的看法","與他人討論關於 {name} 的看法","Compartir opiniones sobre {name} con otros","Échanger avec d'autres au sujet de {name}"],
  "{rating}점": ["{rating} pts","{rating}点","{rating}分","{rating}分","{rating} pts","{rating} pts"],
  "{name} 파트너 혜택": ["{name} partner benefits","{name} パートナー特典","{name} 合作伙伴福利","{name} 合作夥伴福利","Beneficios de socio de {name}","Avantages partenaires {name}"],
  "{name} 계정 개설 ↗": ["Open {name} account ↗","{name} 口座開設 ↗","开设 {name} 账户 ↗","開立 {name} 帳戶 ↗","Abrir cuenta en {name} ↗","Ouvrir un compte {name} ↗"],
  "{name}에 대하여": ["About {name}","{name}について","关于 {name}","關於 {name}","Acerca de {name}","À propos de {name}"],
  "{rating}점 정보 미제공": ["{rating}-star info not provided","{rating}点の情報未提供","未提供 {rating} 星信息","未提供 {rating} 星資訊","Información de {rating} estrellas no disponible","Information non fournie pour {rating} étoiles"],
  "{rating}점 {count}개 리뷰": ["{count} reviews for {rating} stars","{rating}点 レビュー{count}件","{rating}分 {count}条评价","{rating}分 {count}條評價","{count} reseñas de {rating} estrellas","{count} avis pour {rating} étoiles"],
  "{category} 리뷰 {count}개 · {page} / {total} 페이지": ["{count} {category} reviews · Page {page} of {total}","{category} レビュー{count}件 · {page} / {total} ページ","{category} 评价 {count} 条 · 第 {page} / {total} 页","{category} 評價 {count} 條 · 第 {page} / {total} 頁","{count} reseñas de {category} · Página {page} de {total}","{count} avis {category} · Page {page} / {total}"],
  "{name} 자세히": ["{name} details","{name}の詳細","{name} 详情","{name} 詳情","Detalles de {name}","Détails de {name}"],
  "수수료와 레버리지는 기본 등급(VIP0) 공식 문서 기준, {date} 기준 스냅샷이에요.": ["Fees and leverage are snapshots as of {date}, based on standard tier (VIP0) official documentation.","手数料およびレバレッジは基本ランク（VIP0）の公式ドキュメント基準、{date}時点のスナップショットです。","手续费与杠杆是基于基础等级(VIP0)官方文档截至 {date} 的快照。","手續費與槓桿是基於基礎等級(VIP0)官方文件截至 {date} 的快照。","Las comisiones y el apalancamiento son instantáneas a fecha de {date}, basadas en la documentación oficial del nivel básico (VIP0).","Les frais et l'effet de levier sont des instantanés au {date}, basés sur la documentation officielle du niveau standard (VIP0)."],
  "전략 검증을 통과한 뒤 연결 화면에서 {name} API 키를 등록하면 돼요. 약 5분이면 끝납니다.": ["After passing strategy validation, simply register your {name} API key on the connection screen. It takes about 5 minutes.","戦略の検証に合格した後、連携画面で{name}のAPIキーを登録するだけです。約5分で完了します。","通过策略验证后，在连接页面注册 {name} 的API密钥即可。大约需要5分钟。","通過策略驗證後，在連接頁面註冊 {name} 的API密鑰即可。大約需要5分鐘。","Tras superar la validación de la estrategia, solo tiene que registrar su clave API de {name} en la pantalla de conexión. Toma unos 5 minutos.","Après avoir réussi la validation de la stratégie, enregistrez simplement votre clé API {name} sur l'écran de connexion. Cela prend environ 5 minutes."],
}
const indexes: Record<Exclude<ClientLanguage, 'ko'>, number> = { en: 0, ja: 1, 'zh-CN': 2, 'zh-TW': 3, es: 4, fr: 5 }
export function brokerText(language: ClientLanguage, key: string, values: Readonly<Record<string,string|number>> = {}): string {
  const source = key.trim()
  const template = language === 'ko' ? key : source === '지원 거래소' ? researchNavigationLabel(language, 'brokers')
    : translations[source]?.[indexes[language]] ?? key
  return template.replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token)
}
export function useBrokerText() {
  const { language } = useClientPreferences()
  return (key: string, values?: Readonly<Record<string,string|number>>) => brokerText(language, key, values)
}
