import type { ClientLanguage } from './client-preferences'
const columns = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const
export const terminalMarketCopy = {
  inspection: ['시장 조회 · 전략과 주문은 변경되지 않습니다.', 'Market view · Strategy and orders are unchanged.', '市場の閲覧 · 戦略と注文は変更されません。', '市场查看 · 策略和订单不会改变。', '市場查看 · 策略和訂單不會變更。', 'Vista del mercado · La estrategia y las órdenes no cambian.', 'Vue du marché · La stratégie et les ordres restent inchangés.'],
  selectionUnsaved: ['종목 선택과 즐겨찾기를 저장하지 못했습니다.', 'Could not save the symbol selection and favorites.', '銘柄の選択とお気に入りを保存できませんでした。', '无法保存品种选择和自选。', '無法儲存品種選擇和自選。', 'No se pudieron guardar la selección y los favoritos.', 'Impossible d’enregistrer la sélection et les favoris.'],
  retry: ['다시 시도', 'Retry', '再試行', '重试', '重試', 'Reintentar', 'Réessayer'],
  market: ['시장 정보','Market information','市場情報','市场信息','市場資訊','Información del mercado','Informations du marché'],
  chart: ['차트','Chart','チャート','图表','圖表','Gráfico','Graphique'],
  info: ['정보','Information','情報','信息','資訊','Información','Informations'],
  data: ['데이터','Data','データ','数据','資料','Datos','Données'],
  period: ['기간','Period','期間','周期','週期','Periodo','Période'],
  loading: ['불러오는 중','Loading','読み込み中','加载中','載入中','Cargando','Chargement'],
  error: ['자료를 불러오지 못했습니다.','Could not load the data.','資料を読み込めませんでした。','未能加载资料。','無法載入資料。','No se pudieron cargar los datos.','Impossible de charger les données.'],
  unavailable: ['아직 제공된 자료가 없습니다.','No data has been provided yet.','まだ資料が提供されていません。','暂无提供的资料。','尚未提供資料。','Todavía no se han proporcionado datos.','Aucune donnée fournie pour le moment.'],
  mark: ['표시가격','Mark price','マーク価格','标记价格','標記價格','Precio de marca','Prix de référence'],
  index: ['지수가격','Index price','指数価格','指数价格','指數價格','Precio del índice','Prix de l’indice'],
  funding: ['펀딩비 / 남은 시간','Funding / time remaining','資金調達率 / 残り時間','资金费率 / 剩余时间','資金費率 / 剩餘時間','Financiación / tiempo restante','Financement / temps restant'],
  high: ['24시간 고가','24h high','24時間高値','24小时最高价','24小時最高價','Máximo 24 h','Plus haut 24 h'],
  low: ['24시간 저가','24h low','24時間安値','24小时最低价','24小時最低價','Mínimo 24 h','Plus bas 24 h'],
  volume: ['24시간 거래량','24h volume','24時間出来高','24小时成交量','24小時成交量','Volumen 24 h','Volume 24 h'],
  notional: ['24시간 거래대금','24h turnover','24時間売買代金','24小时成交额','24小時成交額','Importe 24 h','Montant échangé 24 h'],
  rank: ['순위','Rank','順位','排名','排名','Clasificación','Classement'],
  cap: ['시가총액','Market cap','時価総額','市值','市值','Capitalización','Capitalisation'],
  diluted: ['완전 희석 시가총액','Fully diluted valuation','完全希薄化時価総額','完全稀释市值','完全稀釋市值','Valoración totalmente diluida','Valorisation entièrement diluée'],
  share: ['시장 점유율','Market share','市場占有率','市场占比','市場占比','Cuota de mercado','Part de marché'],
  coinVolume: ['거래량','Volume','出来高','成交量','成交量','Volumen','Volume'],
  volumeCap: ['거래량 / 시가총액','Volume / market cap','出来高 / 時価総額','成交量 / 市值','成交量 / 市值','Volumen / capitalización','Volume / capitalisation'],
  circulating: ['유통 공급량','Circulating supply','流通供給量','流通供应量','流通供應量','Oferta circulante','Offre en circulation'],
  maximum: ['최대 공급량','Maximum supply','最大供給量','最大供应量','最大供應量','Oferta máxima','Offre maximale'],
  supply: ['총 공급량','Total supply','総供給量','总供应量','總供應量','Oferta total','Offre totale'],
  links: ['링크','Links','リンク','链接','連結','Enlaces','Liens'],
  rules: ['거래 규칙','Trading rules','取引ルール','交易规则','交易規則','Reglas de negociación','Règles de négociation'],
  tick: ['가격 단위','Tick size','価格刻み','价格单位','價格單位','Incremento de precio','Pas de cotation'],
  minQuantity: ['최소 주문 수량','Minimum order quantity','最小注文数量','最小下单数量','最小下單數量','Cantidad mínima','Quantité minimale'],
  minNotional: ['최소 주문 금액','Minimum order value','最小注文金額','最小下单金额','最小下單金額','Importe mínimo','Montant minimal'],
  listed: ['상장일','Listing date','上場日','上市日期','上市日期','Fecha de cotización','Date de cotation'],
  oi: ['미결제약정','Open interest','建玉','持仓量','未平倉量','Interés abierto','Positions ouvertes'],
  accounts: ['상위 트레이더 롱숏 비율(계정)','Top trader long/short ratio (accounts)','上位トレーダーロング・ショート比率（口座）','大户多空比（账户）','大戶多空比（帳戶）','Ratio largo/corto de principales traders (cuentas)','Ratio long/short des principaux traders (comptes)'],
  positions: ['상위 트레이더 롱숏 비율(포지션)','Top trader long/short ratio (positions)','上位トレーダーロング・ショート比率（ポジション）','大户多空比（持仓）','大戶多空比（持倉）','Ratio largo/corto de principales traders (posiciones)','Ratio long/short des principaux traders (positions)'],
  globalRatio: ['전체 롱숏 비율','Global long/short ratio','全体ロング・ショート比率','整体多空比','整體多空比','Ratio largo/corto global','Ratio long/short global'],
  taker: ['테이커 매수와 매도량','Taker buy and sell volume','テイカー売買数量','主动买卖量','主動買賣量','Volumen comprador y vendedor taker','Volume acheteur et vendeur taker'],
  basis: ['베이시스','Basis','ベーシス','基差','基差','Base','Base'],
  fundingHistory: ['펀딩비','Funding rates','資金調達率','资金费率','資金費率','Tasas de financiación','Taux de financement'],
  supplyRatio: ['미결제약정 / 유통량 비율','Open interest / circulating supply','建玉 / 流通供給量','持仓量 / 流通量','未平倉量 / 流通量','Interés abierto / oferta circulante','Positions ouvertes / offre en circulation'],
  values: ['값 보기','View values','値を表示','查看数值','查看數值','Ver valores','Voir les valeurs'],
  time: ['시각','Time','時刻','时间','時間','Hora','Heure'],
} as const satisfies Record<string, readonly [string,string,string,string,string,string,string]>
export function terminalMarketText(language: ClientLanguage, key: keyof typeof terminalMarketCopy): string { return terminalMarketCopy[key][columns[language]] }
