import type { ClientLanguage } from './client-preferences'

/** Display-only source performance copy; supplied calculations and asset names stay unchanged. */
const ko = {
  "월별 성과와 보유기간": "월별 성과와 보유기간",
  "이전 월": "이전 월",
  "다음 월": "다음 월",
  "월 합산 {return}%, 체결 {count}회": "월 합산 {return}%, 체결 {count}회",
  "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%": "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%",
  "검증 시뮬레이션": "검증 시뮬레이션",
  "평가 기록 없음": "평가 기록 없음",
  "검증 수익 {return}%": "검증 수익 {return}%",
  "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.": "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.",
  "표시할 기간 데이터가 없어요.": "표시할 기간 데이터가 없어요.",
  "보유기간 분포": "보유기간 분포",
  "평균 {average}봉, 최장 {longest}봉": "평균 {average}봉, 최장 {longest}봉",
  "≤2봉": "≤2봉",
  "3–5봉": "3–5봉",
  "6–10봉": "6–10봉",
  "11–24봉": "11–24봉",
  "25봉+": "25봉+",
  "익 {wins}, 손 {losses}": "익 {wins}, 손 {losses}",
  "이익 청산": "이익 청산",
  "손실 청산": "손실 청산",
  "연도별 손익과 체결 이력": "연도별 손익과 체결 이력",
  "연도별 손익, 체결 이력": "연도별 손익, 체결 이력",
  "최근 {count}건, 검증 시뮬레이션 체결": "최근 {count}건, 검증 시뮬레이션 체결",
  "연도별 검증 손익": "연도별 검증 손익",
  "{year}년 {return}%": "{year}년 {return}%",
  "최근 검증 시뮬레이션 체결": "최근 검증 시뮬레이션 체결",
  "진입일": "진입일",
  "청산일": "청산일",
  "보유": "보유",
  "자산": "자산",
  "구분": "구분",
  "진입가": "진입가",
  "청산가": "청산가",
  "손익률": "손익률",
  "{count}봉": "{count}봉",
  "손절": "손절",
  "익절": "익절",
  "기간 청산": "기간 청산",
  "이 기간에는 체결이 없어요": "이 기간에는 체결이 없어요"
} as const

export type SharedPerformanceCopyKey = keyof typeof ko

export const CLIENT_SHARED_PERFORMANCE_COPY: Record<ClientLanguage, Record<SharedPerformanceCopyKey, string>> = {
  ko,
  "en": {
  "월별 성과와 보유기간": "Monthly performance and holding period",
  "이전 월": "Previous month",
  "다음 월": "Next month",
  "월 합산 {return}%, 체결 {count}회": "Monthly total {return}%, {count} executions",
  "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%": "Monthly total {return}%, {count} executions, win rate {winRate}%",
  "검증 시뮬레이션": "Validation simulation",
  "평가 기록 없음": "No evaluation records",
  "검증 수익 {return}%": "Validation return {return}%",
  "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.": "Only bars with evaluation records are colored. Based on past bars.",
  "표시할 기간 데이터가 없어요.": "No period data to display.",
  "보유기간 분포": "Holding period distribution",
  "평균 {average}봉, 최장 {longest}봉": "Average {average} bars, longest {longest} bars",
  "≤2봉": "≤2 bars",
  "3–5봉": "3–5 bars",
  "6–10봉": "6–10 bars",
  "11–24봉": "11–24 bars",
  "25봉+": "25+ bars",
  "익 {wins}, 손 {losses}": "W {wins}, L {losses}",
  "이익 청산": "Winning exits",
  "손실 청산": "Losing exits",
  "연도별 손익과 체결 이력": "Annual P&L and execution history",
  "연도별 손익, 체결 이력": "Annual P&L, execution history",
  "최근 {count}건, 검증 시뮬레이션 체결": "Recent {count}, validation simulation executions",
  "연도별 검증 손익": "Annual validation P&L",
  "{year}년 {return}%": "{year} {return}%",
  "최근 검증 시뮬레이션 체결": "Recent validation simulation executions",
  "진입일": "Entry date",
  "청산일": "Exit date",
  "보유": "Holding",
  "자산": "Asset",
  "구분": "Type",
  "진입가": "Entry price",
  "청산가": "Exit price",
  "손익률": "Return rate",
  "{count}봉": "{count} bars",
  "손절": "Stop-loss",
  "익절": "Take-profit",
  "기간 청산": "Time-based exit",
  "이 기간에는 체결이 없어요": "No executions during this period"
},
  "ja": {
  "월별 성과와 보유기간": "月別パフォーマンスと保有期間",
  "이전 월": "前月",
  "다음 월": "翌月",
  "월 합산 {return}%, 체결 {count}회": "月合計 {return}%、約定 {count}回",
  "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%": "月合計 {return}%、約定 {count}回、勝率 {winRate}%",
  "검증 시뮬레이션": "検証シミュレーション",
  "평가 기록 없음": "評価記録なし",
  "검증 수익 {return}%": "検証リターン {return}%",
  "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.": "評価記録のあるバーのみ色付けされます。過去のバーが基準です。",
  "표시할 기간 데이터가 없어요.": "表示する期間データがありません。",
  "보유기간 분포": "保有期間の分布",
  "평균 {average}봉, 최장 {longest}봉": "平均 {average}バー、最長 {longest}バー",
  "≤2봉": "≤2バー",
  "3–5봉": "3–5バー",
  "6–10봉": "6–10バー",
  "11–24봉": "11–24バー",
  "25봉+": "25バー+",
  "익 {wins}, 손 {losses}": "勝 {wins}、負 {losses}",
  "이익 청산": "利益決済",
  "손실 청산": "損失決済",
  "연도별 손익과 체결 이력": "年別損益と約定履歴",
  "연도별 손익, 체결 이력": "年別損益、約定履歴",
  "최근 {count}건, 검증 시뮬레이션 체결": "直近 {count}件、検証シミュレーション約定",
  "연도별 검증 손익": "年別検証損益",
  "{year}년 {return}%": "{year}年 {return}%",
  "최근 검증 시뮬레이션 체결": "直近の検証シミュレーション約定",
  "진입일": "エントリー日",
  "청산일": "決済日",
  "보유": "保有",
  "자산": "資産",
  "구분": "区分",
  "진입가": "エントリー価格",
  "청산가": "決済価格",
  "손익률": "損益率",
  "{count}봉": "{count}バー",
  "손절": "損切り",
  "익절": "利確",
  "기간 청산": "時間決済",
  "이 기간에는 체결이 없어요": "この期間の約定はありません"
},
  "zh-CN": {
  "월별 성과와 보유기간": "月度表现与持仓周期",
  "이전 월": "上月",
  "다음 월": "下月",
  "월 합산 {return}%, 체결 {count}회": "月度合计 {return}%，成交 {count} 次",
  "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%": "月度合计 {return}%，成交 {count} 次，胜率 {winRate}%",
  "검증 시뮬레이션": "验证模拟",
  "평가 기록 없음": "无评估记录",
  "검증 수익 {return}%": "验证收益 {return}%",
  "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.": "仅有评估记录的K线才会着色。基于过去的K线。",
  "표시할 기간 데이터가 없어요.": "没有可显示的时间段数据。",
  "보유기간 분포": "持仓周期分布",
  "평균 {average}봉, 최장 {longest}봉": "平均 {average} 根K线，最长 {longest} 根K线",
  "≤2봉": "≤2根K线",
  "3–5봉": "3–5根K线",
  "6–10봉": "6–10根K线",
  "11–24봉": "11–24根K线",
  "25봉+": "25+根K线",
  "익 {wins}, 손 {losses}": "胜 {wins}，负 {losses}",
  "이익 청산": "盈利平仓",
  "손실 청산": "亏损平仓",
  "연도별 손익과 체결 이력": "年度盈亏与成交历史",
  "연도별 손익, 체결 이력": "年度盈亏，成交历史",
  "최근 {count}건, 검증 시뮬레이션 체결": "最近 {count} 笔，验证模拟成交",
  "연도별 검증 손익": "年度验证盈亏",
  "{year}년 {return}%": "{year}年 {return}%",
  "최근 검증 시뮬레이션 체결": "最近验证模拟成交",
  "진입일": "开仓日期",
  "청산일": "平仓日期",
  "보유": "持仓",
  "자산": "资产",
  "구분": "类型",
  "진입가": "开仓价",
  "청산가": "平仓价",
  "손익률": "收益率",
  "{count}봉": "{count} 根K线",
  "손절": "止损",
  "익절": "止盈",
  "기간 청산": "时间平仓",
  "이 기간에는 체결이 없어요": "此期间内无成交"
},
  "zh-TW": {
  "월별 성과와 보유기간": "月度表現與持倉週期",
  "이전 월": "上月",
  "다음 월": "下月",
  "월 합산 {return}%, 체결 {count}회": "月度合計 {return}%，成交 {count} 次",
  "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%": "月度合計 {return}%，成交 {count} 次，勝率 {winRate}%",
  "검증 시뮬레이션": "驗證模擬",
  "평가 기록 없음": "無評估記錄",
  "검증 수익 {return}%": "驗證收益 {return}%",
  "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.": "僅有評估紀錄的K線才會著色。基於過去的K線。",
  "표시할 기간 데이터가 없어요.": "沒有可顯示的時間段資料。",
  "보유기간 분포": "持倉週期分佈",
  "평균 {average}봉, 최장 {longest}봉": "平均 {average} 根K線，最長 {longest} 根K線",
  "≤2봉": "≤2根K線",
  "3–5봉": "3–5根K線",
  "6–10봉": "6–10根K線",
  "11–24봉": "11–24根K線",
  "25봉+": "25+根K線",
  "익 {wins}, 손 {losses}": "勝 {wins}，負 {losses}",
  "이익 청산": "獲利平倉",
  "손실 청산": "虧損平倉",
  "연도별 손익과 체결 이력": "年度損益與成交歷史",
  "연도별 손익, 체결 이력": "年度損益，成交歷史",
  "최근 {count}건, 검증 시뮬레이션 체결": "最近 {count} 筆，驗證模擬成交",
  "연도별 검증 손익": "年度驗證損益",
  "{year}년 {return}%": "{year}年 {return}%",
  "최근 검증 시뮬레이션 체결": "最近驗證模擬成交",
  "진입일": "開倉日期",
  "청산일": "平倉日期",
  "보유": "持倉",
  "자산": "資產",
  "구분": "類型",
  "진입가": "開倉價",
  "청산가": "平倉價",
  "손익률": "損益率",
  "{count}봉": "{count} 根K線",
  "손절": "停損",
  "익절": "停利",
  "기간 청산": "時間平倉",
  "이 기간에는 체결이 없어요": "此期間內無成交"
},
  "es": {
  "월별 성과와 보유기간": "Rendimiento mensual y período de tenencia",
  "이전 월": "Mes anterior",
  "다음 월": "Mes siguiente",
  "월 합산 {return}%, 체결 {count}회": "Total mensual {return}%, {count} ejecuciones",
  "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%": "Total mensual {return}%, {count} ejecuciones, tasa de acierto {winRate}%",
  "검증 시뮬레이션": "Simulación de validación",
  "평가 기록 없음": "Sin registros de evaluación",
  "검증 수익 {return}%": "Rentabilidad de validación {return}%",
  "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.": "Solo las barras con registros de evaluación están coloreadas. Se basa en barras pasadas.",
  "표시할 기간 데이터가 없어요.": "No hay datos de período para mostrar.",
  "보유기간 분포": "Distribución del período de tenencia",
  "평균 {average}봉, 최장 {longest}봉": "Promedio {average} barras, máxima {longest} barras",
  "≤2봉": "≤2 barras",
  "3–5봉": "3–5 barras",
  "6–10봉": "6–10 barras",
  "11–24봉": "11–24 barras",
  "25봉+": "25+ barras",
  "익 {wins}, 손 {losses}": "V {wins}, D {losses}",
  "이익 청산": "Cierres ganadores",
  "손실 청산": "Cierres perdedores",
  "연도별 손익과 체결 이력": "Pérdidas y ganancias anuales e historial de ejecuciones",
  "연도별 손익, 체결 이력": "Pérdidas y ganancias anuales, historial de ejecuciones",
  "최근 {count}건, 검증 시뮬레이션 체결": "Últimas {count}, ejecuciones de simulación de validación",
  "연도별 검증 손익": "Pérdidas y ganancias anuales de validación",
  "{year}년 {return}%": "{year} {return}%",
  "최근 검증 시뮬레이션 체결": "Ejecuciones recientes de simulación de validación",
  "진입일": "Fecha de entrada",
  "청산일": "Fecha de salida",
  "보유": "Tenencia",
  "자산": "Activo",
  "구분": "Tipo",
  "진입가": "Precio de entrada",
  "청산가": "Precio de salida",
  "손익률": "Rentabilidad",
  "{count}봉": "{count} barras",
  "손절": "Stop-loss",
  "익절": "Take-profit",
  "기간 청산": "Salida basada en tiempo",
  "이 기간에는 체결이 없어요": "No hay ejecuciones durante este período"
},
  "fr": {
  "월별 성과와 보유기간": "Performance mensuelle et durée de détention",
  "이전 월": "Mois précédent",
  "다음 월": "Mois suivant",
  "월 합산 {return}%, 체결 {count}회": "Total mensuel {return}%, {count} exécutions",
  "월 합산 {return}%, 체결 {count}회, 승률 {winRate}%": "Total mensuel {return}%, {count} exécutions, taux de réussite {winRate}%",
  "검증 시뮬레이션": "Simulation de validation",
  "평가 기록 없음": "Aucun enregistrement d'évaluation",
  "검증 수익 {return}%": "Rendement de validation {return}%",
  "평가 기록이 있는 봉만 색이 칠해져요. 지난 봉 기준이에요.": "Seules les barres ayant des enregistrements d'évaluation sont colorées. Basé sur les barres passées.",
  "표시할 기간 데이터가 없어요.": "Aucune donnée de période à afficher.",
  "보유기간 분포": "Distribution de la durée de détention",
  "평균 {average}봉, 최장 {longest}봉": "Moyenne {average} barres, plus longue {longest} barres",
  "≤2봉": "≤2 barres",
  "3–5봉": "3–5 barres",
  "6–10봉": "6–10 barres",
  "11–24봉": "11–24 barres",
  "25봉+": "25+ barres",
  "익 {wins}, 손 {losses}": "V {wins}, D {losses}",
  "이익 청산": "Clôtures gagnantes",
  "손실 청산": "Clôtures perdantes",
  "연도별 손익과 체결 이력": "Pertes et profits annuels et historique des exécutions",
  "연도별 손익, 체결 이력": "Pertes et profits annuels, historique des exécutions",
  "최근 {count}건, 검증 시뮬레이션 체결": "Dernières {count}, exécutions de simulation de validation",
  "연도별 검증 손익": "Pertes et profits de validation annuels",
  "{year}년 {return}%": "{year} {return}%",
  "최근 검증 시뮬레이션 체결": "Exécutions récentes de simulation de validation",
  "진입일": "Date d'entrée",
  "청산일": "Date de sortie",
  "보유": "Détention",
  "자산": "Actif",
  "구분": "Type",
  "진입가": "Prix d'entrée",
  "청산가": "Prix de sortie",
  "손익률": "Rendement",
  "{count}봉": "{count} barres",
  "손절": "Stop-loss",
  "익절": "Take-profit",
  "기간 청산": "Sortie basée sur le temps",
  "이 기간에는 체결이 없어요": "Aucune exécution pendant cette période"
},
}

export function sharedPerformanceCopy(language: ClientLanguage, key: SharedPerformanceCopyKey, values: Record<string, string | number> = {}) {
  return CLIENT_SHARED_PERFORMANCE_COPY[language][key].replace(/\{(\w+)\}/g, (token, name: string) => String(values[name] ?? token))
}

