import type { ClientLanguage } from './client-preferences'
import { copyActionError } from './client-copy-trading-copy'

// Presentation only: recovery codes, archived bytes and reset policy stay unchanged.
const labels = {
  '저장 상태 다시 확인': ['Check saved state again', '保存状態を再確認', '重新检查保存状态', '重新檢查儲存狀態', 'Volver a comprobar el estado', 'Revérifier l’état enregistré'],
  '사본 보관 후 새로 시작': ['Keep a copy and start over', 'コピーを保管してやり直す', '保留副本后重新开始', '保留副本後重新開始', 'Conservar una copia y reiniciar', 'Conserver une copie et recommencer'],
  '카피 미리보기를 새로 시작할까요?': ['Restart the copy trading preview?', 'コピートレードのプレビューをやり直しますか？', '重新开始跟单预览？', '重新開始跟單預覽？', '¿Reiniciar la vista previa de copia?', 'Recommencer l’aperçu de copy trading ?'],
  '현재 탭에 저장된 기존 기록의 사본을 먼저 보관한 뒤, 카피 목록과 체험용 잔고를 처음 상태로 바꿉니다. 실제 계좌나 자금에는 영향을 주지 않아요.': ['First, a copy of the existing records in this tab is kept. Then the copy list and trial balance are reset. Real accounts and funds are not affected.', 'このタブの既存記録のコピーを保管してから、コピー一覧と体験用残高を初期状態に戻します。実際の口座や資金には影響しません。', '先保留当前标签页中现有记录的副本，再重置跟单列表和体验余额。不会影响真实账户或资金。', '先保留目前分頁中既有紀錄的副本，再重設跟單清單和體驗餘額。不會影響真實帳戶或資金。', 'Primero se conserva una copia de los registros de esta pestaña. Después se restablecen la lista de copias y el saldo de prueba. Las cuentas y los fondos reales no se ven afectados.', 'Une copie des données de cet onglet est d’abord conservée. La liste des copies et le solde d’essai sont ensuite réinitialisés. Les comptes et fonds réels ne sont pas affectés.'],
  '사본은 이 탭의 임시 저장소에 남으며, 탭을 닫으면 사라질 수 있어요. 사본 저장을 확인하지 못하면 초기화하지 않습니다.': ['The copy stays in this tab’s temporary storage and may disappear when the tab is closed. Nothing is reset unless the copy is verified as saved.', 'コピーはこのタブの一時ストレージに保存され、タブを閉じると失われる場合があります。コピーの保存を確認できなければ初期化しません。', '副本保留在此标签页的临时存储中，关闭标签页后可能丢失。未确认副本已保存时，不会重置。', '副本保留在此分頁的暫存空間中，關閉分頁後可能遺失。未確認副本已儲存時，不會重設。', 'La copia queda en el almacenamiento temporal de esta pestaña y puede perderse al cerrarla. No se restablece nada si no se verifica que la copia se guardó.', 'La copie reste dans le stockage temporaire de cet onglet et peut disparaître à sa fermeture. Aucune réinitialisation n’a lieu sans vérification de son enregistrement.'],
  '사본 보관하고 초기화': ['Keep a copy and reset', 'コピーを保管して初期化', '保留副本并重置', '保留副本並重設', 'Conservar una copia y restablecer', 'Conserver une copie et réinitialiser'],
  '복구 요청을 만들지 못했어요. 저장 상태를 다시 확인해주세요.': ['Could not create the recovery request. Check the saved state again.', '復旧リクエストを作成できませんでした。保存状態を再確認してください。', '无法创建恢复请求，请重新检查保存状态。', '無法建立復原請求，請重新檢查儲存狀態。', 'No se pudo crear la solicitud de recuperación. Vuelve a comprobar el estado guardado.', 'Impossible de créer la demande de récupération. Revérifiez l’état enregistré.'],
  '현재 계정을 다시 확인해주세요.': ['Check the current account again.', '現在のアカウントを再確認してください。', '请重新检查当前账户。', '請重新檢查目前帳戶。', 'Vuelve a comprobar la cuenta actual.', 'Revérifiez le compte actuel.'],
  '복구 요청을 새로 열어 다시 확인해주세요.': ['Open a new recovery request and confirm again.', '復旧リクエストを新しく開いて再確認してください。', '请重新打开恢复请求并确认。', '請重新開啟復原請求並確認。', 'Abre una nueva solicitud de recuperación y vuelve a confirmar.', 'Ouvrez une nouvelle demande de récupération et confirmez à nouveau.'],
  '이 브라우저에서 미리보기 저장소를 사용할 수 없어요.': ['Preview storage is unavailable in this browser.', 'このブラウザではプレビュー用ストレージを利用できません。', '此浏览器无法使用预览存储。', '此瀏覽器無法使用預覽儲存空間。', 'El almacenamiento de la vista previa no está disponible en este navegador.', 'Le stockage de l’aperçu est indisponible dans ce navigateur.'],
  '기존 미리보기를 읽지 못해 초기화하지 않았어요. 다시 불러와 확인해주세요.': ['The existing preview could not be read, so it was not reset. Reload it to check.', '既存のプレビューを読み込めなかったため初期化していません。再読み込みして確認してください。', '无法读取现有预览，因此未重置。请重新加载后检查。', '無法讀取既有預覽，因此未重設。請重新載入後檢查。', 'No se pudo leer la vista previa existente, por lo que no se restableció. Vuelve a cargarla para comprobarlo.', 'L’aperçu existant n’a pas pu être lu ; il n’a donc pas été réinitialisé. Rechargez-le pour vérifier.'],
  '기존 미리보기가 보관 한도를 넘어 초기화하지 않았어요. 원본은 그대로 남아 있어요.': ['The existing preview exceeds the archive limit and was not reset. The original is unchanged.', '既存のプレビューが保管上限を超えているため初期化していません。元のデータはそのまま残っています。', '现有预览超出保留限额，因此未重置。原始记录保持不变。', '既有預覽超出保留上限，因此未重設。原始紀錄保持不變。', 'La vista previa supera el límite de archivo y no se restableció. El original no ha cambiado.', 'L’aperçu dépasse la limite d’archivage et n’a pas été réinitialisé. L’original reste inchangé.'],
  '같은 복구 요청의 보관함이 이미 있어요. 다시 불러온 뒤 새 복구 요청을 확인해주세요.': ['An archive already exists for this recovery request. Reload, then confirm a new recovery request.', '同じ復旧リクエストの保管データが既にあります。再読み込み後、新しい復旧リクエストを確認してください。', '此恢复请求已有存档。请重新加载后确认新的恢复请求。', '此復原請求已有封存資料。請重新載入後確認新的復原請求。', 'Ya existe un archivo para esta solicitud. Vuelve a cargar y confirma una nueva solicitud de recuperación.', 'Une archive existe déjà pour cette demande. Rechargez, puis confirmez une nouvelle demande de récupération.'],
  '보관함을 확인하지 못해 초기화하지 않았어요.': ['The archive could not be checked, so nothing was reset.', '保管データを確認できなかったため初期化していません。', '无法检查存档，因此未重置。', '無法檢查封存資料，因此未重設。', 'No se pudo comprobar el archivo, por lo que no se restableció nada.', 'L’archive n’a pas pu être vérifiée ; aucune réinitialisation n’a eu lieu.'],
  '기존 미리보기의 사본 저장을 확인하지 못해 초기화하지 않았어요. 원본은 그대로 남아 있어요.': ['The preview copy could not be verified as saved, so nothing was reset. The original is unchanged.', '既存プレビューのコピーの保存を確認できなかったため初期化していません。元のデータはそのまま残っています。', '未能确认现有预览的副本已保存，因此未重置。原始记录保持不变。', '未能確認既有預覽的副本已儲存，因此未重設。原始紀錄保持不變。', 'No se pudo verificar que la copia se guardó, por lo que no se restableció nada. El original no ha cambiado.', 'L’enregistrement de la copie n’a pas pu être vérifié ; aucune réinitialisation n’a eu lieu. L’original reste inchangé.'],
  '보관 사본을 다시 읽어 확인하지 못해 초기화하지 않았어요. 원본은 그대로 남아 있어요.': ['The archived copy could not be read back and verified, so nothing was reset. The original is unchanged.', '保管コピーを再読み込みして確認できなかったため初期化していません。元のデータはそのまま残っています。', '未能重新读取并验证保留副本，因此未重置。原始记录保持不变。', '未能重新讀取並驗證保留副本，因此未重設。原始紀錄保持不變。', 'No se pudo volver a leer y verificar la copia archivada, por lo que no se restableció nada. El original no ha cambiado.', 'La copie archivée n’a pas pu être relue et vérifiée ; aucune réinitialisation n’a eu lieu. L’original reste inchangé.'],
  '복구 중 미리보기가 바뀌어 초기화하지 않았어요. 다시 불러와 확인해주세요.': ['The preview changed during recovery and was not reset. Reload it to check.', '復旧中にプレビューが変わったため初期化していません。再読み込みして確認してください。', '恢复过程中预览发生变化，因此未重置。请重新加载后检查。', '復原過程中預覽發生變更，因此未重設。請重新載入後檢查。', 'La vista previa cambió durante la recuperación y no se restableció. Vuelve a cargarla para comprobarlo.', 'L’aperçu a changé pendant la récupération et n’a pas été réinitialisé. Rechargez-le pour vérifier.'],
  '초기화 결과를 확인하지 못했어요. 다시 불러와 현재 상태를 확인해주세요.': ['The reset result could not be verified. Reload to check the current state.', '初期化の結果を確認できませんでした。再読み込みして現在の状態を確認してください。', '无法确认重置结果。请重新加载以检查当前状态。', '無法確認重設結果。請重新載入以檢查目前狀態。', 'No se pudo verificar el resultado del restablecimiento. Vuelve a cargar para comprobar el estado actual.', 'Le résultat de la réinitialisation n’a pas pu être vérifié. Rechargez pour vérifier l’état actuel.'],
} as const satisfies Record<string, readonly [string, string, string, string, string, string]>
export type CopyRecoveryKey = keyof typeof labels
export function copyRecoveryText(language: ClientLanguage, message: string): string {
  if (!Object.hasOwn(labels, message)) return copyActionError(language, message)
  const index = ['ko', 'en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr'].indexOf(language)
  return index <= 0 ? message : labels[message as CopyRecoveryKey][index - 1]
}
