import type { ClientLanguage } from './client-preferences'

type Translations = readonly [string, string, string, string, string, string, string]
const column = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const satisfies Record<ClientLanguage, number>
// Static UI only. Never translate supplied notification bodies, evidence, or custom names.
export const accountActivityCopy = {
  alerts: ["알림","Alerts","通知","通知","通知","Alertas","Alertes"],
  all: ["전체","All","すべて","全部","全部","Todos","Tout"],
  position: ["포지션","Position","ポジション","持仓","持倉","Posición","Position"],
  strategy: ["전략","Strategy","戦略","策略","策略","Estrategia","Stratégie"],
  review: ["거래복기","Trade Review","トレード振り返り","交易复盘","交易複盤","Revisión de operaciones","Revue de trade"],
  rebates: ["정산","Settlement","精算","结算","結算","Liquidación","Règlement"],
  credits: ["크레딧","Credits","クレジット","额度","額度","Créditos","Crédits"],
  reports: ["보고서","Reports","レポート","报告","報告","Informes","Rapports"],
  unread: ["{count}개 안읽음","{count} unread","未読{count}件","{count}条未读","{count}則未讀","{count} no leídas","{count} non lues"],
  unreadOne: ["{count}개 안읽음","{count} unread","未読{count}件","{count}条未读","{count}則未讀","{count} no leída","{count} non lue"],
  readAll: ["모두 읽음","Mark all as read","すべて既読にする","全部标为已读","全部標為已讀","Marcar todo como leído","Tout marquer comme lu"],
  preferences: ["수신 설정","Notification Preferences","受信設定","接收设置","接收設定","Preferencias de notificación","Préférences de notification"],
  categories: ["알림 분류","Alert Categories","通知カテゴリ","通知分类","通知分類","Categorías de alertas","Catégories d'alertes"],
  read: ["읽음","Read","既読","已读","已讀","Leído","Lu"],
  notRead: ["안읽음","Unread","未読","未读","未讀","No leído","Non lu"],
  noCategory: ["이 분류의 알림이 없습니다","No alerts in this category","このカテゴリの通知はありません","该分类下暂无通知","該分類下暫無通知","No hay alertas en esta categoría","Aucune alerte dans cette catégorie"],
  noAlerts: ["아직 알림이 없습니다","No alerts yet","通知はまだありません","暂无通知","暫無通知","Aún no hay alertas","Pas encore d'alertes"],
  otherAlerts: ["다른 필터에서 {count}건을 확인할 수 있습니다.","You can check {count} alerts in other filters.","他のフィルターで{count}件を確認できます。","可以在其他筛选器中查看 {count} 条通知。","可以在其他篩選器中查看 {count} 則通知。","Puedes consultar {count} alertas en otros filtros.","Vous pouvez consulter {count} alertes dans d'autres filtres."],
  otherAlertOne: ["다른 필터에서 {count}건을 확인할 수 있습니다.","You can check {count} alert in other filters.","他のフィルターで{count}件を確認できます。","可以在其他筛选器中查看 {count} 条通知。","可以在其他篩選器中查看 {count} 則通知。","Puedes consultar {count} alerta en otros filtros.","Vous pouvez consulter {count} alerte dans d'autres filtres."],
  alertsEmptyDescription: ["전략이 실행되면 체결, 복기, 정산 소식이 여기로 옵니다.","When strategies run, updates on fills, reviews, and settlements will arrive here.","戦略が実行されると、約定、振り返り、精算の通知がここに届きます。","策略运行时，成交、复盘与结算通知将发送至此处。","策略執行時，成交、複盤與結算通知將發送至此處。","Cuando se ejecuten las estrategias, aquí recibirás las novedades de ejecuciones, revisiones y liquidaciones.","Lorsque les stratégies sont exécutées, les notifications d'exécutions, de revues et de règlements arriveront ici."],
  justNow: ["방금 전","Just now","たった今","刚刚","剛剛","Hace un momento","À l'instant"],
  noReports: ["아직 보고서가 없습니다","No reports yet","レポートはまだありません","暂无报告","暫無報告","Aún no hay informes","Pas encore de rapports"],
  reportsEmptyDescription: ["전략이 실행된 뒤 첫 주가 지나면 주간 성과 보고서가 도착합니다. (시뮬레이션)","Weekly performance reports arrive after the first week of strategy execution. (Simulation)","戦略が実行されてから最初の1週間が経過すると、週間パフォーマンスレポートが届きます。（シミュレーション）","策略执行满一周后，周度绩效报告将送达。（模拟）","策略執行滿一週後，週度績效報告將送達。（模擬）","Los informes de rendimiento semanal llegarán tras la primera semana de ejecución de la estrategia. (Simulación)","Les rapports de performance hebdomadaires arrivent après la première semaine d'exécution de la stratégie. (Simulation)"],
  performanceReport: ["{period} 성과 보고서","{period} Performance Report","{period} パフォーマンスレポート","{period}绩效报告","{period}績效報告","Informe de rendimiento {period}","Rapport de performance {period}"],
  report: ["{period} 보고서","{period} Report","{period} レポート","{period}报告","{period}報告","Informe {period}","Rapport {period}"],
  reportSummary: ["{range}, 체결 {count}회, 승률 {winRate}","{range}, {count} fills, win rate {winRate}","{range}、約定{count}回、勝率{winRate}","{range}，成交 {count} 次，胜率 {winRate}","{range}，成交 {count} 次，勝率 {winRate}","{range}, {count} ejecuciones, tasa de acierto {winRate}","{range}, {count} exécutions, taux de réussite {winRate}"],
  reportSummaryOne: ["{range}, 체결 {count}회, 승률 {winRate}","{range}, {count} fill, win rate {winRate}","{range}、約定{count}回、勝率{winRate}","{range}，成交 {count} 次，胜率 {winRate}","{range}，成交 {count} 次，勝率 {winRate}","{range}, {count} ejecución, tasa de acierto {winRate}","{range}, {count} exécution, taux de réussite {winRate}"],
  weekly: ["주간","Weekly","週間","周度","週度","Semanal","Hebdomadaire"],
  monthly: ["월간","Monthly","月間","月度","月度","Mensual","Mensuel"],
  rebateScope: ["계정 전체 범위, UID 파트너 적립 (시뮬레이션)","Account-wide scope, UID partner accumulation (Simulation)","アカウント全体範囲、UIDパートナー積立（シミュレーション）","账户全部范围，UID 合作伙伴累计（模拟）","帳戶全部範圍，UID 合作夥伴累計（模擬）","Alcance de toda la cuenta, acumulación de socios de UID (Simulación)","Périmètre global du compte, cumul partenaire UID (Simulation)"],
  feeRebate: ["수수료 적립","Fee rebates","手数料還元","手续费返佣","手續費返佣","Reembolsos de comisiones","Remboursements de frais"],
  allHistory: ["전체 내역 보기","View all history","全履歴を表示","查看全部记录","查看全部記錄","Ver todo el historial","Voir tout l'historique"],
  location: ["현재 위치","Current location","現在位置","当前位置","目前位置","Ubicación actual","Emplacement actuel"],
  myTrading: ["AI 트레이딩","AI trading","AIトレーディング","AI交易","AI交易","Trading con IA","Trading IA"],
  reviewMissing: ["복기 리포트를 찾을 수 없습니다","Review report not found","振り返りレポートが見つかりません","未找到复盘报告","未找到複盤報告","No se puede encontrar el informe de revisión","Rapport de revue introuvable"],
  reportMissing: ["보고서를 찾을 수 없습니다","Report not found","レポートが見つかりません","未找到报告","未找到報告","No se puede encontrar el informe","Rapport introuvable"],
  stopDescription: ["손절 규칙이 손실을 제한한 거래입니다.","Trade where the stop-loss rule limited losses.","損切りルールにより損失が制限された取引です。","通过止损规则限制了损失的交易。","透過止損規則限制了損失的交易。","Operación en la que la regla de stop loss limitó las pérdidas.","Transaction où la règle de stop loss a limité les pertes."],
  profitDescription: ["익절 규칙으로 청산된 거래예요.","Trade closed by take-profit rule.","利確ルールにより決済された取引です。","通过止盈规则平仓的交易。","透過止盈規則平倉的交易。","Operación cerrada por la regla de take profit.","Transaction clôturée par la règle de take profit."],
  timeDescription: ["시간 조건으로 청산된 거래예요.","Trade closed by time condition.","時間条件により決済された取引です。","通过时间条件平仓的交易。","透過時間條件平倉的交易。","Operación cerrada por condición de tiempo.","Transaction clôturée par condition temporelle."],
  reviewTitle: ["{asset} {kind} 복기","{asset} {kind} Review","{asset} {kind} 振り返り","{asset} {kind} 复盘","{asset} {kind} 複盤","Revisión de {asset} {kind}","Revue {asset} {kind}"],
  toReport: ["{period} 보고서로","To {period} Report","{period} レポートへ","前往 {period} 报告","前往 {period} 報告","Ir al informe {period}","Vers le rapport {period}"],
  realizedLoss: ["실현 손익, 손실 제한","Realized PnL, loss limited","実現損益、損失制限","已实现盈亏，限制损失","已實現盈虧，限制損失","PyG realizado, pérdida limitada","PnL réalisé, perte limitée"],
  realizedRule: ["실현 손익, 규칙 작동","Realized PnL, rule triggered","実現損益、ルール作動","已实现盈亏，规则触发","已實現盈虧，規則觸發","PyG realizado, regla activada","PnL réalisé, règle déclenchée"],
  category: ["구분","Category","区分","类别","類別","Categoría","Catégorie"],
  causality: ["TETH 의 인과 분석","TETH Causal Analysis","TETHの因果分析","TETH 因果分析","TETH 因果分析","Análisis causal de TETH","Analyse causale de TETH"],
  engineSignals: ["규칙 엔진 신호 기준","Based on rule engine signals","ルールエンジンシグナル基準","基于规则引擎信号","基於規則引擎信號","Según señales del motor de reglas","Basé sur les signaux du moteur de règles"],
  strategyDetail: ["이 전략 상세로","To strategy details","この戦略の詳細へ","查看该策略详情","查看該策略詳情","A los detalles de esta estrategia","Aux détails de cette stratégie"],
  stopLoss: ["손절","Stop Loss","損切り","止损","止損","Stop Loss","Stop Loss"],
  takeProfit: ["익절","Take Profit","利確","止盈","止盈","Take Profit","Take Profit"],
  timedExit: ["시간 청산","Timed Exit","時間決済","定时平仓","定時平倉","Salida por tiempo","Sortie programmée"],
  entryReason: ["진입 근거","Entry Reason","エントリー根拠","入场依据","入場依據","Motivo de entrada","Raison d'entrée"],
  exitReason: ["청산 근거","Exit Reason","決済根拠","出场依据","出場依據","Motivo de salida","Raison de sortie"],
  lossCause: ["손실 원인","Loss Cause","損失原因","亏损原因","虧損原因","Causa de la pérdida","Cause de la perte"],
  ruleAssessment: ["규칙 평가","Rule Assessment","ルール評価","规则评估","規則評估","Evaluación de la regla","Évaluation de la règle"],
  nextSuggestion: ["다음 제안","Next Suggestion","次の提案","下一步建议","下一步建議","Siguiente sugerencia","Suggestion suivante"],
  periodPnl: ["기간 합산 손익","Total Period PnL","期間合算損益","期间累计盈亏","期間累計盈虧","PyG total del período","PnL total de la période"],
  fills: ["체결","Fills","約定","成交","成交","Ejecuciones","Exécutions"],
  fillCount: ["{count}회","{count} fills","{count}回","{count}次","{count}次","{count} ejecuciones","{count} exécutions"],
  fillOne: ["{count}회","{count} fill","{count}回","{count}次","{count}次","{count} ejecución","{count} exécution"],
  winRate: ["승률","Win Rate","勝率","胜率","勝率","Tasa de acierto","Taux de réussite"],
  periodReviews: ["기간 체결 복기","Period Trade Reviews","期間約定の振り返り","期间成交复盘","期間成交複盤","Revisiones de operaciones del período","Revues d'exécutions de la période"],
  none: ["없음","None","なし","无","無","Ninguno","Aucun"],
  noReviews: ["현재 조회 가능한 복기가 없습니다","No trade reviews currently available","現在照会可能な振り返りはありません","当前暂无可查询的复盘","目前暫無可查詢的複盤","No hay revisiones disponibles actualmente","Aucune revue disponible pour le moment"],
  reviewsExpired: ["이 기간의 복기 리포트가 보관 기간을 지나 정리됐습니다. 요약 수치는 위에 그대로 남아 있습니다.","Review reports for this period have expired and been cleaned up. Summary metrics remain above.","この期間の振り返りレポートは保管期間を経過したため整理されました。要約の数値は上記にそのまま残っています。","该时期的复盘报告已过保留期并已清理。汇总数据仍保留在上方。","該時期的複盤報告已過保留期並已清理。彙總數據仍保留在上方。","Los informes de revisión de este período superaron el plazo de conservación y se limpiaron. Las cifras resumidas se mantienen arriba.","Les rapports de revue de cette période ont dépassé la durée de conservation et ont été supprimés. Les chiffres de synthèse restent inchangés ci-dessus."],
  allRebates: ["정산 내역 보기 (전체)","View Settlement History (All)","精算履歴を見る（全体）","查看结算记录（全部）","查看結算記錄（全部）","Ver historial de liquidación (completo)","Voir l'historique des règlements (tout)"],
} as const satisfies Record<string, Translations>

export type AccountActivityCopyKey = keyof typeof accountActivityCopy
export function accountActivityText(language: ClientLanguage, key: AccountActivityCopyKey, values: Readonly<Record<string, string>> = {}): string {
  return accountActivityCopy[key][column[language]].replace(/\{(\w+)\}/g, (slot, name: string) => Object.hasOwn(values, name) ? values[name] : slot)
}
