import type { ClientLanguage } from './client-preferences'
import { researchStaticText } from './client-research-static-content-copy'

type Row = readonly [string, string, string, string, string, string, string]
const column = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const
/** Chart interface and original static simulation copy, never supplied prose or identifiers. */
export const researchChartUiCopy = {
  back: ['{title}로 돌아가기', 'Return to {title}', '{title}に戻る', '返回{title}', '返回{title}', 'Volver a {title}', 'Retour à {title}'],
  ask: ['{title}에 질문', 'Ask about {title}', '{title}について質問', '询问{title}', '詢問{title}', 'Preguntar sobre {title}', 'Question sur {title}'],
  analysis: ['{title} 차트 분석', '{title} chart analysis', '{title}のチャート分析', '{title}图表分析', '{title}圖表分析', 'Análisis gráfico de {title}', 'Analyse graphique de {title}'],
  thread: ['{title} 대화 기록', '{title} conversation history', '{title}の会話履歴', '{title}对话记录', '{title}對話記錄', 'Conversación de {title}', 'Conversation de {title}'],
  bar: ['{count}번째 봉', 'Candle {count}', '{count}本目の足', '第{count}根K线', '第{count}根K線', 'Vela {count}', 'Bougie {count}'],
  trade: ['거래 {count}', 'Trade {count}', '取引{count}', '交易{count}', '交易{count}', 'Operación {count}', 'Transaction {count}'],
  tradeQuestion: ['거래 {count}에 질문하기', 'Ask about trade {count}', '取引{count}について質問', '询问交易{count}', '詢問交易{count}', 'Preguntar sobre la operación {count}', 'Question sur la transaction {count}'],
  tradeAria: ['거래 {count}, {entry} 매수, {exit} 매도, {reason}, {pnl}', 'Trade {count}, buy {entry}, sell {exit}, {reason}, {pnl}', '取引{count}、{entry}買い、{exit}売り、{reason}、{pnl}', '交易{count}，{entry}买入，{exit}卖出，{reason}，{pnl}', '交易{count}，{entry}買入，{exit}賣出，{reason}，{pnl}', 'Operación {count}, compra {entry}, venta {exit}, {reason}, {pnl}', 'Transaction {count}, achat {entry}, vente {exit}, {reason}, {pnl}'],
  chartAria: ['{title} {mode} 및 거래 손익 차트', '{title} {mode} and trade profit/loss chart', '{title}の{mode}と取引損益チャート', '{title}{mode}及交易盈亏图表', '{title}{mode}及交易損益圖表', 'Gráfico de {title}: {mode} y resultados de operaciones', 'Graphique de {title} : {mode} et résultats des transactions'],
  fillAria: ['{side} {time} UTC, 체결가 {price}, 거래 {id}', '{side} {time} UTC, execution price {price}, trade {id}', '{side} {time} UTC、約定価格{price}、取引{id}', '{side} {time} UTC，成交价{price}，交易{id}', '{side} {time} UTC，成交價{price}，交易{id}', '{side} {time} UTC, precio de ejecución {price}, operación {id}', '{side} {time} UTC, prix d’exécution {price}, transaction {id}'],
  skip: ['결과 재생 건너뛰기', 'Skip result replay', '結果の再生をスキップ', '跳过结果回放', '跳過結果重播', 'Omitir reproducción de resultados', 'Passer la relecture des résultats'],
  skipLabel: ['Skip', 'Skip', 'スキップ', '跳过', '跳過', 'Omitir', 'Passer'],
  skipResults: ['Skip · 결과 보기', 'Skip · View results', 'スキップ · 結果を見る', '跳过 · 查看结果', '跳過 · 查看結果', 'Omitir · Ver resultados', 'Passer · Voir les résultats'],
  replay: ['거래 재생', 'Replay trades', '取引を再生', '回放交易', '重播交易', 'Reproducir operaciones', 'Rejouer les transactions'],
  resultReplay: ['결과 재생', 'Result replay', '結果の再生', '结果回放', '結果重播', 'Reproducción de resultados', 'Relecture des résultats'],
  choosePanel: ['분석 화면 선택', 'Choose analysis panel', '分析画面を選択', '选择分析界面', '選擇分析介面', 'Elegir panel de análisis', 'Choisir le panneau d’analyse'],
  chartTrades: ['차트·거래', 'Chart · Trades', 'チャート・取引', '图表·交易', '圖表·交易', 'Gráfico · Operaciones', 'Graphique · Transactions'],
  chartFills: ['차트·체결', 'Chart · Executions', 'チャート・約定', '图表·成交', '圖表·成交', 'Gráfico · Ejecuciones', 'Graphique · Exécutions'],
  continueConversation: ['대화 이어가기', 'Continue conversation', '会話を続ける', '继续对话', '繼續對話', 'Continuar conversación', 'Poursuivre la conversation'],
  chartDisplay: ['차트 표시', 'Chart display', 'チャート表示', '图表显示', '圖表顯示', 'Visualización del gráfico', 'Affichage du graphique'],
  price: ['가격', 'Price', '価格', '价格', '價格', 'Precio', 'Prix'],
  fit: ['전체 구간 보기', 'View full range', '全区間を見る', '查看完整区间', '查看完整區間', 'Ver intervalo completo', 'Voir toute la période'],
  tradePnl: ['거래 손익 (%)', 'Trade profit/loss (%)', '取引損益（%）', '交易盈亏（%）', '交易損益（%）', 'Resultado de operaciones (%)', 'Résultat des transactions (%)'],
  priceSample: ['가격 표본 · 봉 번호 기준', 'Price sample · Candle index', '価格標本・足番号基準', '价格样本·K线编号', '價格樣本·K線編號', 'Muestra de precios · Índice de vela', 'Échantillon de prix · Numéro de bougie'],
  priceAndTrades: ['가격 표본과 거래 시점', 'Price sample and trade times', '価格標本と取引時点', '价格样本和交易时点', '價格樣本和交易時點', 'Muestra de precios y momentos de operación', 'Échantillon de prix et instants de transaction'],
  chartFailure: ['차트를 표시하지 못했습니다. 아래 거래 기록과 문서로 확인할 수 있습니다.', 'Could not display the chart. Check the trade records below and the document.', 'チャートを表示できませんでした。下の取引記録と文書で確認できます。', '无法显示图表。可查看下方交易记录和文档。', '無法顯示圖表。可查看下方交易記錄和文件。', 'No se pudo mostrar el gráfico. Consulta las operaciones y el documento.', 'Impossible d’afficher le graphique. Consultez les transactions et le document.'],
  buy: ['BUY 매수', 'BUY Buy', 'BUY 買い', 'BUY 买入', 'BUY 買入', 'BUY Compra', 'BUY Achat'],
  sell: ['SELL 매도', 'SELL Sell', 'SELL 売り', 'SELL 卖出', 'SELL 賣出', 'SELL Venta', 'SELL Vente'],
  sameSample: ['문서와 동일한 가격 표본 · OHLC/거래량 미제공', 'Same price sample as document · OHLC/volume not supplied', '文書と同じ価格標本・OHLC/出来高は未提供', '与文档相同的价格样本·未提供OHLC/成交量', '與文件相同的價格樣本·未提供OHLC/成交量', 'Misma muestra que el documento · OHLC/volumen no suministrados', 'Même échantillon que le document · OHLC/volume non fournis'],
  tradeHistory: ['거래 기록', 'Trade records', '取引記録', '交易记录', '交易記錄', 'Registro de operaciones', 'Registre des transactions'],
  previousTrade: ['이전 거래', 'Previous trade', '前の取引', '上一笔交易', '上一筆交易', 'Operación anterior', 'Transaction précédente'],
  nextTrade: ['다음 거래', 'Next trade', '次の取引', '下一笔交易', '下一筆交易', 'Operación siguiente', 'Transaction suivante'],
  chooseTrade: ['거래 선택', 'Choose trade', '取引を選択', '选择交易', '選擇交易', 'Elegir operación', 'Choisir une transaction'],
  tradeColumn: ['거래', 'Trade', '取引', '交易', '交易', 'Operación', 'Transaction'],
  buyPoint: ['매수 지점', 'Buy point', '買い時点', '买入点', '買入點', 'Punto de compra', 'Point d’achat'],
  sellPoint: ['매도 지점', 'Sell point', '売り時点', '卖出点', '賣出點', 'Punto de venta', 'Point de vente'],
  exitReason: ['청산 사유', 'Exit reason', '決済理由', '离场原因', '出場原因', 'Motivo de salida', 'Motif de sortie'],
  holdingEnded: ['보유 기간 종료', 'Holding period ended', '保有期間終了', '持有期结束', '持有期結束', 'Fin del periodo de tenencia', 'Fin de la durée de détention'],
  researchConversation: ['연구 대화 이어가기', 'Continue research conversation', '研究の会話を続ける', '继续研究对话', '繼續研究對話', 'Continuar conversación de investigación', 'Poursuivre la conversation de recherche'],
  threadIntro: ['문서를 읽으며 나누던 대화가 이어집니다. 거래를 선택해 함께 확인하세요.', 'Continue the conversation from the document. Select a trade to review together.', '文書を読みながらの会話を続けます。取引を選択して一緒に確認してください。', '继续阅读文档时的对话。选择一笔交易共同检查。', '繼續閱讀文件時的對話。選擇一筆交易共同檢查。', 'Continúa la conversación del documento. Selecciona una operación para revisarla.', 'Poursuivez la conversation du document. Sélectionnez une transaction à examiner ensemble.'],
  clearTrade: ['거래 참고대상 해제', 'Clear trade reference', '参照取引を解除', '清除交易参考', '清除交易參考', 'Quitar referencia de operación', 'Retirer la référence de transaction'],
  placeholder: ['이 결과에 대해 이어서 물어보세요', 'Ask a follow-up about this result', 'この結果について続けて質問してください', '继续询问此结果', '繼續詢問此結果', 'Pregunta más sobre este resultado', 'Posez une autre question sur ce résultat'],
  send: ['차트 질문 보내기', 'Send chart question', 'チャートの質問を送信', '发送图表问题', '傳送圖表問題', 'Enviar pregunta sobre el gráfico', 'Envoyer la question sur le graphique'],
  fillHistory: ['체결 기록', 'Execution records', '約定記録', '成交记录', '成交記錄', 'Registro de ejecuciones', 'Registre des exécutions'],
  fillQuestion: ['선택한 체결에 질문하기', 'Ask about selected execution', '選択した約定について質問', '询问选中的成交', '詢問選取的成交', 'Preguntar sobre la ejecución elegida', 'Question sur l’exécution sélectionnée'],
  fillDirection: ['체결 방향', 'Execution side', '約定方向', '成交方向', '成交方向', 'Lado de ejecución', 'Sens de l’exécution'],
  all: ['전체', 'All', 'すべて', '全部', '全部', 'Todas', 'Toutes'],
  searchLabel: ['체결 ID 또는 거래 ID 검색', 'Search execution or trade ID', '約定IDまたは取引IDを検索', '搜索成交ID或交易ID', '搜尋成交ID或交易ID', 'Buscar ID de ejecución u operación', 'Rechercher un ID d’exécution ou de transaction'],
  search: ['체결·거래 ID 검색', 'Search execution/trade ID', '約定・取引IDを検索', '搜索成交/交易ID', '搜尋成交/交易ID', 'Buscar ID de ejecución/operación', 'Rechercher un ID d’exécution/transaction'],
  chooseFill: ['체결 선택', 'Choose execution', '約定を選択', '选择成交', '選擇成交', 'Elegir ejecución', 'Choisir une exécution'],
  side: ['구분', 'Side', '区分', '类别', '類別', 'Lado', 'Sens'],
  fillTime: ['체결 시각 · UTC', 'Execution time · UTC', '約定時刻 · UTC', '成交时间·UTC', '成交時間·UTC', 'Hora de ejecución · UTC', 'Heure d’exécution · UTC'],
  fillPrice: ['체결가', 'Execution price', '約定価格', '成交价', '成交價', 'Precio de ejecución', 'Prix d’exécution'],
  tradeId: ['거래 ID', 'Trade ID', '取引ID', '交易ID', '交易ID', 'ID de operación', 'ID de transaction'],
  noMatchingFills: ['검색 조건에 맞는 체결이 없습니다.', 'No executions match your search.', '検索条件に一致する約定はありません。', '没有符合搜索条件的成交。', '沒有符合搜尋條件的成交。', 'No hay ejecuciones que coincidan.', 'Aucune exécution ne correspond à la recherche.'],
  noFills: ['표시할 체결 기록이 없습니다.', 'No execution records to display.', '表示する約定記録はありません。', '没有可显示的成交记录。', '沒有可顯示的成交記錄。', 'No hay ejecuciones que mostrar.', 'Aucune exécution à afficher.'],
  fillPages: ['체결 페이지', 'Execution pages', '約定のページ', '成交分页', '成交分頁', 'Páginas de ejecuciones', 'Pages d’exécutions'],
  firstPage: ['체결 첫 페이지', 'First execution page', '約定の最初のページ', '成交首页', '成交首頁', 'Primera página de ejecuciones', 'Première page d’exécutions'],
  previousPage: ['체결 이전 페이지', 'Previous execution page', '約定の前のページ', '成交上一页', '成交上一頁', 'Página anterior de ejecuciones', 'Page précédente d’exécutions'],
  nextPage: ['체결 다음 페이지', 'Next execution page', '約定の次のページ', '成交下一页', '成交下一頁', 'Página siguiente de ejecuciones', 'Page suivante d’exécutions'],
  lastPage: ['체결 마지막 페이지', 'Last execution page', '約定の最後のページ', '成交末页', '成交末頁', 'Última página de ejecuciones', 'Dernière page d’exécutions'],
  clearFill: ['체결 참고대상 해제', 'Clear execution reference', '参照約定を解除', '清除成交参考', '清除成交參考', 'Quitar referencia de ejecución', 'Retirer la référence d’exécution'],
  sending: ['전송 중…', 'Sending…', '送信中…', '正在发送…', '正在傳送…', 'Enviando…', 'Envoi…'],
  sendError: ['질문을 보내지 못했습니다. 입력 내용은 유지됩니다. 다시 전송해주세요.', 'Could not send the question. Your input is preserved. Send it again.', '質問を送信できませんでした。入力内容は保持されています。再送信してください。', '无法发送问题。输入已保留，请重新发送。', '無法傳送問題。輸入已保留，請重新傳送。', 'No se pudo enviar. Tu texto se conserva; envíalo de nuevo.', 'Impossible d’envoyer la question. Votre saisie est conservée ; renvoyez-la.'],
  strategyResult: ['전략 검증 결과', 'Strategy validation result', '戦略検証結果', '策略验证结果', '策略驗證結果', 'Resultado de validación de estrategia', 'Résultat de validation de stratégie'],
  ordinal: ['{count}차, 수수료 0.2% 반영, 시뮬레이션', 'Run {count}, 0.2% fees included, simulation', '{count}回目、手数料0.2%反映、シミュレーション', '第{count}次，计入0.2%手续费，模拟', '第{count}次，計入0.2%手續費，模擬', 'Prueba {count}, comisión 0,2% incluida, simulación', 'Essai {count}, frais 0,2 % inclus, simulation'],
  scorePass: ['실행 기준 통과', 'Execution threshold passed', '実行基準に合格', '通过执行标准', '通過執行標準', 'Umbral de ejecución superado', 'Seuil d’exécution atteint'],
  scoreFail: ['기준 80점 미달', 'Below the 80-point threshold', '基準80点未満', '低于80分标准', '低於80分標準', 'Por debajo del umbral de 80 puntos', 'Sous le seuil de 80 points'],
  validationReturn: ['검증 수익', 'Validation return', '検証リターン', '验证收益', '驗證報酬', 'Rentabilidad de validación', 'Rendement de validation'],
  tradeCount: ['거래 수', 'Trade count', '取引数', '交易次数', '交易次數', 'Número de operaciones', 'Nombre de transactions'],
  countTrades: ['{count}회', '{count} trades', '{count}回', '{count}次', '{count}次', '{count} operaciones', '{count} transactions'],
  details: ['상세 조건 펼치기', 'Expand detailed conditions', '詳細条件を展開', '展开详细条件', '展開詳細條件', 'Ver condiciones detalladas', 'Afficher les conditions détaillées'],
  interval: ['{pair} · 요청 간격 {interval}', '{pair} · Requested interval {interval}', '{pair} · 指定間隔{interval}', '{pair} · 请求间隔{interval}', '{pair} · 請求間隔{interval}', '{pair} · Intervalo solicitado {interval}', '{pair} · Intervalle demandé {interval}'],
  entry: ['진입: RSI {rsi} 이하 눌림 후 반등{filter}', 'Entry: rebound after a dip with RSI ≤ {rsi}{filter}', 'エントリー：RSI{rsi}以下の押し目後の反発{filter}', '入场：RSI≤{rsi}回落后反弹{filter}', '進場：RSI≤{rsi}回落後反彈{filter}', 'Entrada: rebote tras caída con RSI ≤ {rsi}{filter}', 'Entrée : rebond après repli avec RSI ≤ {rsi}{filter}'],
  filter: [' + 추세 필터', ' + trend filter', ' + トレンドフィルター', ' + 趋势过滤', ' + 趨勢篩選', ' + filtro de tendencia', ' + filtre de tendance'],
  exit: ['청산: 손절 {stop}%{target}, 최대 보유 25봉', 'Exit: stop loss {stop}%{target}, maximum holding 25 candles', '決済：損切り{stop}%{target}、最大保有25本', '离场：止损{stop}%{target}，最长持有25根K线', '出場：停損{stop}%{target}，最長持有25根K線', 'Salida: límite de pérdidas {stop}%{target}, máximo 25 velas', 'Sortie : seuil de perte {stop}%{target}, durée maximale 25 bougies'],
  takeProfit: [', 익절 +{target}%', ', take profit +{target}%', '、利確+{target}%', '，止盈+{target}%', '，停利+{target}%', ', objetivo +{target}%', ', objectif +{target}%'],
  noTakeProfit: [', 익절 없음', ', no take profit', '、利確なし', '，无止盈', '，無停利', ', sin objetivo de beneficio', ', sans objectif de gain'],
  simulationBoundary: ['구간: 원본 공통 합성 일봉. 요청 간격과 관계없이 같은 일봉으로 계산합니다. 판정·진입·기간 청산은 봉 종가, 손절·익절은 규칙가 가정입니다. 일중 변동·갭·슬리피지는 반영하지 않습니다.', 'Period: the original shared synthetic daily candles. The same daily candles are used regardless of requested interval. Assessment, entry and timed exits use candle closes; stop loss and take profit assume rule prices. Intraday moves, gaps and slippage are excluded.', '区間：原本の共通合成日足。指定間隔に関係なく同じ日足で計算します。判定・エントリー・期間決済は終値、損切り・利確はルール価格を仮定します。日中変動・ギャップ・スリッページは含みません。', '区间：原始共用合成日K线。无论请求间隔，均使用同一日K线计算。判定、入场和定期离场采用收盘价；止损和止盈假设规则价格。不计日内波动、跳空及滑点。', '區間：原始共用合成日K線。無論請求間隔，均使用同一日K線計算。判定、進場和定期出場採用收盤價；停損和停利假設規則價格。不計日內波動、跳空及滑價。', 'Periodo: velas diarias sintéticas originales, idénticas para cualquier intervalo solicitado. Evaluación, entrada y salida temporal usan cierres; los límites asumen precios reglados. No se incluyen movimientos intradía, huecos ni deslizamiento.', 'Période : bougies journalières synthétiques originales, identiques quel que soit l’intervalle demandé. Évaluation, entrée et sortie temporelle utilisent les clôtures ; les seuils supposent des prix réglés. Variations intrajournalières, écarts et glissement sont exclus.'],
  syntheticBoundary: ['원본 합성 데이터 미리보기입니다. 실제 시장의 검증·승인이나 수익 보장이 아닙니다.', 'Preview of the original synthetic data, not real-market validation, approval or a profit guarantee.', '原本の合成データプレビューです。実市場の検証・承認や利益保証ではありません。', '这是原始合成数据预览，不是实际市场验证、批准或收益保证。', '這是原始合成資料預覽，不是實際市場驗證、批准或報酬保證。', 'Vista de datos sintéticos originales, no validación o aprobación del mercado real ni garantía de ganancias.', 'Aperçu des données synthétiques originales, non une validation ou approbation du marché réel ni une garantie de gain.'],
  conditionalPass: [' 파라미터 민감도와 시장 국면별 검증을 거치지 않은 조건부 통과입니다.', ' Conditional pass without parameter-sensitivity or market-regime validation.', ' パラメーター感度や相場局面別の検証を経ていない条件付き合格です。', ' 这是未经参数敏感度或市场状态验证的条件性通过。', ' 這是未經參數敏感度或市場狀態驗證的條件性通過。', ' Aprobación condicional sin validar sensibilidad ni regímenes de mercado.', ' Réussite conditionnelle sans validation de sensibilité ni des régimes de marché.'],
  passedReply: ['기준을 통과했어요. 리포트도 여기서 바로 보여드릴게요.', 'The threshold was passed. The report is shown here too.', '基準に合格しました。レポートもここに表示します。', '已通过标准，报告也会直接显示在这里。', '已通過標準，報告也會直接顯示在這裡。', 'Se superó el umbral. El informe también se muestra aquí.', 'Le seuil a été atteint. Le rapport s’affiche aussi ici.'],
  strategyReport: ['전략 리포트', 'Strategy report', '戦略レポート', '策略报告', '策略報告', 'Informe de estrategia', 'Rapport de stratégie'],
  reportOrdinal: ['검증 {count}차 기준', 'Based on validation run {count}', '検証{count}回目基準', '基于第{count}次验证', '基於第{count}次驗證', 'Según la validación {count}', 'Selon la validation {count}'],
  loadFailed: ['차트를 불러오지 못했어요. 검증 지표와 조건은 위에서 확인할 수 있어요.', 'Could not load the chart. Check validation metrics and conditions above.', 'チャートを読み込めませんでした。上の検証指標と条件を確認できます。', '无法加载图表，可在上方查看验证指标和条件。', '無法載入圖表，可在上方查看驗證指標和條件。', 'No se pudo cargar el gráfico. Consulta métricas y condiciones arriba.', 'Impossible de charger le graphique. Consultez les indicateurs et conditions ci-dessus.'],
  loading: ['차트 불러오는 중', 'Loading chart', 'チャートを読み込み中', '正在加载图表', '正在載入圖表', 'Cargando gráfico', 'Chargement du graphique'],
  explanation: ['전략 설명', 'Strategy explanation', '戦略説明', '策略说明', '策略說明', 'Descripción de estrategia', 'Explication de stratégie'],
  explained: ['100번 중 {wins}번 꼴로 이기는 전략이었고, 가장 안 좋았던 구간에서는 약 {loss}%까지 내려갔어요. 검증 구간 동안 총 {count}번 사고팔았습니다.', 'The strategy won about {wins} out of 100 times, falling by about {loss}% in the worst period. It traded {count} times during validation.', '100回中約{wins}回勝ち、最悪の区間で約{loss}%下落した戦略です。検証区間で合計{count}回売買しました。', '该策略约每100次赢{wins}次，最差区间下跌约{loss}%。验证区间共交易{count}次。', '該策略約每100次贏{wins}次，最差區間下跌約{loss}%。驗證區間共交易{count}次。', 'Ganó unas {wins} veces de cada 100 y cayó aproximadamente un {loss}% en el peor periodo. Operó {count} veces durante la validación.', 'La stratégie gagnait environ {wins} fois sur 100 et reculait d’environ {loss} % au pire. Elle a effectué {count} transactions pendant la validation.'],
  risks: ['위험 요소', 'Risk factors', 'リスク要因', '风险因素', '風險因素', 'Factores de riesgo', 'Facteurs de risque'],
  riskExplanation: ['하락 뒤 반등을 노리는 구조라 큰 추세 하락장에서는 신호가 약해질 수 있어요. 최악 구간에서는 약 {loss}%의 평가 손실을 견뎌야 했고, 시장 급변 시 검증 결과와 다르게 움직일 수 있습니다.', 'Because it targets rebounds after declines, signals may weaken in strong downtrends. The worst period required tolerating about {loss}% unrealized loss; sudden market changes may differ from validation results.', '下落後の反発を狙うため、大きな下降トレンドではシグナルが弱まる可能性があります。最悪の区間で約{loss}%の含み損に耐える必要があり、市場急変時は検証結果と異なる動きがあり得ます。', '由于捕捉下跌后反弹，强烈下行趋势中信号可能减弱。最差区间须承受约{loss}%浮亏；市场急变时可能与验证结果不同。', '由於捕捉下跌後反彈，強烈下行趨勢中訊號可能減弱。最差區間須承受約{loss}%浮虧；市場急變時可能與驗證結果不同。', 'Al buscar rebotes tras caídas, las señales pueden debilitarse en tendencias bajistas fuertes. El peor periodo exigió soportar cerca del {loss}% de pérdida latente; cambios bruscos pueden diferir de la validación.', 'Visant les rebonds après baisse, les signaux peuvent s’affaiblir en forte tendance baissière. Le pire passage exigeait de supporter environ {loss} % de perte latente ; un marché brusquement changeant peut différer de la validation.'],
  runStrategy: ['이 전략 실행하기', 'Run this strategy', 'この戦略を実行', '执行此策略', '執行此策略', 'Ejecutar esta estrategia', 'Exécuter cette stratégie'],
  planHint: ['현재 대화의 조건을 정리한 연구 계획', 'Research plan organizing this conversation’s conditions', '現在の会話の条件をまとめた研究計画', '整理当前对话条件的研究计划', '整理目前對話條件的研究計畫', 'Plan con las condiciones de esta conversación', 'Plan organisant les conditions de cette conversation'],
  openPlan: ['연구 계획서 크게 보기', 'Open full research plan', '研究計画を大きく表示', '打开完整研究计划', '開啟完整研究計畫', 'Abrir plan completo', 'Ouvrir le plan complet'],
  failedReply: ['실행 기준(80점)에는 아직 못 미쳐요. 추천 설정으로 조정하면 통과 가능성이 높아집니다.', 'It is still below the execution threshold of 80 points. Recommended settings increase the chance of passing.', '実行基準80点にはまだ達していません。推奨設定への調整で合格の可能性が高まります。', '尚未达到80分执行标准。调整为推荐设置可提高通过可能性。', '尚未達到80分執行標準。調整為推薦設定可提高通過可能性。', 'Aún no llega al umbral de 80 puntos. Los ajustes recomendados aumentan la posibilidad de superarlo.', 'Le seuil d’exécution de 80 points n’est pas encore atteint. Les réglages recommandés augmentent la probabilité de réussite.'],
  recommend: ['추천 설정으로 다시 검증', 'Revalidate with recommended settings', '推奨設定で再検証', '使用推荐设置重新验证', '使用推薦設定重新驗證', 'Revalidar con ajustes recomendados', 'Revalider avec les réglages recommandés'],
  edit: ['조건을 직접 수정할게요', 'Edit conditions myself', '条件を自分で修正', '自行修改条件', '自行修改條件', 'Modificar las condiciones', 'Modifier les conditions moi-même'],
  hourly: ['1시간봉', '1-hour candles', '1時間足', '1小时K线', '1小時K線', 'Velas de 1 hora', 'Bougies de 1 heure'],
  fourHourly: ['4시간봉', '4-hour candles', '4時間足', '4小时K线', '4小時K線', 'Velas de 4 horas', 'Bougies de 4 heures'],
  minute: ['1분봉', '1-minute candles', '1分足', '1分钟K线', '1分鐘K線', 'Velas de 1 minuto', 'Bougies de 1 minute'],
  fiveMinute: ['5분봉', '5-minute candles', '5分足', '5分钟K线', '5分鐘K線', 'Velas de 5 minutos', 'Bougies de 5 minutes'],
  fifteenMinute: ['15분봉', '15-minute candles', '15分足', '15分钟K线', '15分鐘K線', 'Velas de 15 minutos', 'Bougies de 15 minutes'],
  thirtyMinute: ['30분봉', '30-minute candles', '30分足', '30分钟K线', '30分鐘K線', 'Velas de 30 minutos', 'Bougies de 30 minutes'],
  research: ['Research', 'Research', '研究', '研究', '研究', 'Investigación', 'Recherche'],
  miniPriceCaption: ['가격, 거래 시점, 봉인 구간', 'Prices, trade times and sealed period', '価格・取引時点・封印区間', '价格、交易时点和封存区间', '價格、交易時點和封存區間', 'Precios, operaciones y periodo sellado', 'Prix, transactions et période scellée'],
  miniEquityCaption: ['자산 곡선 · 연구 구간', 'Equity curve · Research period', '資産曲線・研究区間', '资产曲线·研究区间', '資產曲線·研究區間', 'Curva de capital · Periodo de investigación', 'Courbe de capital · Période de recherche'],
  miniKeyboardHint: ['방향키로 표시된 가격 지점을 이동합니다. PageUp과 PageDown은 10개 지점, Home과 End는 처음과 끝으로 이동합니다. 가격 표본 간 봉 간격은 일정하지 않습니다.', 'Use arrow keys to move through displayed price points. PageUp and PageDown move 10 points; Home and End move to the first and last. Candle spacing between price samples is irregular.', '方向キーで表示価格の点を移動します。PageUpとPageDownは10点、HomeとEndは最初と最後へ移動します。価格標本間の足間隔は一定ではありません。', '使用方向键移动显示的价格点。PageUp和PageDown移动10个点，Home和End移至首尾。价格样本之间的K线间隔不均匀。', '使用方向鍵移動顯示的價格點。PageUp和PageDown移動10個點，Home和End移至首尾。價格樣本之間的K線間隔不均勻。', 'Usa las flechas para recorrer los puntos de precio. PageUp y PageDown avanzan 10 puntos; Home y End van al primero y último. El espaciado de velas es irregular.', 'Utilisez les flèches pour parcourir les points de prix. PageUp et PageDown déplacent de 10 points ; Home et End vont au premier et au dernier. L’espacement des bougies est irrégulier.'],
  miniEquityAria: ['{title} 자산 곡선', '{title} equity curve', '{title}の資産曲線', '{title}资产曲线', '{title}資產曲線', 'Curva de capital de {title}', 'Courbe de capital de {title}'],
  miniPriceAria: ['{title} 가격과 매수·매도 시점', '{title} prices and buy/sell times', '{title}の価格と売買時点', '{title}价格及买入/卖出时点', '{title}價格及買入/賣出時點', 'Precios y momentos de compra/venta de {title}', 'Prix et instants d’achat/vente de {title}'],
  miniSell: ['SELL 매도, 거래 손익 {pnl}', 'SELL Sell, trade profit/loss {pnl}', 'SELL 売り、取引損益{pnl}', 'SELL 卖出，交易盈亏{pnl}', 'SELL 賣出，交易損益{pnl}', 'SELL Venta, resultado {pnl}', 'SELL Vente, résultat {pnl}'],
  positionHeld: ['포지션 보유 중', 'Position held', 'ポジション保有中', '持仓中', '持倉中', 'Posición abierta', 'Position détenue'],
  researchPeriod: ['연구 구간', 'Research period', '研究区間', '研究区间', '研究區間', 'Periodo de investigación', 'Période de recherche'],
  initialEquity: ['시작 자산', 'Initial equity', '開始資産', '初始资产', '初始資產', 'Capital inicial', 'Capital initial'],
  sealedLabel: ['HOLDOUT', 'HOLDOUT', 'ホールドアウト', '留出区间', '保留區間', 'RESERVA', 'RÉSERVE'],
} as const satisfies Record<string, Row>

const researchChartSingularCopy: Readonly<Partial<Record<keyof typeof researchChartUiCopy, Row>>> = {
  countTrades: ["{count}회","{count} trade","{count}回","{count}次","{count}次","{count} operación","{count} transaction"],
  explained: ["100번 중 {wins}번 꼴로 이기는 전략이었고, 가장 안 좋았던 구간에서는 약 {loss}%까지 내려갔어요. 검증 구간 동안 총 {count}번 사고팔았습니다.","The strategy won about {wins} out of 100 times, falling by about {loss}% in the worst period. It traded {count} time during validation.","100回中約{wins}回勝ち、最悪の区間で約{loss}%下落した戦略です。検証区間で合計{count}回売買しました。","该策略约每100次赢{wins}次，最差区间下跌约{loss}%。验证区间共交易{count}次。","該策略約每100次贏{wins}次，最差區間下跌約{loss}%。驗證區間共交易{count}次。","Ganó unas {wins} veces de cada 100 y cayó aproximadamente un {loss}% en el peor periodo. Operó {count} vez durante la validación.","La stratégie gagnait environ {wins} fois sur 100 et reculait d’environ {loss} % au pire. Elle a effectué {count} transaction pendant la validation."],
}

export function researchChartText(language: ClientLanguage, key: keyof typeof researchChartUiCopy, values: Record<string, string | number> = {}): string {
  const row = language !== 'ko' && new Intl.PluralRules(language).select(Number(values.count)) === 'one' ? researchChartSingularCopy[key] ?? researchChartUiCopy[key] : researchChartUiCopy[key]
  return row[column[language]].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token)
}
export function researchChartStaticText(value: string, language: ClientLanguage): string {
  const row = Object.values(researchChartUiCopy).find(row => row[0] === value)
  return row ? row[column[language]] : researchStaticText(value, language)
}
