import type { ClientLanguage } from './client-preferences'

/** Display-only source copy. Metric calculations and user-authored content are unchanged. */
const ko = {
  "닫기": "닫기",
  "작성자 {nick}": "작성자 {nick}",
  "검증 수익": "검증 수익",
  "TETH 점수": "TETH 점수",
  "최대 낙폭 (MDD)": "최대 낙폭 (MDD)",
  "손익비 (Profit Factor)": "손익비 (Profit Factor)",
  "평균 보유일": "평균 보유일",
  "거래 수": "거래 수",
  "전체 기간": "전체 기간",
  "최근 2년": "최근 2년",
  "최근 1년": "최근 1년",
  "전체": "전체",
  "검증 기간": "검증 기간",
  ", {period} 검증, 거래 {count}회": ", {period} 검증, 거래 {count}회",
  "검증 수익률 ({period})": "검증 수익률 ({period})",
  "TETH 점수, 근거 보기": "TETH 점수, 근거 보기",
  "승률 ({count}전 {wins}승 {losses}패)": "승률 ({count}전 {wins}승 {losses}패)",
  "누적 수익 곡선": "누적 수익 곡선",
  "수수료 0.2% 반영": "수수료 0.2% 반영",
  "검증 성과 지표": "검증 성과 지표",
  "{period}, 지표를 누르면 뜻을 볼 수 있어요": "{period}, 지표를 누르면 뜻을 볼 수 있어요",
  "{days}일": "{days}일",
  "{count}회 (이익 {wins}, 손실 {losses})": "{count}회 (이익 {wins}, 손실 {losses})",
  "저장된 검증 성과": "저장된 검증 성과",
  "검증 곡선 없음. 저장된 요약 지표만 표시합니다.": "검증 곡선 없음. 저장된 요약 지표만 표시합니다.",
  "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.": "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.",
  "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.": "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.",
  "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.": "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.",
  "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.": "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.",
  "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.": "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.",
  "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.": "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.",
  "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.": "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.",
  "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.": "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.",
  "승률": "승률",
  "수익 (CAGR)": "수익 (CAGR)",
  "낙폭 방어": "낙폭 방어",
  "거래 활동": "거래 활동",
  "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.": "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.",
  "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.": "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.",
  "표본 4회 미만, 점수 35% 감점": "표본 4회 미만, 점수 35% 감점",
  "표본 6회 미만, 79점 상한": "표본 6회 미만, 79점 상한",
  "기여": "기여",
  "{points}점": "{points}점",
  "공유 전략 중앙값 {value}": "공유 전략 중앙값 {value}",
  "공유 전략 중앙값 {value} 대비 {position}": "공유 전략 중앙값 {value} 대비 {position}",
  "위": "위",
  "아래": "아래",
  "TETH 점수 {score}점 산출 근거": "TETH 점수 {score}점 산출 근거"
} as const

export type SharingDetailCopyKey = keyof typeof ko

export const CLIENT_SHARING_DETAIL_COPY: Record<ClientLanguage, Record<SharingDetailCopyKey, string>> = {
  ko,
  "en": {
  "닫기": "Close",
  "작성자 {nick}": "Author {nick}",
  "검증 수익": "Validation return",
  "TETH 점수": "TETH score",
  "최대 낙폭 (MDD)": "Maximum drawdown (MDD)",
  "손익비 (Profit Factor)": "Profit Factor",
  "평균 보유일": "Average holding days",
  "거래 수": "Trade count",
  "전체 기간": "All time",
  "최근 2년": "Past 2 years",
  "최근 1년": "Past 1 year",
  "전체": "All",
  "검증 기간": "Validation period",
  ", {period} 검증, 거래 {count}회": ", {period} validation, {count} trades",
  "검증 수익률 ({period})": "Validation return ({period})",
  "TETH 점수, 근거 보기": "TETH score, view breakdown",
  "승률 ({count}전 {wins}승 {losses}패)": "Win rate ({count} trades: {wins}W {losses}L)",
  "누적 수익 곡선": "Cumulative return curve",
  "수수료 0.2% 반영": "0.2% fee included",
  "검증 성과 지표": "Validation performance metrics",
  "{period}, 지표를 누르면 뜻을 볼 수 있어요": "{period}, click a metric to view its definition",
  "{days}일": "{days} days",
  "{count}회 (이익 {wins}, 손실 {losses})": "{count} trades (profit {wins}, loss {losses})",
  "저장된 검증 성과": "Saved validation performance",
  "검증 곡선 없음. 저장된 요약 지표만 표시합니다.": "No validation curve available. Showing saved summary metrics only.",
  "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.": "Validation figures are backtest results based on historical data and do not guarantee future returns.",
  "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.": "All figures are historical data validation simulations and do not guarantee future returns.",
  "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.": "Cumulative return when strategy rules were executed as-is over the selected validation period. 0.2% fee is included.",
  "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.": "A 4-axis weighted sum score (0–99) based on win rate, return, drawdown, and trading activity. Tap the score badge to view the breakdown by axis.",
  "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.": "The largest drop in asset value from its peak during the validation period. Calculated based on mark-to-market value during holding.",
  "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.": "Calculated by dividing total profits by total losses. A 1.5:1 ratio means making 1.5 for every 1 lost.",
  "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.": "Average holding period from entry to exit. If it exceeds 25 bars, the time-based exit rule is triggered.",
  "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.": "Number of executed trades during the validation period. A small sample size incurs a score penalty.",
  "승률": "Win rate",
  "수익 (CAGR)": "Return (CAGR)",
  "낙폭 방어": "Drawdown defense",
  "거래 활동": "Trading activity",
  "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.": "A weighted sum score of 0–99 across 4 axes: win rate, return, drawdown, and trading activity. You can see where this score comes from by looking at each axis. All values are calculated from validation simulations.",
  "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.": "Baseline range: win rate 35–60%, CAGR 0–6%, drawdown -25–-6%. Only 80 points or higher are eligible to run.",
  "표본 4회 미만, 점수 35% 감점": "Under 4 samples, 35% score deduction",
  "표본 6회 미만, 79점 상한": "Under 6 samples, capped at 79 points",
  "기여": "Contribution",
  "{points}점": "{points} pts",
  "공유 전략 중앙값 {value}": "Shared strategy median {value}",
  "공유 전략 중앙값 {value} 대비 {position}": "{position} vs. shared strategy median {value}",
  "위": "Above",
  "아래": "Below",
  "TETH 점수 {score}점 산출 근거": "Calculation basis for TETH score {score}"
},
  "ja": {
  "닫기": "閉じる",
  "작성자 {nick}": "作成者 {nick}",
  "검증 수익": "検証リターン",
  "TETH 점수": "TETHスコア",
  "최대 낙폭 (MDD)": "最大ドローダウン (MDD)",
  "손익비 (Profit Factor)": "損益比 (Profit Factor)",
  "평균 보유일": "平均保有日数",
  "거래 수": "取引数",
  "전체 기간": "全期間",
  "최근 2년": "過去2年",
  "최근 1년": "過去1年",
  "전체": "全て",
  "검증 기간": "検証期間",
  ", {period} 검증, 거래 {count}회": "、{period}検証、取引{count}回",
  "검증 수익률 ({period})": "検証リターン ({period})",
  "TETH 점수, 근거 보기": "TETHスコア、根拠を見る",
  "승률 ({count}전 {wins}승 {losses}패)": "勝率 ({count}戦{wins}勝{losses}敗)",
  "누적 수익 곡선": "累積収益曲線",
  "수수료 0.2% 반영": "手数料0.2%反映",
  "검증 성과 지표": "検証パフォーマンス指標",
  "{period}, 지표를 누르면 뜻을 볼 수 있어요": "{period}、指標をタップすると意味を確認できます",
  "{days}일": "{days}日",
  "{count}회 (이익 {wins}, 손실 {losses})": "{count}回 (利益{wins}、損失{losses})",
  "저장된 검증 성과": "保存された検証パフォーマンス",
  "검증 곡선 없음. 저장된 요약 지표만 표시합니다.": "検証曲線はありません。保存されたサマリー指標のみ表示します。",
  "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.": "検証数値は過去データに基づくバックテスト結果であり、将来の収益を保証するものではありません。",
  "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.": "すべての数値は過去データ検証シミュレーションであり、将来の収益を保証するものではありません。",
  "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.": "選択した検証期間で戦略ルールをそのまま実行した場合の累積収益率です。手数料0.2%が反映されています。",
  "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.": "勝率、収益、ドローダウン、取引活動の4軸による加重合計スコア（0〜99）です。スコアバッジを押すと軸ごとの根拠を確認できます。",
  "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.": "検証期間中に資産が高点から最も下落した幅です。保有中の評価額を基準に計算します。",
  "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.": "総利益を総損失で割った値です。1.5:1の場合、1の損失に対して1.5の利益を得たことを意味します。",
  "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.": "エントリーから決済までの平均保有期間です。25本を超えると期間決済ルールが実行されます。",
  "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.": "検証期間中に発生した約定回数です。サンプルが少ない場合はスコアにペナルティが適用されます。",
  "승률": "勝率",
  "수익 (CAGR)": "収益 (CAGR)",
  "낙폭 방어": "ドローダウン防御",
  "거래 활동": "取引活動",
  "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.": "勝率、収益、ドローダウン、取引活動の4軸を加重合算した0〜99点のスコアです。各軸を見ることでこのスコアの内訳が分かります。すべて検証シミュレーションの実際の計算値です。",
  "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.": "基準区間: 勝率 35〜60%、CAGR 0〜6%、ドローダウン -25〜-6%。80点以上のみ実行資格があります。",
  "표본 4회 미만, 점수 35% 감점": "サンプル4回未満、スコア35%減点",
  "표본 6회 미만, 79점 상한": "サンプル6回未満、上限79点",
  "기여": "寄与",
  "{points}점": "{points}点",
  "공유 전략 중앙값 {value}": "共有戦略中央値 {value}",
  "공유 전략 중앙값 {value} 대비 {position}": "共有戦略中央値 {value} に対して {position}",
  "위": "上",
  "아래": "下",
  "TETH 점수 {score}점 산출 근거": "TETHスコア {score}点の算出根拠"
},
  "zh-CN": {
  "닫기": "关闭",
  "작성자 {nick}": "作者 {nick}",
  "검증 수익": "验证收益",
  "TETH 점수": "TETH评分",
  "최대 낙폭 (MDD)": "最大回撤 (MDD)",
  "손익비 (Profit Factor)": "盈亏比 (Profit Factor)",
  "평균 보유일": "平均持仓天数",
  "거래 수": "交易次数",
  "전체 기간": "全部期间",
  "최근 2년": "近2年",
  "최근 1년": "近1年",
  "전체": "全部",
  "검증 기간": "验证期间",
  ", {period} 검증, 거래 {count}회": "，{period}验证，交易{count}次",
  "검증 수익률 ({period})": "验证收益 ({period})",
  "TETH 점수, 근거 보기": "TETH评分，查看依据",
  "승률 ({count}전 {wins}승 {losses}패)": "胜率 ({count}战{wins}胜{losses}负)",
  "누적 수익 곡선": "累计收益曲线",
  "수수료 0.2% 반영": "已计入0.2%手续费",
  "검증 성과 지표": "验证表现指标",
  "{period}, 지표를 누르면 뜻을 볼 수 있어요": "{period}，点击指标可查看说明",
  "{days}일": "{days}天",
  "{count}회 (이익 {wins}, 손실 {losses})": "{count}次 (盈利{wins}，亏损{losses})",
  "저장된 검증 성과": "已保存的验证表现",
  "검증 곡선 없음. 저장된 요약 지표만 표시합니다.": "暂无验证曲线。仅显示已保存的摘要指标。",
  "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.": "验证数据是基于历史数据的回测结果，不保证未来收益。",
  "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.": "所有数据均为历史数据验证模拟，不保证未来收益。",
  "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.": "在所选验证区间内按原样执行策略规则时的累计收益率。已计入0.2%手续费。",
  "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.": "基于胜率、收益、回撤和交易活跃度4个维度的加权综合评分（0~99）。点击评分徽章可查看各维度的计算依据。",
  "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.": "验证区间内资产相对高点的最大回撤幅度。根据持仓期间的评估净值计算。",
  "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.": "总盈利除以总亏损所得的值。1.5:1意味着每亏损1的同时盈利1.5。",
  "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.": "从入场到平仓的平均持仓周期。若超过25根K线，将触发时间平仓规则。",
  "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.": "验证区间内发生的成交次数。样本量较少时会对评分进行扣分惩罚。",
  "승률": "胜率",
  "수익 (CAGR)": "收益 (CAGR)",
  "낙폭 방어": "回撤防守",
  "거래 활동": "交易活跃度",
  "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.": "由胜率、收益、回撤、交易活跃度4个维度加权汇总的0~99分。通过各维度可了解该评分的来源。全部数值均为验证模拟的实际计算值。",
  "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.": "基准区间：胜率 35~60%，CAGR 0~6%，回撤 -25~-6%。80分以上才具备运行资格。",
  "표본 4회 미만, 점수 35% 감점": "样本少于4次，评分扣除35%",
  "표본 6회 미만, 79점 상한": "样本少于6次，上限79分",
  "기여": "贡献",
  "{points}점": "{points}分",
  "공유 전략 중앙값 {value}": "共享策略中位数 {value}",
  "공유 전략 중앙값 {value} 대비 {position}": "相对共享策略中位数 {value} {position}",
  "위": "上方",
  "아래": "下方",
  "TETH 점수 {score}점 산출 근거": "TETH评分 {score}分计算依据"
},
  "zh-TW": {
  "닫기": "關閉",
  "작성자 {nick}": "作者 {nick}",
  "검증 수익": "驗證收益",
  "TETH 점수": "TETH評分",
  "최대 낙폭 (MDD)": "最大回撤 (MDD)",
  "손익비 (Profit Factor)": "盈虧比 (Profit Factor)",
  "평균 보유일": "平均持倉天數",
  "거래 수": "交易次數",
  "전체 기간": "全部期間",
  "최근 2년": "近2年",
  "최근 1년": "近1年",
  "전체": "全部",
  "검증 기간": "驗證期間",
  ", {period} 검증, 거래 {count}회": "，{period}驗證，交易{count}次",
  "검증 수익률 ({period})": "驗證收益 ({period})",
  "TETH 점수, 근거 보기": "TETH評分，查看依據",
  "승률 ({count}전 {wins}승 {losses}패)": "勝率 ({count}戰{wins}勝{losses}負)",
  "누적 수익 곡선": "累計收益曲線",
  "수수료 0.2% 반영": "已計入0.2%手續費",
  "검증 성과 지표": "驗證績效指標",
  "{period}, 지표를 누르면 뜻을 볼 수 있어요": "{period}，點擊指標可查看說明",
  "{days}일": "{days}天",
  "{count}회 (이익 {wins}, 손실 {losses})": "{count}次 (獲利{wins}，虧損{losses})",
  "저장된 검증 성과": "已儲存的驗證績效",
  "검증 곡선 없음. 저장된 요약 지표만 표시합니다.": "暫無驗證曲線。僅顯示已儲存的摘要指標。",
  "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.": "驗證數據是基於歷史數據的回測結果，不保證未來收益。",
  "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.": "所有數據均為歷史數據驗證模擬，不保證未來收益。",
  "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.": "在所選驗證區間內按原樣執行策略規則時的累計收益率。已計入0.2%手續費。",
  "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.": "基於勝率、收益、回撤與交易活躍度4個維度的加權加總評分（0~99）。點擊評分徽章即可查看各維度的計算依據。",
  "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.": "驗證區間內資產相對高點的最大回撤幅度。根據持倉期間的評估淨值計算。",
  "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.": "總獲利除以總虧損所得的值。1.5:1意味著每虧損1的同時獲利1.5。",
  "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.": "從進場到平倉的平均持倉週期。若超過25根K線，將觸發時間平倉規則。",
  "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.": "驗證區間內發生的成交次數。樣本量較少時會對評分進行扣分懲罰。",
  "승률": "勝率",
  "수익 (CAGR)": "收益 (CAGR)",
  "낙폭 방어": "回撤防禦",
  "거래 활동": "交易活躍度",
  "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.": "由勝率、收益、回撤、交易活躍度4個維度加權匯總的0~99分。透過各維度可了解該評分的來源。全部數值均為驗證模擬的實際計算值。",
  "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.": "基準區間：勝率 35~60%，CAGR 0~6%，回撤 -25~-6%。80分以上才具備執行資格。",
  "표본 4회 미만, 점수 35% 감점": "樣本少於4次，評分扣除35%",
  "표본 6회 미만, 79점 상한": "樣本少於6次，上限79分",
  "기여": "貢獻",
  "{points}점": "{points}分",
  "공유 전략 중앙값 {value}": "共享策略中位數 {value}",
  "공유 전략 중앙값 {value} 대비 {position}": "相對共享策略中位數 {value} {position}",
  "위": "上方",
  "아래": "下方",
  "TETH 점수 {score}점 산출 근거": "TETH評分 {score}分計算依據"
},
  "es": {
  "닫기": "Cerrar",
  "작성자 {nick}": "Autor {nick}",
  "검증 수익": "Rentabilidad de validación",
  "TETH 점수": "Puntuación TETH",
  "최대 낙폭 (MDD)": "Drawdown máximo (MDD)",
  "손익비 (Profit Factor)": "Factor de beneficio (Profit Factor)",
  "평균 보유일": "Días promedio de tenencia",
  "거래 수": "Número de operaciones",
  "전체 기간": "Todo el período",
  "최근 2년": "Últimos 2 años",
  "최근 1년": "Último año",
  "전체": "Todo",
  "검증 기간": "Período de verificación",
  ", {period} 검증, 거래 {count}회": ", {period} de verificación, {count} operaciones",
  "검증 수익률 ({period})": "Rentabilidad de validación ({period})",
  "TETH 점수, 근거 보기": "Puntuación TETH, ver justificación",
  "승률 ({count}전 {wins}승 {losses}패)": "Tasa de acierto ({count} ops.: {wins}V {losses}D)",
  "누적 수익 곡선": "Curva de rendimiento acumulado",
  "수수료 0.2% 반영": "Comisión del 0,2 % incluida",
  "검증 성과 지표": "Métricas de rendimiento verificado",
  "{period}, 지표를 누르면 뜻을 볼 수 있어요": "{period}, toca una métrica para ver su definición",
  "{days}일": "{days} días",
  "{count}회 (이익 {wins}, 손실 {losses})": "{count} operaciones (Ganancia {wins}, Pérdida {losses})",
  "저장된 검증 성과": "Rendimiento verificado guardado",
  "검증 곡선 없음. 저장된 요약 지표만 표시합니다.": "Sin curva de verificación. Solo se muestran las métricas de resumen guardadas.",
  "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.": "Las cifras de verificación son resultados de backtest basados en datos históricos y no garantizan rendimientos futuros.",
  "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.": "Todas las cifras son simulaciones de verificación con datos históricos y no garantizan rendimientos futuros.",
  "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.": "Rendimiento acumulado al ejecutar las reglas de la estrategia tal cual en el período de verificación seleccionado. Incluye una comisión del 0,2 %.",
  "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.": "Puntuación ponderada de 4 ejes (0–99) basada en tasa de acierto, rendimiento, drawdown y actividad operativa. Toca la insignia de puntuación para ver el desglose por eje.",
  "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.": "La mayor caída de los activos desde su punto máximo en el período de verificación. Se calcula sobre el valor de mercado durante la tenencia.",
  "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.": "Se calcula dividiendo las ganancias totales entre las pérdidas totales. Un valor de 1,5:1 significa que se ganó 1,5 por cada 1 perdido.",
  "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.": "Período promedio de tenencia desde la entrada hasta el cierre. Si supera las 25 barras, se activa la regla de cierre por tiempo.",
  "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.": "Número de ejecuciones producidas en el período de verificación. Una muestra pequeña conlleva una penalización en la puntuación.",
  "승률": "Tasa de acierto",
  "수익 (CAGR)": "Rendimiento (CAGR)",
  "낙폭 방어": "Defensa contra drawdown",
  "거래 활동": "Actividad operativa",
  "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.": "Puntuación de 0 a 99 calculada como suma ponderada de 4 ejes: tasa de acierto, rendimiento, drawdown y actividad operativa. Cada eje permite ver el origen de esta puntuación. Todos los valores son cálculos reales de la simulación de verificación.",
  "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.": "Rango de referencia: tasa de acierto 35-60 %, CAGR 0-6 %, drawdown -25 a -6 %. Solo con 80 puntos o más se tiene derecho de ejecución.",
  "표본 4회 미만, 점수 35% 감점": "Menos de 4 muestras, deducción del 35 % de la puntuación",
  "표본 6회 미만, 79점 상한": "Menos de 6 muestras, límite de 79 puntos",
  "기여": "Contribución",
  "{points}점": "{points} pts",
  "공유 전략 중앙값 {value}": "Mediana de estrategias compartidas {value}",
  "공유 전략 중앙값 {value} 대비 {position}": "{position} respecto a la mediana de estrategias compartidas {value}",
  "위": "Por encima",
  "아래": "Por debajo",
  "TETH 점수 {score}점 산출 근거": "Base de cálculo de la puntuación TETH: {score}"
},
  "fr": {
  "닫기": "Fermer",
  "작성자 {nick}": "Auteur {nick}",
  "검증 수익": "Rendement de validation",
  "TETH 점수": "Score TETH",
  "최대 낙폭 (MDD)": "Drawdown maximal (MDD)",
  "손익비 (Profit Factor)": "Facteur de profit (Profit Factor)",
  "평균 보유일": "Jours moyens de détention",
  "거래 수": "Nombre de transactions",
  "전체 기간": "Toute la période",
  "최근 2년": "2 dernières années",
  "최근 1년": "Dernière année",
  "전체": "Tout",
  "검증 기간": "Période de vérification",
  ", {period} 검증, 거래 {count}회": ", vérification {period}, {count} transactions",
  "검증 수익률 ({period})": "Rendement de validation ({period})",
  "TETH 점수, 근거 보기": "Score TETH, voir les détails",
  "승률 ({count}전 {wins}승 {losses}패)": "Taux de réussite ({count} trades : {wins}V {losses}D)",
  "누적 수익 곡선": "Courbe de rendement cumulé",
  "수수료 0.2% 반영": "Frais de 0,2 % inclus",
  "검증 성과 지표": "Indicateurs de performance vérifiée",
  "{period}, 지표를 누르면 뜻을 볼 수 있어요": "{period}, cliquez sur un indicateur pour voir sa définition",
  "{days}일": "{days} jours",
  "{count}회 (이익 {wins}, 손실 {losses})": "{count} transactions (Gain {wins}, Perte {losses})",
  "저장된 검증 성과": "Performance vérifiée enregistrée",
  "검증 곡선 없음. 저장된 요약 지표만 표시합니다.": "Aucune courbe de vérification. Seuls les indicateurs récapitulatifs enregistrés sont affichés.",
  "검증 수치는 과거 데이터 기반 백테스트 결과이며 미래 수익을 보장하지 않아요.": "Les chiffres de vérification sont des résultats de backtest basés sur des données historiques et ne garantissent pas les rendements futurs.",
  "모든 수치는 과거 데이터 검증 시뮬레이션이며 미래 수익을 보장하지 않아요.": "Tous les chiffres sont des simulations de vérification sur données historiques et ne garantissent pas les rendements futurs.",
  "선택한 검증 구간에서 전략 규칙을 그대로 실행했을 때의 누적 수익률이에요. 수수료 0.2%가 반영돼요.": "Rendement cumulé lorsque les règles de la stratégie sont exécutées telles quelles sur la période de vérification sélectionnée. Des frais de 0,2 % sont inclus.",
  "승률, 수익, 낙폭, 거래 활동 4축 가중 합산 점수(0~99)예요. 점수 배지를 누르면 축별 근거를 볼 수 있어요.": "Score pondéré sur 4 axes (0–99) basé sur le taux de réussite, le rendement, le drawdown et l'activité de trading. Appuyez sur le badge de score pour afficher le détail par axe.",
  "검증 구간에서 자산이 고점 대비 가장 많이 하락한 폭이에요. 보유 중 평가액 기준으로 계산해요.": "La plus forte baisse de l'actif par rapport à son sommet au cours de la période de vérification. Calculée sur la valeur évaluée pendant la détention.",
  "총이익을 총손실로 나눈 값이에요. 1.5:1 이면 1을 잃는 동안 1.5를 벌었다는 뜻이에요.": "Calculé en divisant les gains totaux par les pertes totales. Un ratio de 1,5:1 signifie que vous avez gagné 1,5 pour chaque 1 perdu.",
  "진입부터 청산까지 평균 보유 기간이에요. 25봉이 넘으면 기간 청산 규칙이 실행돼요.": "Durée moyenne de détention de l'entrée à la clôture. Si elle dépasse 25 barres, la règle de clôture temporelle est déclenchée.",
  "검증 구간에서 발생한 체결 횟수예요. 표본이 적으면 점수에 페널티가 붙어요.": "Nombre d'exécutions survenues au cours de la période de vérification. Un échantillon faible entraîne une pénalité sur le score.",
  "승률": "Taux de réussite",
  "수익 (CAGR)": "Rendement (CAGR)",
  "낙폭 방어": "Défense contre le drawdown",
  "거래 활동": "Activité de trading",
  "승률, 수익, 낙폭, 거래 활동 4개 축을 가중 합산한 0~99점이에요. 축을 보면 이 점수가 어디서 왔는지 알 수 있어요. 전부 검증 시뮬레이션 실계산 값입니다.": "Score de 0 à 99 issu de la somme pondérée de 4 axes : taux de réussite, rendement, drawdown et activité de trading. L'observation des axes permet de comprendre l'origine de ce score. Toutes les valeurs sont des calculs réels issus de simulations de vérification.",
  "기준 구간: 승률 35~60%, CAGR 0~6%, 낙폭 -25~-6%. 80점 이상만 실행 자격이 있어요.": "Plage de référence : taux de réussite 35–60 %, CAGR 0–6 %, drawdown -25 à -6 %. Seuls les scores de 80 points ou plus sont éligibles à l'exécution.",
  "표본 4회 미만, 점수 35% 감점": "Moins de 4 échantillons, déduction de 35 % du score",
  "표본 6회 미만, 79점 상한": "Moins de 6 échantillons, plafonné à 79 points",
  "기여": "Contribution",
  "{points}점": "{points} pts",
  "공유 전략 중앙값 {value}": "Médiane des stratégies partagées {value}",
  "공유 전략 중앙값 {value} 대비 {position}": "{position} par rapport à la médiane des stratégies partagées {value}",
  "위": "Au-dessus",
  "아래": "En dessous",
  "TETH 점수 {score}점 산출 근거": "Base de calcul du score TETH {score}"
},
}

export function sharingDetailCopy(language: ClientLanguage, key: SharingDetailCopyKey, values: Record<string, string | number> = {}) {
  return CLIENT_SHARING_DETAIL_COPY[language][key].replace(/\{(\w+)\}/g, (token, name: string) => String(values[name] ?? token))
}
