import type { ClientLanguage } from './client-preferences'
import { sharedNumber } from './client-shared-number-format'

// Display labels only. Caller-owned records, IDs, raw settings and calculations stay unchanged.
type Translations = readonly [string, string, string, string, string, string, string]
const column = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const satisfies Record<ClientLanguage, number>
export const terminalReadCopy = {
  agentName: ["TETH 에이전트", "TETH Agent", "TETHエージェント", "TETH 智能体", "TETH 代理", "Agente TETH", "Agent TETH"],
  promptSection: ["사용자 프롬프트", "User Prompt", "ユーザープロンプト", "用户提示词", "使用者提示詞", "Indicación del usuario", "Invite utilisateur"],
  rationaleSection: ["생각의 사슬", "Chain of Thought", "思考の連鎖", "思维链", "思維鏈", "Cadena de pensamiento", "Chaîne de pensée"],
  decisionSection: ["거래 결정", "Trade Decision", "取引判断", "交易决策", "交易決策", "Decisión de operación", "Décision de trading"],
  watchDetails: ["봉별 판단 {count}건 보기", "View {count} per-candle decisions", "ローソク足ごとの判断 {count}件を表示", "查看 {count} 条 K 线判断", "查看 {count} 筆 K 線判斷", "Ver {count} decisiones por vela", "Voir {count} décisions par bougie"],
  scanEvent: ["시장 분석", "Market Analysis", "市場分析", "市场分析", "市場分析", "Análisis de mercado", "Analyse du marché"],
  exitPrice: ["청산가","Exit price","決済価格","平仓价","平倉價","Precio de salida","Prix de sortie"],
  targetPrice: ["목표가","Target price","目標価格","目标价","目標價","Precio objetivo","Prix cible"],
  versionHistory: ["버전 기록 보기 ({version})","View version history ({version})","バージョン履歴を見る（{version}）","查看版本记录（{version}）","查看版本紀錄（{version}）","Ver el historial de versiones ({version})","Voir l'historique des versions ({version})"],
  versionsTitle: ["버전 기록: {name}","Version history: {name}","バージョン履歴：{name}","版本记录：{name}","版本紀錄：{name}","Historial de versiones: {name}","Historique des versions : {name}"],
  currentVersion: ["현재 버전","Current version","現在のバージョン","当前版本","目前版本","Versión actual","Version actuelle"],
  noVersions: ["아직 수정 이력이 없어요. Agent 패널에서 자연어로 전략을 수정하면 버전이 생성돼요.","There is no edit history yet. When you modify the strategy in natural language in the Agent panel, a version is created.","まだ修正履歴はありません。Agentパネルで自然言語で戦略を修正すると、バージョンが作成されます。","还没有修改记录。在 Agent 面板用自然语言修改策略后，会生成版本。","還沒有修改紀錄。在 Agent 面板用自然語言修改策略後，會產生版本。","Todavía no hay historial de cambios. Cuando modificas la estrategia en lenguaje natural desde el panel Agent, se crea una versión.","Il n'y a pas encore d'historique de modifications. Lorsque vous modifiez la stratégie en langage naturel dans le panneau Agent, une version est créée."],
  versionsUnavailable: ["버전 기록이 제공되지 않았습니다.","No version history was provided.","バージョン履歴は提供されていません。","未提供版本记录。","未提供版本紀錄。","No se proporcionó el historial de versiones.","Aucun historique des versions n'a été fourni."],
  user: ["사용자","User","ユーザー","用户","使用者","Usuario","Utilisateur"],
  close: ["닫기","Close","閉じる","关闭","關閉","Cerrar","Fermer"],
  tradeDetails: ["{date} 거래 추적","{date} trade tracking","{date} の取引トラッキング","{date} 交易追踪","{date} 交易追蹤","Seguimiento de la operación {date}","Suivi de l'opération {date}"],
  barsOne: ["{value}봉","{value} bar","{value}本","{value}根K线","{value}根K線","{value} vela","{value} bougie"],
  capital: ["운용 자금","Managed capital","運用資金","管理资金","管理資金","Capital gestionado","Capital géré"],
  navSimulation: ["전략 NAV · 시뮬레이션","Strategy NAV · simulation","戦略NAV · シミュレーション","策略 NAV · 模拟","策略 NAV · 模擬","NAV de la estrategia · simulación","NAV de la stratégie · simulation"],
  totalPnl: ["Total P&L","Total P&L","Total P&L","Total P&L","Total P&L","Total P&L","Total P&L"],
  realized: ["실현 / 미실현","Realized / unrealized","実現 / 未実現","已实现 / 未实现","已實現 / 未實現","Realizado / no realizado","Réalisé / non réalisé"],
  feeCaption: ["수수료 (왕복 0.2%, 손익에 반영됨)","Fees (0.2% round trip, included in P&L)","手数料（往復0.2%、損益に反映）","手续费（往返 0.2%，已计入盈亏）","手續費（來回 0.2%，已計入損益）","Comisiones (0,2% ida y vuelta, incluidas en el resultado)","Frais (0,2% aller-retour, inclus dans le résultat)"],
  estimated: ["{value} 추정","{value} (estimated)","{value}（推定）","{value}（估算）","{value}（估算）","{value} (estimado)","{value} (estimé)"],
  navCurve: ["NAV 곡선","NAV curve","NAVカーブ","NAV 曲线","NAV 曲線","Curva NAV","Courbe NAV"],
  emptyCurve: ["곡선 데이터가 없어요","No curve data","カーブデータがありません","暂无曲线数据","目前沒有曲線資料","No hay datos de la curva","Aucune donnée de courbe"],
  simulationRange: ["검증 구간, 시뮬레이션","Validation period, simulation","検証区間、シミュレーション","验证区间，模拟","驗證區間，模擬","Periodo de validación, simulación","Période de validation, simulation"],
  navDescription: ["합성 NAV 곡선, {value}","Synthetic NAV curve, {value}","合成NAVカーブ、{value}","合成 NAV 曲线，{value}","合成 NAV 曲線，{value}","Curva NAV sintética, {value}","Courbe NAV synthétique, {value}"],
  winRate: ["승률","Win rate","勝率","胜率","勝率","Tasa de acierto","Taux de réussite"],
  drawdown: ["최대 낙폭","Max drawdown","最大ドローダウン","最大回撤","最大回撤","Caída máxima","Drawdown maximal"],
  profitFactor: ["손익비","Profit factor","プロフィットファクター","盈亏比","損益比","Factor de beneficio","Facteur de profit"],
  sharpe: ["샤프","Sharpe","シャープ","夏普","夏普","Sharpe","Sharpe"],
  averageHolding: ["평균 보유","Average holding period","平均保有期間","平均持仓时长","平均持倉時長","Duración media","Durée moyenne"],
  marketExposure: ["시장 노출","Market exposure","市場エクスポージャー","市场敞口","市場曝險","Exposición al mercado","Exposition au marché"],
  tradeCount: ["거래 수","Trade count","取引数","交易数","交易數","Número de operaciones","Nombre d'opérations"],
  maxGainLoss: ["최대 익/손","Max gain/loss","最大益/損","最大盈/亏","最大盈/虧","Máx. ganancia/pérdida","Gain/perte max."],
  bars: ["{value}봉","{value} bars","{value}本","{value}根K线","{value}根K線","{value} velas","{value} bougies"],
  trades: ["{value}회","{value}","{value}回","{value}次","{value}次","{value}","{value}"],
  count: ["{count}건","{count}","{count}件","{count} 条","{count} 筆","{count}","{count}"],
  currentPosition: ["현재 포지션","Current position","現在のポジション","当前持仓","目前持倉","Posición actual","Position actuelle"],
  simulationEnd: ["검증 구간 종료 시점 · 시뮬레이션","End of the validation period · simulation","検証区間の終了時点 · シミュレーション","验证区间结束时点 · 模拟","驗證區間結束時點 · 模擬","Fin del periodo de validación · simulación","Fin de la période de validation · simulation"],
  entryPrice: ["진입가","Entry price","エントリー価格","入场价","進場價","Precio de entrada","Prix d'entrée"],
  currentPrice: ["현재가","Current price","現在価格","当前价格","目前價格","Precio actual","Prix actuel"],
  quantity: ["수량","Quantity","数量","数量","數量","Cantidad","Quantité"],
  stopPrice: ["손절가","Stop-loss price","損切り価格","止损价","停損價","Precio de stop loss","Prix du stop-loss"],
  holding: ["보유","Holding period","保有期間","持仓时长","持倉時長","Duración","Durée"],
  noPosition: ["현재 포지션이 없습니다.","There is no current position.","現在のポジションはありません。","当前没有持仓。","目前沒有持倉。","No hay ninguna posición actual.","Il n'y a aucune position actuelle."],
  seekingEntry: ["진입 신호를 탐색하는 중이에요.","Looking for an entry signal.","エントリーシグナルを探しています。","正在寻找入场信号。","正在尋找進場訊號。","Buscando una señal de entrada.","Recherche d'un signal d'entrée en cours."],
  notRunning: ["전략이 실행 중이 아니에요.","The strategy is not running.","戦略は実行中ではありません。","策略未在运行。","策略未在執行。","La estrategia no está en ejecución.","La stratégie n'est pas en cours d'exécution."],
  recentTrades: ["최근 거래","Recent trades","最近の取引","最近交易","最近交易","Operaciones recientes","Opérations récentes"],
  recentTradesLabel: ["{name} 최근 거래 내역","{name} recent trade history","{name} の最近の取引履歴","{name} 最近交易记录","{name} 最近交易紀錄","Historial de operaciones recientes de {name}","Historique des opérations récentes de {name}"],
  exitDate: ["청산일","Exit date","決済日","平仓日期","平倉日期","Fecha de salida","Date de sortie"],
  type: ["구분","Type","区分","类型","類型","Tipo","Type"],
  pnl: ["손익","P&L","損益","盈亏","損益","Resultado","Résultat"],
  takeProfit: ["익절","Take profit","利確","止盈","停利","Take profit","Take-profit"],
  stopLoss: ["손절","Stop loss","損切り","止损","停損","Stop loss","Stop-loss"],
  period: ["기간","Time","期間","到期","到期","Tiempo","Échéance"],
  noFills: ["이 구간 체결이 없어요","There are no fills in this period","この区間の約定はありません","该区间没有成交","此區間沒有成交","No hay ejecuciones en este periodo","Aucune exécution sur cette période"],
  completed: ["완료된 거래","Completed trades","完了した取引","已完成交易","已完成交易","Operaciones completadas","Opérations terminées"],
  completedRange: ["{total}건 중 최근 {recent}, 시뮬레이션","Most recent {recent} of {total}, simulation","{total}件のうち直近{recent}、シミュレーション","{total} 条中最近 {recent} 条，模拟","{total} 筆中最近 {recent} 筆，模擬","Las {recent} más recientes de {total}, simulación","Les {recent} plus récentes sur {total}, simulation"],
  entry: ["진입","Entry","エントリー","入场","進場","Entrada","Entrée"],
  exit: ["청산","Exit","決済","平仓","平倉","Salida","Sortie"],
  fee: ["수수료","Fees","手数料","手续费","手續費","Comisiones","Frais"],
  whyEntered: ["WHY ENTERED","WHY ENTERED","WHY ENTERED","WHY ENTERED","WHY ENTERED","WHY ENTERED","WHY ENTERED"],
  whyExited: ["WHY EXITED","WHY EXITED","WHY EXITED","WHY EXITED","WHY EXITED","WHY EXITED","WHY EXITED"],
  fullDecision: ["전체 판단 기록 →","Full decision log →","判断記録の全体 →","查看完整判断记录 →","查看完整判斷紀錄 →","Registro completo de decisiones →","Journal complet des décisions →"],
  noCompleted: ["완료된 거래가 없어요","There are no completed trades","完了した取引はありません","没有已完成的交易","沒有已完成的交易","No hay operaciones completadas","Aucune opération terminée"],
  noCompletedHint: ["검증 구간에서 완결된 거래가 생기면 여기에 정리돼요.","When a trade is completed in the validation period, it is summarized here.","検証区間で完結した取引が発生すると、ここにまとめられます。","验证区间内出现完结的交易后，会在这里汇总。","驗證區間內出現完結的交易後，會在這裡彙整。","Cuando se complete una operación en el periodo de validación, se resumirá aquí.","Lorsqu'une opération est clôturée sur la période de validation, elle est récapitulée ici."],
  eventEntry: ["진입","Entry","エントリー","入场","進場","Entrada","Entrée"],
  eventTp: ["익절 청산","Take-profit exit","利確決済","止盈平仓","停利平倉","Salida por take profit","Sortie en take-profit"],
  eventSl: ["손절 청산","Stop-loss exit","損切り決済","止损平仓","停損平倉","Salida por stop loss","Sortie en stop-loss"],
  eventTime: ["기간 청산","Time exit","期間決済","到期平仓","到期平倉","Salida por tiempo","Sortie à échéance"],
  eventWatch: ["관망","Watching","様子見","观望","觀望","A la espera","Observation"],
  eventRisk: ["보유 점검","Holding check","保有チェック","持仓检查","持倉檢查","Revisión de la posición","Vérification de la position"],
  userPrompt: ["USER PROMPT","USER PROMPT","USER PROMPT","USER PROMPT","USER PROMPT","USER PROMPT","USER PROMPT"],
  savedSettings: ["이 주기에 적용된 저장 전략 설정","Saved strategy settings applied in this cycle","このサイクルに適用された保存済み戦略設定","本周期应用的已保存策略设置","本週期套用的已儲存策略設定","Ajustes de estrategia guardados aplicados en este ciclo","Paramètres de stratégie enregistrés appliqués à ce cycle"],
  rawSettings: ["Raw 설정 보기","View Raw settings","Raw設定を見る","查看 Raw 设置","查看 Raw 設定","Ver los ajustes Raw","Voir les paramètres Raw"],
  rationale: ["판단 근거","Rationale","判断根拠","判断依据","判斷依據","Fundamento de la decisión","Fondement de la décision"],
  decisions: ["TRADING DECISIONS","TRADING DECISIONS","TRADING DECISIONS","TRADING DECISIONS","TRADING DECISIONS","TRADING DECISIONS","TRADING DECISIONS"],
  justification: ["JUSTIFICATION","JUSTIFICATION","JUSTIFICATION","JUSTIFICATION","JUSTIFICATION","JUSTIFICATION","JUSTIFICATION"],
  invalidation: ["INVALIDATION","INVALIDATION","INVALIDATION","INVALIDATION","INVALIDATION","INVALIDATION","INVALIDATION"],
  collapse: ["세부 정보 접기 ▴","Collapse details ▴","詳細を折りたたむ ▴","收起详细信息 ▴","收合詳細資訊 ▴","Contraer detalles ▴","Réduire les détails ▴"],
  expand: ["세부 정보 ▾","Details ▾","詳細 ▾","详细信息 ▾","詳細資訊 ▾","Detalles ▾","Détails ▾"],
  feed: ["Agent 판단 기록","Agent decision log","Agent判断記録","Agent 判断记录","Agent 判斷紀錄","Registro de decisiones del Agent","Journal des décisions de l'Agent"],
  operations: ["운영 기록","Operations log","運用記録","运营记录","營運紀錄","Registro operativo","Journal d'exploitation"],
  error: ["오류","Error","エラー","错误","錯誤","Error","Erreur"],
  reconnect: ["다시 연결","Reconnect","再接続","重新连接","重新連接","Volver a conectar","Reconnecter"],
  decisionHistory: ["판단 기록","Decision log","判断記録","判断记录","判斷紀錄","Registro de decisiones","Journal des décisions"],
  historyFilter: ["판단 기록 필터","Decision log filter","判断記録フィルター","判断记录筛选","判斷紀錄篩選","Filtro del registro de decisiones","Filtre du journal des décisions"],
  all: ["전체","All","すべて","全部","全部","Todo","Tout"],
  fillsOnly: ["체결만","Fills only","約定のみ","仅成交","僅成交","Solo ejecuciones","Exécutions uniquement"],
  unavailable: ["Agent 판단 기록을 확인하지 못했습니다.","The Agent decision log could not be confirmed.","Agent判断記録を確認できませんでした。","未能确认 Agent 判断记录。","未能確認 Agent 判斷紀錄。","No se pudo confirmar el registro de decisiones del Agent.","Le journal des décisions de l'Agent n'a pas pu être confirmé."],
  empty: ["아직 Agent 판단 기록이 없습니다.","There is no Agent decision log yet.","まだAgent判断記録はありません。","还没有 Agent 判断记录。","還沒有 Agent 判斷紀錄。","Todavía no hay registro de decisiones del Agent.","Il n'y a pas encore de journal des décisions de l'Agent."],
  emptyFills: ["체결 판단 기록이 없습니다.","There are no fill decision records.","約定の判断記録はありません。","没有成交的判断记录。","沒有成交的判斷紀錄。","No hay registros de decisiones de ejecución.","Aucun enregistrement de décision d'exécution."],
  firstEvaluation: ["전략이 첫 번째 평가를 완료하면 여기에 표시됩니다.","It will appear here once the strategy completes its first evaluation.","戦略が最初の評価を完了すると、ここに表示されます。","策略完成首次评估后会显示在这里。","策略完成首次評估後會顯示在這裡。","Aparecerá aquí cuando la estrategia complete su primera evaluación.","S'affichera ici une fois que la stratégie aura terminé sa première évaluation."],
  historyList: ["판단 기록 목록","Decision log list","判断記録リスト","判断记录列表","判斷紀錄清單","Lista del registro de decisiones","Liste du journal des décisions"],
  moreHistory: ["이전 판단 더 보기 ({count})","Show more previous decisions ({count})","以前の判断をさらに表示（{count}）","查看更多历史判断（{count}）","查看更多先前判斷（{count}）","Ver más decisiones anteriores ({count})","Voir plus de décisions précédentes ({count})"],
} as const satisfies Record<string, Translations>
export function terminalReadText(language: ClientLanguage, key: keyof typeof terminalReadCopy, values: Readonly<Record<string, string>> = {}): string {
  return terminalReadCopy[key][column[language]].replace(/\{([a-zA-Z]+)\}/g, (placeholder, name: string) => Object.hasOwn(values, name) ? values[name] : placeholder)
}

/** Use the rounded display quantity for grammar, never parse a localized decimal. */
export function terminalBarsText(language: ClientLanguage, value: number, digits: 0 | 1 = 0): string {
  return terminalReadText(language, Number(value.toFixed(digits)) === 1 ? 'barsOne' : 'bars', { value: sharedNumber(value, language, digits) })
}
