import type { ClientLanguage } from './client-preferences'

/** Public design-preview notices only. These do not set live billing policy. */
const rows = {
  preview: ['제품 디자인 미리보기 · 현재는 Mock UI이며 실제 주문·결제·거래소 연결은 진행되지 않습니다.', 'Product design preview · Currently a Mock UI; real orders, payments, and exchange connections are not processed.', '製品デザインプレビュー・現在はMock UIであり、実際の注文・決済・取引所連携は行われません。', '产品设计预览 · 当前为Mock UI，不进行实际下单、支付或交易所连接。', '產品設計預覽 · 目前為Mock UI，不進行實際下單、付款或交易所連接。', 'Vista previa del diseño del producto · Actualmente es una Mock UI; no se procesan órdenes, pagos ni conexiones con exchanges reales.', 'Aperçu du design du produit · Actuellement une Mock UI ; les ordres, paiements et connexions réels aux plateformes d’échange ne sont pas traités.'],
  policy: ['정책 디자인 검토용 초안입니다. 아래 요금·보안·데이터 처리 설명은 출시 제품의 확정 정책이 아니며, 현재 화면은 Mock UI입니다.', 'Draft for policy design review. The pricing, security, and data processing descriptions below are not finalized product policies, and the current screen is a Mock UI.', 'ポリシーデザイン検討用の下書きです。下記の料金・セキュリティ・データ処理に関する説明は製品の確定ポリシーではなく、現在の画面はMock UIです。', '政策设计审查草案。以下关于费用、安全及数据处理的说明并非产品的最终政策，当前界面为Mock UI。', '政策設計審查草案。以下關於費用、安全及資料處理的說明並非產品的最終政策，目前畫面為Mock UI。', 'Borrador para la revisión del diseño de políticas. Las descripciones a continuación sobre tarifas, seguridad y procesamiento de datos no son políticas definitivas del producto final, y la pantalla actual es una Mock UI.', 'Brouillon pour l’examen du design des politiques. Les descriptions ci-dessous concernant les tarifs, la sécurité et le traitement des données ne sont pas des politiques définitives du produit, et l’écran actuel est une Mock UI.'],
  pricing: ['요금제 디자인 예시 · 결제·파트너 가입은 진행되지 않습니다.', 'Pricing plan design preview · Payments and partner registrations are not processed.', '料金プランデザインの例・決済やパートナー登録は行われません。', '价格方案设计示例 · 不进行支付或合作伙伴注册。', '價格方案設計範例 · 不進行付款或合作夥伴註冊。', 'Ejemplo de diseño de planes · No se procesan pagos ni registros de socios.', 'Exemple de design tarifaire · Aucun paiement ni inscription de partenaire n’est traité.'],
  faq: ['출시 제품을 설명하는 원본 카피입니다. 현재 Mock 화면에서는 실제 자동매매·거래소 연결이 실행되지 않습니다.', 'Original copy describing the planned product. On the current Mock screen, real automated trading and exchange connections are not executed.', '製品構想を説明する元のコピーです。現在のMock画面では、実際の自動売買・取引所連携は実行されません。', '说明产品构想的原始文案。在当前Mock界面中，不执行实际的自动交易或交易所连接。', '說明產品構想的原始文案。在目前Mock畫面中，不執行實際的自動交易或交易所連接。', 'Texto original que describe el producto previsto. En la pantalla Mock actual, no se ejecutan operaciones automáticas ni conexiones con exchanges reales.', 'Texte original décrivant le produit prévu. Sur l’écran Mock actuel, le trading automatisé réel et les connexions aux plateformes d’échange ne sont pas exécutés.'],
  month: ['월', 'per month', '毎月', '每月', '每月', 'al mes', 'par mois'],
} as const
const languages: readonly ClientLanguage[] = ['ko', 'en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr']
export function publicPreviewText(language: ClientLanguage, key: keyof typeof rows): string {
  return rows[key][languages.indexOf(language)] ?? rows[key][0]
}
