import type { ClientLanguage } from './client-preferences'

export type BillingCopyKey =
  | 'bill.watch.t'
  | 'bill.watch.b'
  | 'bill.recover.t'
  | 'bill.recover.b'
  | 'bill.uid.novol.t'
  | 'bill.uid.novol.b'
  | 'bill.uid.small.t'
  | 'bill.uid.small.b'
  | 'bill.uid.heavy.t'
  | 'bill.uid.heavy.b'
  | 'bill.free.out.t'
  | 'bill.free.out.b'
  | 'bill.card.out.t'
  | 'bill.card.out.b'
  | 'bill.carduid.out.t'
  | 'bill.carduid.out.b'
  | 'bill.dunning.t'
  | 'bill.dunning.b'
  | 'bill.card.cross.t'
  | 'bill.card.cross.b'
  | 'standby'
  | 'standbyValue'
  | 'standbyDescription'
  | 'blocked'
  | 'storageError'
  | 'unavailable'
  | 'clockSkew'
  | 'retry'
  | 'billingTag'

export const BILLING_COPY = {
  ko: {
    'bill.watch.t': '크레딧이 소진되어 잠시 관망 모드로 전환했어요',
    'bill.watch.b': '실행 중인 손절과 목표가 관리는 그대로 유지돼요. 충전이나 연동 즉시 다시 시작할 수 있어요.',
    'bill.recover.t': 'AI 기능이 다시 켜졌어요',
    'bill.recover.b': '크레딧이 충전되어 모든 기능을 다시 사용할 수 있어요.',
    'bill.uid.novol.t': '최근 거래가 없어 크레딧 충전이 멈췄어요',
    'bill.uid.novol.b': '전략 점검이 필요할 수 있어요. 새 연구로 지금 시장에 맞는 전략을 찾아보세요.',
    'bill.uid.small.t': '거래 규모보다 AI 사용량이 많아요',
    'bill.uid.small.b': '현재 거래량으로는 충전이 사용량을 따라가지 못해요. 거래 규모를 늘리거나 카드 등록을 고려해보세요.',
    'bill.uid.heavy.t': 'AI 사용량이 많은 편이에요',
    'bill.uid.heavy.b': '카드를 등록하면 90% 할인으로 시작할 수 있어요. 거래량 충전분은 카드 요금에서 계속 차감돼요.',
    'bill.free.out.t': '웰컴 크레딧을 모두 사용했어요',
    'bill.free.out.b': '거래소 UID 연동은 0원으로 계속 쓸 수 있어요. 카드 등록으로도 이어갈 수 있어요.',
    'bill.card.out.t': '이번 달 크레딧을 모두 사용했어요',
    'bill.card.out.b': 'UID 연동으로 거래량 충전을 더할 수 있어요. 다음 결제일에는 자동으로 다시 채워져요.',
    'bill.carduid.out.t': '이번 달 크레딧을 모두 사용했어요',
    'bill.carduid.out.b': '다음 결제일에 자동으로 다시 채워져요. 그동안 쌓이는 거래량 충전분은 다음 결제에서 할인으로 이어져요.',
    'bill.dunning.t': '결제가 완료되지 않아 잠시 관망 모드로 전환했어요',
    'bill.dunning.b': '결제 수단을 확인해주세요. 실행 중인 손절과 목표가 관리는 그대로 유지되고, 결제 즉시 다시 시작돼요.',
    'bill.card.cross.t': '거래소 연동으로 요금을 아껴보세요',
    'bill.card.cross.b': 'UID를 연동하면 거래량만큼 크레딧이 충전되고 다음 결제에서 그만큼 할인돼요. AI 이용 크레딧 $100 혜택도 받을 수 있어요.',
    standby: '관망 중',
    standbyValue: '관망',
    standbyDescription: '크레딧이 소진되어 AI 기능이 잠시 멈춰 있어요. 실행 중인 손절과 목표가 관리는 그대로 유지되고, 충전이나 연동 즉시 재개돼요.',
    blocked: '크레딧이 소진되어 AI 기능이 잠시 멈춰 있어요',
    storageError: '이 브라우저의 이용 상태를 확인하지 못했어요. 기존 기록을 보존하고 새 요청을 멈췄어요.',
    unavailable: '이용 상태를 확인하지 못해 요청을 보내지 않았어요. 기기의 날짜·시간과 저장 상태를 확인한 뒤 다시 시도해주세요. 기존 내용은 그대로 유지됩니다.',
    clockSkew: '기기 시간이 저장된 기록보다 이전입니다. 날짜·시간을 확인하고, 저장된 기록 시각 이후에 다시 요청해주세요. 입력 내용과 기록은 그대로 보존됩니다.',
    retry: '저장 상태 다시 확인',
    billingTag: '이용 안내',
  },
  en: {
    'bill.watch.t': 'Credits ran out, switching to standby',
    'bill.watch.b': 'Your stop-loss and take-profit rules stay active. Recharge or link to resume instantly.',
    'bill.recover.t': 'AI features are back on',
    'bill.recover.b': 'Credits recharged, everything is available again.',
    'bill.uid.novol.t': 'No recent trades, so credit top-ups paused',
    'bill.uid.novol.b': 'Your strategy may need a check. Try a new research run for the current market.',
    'bill.uid.small.t': 'AI usage is outpacing your trading volume',
    'bill.uid.small.b': 'Top-ups from your volume cannot keep up. Consider trading more or adding a card.',
    'bill.uid.heavy.t': 'You are a heavy AI user',
    'bill.uid.heavy.b': 'Add a card to start with a 90% discount. Volume top-ups keep reducing your card bill.',
    'bill.free.out.t': 'Welcome credits are used up',
    'bill.free.out.b': 'Link an exchange UID to continue for free, or add a card.',
    'bill.card.out.t': "This month's credits are used up",
    'bill.card.out.b': 'Link a UID to add volume top-ups. Credits refill automatically next billing day.',
    'bill.carduid.out.t': "This month's credits are used up",
    'bill.carduid.out.b': 'Credits refill automatically next billing day. Volume top-ups keep cutting your next bill.',
    'bill.dunning.t': 'Payment failed, switching to standby',
    'bill.dunning.b': 'Please check your payment method. Stop-loss and take-profit rules stay active, and everything resumes right after payment.',
    'bill.card.cross.t': 'Save on your bill by linking an exchange',
    'bill.card.cross.b': 'Link a UID to earn credits from your volume and cut your next bill. Includes $100 in AI credits.',
    standby: 'Standing by',
    standbyValue: 'Standby',
    standbyDescription: 'AI features are paused because your credits have run out. Active stop-loss and take-profit management remains in place, and resumes as soon as you recharge or link an exchange.',
    blocked: 'AI features are temporarily paused because your credits have run out',
    storageError: "We couldn't check this browser's usage status. We preserved your existing history and paused new requests.",
    unavailable: "We couldn't verify your usage status, so we didn't send the request. Check your device's date, time and storage status, then try again. Your existing content is unchanged.",
    clockSkew: "Your device's time is earlier than the saved records. Check the date and time, then send your request once the saved record time has passed. Your input and records are preserved.",
    retry: 'Check storage status again',
    billingTag: 'Usage notice',
  },
  ja: {
    'bill.watch.t': 'クレジットを使い切ったため、一時的に待機モードへ切り替えました',
    'bill.watch.b': '実行中の損切りと利確ルールはそのまま維持されます。チャージまたは連携後すぐに再開できます。',
    'bill.recover.t': 'AI機能が再び有効になりました',
    'bill.recover.b': 'クレジットがチャージされ、すべての機能を再び利用できます。',
    'bill.uid.novol.t': '最近の取引がないため、クレジットのチャージが停止しました',
    'bill.uid.novol.b': '戦略の見直しが必要かもしれません。新しいリサーチで現在の市場に合う戦略を探してみてください。',
    'bill.uid.small.t': '取引規模に対してAIの利用量が多くなっています',
    'bill.uid.small.b': '現在の取引量によるチャージでは利用量に追いつきません。取引規模を増やすか、カードの登録をご検討ください。',
    'bill.uid.heavy.t': 'AIの利用量が多めです',
    'bill.uid.heavy.b': 'カードを登録すると90%割引で始められます。取引量によるチャージ分は引き続きカード料金から差し引かれます。',
    'bill.free.out.t': 'ウェルカムクレジットをすべて使い切りました',
    'bill.free.out.b': '取引所UIDを連携すると無料で使い続けられます。カードを登録して続けることもできます。',
    'bill.card.out.t': '今月のクレジットをすべて使い切りました',
    'bill.card.out.b': 'UIDを連携すると取引量によるチャージを追加できます。次回の請求日に自動で補充されます。',
    'bill.carduid.out.t': '今月のクレジットをすべて使い切りました',
    'bill.carduid.out.b': '次回の請求日に自動で補充されます。その間に貯まる取引量チャージ分は、次回の請求で割引に使われます。',
    'bill.dunning.t': '決済が完了しなかったため、一時的に待機モードへ切り替えました',
    'bill.dunning.b': 'お支払い方法をご確認ください。実行中の損切りと利確ルールはそのまま維持され、決済後すぐに再開します。',
    'bill.card.cross.t': '取引所を連携して料金を節約しましょう',
    'bill.card.cross.b': 'UIDを連携すると取引量に応じてクレジットがチャージされ、次回の請求がその分割引されます。AI利用クレジット100ドル分も含まれます。',
    standby: '待機中',
    standbyValue: '待機',
    standbyDescription: 'クレジットを使い切ったため、AI機能が一時停止しています。実行中の損切りと利確の管理はそのまま維持され、チャージまたは連携後すぐに再開します。',
    blocked: 'クレジットを使い切ったため、AI機能が一時停止しています',
    storageError: 'このブラウザの利用状況を確認できませんでした。既存の記録を保持し、新しいリクエストを停止しました。',
    unavailable: '利用状況を確認できなかったため、リクエストを送信しませんでした。端末の日付・時刻と保存状態を確認してから、もう一度お試しください。既存の内容はそのまま保持されます。',
    clockSkew: '端末の時刻が保存済みの記録より前になっています。日付・時刻を確認し、記録の時刻を過ぎてから再度リクエストしてください。入力内容と記録はそのまま保持されます。',
    retry: '保存状態を再確認',
    billingTag: '利用案内',
  },
  'zh-CN': {
    'bill.watch.t': '点数已用完，暂时切换为观望模式',
    'bill.watch.b': '正在执行的止损和止盈规则会继续保留。充值或完成关联后即可立即恢复。',
    'bill.recover.t': 'AI功能已重新开启',
    'bill.recover.b': '点数已充值，所有功能均可重新使用。',
    'bill.uid.novol.t': '近期没有交易，点数充值已暂停',
    'bill.uid.novol.b': '您的策略可能需要检查。可以通过新的研究寻找适合当前市场的策略。',
    'bill.uid.small.t': 'AI使用量高于您的交易规模',
    'bill.uid.small.b': '当前交易量带来的充值无法跟上使用量。请考虑增加交易规模或添加银行卡。',
    'bill.uid.heavy.t': '您的AI使用量较高',
    'bill.uid.heavy.b': '添加银行卡即可享受90%折扣开始使用。交易量充值部分会继续从银行卡账单中抵扣。',
    'bill.free.out.t': '欢迎点数已全部用完',
    'bill.free.out.b': '关联交易所UID即可继续免费使用，也可以添加银行卡继续使用。',
    'bill.card.out.t': '本月点数已全部用完',
    'bill.card.out.b': '关联UID可增加交易量充值。点数会在下一个账单日自动补充。',
    'bill.carduid.out.t': '本月点数已全部用完',
    'bill.carduid.out.b': '点数会在下一个账单日自动补充。期间累积的交易量充值将在下一笔账单中抵扣。',
    'bill.dunning.t': '付款未完成，暂时切换为观望模式',
    'bill.dunning.b': '请检查您的付款方式。正在执行的止损和止盈规则会继续保留，并在付款后立即恢复。',
    'bill.card.cross.t': '关联交易所以节省费用',
    'bill.card.cross.b': '关联UID后，可按交易量获得点数并抵扣下一笔账单。还包含价值100美元的AI使用点数。',
    standby: '观望中',
    standbyValue: '观望',
    standbyDescription: '点数已用完，AI功能暂时停止。正在执行的止损和止盈管理会继续保留，充值或完成关联后立即恢复。',
    blocked: '点数已用完，AI功能暂时停止',
    storageError: '无法确认此浏览器的使用状态。已保留现有记录并暂停新请求。',
    unavailable: '无法确认使用状态，因此未发送请求。请检查设备的日期、时间和存储状态后重试。现有内容保持不变。',
    clockSkew: '设备时间早于已保存记录的时间。请检查日期和时间，并在超过记录时间后重新发送请求。输入内容和记录会完整保留。',
    retry: '重新检查保存状态',
    billingTag: '使用说明',
  },
  'zh-TW': {
    'bill.watch.t': '點數已用完，暫時切換為觀望模式',
    'bill.watch.b': '正在執行的停損和停利規則會繼續保留。儲值或完成連結後即可立即恢復。',
    'bill.recover.t': 'AI功能已重新開啟',
    'bill.recover.b': '點數已儲值，所有功能均可重新使用。',
    'bill.uid.novol.t': '近期沒有交易，點數儲值已暫停',
    'bill.uid.novol.b': '您的策略可能需要檢查。可以透過新的研究尋找適合目前市場的策略。',
    'bill.uid.small.t': 'AI使用量高於您的交易規模',
    'bill.uid.small.b': '目前交易量帶來的儲值無法跟上使用量。請考慮增加交易規模或新增信用卡。',
    'bill.uid.heavy.t': '您的AI使用量較高',
    'bill.uid.heavy.b': '新增信用卡即可享有90%折扣開始使用。交易量儲值部分會繼續從信用卡帳單中折抵。',
    'bill.free.out.t': '歡迎點數已全部用完',
    'bill.free.out.b': '連結交易所UID即可繼續免費使用，也可以新增信用卡繼續使用。',
    'bill.card.out.t': '本月點數已全部用完',
    'bill.card.out.b': '連結UID可增加交易量儲值。點數會在下一個帳單日自動補充。',
    'bill.carduid.out.t': '本月點數已全部用完',
    'bill.carduid.out.b': '點數會在下一個帳單日自動補充。期間累積的交易量儲值將在下一筆帳單中折抵。',
    'bill.dunning.t': '付款未完成，暫時切換為觀望模式',
    'bill.dunning.b': '請檢查您的付款方式。正在執行的停損和停利規則會繼續保留，並在付款後立即恢復。',
    'bill.card.cross.t': '連結交易所以節省費用',
    'bill.card.cross.b': '連結UID後，可依交易量獲得點數並折抵下一筆帳單。還包含價值100美元的AI使用點數。',
    standby: '觀望中',
    standbyValue: '觀望',
    standbyDescription: '點數已用完，AI功能暫時停止。正在執行的停損和停利管理會繼續保留，儲值或完成連結後立即恢復。',
    blocked: '點數已用完，AI功能暫時停止',
    storageError: '無法確認此瀏覽器的使用狀態。已保留現有記錄並暫停新請求。',
    unavailable: '無法確認使用狀態，因此未傳送請求。請檢查裝置的日期、時間及儲存狀態後再試一次。現有內容會保持不變。',
    clockSkew: '裝置時間早於已儲存記錄的時間。請檢查日期與時間，並在超過記錄時間後重新傳送請求。輸入內容與記錄會完整保留。',
    retry: '重新檢查儲存狀態',
    billingTag: '使用說明',
  },
  es: {
    'bill.watch.t': 'Los créditos se agotaron; cambiamos temporalmente al modo de espera',
    'bill.watch.b': 'Las reglas de stop-loss y take-profit activas se mantienen. Recarga o vincula una cuenta para reanudar al instante.',
    'bill.recover.t': 'Las funciones de IA vuelven a estar activas',
    'bill.recover.b': 'Los créditos se recargaron y todas las funciones vuelven a estar disponibles.',
    'bill.uid.novol.t': 'No hay operaciones recientes, así que se pausaron las recargas de créditos',
    'bill.uid.novol.b': 'Puede que tu estrategia necesite una revisión. Prueba una nueva investigación para encontrar una estrategia adecuada al mercado actual.',
    'bill.uid.small.t': 'El uso de IA supera tu volumen de operaciones',
    'bill.uid.small.b': 'Las recargas por tu volumen actual no alcanzan para cubrir el uso. Considera operar con un mayor volumen o añadir una tarjeta.',
    'bill.uid.heavy.t': 'Tu uso de IA es elevado',
    'bill.uid.heavy.b': 'Añade una tarjeta para empezar con un 90 % de descuento. Las recargas por volumen seguirán descontándose de la factura de la tarjeta.',
    'bill.free.out.t': 'Has utilizado todos los créditos de bienvenida',
    'bill.free.out.b': 'Vincula el UID de un exchange para seguir usando el servicio gratis, o añade una tarjeta.',
    'bill.card.out.t': 'Has utilizado todos los créditos de este mes',
    'bill.card.out.b': 'Vincula un UID para añadir recargas por volumen. Los créditos se reponen automáticamente en la próxima fecha de facturación.',
    'bill.carduid.out.t': 'Has utilizado todos los créditos de este mes',
    'bill.carduid.out.b': 'Los créditos se reponen automáticamente en la próxima fecha de facturación. Las recargas por volumen acumuladas seguirán reduciendo tu próxima factura.',
    'bill.dunning.t': 'El pago no se completó; cambiamos temporalmente al modo de espera',
    'bill.dunning.b': 'Revisa tu método de pago. Las reglas de stop-loss y take-profit activas se mantienen y todo se reanuda justo después del pago.',
    'bill.card.cross.t': 'Ahorra en tu factura vinculando un exchange',
    'bill.card.cross.b': 'Vincula un UID para obtener créditos según tu volumen y reducir tu próxima factura. Incluye 100 $ en créditos de IA.',
    standby: 'En espera',
    standbyValue: 'Espera',
    standbyDescription: 'Las funciones de IA están temporalmente en pausa porque se agotaron tus créditos. La gestión activa de stop-loss y take-profit se mantiene y se reanuda al recargar o vincular un exchange.',
    blocked: 'Las funciones de IA están temporalmente en pausa porque se agotaron tus créditos',
    storageError: 'No pudimos comprobar el estado de uso de este navegador. Conservamos el historial existente y pausamos las nuevas solicitudes.',
    unavailable: 'No pudimos verificar tu estado de uso, por lo que no enviamos la solicitud. Comprueba la fecha, la hora y el estado del almacenamiento de tu dispositivo y vuelve a intentarlo. Tu contenido existente se mantiene sin cambios.',
    clockSkew: 'La hora de tu dispositivo es anterior a la de los registros guardados. Comprueba la fecha y la hora, y vuelve a enviar la solicitud cuando haya pasado la hora del registro guardado. Se conservan tu texto y tus registros.',
    retry: 'Comprobar de nuevo el estado de guardado',
    billingTag: 'Aviso de uso',
  },
  fr: {
    'bill.watch.t': 'Les crédits sont épuisés ; passage temporaire en mode veille',
    'bill.watch.b': 'Les règles stop-loss et take-profit en cours restent actives. Rechargez ou associez un compte pour reprendre immédiatement.',
    'bill.recover.t': 'Les fonctions d’IA sont de nouveau activées',
    'bill.recover.b': 'Les crédits ont été rechargés et toutes les fonctions sont de nouveau disponibles.',
    'bill.uid.novol.t': 'Aucune transaction récente : les recharges de crédits sont suspendues',
    'bill.uid.novol.b': 'Votre stratégie a peut-être besoin d’être vérifiée. Lancez une nouvelle recherche pour trouver une stratégie adaptée au marché actuel.',
    'bill.uid.small.t': 'L’utilisation de l’IA dépasse votre volume de transactions',
    'bill.uid.small.b': 'Les recharges liées à votre volume actuel ne suivent pas votre utilisation. Envisagez d’augmenter votre volume ou d’ajouter une carte.',
    'bill.uid.heavy.t': 'Votre utilisation de l’IA est élevée',
    'bill.uid.heavy.b': 'Ajoutez une carte pour commencer avec 90 % de réduction. Les recharges liées au volume continuent de réduire votre facture de carte.',
    'bill.free.out.t': 'Tous les crédits de bienvenue ont été utilisés',
    'bill.free.out.b': 'Associez l’UID d’une plateforme d’échange pour continuer gratuitement, ou ajoutez une carte.',
    'bill.card.out.t': 'Tous les crédits de ce mois ont été utilisés',
    'bill.card.out.b': 'Associez un UID pour ajouter des recharges liées au volume. Les crédits se rechargent automatiquement à la prochaine date de facturation.',
    'bill.carduid.out.t': 'Tous les crédits de ce mois ont été utilisés',
    'bill.carduid.out.b': 'Les crédits se rechargent automatiquement à la prochaine date de facturation. Les recharges liées au volume continuent de réduire votre prochaine facture.',
    'bill.dunning.t': 'Le paiement n’a pas abouti ; passage temporaire en mode veille',
    'bill.dunning.b': 'Vérifiez votre moyen de paiement. Les règles stop-loss et take-profit en cours restent actives et tout reprend dès le paiement.',
    'bill.card.cross.t': 'Réduisez votre facture en associant une plateforme d’échange',
    'bill.card.cross.b': 'Associez un UID pour gagner des crédits selon votre volume et réduire votre prochaine facture. Inclut 100 $ de crédits d’IA.',
    standby: 'En veille',
    standbyValue: 'Veille',
    standbyDescription: 'Les fonctions d’IA sont temporairement en pause, car vos crédits sont épuisés. La gestion stop-loss et take-profit en cours est maintenue et reprend dès la recharge ou l’association d’une plateforme.',
    blocked: 'Les fonctions d’IA sont temporairement en pause, car vos crédits sont épuisés',
    storageError: 'Nous n’avons pas pu vérifier l’état d’utilisation de ce navigateur. Nous avons conservé l’historique existant et suspendu les nouvelles demandes.',
    unavailable: 'Nous n’avons pas pu vérifier votre état d’utilisation ; la demande n’a donc pas été envoyée. Vérifiez la date, l’heure et l’état du stockage de votre appareil, puis réessayez. Votre contenu existant reste inchangé.',
    clockSkew: 'L’heure de votre appareil est antérieure à celle des enregistrements sauvegardés. Vérifiez la date et l’heure, puis renvoyez votre demande une fois l’heure enregistrée dépassée. Votre saisie et vos enregistrements sont conservés.',
    retry: 'Vérifier à nouveau l’état de sauvegarde',
    billingTag: 'Avis d’utilisation',
  },
} satisfies Record<ClientLanguage, Record<BillingCopyKey, string>>

export function billingText(language: ClientLanguage, key: BillingCopyKey): string {
  return BILLING_COPY[language][key]
}
