import type { ClientLanguage } from '../client-preferences'
const words = {
  title: ['전략 실행', 'Strategy execution', '戦略の実行', '策略执行', '策略執行', 'Ejecución de estrategia', 'Exécution de stratégie'],
  method: ['실행 방법', 'Execution method', '実行方法', '执行方式', '執行方式', 'Método de ejecución', 'Mode d’exécution'],
  exchange: ['거래소 연결', 'Exchange connection', '取引所の接続', '交易所连接', '交易所連接', 'Conectar exchange', 'Connexion à la plateforme'],
  verify: ['연결 확인', 'Connection check', '接続確認', '连接确认', '連接確認', 'Verificar conexión', 'Vérifier la connexion'],
  start: ['시작', 'Start', '開始', '开始', '開始', 'Iniciar', 'Démarrer'],
  methodTitle: ['어떻게 실행할까요?', 'How would you like to run it?', 'どの方法で実行しますか？', '您想如何执行？', '您想如何執行？', '¿Cómo quieres ejecutarla?', 'Comment souhaitez-vous l’exécuter ?'],
  planTitle: ['결제 주기를 선택해주세요', 'Choose a billing cycle', 'お支払い周期を選択してください', '请选择付款周期', '請選擇付款週期', 'Elige el ciclo de facturación', 'Choisissez la périodicité'],
  payment: ['결제 정보', 'Payment details', 'お支払い情報', '付款信息', '付款資訊', 'Datos de pago', 'Informations de paiement'],
  paymentConfirm: ['결제 확인', 'Confirm payment', 'お支払い確認', '确认付款', '確認付款', 'Confirmar pago', 'Confirmer le paiement'],
  exchangeTitle: ['바로 연결할 거래소를 선택해주세요.', 'Choose an exchange to connect.', '接続する取引所を選択してください。', '请选择要连接的交易所。', '請選擇要連接的交易所。', 'Elige un exchange para conectar.', 'Choisissez la plateforme à connecter.'],
  complete: ['준비가 끝났어요', 'You are ready', '準備が整いました', '准备就绪', '準備就緒', 'Todo listo', 'Tout est prêt'],
  back: ['이전', 'Back', '戻る', '返回', '返回', 'Volver', 'Retour'],
  continue: ['계속', 'Continue', '続ける', '继续', '繼續', 'Continuar', 'Continuer'],
  choose: ['선택', 'Select', '選択', '选择', '選擇', 'Seleccionar', 'Sélectionner'],
  pending: ['확인 중...', 'Checking…', '確認中…', '确认中…', '確認中…', 'Verificando…', 'Vérification…'],
  accepted: ['요청을 전달했습니다. 확인된 상태를 기다리고 있어요.', 'Request submitted. Waiting for confirmed status.', '送信しました。確認済みの状態を待っています。', '请求已提交，正在等待确认状态。', '請求已提交，正在等待確認狀態。', 'Solicitud enviada. Esperando confirmación.', 'Demande envoyée. En attente de confirmation.'],
  failed: ['요청을 완료하지 못했어요. 입력 내용을 확인하고 다시 시도해주세요.', 'Could not complete the request. Check your input and try again.', '処理できませんでした。入力を確認して再試行してください。', '无法完成请求，请检查输入后重试。', '無法完成請求，請檢查輸入後重試。', 'No se pudo completar. Revisa los datos e inténtalo de nuevo.', 'La demande a échoué. Vérifiez la saisie et réessayez.'],
  unavailable: ['아직 연결 정보가 제공되지 않았습니다.', 'Connection information is not available yet.', '接続情報はまだ提供されていません。', '尚未提供连接信息。', '尚未提供連接資訊。', 'La información de conexión aún no está disponible.', 'Les informations de connexion ne sont pas encore disponibles.'],
  empty: ['선택 가능한 항목이 없습니다.', 'No options are available.', '選択できる項目はありません。', '暂无可选项目。', '暫無可選項目。', 'No hay opciones disponibles.', 'Aucune option disponible.'],
  hosted: ['안전한 결제 화면에서 카드 정보를 입력해주세요.', 'Enter card details on the secure payment page.', '安全なお支払い画面でカード情報を入力してください。', '请在安全付款页面输入银行卡信息。', '請在安全付款頁面輸入信用卡資訊。', 'Introduce los datos de tarjeta en la página de pago segura.', 'Saisissez votre carte sur la page de paiement sécurisée.'],
  checkout: ['결제 화면 열기', 'Open payment page', 'お支払い画面を開く', '打开付款页面', '開啟付款頁面', 'Abrir pago', 'Ouvrir le paiement'],
  joined: ['가입 완료했어요', 'I have signed up', '登録が完了しました', '已完成注册', '已完成註冊', 'Ya me registré', 'Inscription terminée'],
  signup: ['가입', 'Sign up', '登録', '注册', '註冊', 'Registrarse', 'Inscription'],
  returnAfter: ['가입을 완료한 뒤 이 화면으로 돌아오세요.', 'Return here after signing up.', '登録後、この画面に戻ってください。', '完成注册后请返回此页面。', '完成註冊後請返回此頁面。', 'Vuelve aquí después de registrarte.', 'Revenez ici après votre inscription.'],
  signupLink: ['가입 링크 열기', 'Open sign-up link', '登録リンクを開く', '打开注册链接', '開啟註冊連結', 'Abrir registro', 'Ouvrir l’inscription'],
  uid: ['UID 연동', 'Link UID', 'UID連携', '关联 UID', '連結 UID', 'Vincular UID', 'Associer l’UID'],
  uidGuide: ['UID가 어디 있어요?', 'Where is my UID?', 'UIDはどこにありますか？', '在哪里查看 UID？', '在哪裡查看 UID？', '¿Dónde encuentro mi UID?', 'Où trouver mon UID ?'],
  uidInvalid: ['UID 숫자 5~12자리를 확인해주세요', 'Enter a 5–12 digit UID.', 'UIDを5～12桁の数字で入力してください。', '请输入 5 至 12 位数字 UID。', '請輸入 5 至 12 位數字 UID。', 'Introduce un UID de 5 a 12 dígitos.', 'Saisissez un UID de 5 à 12 chiffres.'],
  verifyUid: ['연동 확인하기', 'Verify link', '連携を確認する', '验证关联', '驗證連結', 'Verificar vínculo', 'Vérifier l’association'],
  api: ['API 연결', 'API connection', 'API接続', 'API 连接', 'API 連接', 'Conexión API', 'Connexion API'],
  apiGuide: ['발급 방법 보기', 'View setup guide', '発行方法を見る', '查看申请指南', '查看申請指南', 'Ver guía de configuración', 'Voir le guide de configuration'],
  apiInvalid: ['API Key와 Secret Key는 10자 이상, 필요한 Passphrase를 확인해주세요.', 'Use at least 10 characters for each key and provide the required passphrase.', '各キーは10文字以上で、必要なPassphraseも入力してください。', '每个密钥至少 10 个字符，并输入必填口令。', '每個金鑰至少 10 個字元，並輸入必填口令。', 'Cada clave necesita al menos 10 caracteres y la frase requerida.', 'Chaque clé doit avoir au moins 10 caractères, avec la phrase requise.'],
  connect: ['권한 확인하고 연결하기', 'Verify permissions and connect', '権限を確認して接続', '验证权限并连接', '驗證權限並連接', 'Verificar permisos y conectar', 'Vérifier les droits et connecter'],
  guide: ['가이드', 'Guide', 'ガイド', '指南', '指南', 'Guía', 'Guide'],
  close: ['가이드 닫기', 'Close guide', 'ガイドを閉じる', '关闭指南', '關閉指南', 'Cerrar guía', 'Fermer le guide'],
  official: ['공식 안내 열기', 'Open official guide', '公式ガイドを開く', '打开官方指南', '開啟官方指南', 'Abrir guía oficial', 'Ouvrir le guide officiel'],
  requested: ['요청', 'Requested', '要求', '请求', '請求', 'Solicitado', 'Demandé'],
  notRequested: ['요청 안 함', 'Not requested', '要求しない', '不请求', '不請求', 'No solicitado', 'Non demandé'],
} as const
export type ConnectionCopyKey = keyof typeof words
export function connectionCopy(language: ClientLanguage, key: ConnectionCopyKey) {
  return words[key][({ ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const)[language]]
}
