import {
  ApiV11Error, TesiaChronologicalFillV11Client,
  type ChronologicalFillTransport,
} from './contracts/generated/api-v0.11/client'
import type { ChronologicalFillRequest } from './contracts/generated/api-v0.11/types'
import operation from './contracts/generated/api-v0.11/operation-manifest.json'

// Contracts39: exact generated bytes, private candidate, not an HTTP producer.
export const CHRONOLOGICAL_FILL_CONTRACTS_COMMIT = '830da2d2d4194be0de82e9509b3d7a20dcde51dc'
const READ_PATH = /^\/api\/v11\/backtests\/[A-Za-z0-9_-]+\/chronological-fill-markers$/
class FillProtocolRejection extends Error {}

/** One visual reader's browser I/O. JSON, hashes and protocol-header semantics
 * belong exclusively to the immutable SDK. No result/job request is cancelled.
 */
export class NativeChronologicalFillTransport implements ChronologicalFillTransport {
  private readonly requests = new Set<AbortController>()
  private disposed = false
  private readonly ownerSignal?: AbortSignal
  private readonly onOwnerAbort = () => this.dispose()

  constructor(ownerSignal?: AbortSignal) {
    this.ownerSignal = ownerSignal
    if (ownerSignal?.aborted) this.disposed = true
    else ownerSignal?.addEventListener('abort', this.onOwnerAbort, { once: true })
  }

  dispose(): void {
    this.disposed = true
    this.ownerSignal?.removeEventListener('abort', this.onOwnerAbort)
    for (const request of this.requests) request.abort()
    this.requests.clear()
  }

  assertActive(): void {
    if (this.disposed || this.ownerSignal?.aborted) throw new ApiV11Error('TRANSPORT_FAILED')
  }

  async request(request: Parameters<ChronologicalFillTransport['request']>[0]): Promise<Awaited<ReturnType<ChronologicalFillTransport['request']>>> {
    this.assertActive()
    if (typeof request.path !== 'string' || new TextEncoder().encode(request.path).byteLength > operation.maxRequestTargetBytes) {
      throw new FillProtocolRejection('FILL_REQUEST_REJECTED')
    }
    const origin = window.location.origin, url = new URL(request.path, origin)
    const local = ['127.0.0.1', 'localhost', '[::1]'].includes(url.hostname)
    const queryKeys = [...url.searchParams.keys()]
    if ((url.protocol !== 'https:' && !(url.protocol === 'http:' && local))
      || url.origin !== origin || url.username || url.password || url.hash
      || !request.path.startsWith('/api/') || request.path.startsWith('//')
      || `${url.pathname}${url.search}` !== request.path || !READ_PATH.test(url.pathname)
      || request.method !== operation.method || request.credentials !== 'include'
      || request.redirect !== 'manual' || request.cache !== 'no-store'
      || new Set(queryKeys).size !== queryKeys.length
      || queryKeys.some(key => !operation.queryKeys.includes(key))
      || operation.requiredQueryKeys.some(key => !url.searchParams.has(key))) {
      throw new FillProtocolRejection('FILL_REQUEST_REJECTED')
    }
    const requestHeaders = Object.entries(request.headers)
    if (requestHeaders.length !== 1 || requestHeaders[0][0].toLowerCase() !== 'accept'
      || requestHeaders[0][1] !== 'application/json') throw new FillProtocolRejection('FILL_REQUEST_REJECTED')

    const controller = new AbortController()
    this.requests.add(controller)
    const timer = window.setTimeout(() => controller.abort(), 30_000)
    let response: Response | undefined, reader: ReadableStreamDefaultReader<Uint8Array> | undefined
    const assertCurrent = () => {
      this.assertActive()
      if (controller.signal.aborted) throw new ApiV11Error('TRANSPORT_FAILED')
    }
    try {
      response = await fetch(url.href, { method: 'GET', headers: { Accept: 'application/json' },
        credentials: 'include', redirect: 'manual', cache: 'no-store', signal: controller.signal })
      assertCurrent()
      if (response.type === 'opaqueredirect' || response.redirected || response.url !== url.href || response.body === null) {
        throw new FillProtocolRejection('FILL_RESPONSE_REJECTED')
      }
      const declared = response.headers.get('content-length')
      if (declared !== null && (!/^(0|[1-9][0-9]*)$/.test(declared) || Number(declared) > operation.maxResponseBytes)) {
        throw new FillProtocolRejection('FILL_RESPONSE_TOO_LARGE')
      }
      reader = response.body.getReader()
      // Preserve U+FEFF: the SDK explicitly rejects a JSON BOM. The decoder's
      // default would silently strip it and turn invalid wire bytes into valid JSON.
      const decoder = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true })
      let body = '', size = 0
      for (;;) {
        const { done, value } = await reader.read()
        assertCurrent()
        if (done) break
        size += value.byteLength
        if (size > operation.maxResponseBytes) throw new FillProtocolRejection('FILL_RESPONSE_TOO_LARGE')
        try { body += decoder.decode(value, { stream: true }) }
        catch { throw new FillProtocolRejection('FILL_RESPONSE_REJECTED') }
      }
      try { body += decoder.decode() }
      catch { throw new FillProtocolRejection('FILL_RESPONSE_REJECTED') }
      // Preserve Fetch-observable combined values. Do not split conflicting
      // cache-control/ETag/content-type/authentication headers into valid parts.
      const headers = Object.freeze([...response.headers.entries()].map(([name, value]) => Object.freeze([name, value] as const)))
      return { status: response.status, headers, body }
    } finally {
      window.clearTimeout(timer)
      controller.abort()
      if (reader) { void reader.cancel().catch(() => undefined); reader.releaseLock() }
      else if (response?.body) { void response.body.cancel().catch(() => undefined) }
      this.requests.delete(controller)
    }
  }
}

/** SDK-only consumer; no pagination, retry, schema copy or source attestation. */
export function createNativeChronologicalFillClient(ownerSignal?: AbortSignal) {
  const transport = new NativeChronologicalFillTransport(ownerSignal)
  return {
    async read(request: ChronologicalFillRequest) {
      transport.assertActive()
      // This flag is per call: concurrent network/protocol failures cannot leak.
      let rejected = false
      const client = new TesiaChronologicalFillV11Client({ request: async input => {
        try { return await transport.request(input) }
        catch (failure) { rejected = failure instanceof FillProtocolRejection; throw failure }
      } })
      try {
        const result = await client.getChronologicalFillMarkersV11(request)
        transport.assertActive() // Hash validation is asynchronous too.
        return result
      } catch (failure) {
        if (rejected && failure instanceof ApiV11Error && failure.code === 'TRANSPORT_FAILED') {
          throw new ApiV11Error('INVALID_RESPONSE')
        }
        throw failure
      }
    },
    dispose: () => transport.dispose(),
  }
}
