import type { ClientLanguage } from '../client-preferences'

// Presentation only. Korean UI copy is preserved; never translate server
// messages, user content, stored titles, or authority-bearing request values.
type Translations = readonly [string, string, string, string, string, string, string]
const column = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const satisfies Record<ClientLanguage, number>
export const nativeShellCopy = {
  // Reuse the existing common linkError wording from client-upgrade-copy.
  resetFailed: ['요청을 완료하지 못했습니다. 다시 시도해주세요.', 'The request could not be completed. Please try again.', 'リクエストを完了できませんでした。もう一度お試しください。', '请求未能完成。请重试。', '請求未能完成。請重試。', 'No se pudo completar la solicitud. Inténtalo de nuevo.', 'La demande n’a pas pu aboutir. Veuillez réessayer.'],
  requestTitle: ["서버 응답 확인","Checking server response","サーバー応答の確認","检查服务器响应","檢查伺服器回應","Comprobando la respuesta del servidor","Vérification de la réponse du serveur"],
  requestDetail: ["요청을 보냈습니다. 응답이 도착하면 이 대화에 이어집니다.","The request has been sent. When the response arrives, it will continue in this conversation.","リクエストを送信しました。応答が届くと、この会話に続けて表示されます。","请求已发送。响应到达后将接续在此对话中。","請求已送出。回應抵達後會接續在此對話中。","Se envió la solicitud. Cuando llegue la respuesta, continuará en esta conversación.","La requête a été envoyée. Dès que la réponse arrivera, elle s'affichera à la suite de cette conversation."],
  unavailable: ["이 기능은 이 내부 서비스에 아직 연결되지 않았습니다. 현재 대화는 그대로 유지됩니다.","This feature is not connected to this internal service yet. The current conversation stays as it is.","この機能はこの内部サービスにまだ接続されていません。現在の会話はそのまま保持されます。","此功能尚未接入该内部服务。当前对话将保持不变。","此功能尚未接上此內部服務。目前的對話會保持不變。","Esta función aún no está conectada a este servicio interno. La conversación actual se mantiene igual.","Cette fonctionnalité n'est pas encore connectée à ce service interne. La conversation en cours est conservée telle quelle."],
  featureUnavailable: ["{feature} 기능은 이 내부 서비스에 아직 연결되지 않았습니다. 현재 대화는 그대로 유지됩니다.","The {feature} feature is not connected to this internal service yet. The current conversation stays as it is.","{feature} 機能はこの内部サービスにまだ接続されていません。現在の会話はそのまま保持されます。","{feature} 功能尚未接入该内部服务。当前对话将保持不变。","{feature} 功能尚未接上此內部服務。目前的對話會保持不變。","La función {feature} aún no está conectada a este servicio interno. La conversación actual se mantiene igual.","La fonctionnalité {feature} n'est pas encore connectée à ce service interne. La conversation en cours est conservée telle quelle."],
  questionLimit: ["템플릿을 포함한 질문은 1,000자까지 보낼 수 있습니다. 내용을 조금 줄여주세요.","Questions, including the template, can be up to 1,000 characters. Please shorten your text a little.","テンプレートを含む質問は1,000文字まで送信できます。内容を少し短くしてください。","包含模板在内的问题最多可发送 1,000 个字符。请稍微精简内容。","包含範本在內的問題最多可傳送 1,000 個字元。請稍微精簡內容。","Las preguntas, incluida la plantilla, pueden tener hasta 1000 caracteres. Reduce un poco el contenido.","Les questions, modèle inclus, peuvent contenir jusqu'à 1 000 caractères. Veuillez raccourcir un peu le contenu."],
  busyReset: ["요청을 처리 중입니다. 응답을 확인한 뒤 새 전략을 시작해주세요.","A request is being processed. Please start a new strategy after reviewing the response.","リクエストを処理中です。応答を確認してから新しい戦略を開始してください。","正在处理请求。请在查看响应后再开始新策略。","正在處理請求。請在查看回應後再開始新策略。","Se está procesando una solicitud. Inicia una nueva estrategia después de revisar la respuesta.","Une requête est en cours de traitement. Veuillez lancer une nouvelle stratégie après avoir consulté la réponse."],
  recovered: ["서버에서 진행 상태를 다시 확인했습니다. 이전 대화 내용은 복원하지 않았습니다.","The progress state was retrieved from the server again. The previous conversation content was not restored.","サーバーから進行状況を再取得しました。以前の会話内容は復元していません。","已从服务器重新获取进度状态。此前的对话内容未恢复。","已從伺服器重新取得進度狀態。先前的對話內容未還原。","Se volvió a consultar el estado de progreso en el servidor. El contenido de la conversación anterior no se restauró.","L'état d'avancement a été de nouveau récupéré depuis le serveur. Le contenu de la conversation précédente n'a pas été restauré."],
  recoveredLocked: ["아래 문서에서 진행 상태와 다음 단계를 확인해주세요.","Check the progress and next steps in the document below.","以下のドキュメントで進行状況と次のステップをご確認ください。","请在下方文档中查看进度和后续步骤。","請在下方文件中查看進度與後續步驟。","Consulta el progreso y los siguientes pasos en el documento de abajo.","Consultez l'avancement et les étapes suivantes dans le document ci-dessous."],
  recoveredDraft: ["아래 초안을 확인하고 대화를 이어가세요.","Review the draft below and continue the conversation.","以下の下書きを確認して会話を続けてください。","请查看下方草稿并继续对话。","請查看下方草稿並繼續對話。","Revisa el borrador de abajo y continúa la conversación.","Consultez le brouillon ci-dessous et poursuivez la conversation."],
  unrecoverable: ["현재 세션에서 이전 초안을 이어갈 수 없어 새 대화를 준비했습니다. 서버 초안은 삭제하지 않았습니다.","The previous draft can't be continued in this session, so a new conversation has been prepared. The draft on the server was not deleted.","現在のセッションでは以前の下書きを続けられないため、新しい会話を用意しました。サーバー上の下書きは削除していません。","当前会话无法继续之前的草稿，因此已准备新的对话。服务器上的草稿未被删除。","目前工作階段無法接續先前的草稿，因此已準備新的對話。伺服器上的草稿並未刪除。","En esta sesión no se puede continuar el borrador anterior, así que se preparó una conversación nueva. El borrador del servidor no se eliminó.","Le brouillon précédent ne peut pas être repris dans cette session ; une nouvelle conversation a donc été préparée. Le brouillon sur le serveur n'a pas été supprimé."],
  unavailableLink: ["이 링크는 현재 서비스에서 열 수 없습니다. 대화와 입력 내용은 그대로 유지됩니다.","This link can't be opened in the current service. Your conversation and input are kept as they are.","このリンクは現在のサービスでは開けません。会話と入力内容はそのまま保持されます。","当前服务中无法打开此链接。对话和输入内容将保持不变。","目前服務中無法開啟此連結。對話與輸入內容會保持不變。","Este enlace no se puede abrir en el servicio actual. La conversación y lo que has escrito se mantienen.","Ce lien ne peut pas être ouvert dans le service actuel. La conversation et votre saisie sont conservées."],
  publicLink: ["약관·소개·다운로드 페이지는 공개 UI 검수 화면에서 볼 수 있습니다. 이 내부 연결에서는 현재 대화를 유지합니다.","The terms, about, and download pages can be viewed on the public UI review screen. In this internal connection, the current conversation is kept.","利用規約・紹介・ダウンロードの各ページは公開UI検証画面で確認できます。この内部接続では現在の会話を維持します。","条款、介绍和下载页面可在公开 UI 验收界面查看。在此内部连接中将保持当前对话。","條款、介紹與下載頁面可在公開 UI 驗收畫面查看。在此內部連線中會保持目前的對話。","Las páginas de términos, información y descargas se pueden ver en la pantalla pública de revisión de la interfaz. En esta conexión interna se mantiene la conversación actual.","Les pages Conditions, Présentation et Téléchargement sont consultables sur l'écran public de revue de l'interface. Dans cette connexion interne, la conversation en cours est conservée."],
  strategyDraft: ["전략 초안","Strategy draft","戦略ドラフト","策略草稿","策略草稿","Borrador de estrategia","Brouillon de stratégie"],
  openStrategyDraft: ["현재 서버 전략 초안 열기","Open current server strategy draft","現在のサーバー戦略ドラフトを開く","打开当前服务器策略草稿","開啟目前伺服器策略草稿","Abrir el borrador de estrategia actual del servidor","Ouvrir le brouillon de stratégie actuel du serveur"],
  loggedOut: ["로그아웃 응답을 확인했습니다.","The logout response was received.","ログアウトの応答を確認しました。","已收到登出响应。","已收到登出回應。","Se recibió la respuesta de cierre de sesión.","La réponse de déconnexion a été reçue."],
  loggedOutDetail: ["이 세션은 종료되었습니다. 새 세션에서 다시 시작할 수 있습니다.","This session has ended. You can start again in a new session.","このセッションは終了しました。新しいセッションで再開できます。","此会话已结束。你可以在新会话中重新开始。","此工作階段已結束。你可以在新的工作階段中重新開始。","Esta sesión ha finalizado. Puedes empezar de nuevo en una sesión nueva.","Cette session est terminée. Vous pouvez recommencer dans une nouvelle session."],
  uncertainDelivery: ["이 메시지의 응답을 확인하지 못했습니다.","The response to this message could not be confirmed.","このメッセージの応答を確認できませんでした。","未能确认此消息的响应。","未能確認此訊息的回應。","No se pudo confirmar la respuesta a este mensaje.","La réponse à ce message n'a pas pu être confirmée."],
  quickReplies: ["추가 확인","Additional checks","追加確認","补充确认","補充確認","Comprobaciones adicionales","Vérifications supplémentaires"],
  strategyReview: ["서버 전략 검토","Server strategy review","サーバー戦略のレビュー","服务器策略审阅","伺服器策略審閱","Revisión de la estrategia del servidor","Revue de la stratégie du serveur"],
  newSession: ["새 세션 시작","Start new session","新しいセッションを開始","开始新会话","開始新工作階段","Empezar una sesión nueva","Démarrer une nouvelle session"],
  checkSession: ["세션 다시 확인","Check session again","セッションを再確認","重新检查会话","重新檢查工作階段","Volver a comprobar la sesión","Revérifier la session"],
  resetConfirm: ["새 전략을 시작하면 현재 화면의 대화는 사라집니다. 서버 작업을 취소하는 동작은 아닙니다.","Starting a new strategy clears the conversation on this screen. It does not cancel the work on the server.","新しい戦略を開始すると、現在の画面の会話は消えます。サーバー上の処理を取り消す操作ではありません。","开始新策略后，当前界面的对话将消失。此操作不会取消服务器上的处理。","開始新策略後，目前畫面的對話將消失。此操作不會取消伺服器上的處理。","Si inicias una nueva estrategia, la conversación de esta pantalla desaparecerá. No es una acción que cancele el trabajo en el servidor.","Si vous lancez une nouvelle stratégie, la conversation affichée à l'écran disparaîtra. Cette action n'annule pas le traitement côté serveur."],
  startStrategy: ["새 전략 시작","Start new strategy","新しい戦略を開始","开始新策略","開始新策略","Empezar una nueva estrategia","Lancer une nouvelle stratégie"],
  environment: ["로컬 연결 환경","Local connection environment","ローカル接続環境","本地连接环境","本機連線環境","Entorno de conexión local","Environnement de connexion locale"],
  mockSummary: ["Mock fixture 검수","Mock fixture review","Mock fixture 検証","Mock fixture 验收","Mock fixture 驗收","Revisión de mock fixture","Revue des mock fixtures"],
  serviceSummary: ["내부 서비스 연결 · 공개 배포 아님","Internal service connection · not a public deployment","内部サービス接続 · 一般公開ではありません","内部服务连接 · 非公开发布","內部服務連線 · 非公開發布","Conexión a servicio interno · no es un despliegue público","Connexion au service interne · pas un déploiement public"],
  mockDetail: ["자동화 시험용 고정 응답입니다. 실제 서버 결과가 아닙니다.","This is a fixed response for automated testing. It is not an actual server result.","自動テスト用の固定応答です。実際のサーバーの結果ではありません。","这是用于自动化测试的固定响应，并非实际的服务器结果。","這是用於自動化測試的固定回應，並非實際的伺服器結果。","Es una respuesta fija para pruebas automatizadas. No es un resultado real del servidor.","Il s'agit d'une réponse fixe destinée aux tests automatisés. Ce n'est pas un résultat réel du serveur."],
} as const satisfies Record<string, Translations>
export type NativeShellCopyKey = keyof typeof nativeShellCopy
export function nativeShellText(language: ClientLanguage, key: NativeShellCopyKey, feature = ''): string {
  // A callback replacement keeps $ characters in a supplied label literal.
  return nativeShellCopy[key][column[language]].replace('{feature}', () => feature)
}
