import type { ClientLanguage } from '../client-preferences'

type Translations = readonly [string, string, string, string, string, string, string]
const column = { ko: 0, en: 1, ja: 2, 'zh-CN': 3, 'zh-TW': 4, es: 5, fr: 6 } as const satisfies Record<ClientLanguage, number>
const copy = {
  unavailable: ['아직 공급된 계정 데이터가 없습니다.', 'Account data has not been supplied yet.', '口座データはまだ提供されていません。', '尚未提供账户数据。', '尚未提供帳戶資料。', 'Aún no se han proporcionado datos de la cuenta.', 'Les données du compte n’ont pas encore été fournies.'],
  connectedUnavailable: ['거래소는 연결되어 있습니다. 아직 표시할 데이터가 없습니다.', 'Your exchange is connected. There is no data to display yet.', '取引所は接続されています。表示できるデータはまだありません。', '交易所已连接，暂时没有可显示的数据。', '交易所已連接，暫時沒有可顯示的資料。', 'Tu exchange está conectado. Aún no hay datos para mostrar.', 'Votre plateforme est connectée. Aucune donnée à afficher pour le moment.'],
  accountPermissionRejected: ['계정 데이터 조회가 거부되었습니다. Bitget의 연결 권한과 API 설정을 확인해주세요.', 'Account data access was denied. Check your connection permissions and API settings in Bitget.', '口座データへのアクセスが拒否されました。Bitgetの接続権限とAPI設定を確認してください。', '账户数据访问被拒绝。请检查 Bitget 的连接权限和 API 设置。', '帳戶資料存取被拒絕。請檢查 Bitget 的連接權限與 API 設定。', 'Se denegó el acceso a los datos de la cuenta. Revisa los permisos de conexión y la configuración de API en Bitget.', 'L’accès aux données du compte a été refusé. Vérifiez les autorisations de connexion et les paramètres API dans Bitget.'],
  accountTemporarilyUnavailable: ['계정 데이터를 일시적으로 조회하지 못했습니다. 잠시 후 다시 확인합니다.', 'Account data could not be loaded temporarily. We will check again shortly.', '口座データを一時的に取得できませんでした。まもなく再確認します。', '暂时无法获取账户数据，稍后将再次检查。', '暫時無法取得帳戶資料，稍後將再次檢查。', 'No se pudieron cargar los datos de la cuenta temporalmente. Volveremos a comprobarlos en breve.', 'Les données du compte sont temporairement indisponibles. Nous réessaierons dans un instant.'],
  accountRateLimited: ['계정 데이터 조회가 잠시 제한되었습니다. 잠시 후 다시 확인합니다.', 'Account data requests are temporarily limited. We will check again shortly.', '口座データの取得が一時的に制限されています。まもなく再確認します。', '账户数据请求暂时受限，稍后将再次检查。', '帳戶資料請求暫時受限，稍後將再次檢查。', 'Las consultas de datos de la cuenta están temporalmente limitadas. Volveremos a comprobarlas en breve.', 'Les demandes de données du compte sont temporairement limitées. Nous réessaierons dans un instant.'],
  accountScopeUnavailable: ['일부 계정 데이터를 조회할 수 없습니다.', 'Some account data cannot be retrieved.', '一部の口座データを取得できません。', '无法获取部分账户数据。', '無法取得部分帳戶資料。', 'No se pueden consultar algunos datos de la cuenta.', 'Certaines données du compte ne peuvent pas être récupérées.'],
  empty: ['해당 기록이 없습니다.', 'There are no matching records.', '該当する記録はありません。', '没有相应记录。', '沒有相應紀錄。', 'No hay registros correspondientes.', 'Aucun enregistrement correspondant.'],
  failed: ['요청을 완료하지 못했습니다. 다시 시도해주세요.', 'Could not complete the request. Please try again.', '処理を完了できませんでした。再試行してください。', '未能完成请求，请重试。', '無法完成要求，請重試。', 'No se pudo completar. Inténtalo de nuevo.', 'Impossible de terminer. Réessayez.'],
  accepted: ['요청을 전달했습니다. 갱신된 계정 기록을 확인해주세요.', 'Request submitted. Check the updated account records.', '要求を送信しました。更新された口座記録を確認してください。', '请求已提交，请查看更新后的账户记录。', '要求已送出，請查看更新後的帳戶紀錄。', 'Solicitud enviada. Consulta los registros actualizados.', 'Demande transmise. Consultez les données actualisées du compte.'],
  pending: ['처리 중', 'Pending', '処理中', '处理中', '處理中', 'En curso', 'En cours'],
  stopNotice: ['전략 중지 요청이며 포지션 청산 요청이 아닙니다.', 'This is a request to stop the strategy, not to close positions.', '戦略の停止リクエストであり、ポジションの決済リクエストではありません。', '此为停止策略请求，并非平仓请求。', '此為停止策略請求，並非平倉請求。', 'Esta es una solicitud para detener la estrategia, no para cerrar posiciones.', 'Il s’agit d’une demande d’arrêt de la stratégie, et non d’une clôture de positions.'],
  accounts: ['계정 상세', 'Account details', '口座詳細', '账户详情', '帳戶詳情', 'Detalles de la cuenta', 'Détails du compte'],
  detail: ['상세 보기', 'View details', '詳細を見る', '查看详情', '查看詳情', 'Ver detalles', 'Voir les détails'],
  publicEvidence: ['공급된 공개 관측 기록', 'Supplied public observations', '提供された公開観測記録', '提供的公开观测记录', '提供的公開觀測紀錄', 'Observaciones públicas proporcionadas', 'Observations publiques fournies'],
  exchange: ['거래소', 'Exchange', '取引所', '交易所', '交易所', 'Exchange', 'Plateforme'],
  strategy: ['전략', 'Strategy', '戦略', '策略', '策略', 'Estrategia', 'Stratégie'],
  symbol: ['심볼', 'Symbol', '銘柄', '交易代码', '交易代碼', 'Símbolo', 'Symbole'],
  side: ['방향', 'Side', '方向', '方向', '方向', 'Lado', 'Sens'],
  quantity: ['수량', 'Quantity', '数量', '数量', '數量', 'Cantidad', 'Quantité'],
  entry: ['진입가', 'Entry price', 'エントリー価格', '开仓价', '開倉價', 'Precio de entrada', 'Prix d’entrée'],
  current: ['현재가', 'Current price', '現在値', '现价', '現價', 'Precio actual', 'Prix actuel'],
  stop: ['손절가', 'Stop price', '損切り価格', '止损价', '停損價', 'Precio de stop', 'Prix stop'],
  unrealized: ['미실현', 'Unrealized', '未実現', '未实现', '未實現', 'No realizado', 'Non réalisé'],
  percent: ['%', '%', '%', '%', '%', '%', '%'],
  type: ['유형', 'Type', '種類', '类型', '類型', 'Tipo', 'Type'],
  price: ['가격', 'Price', '価格', '价格', '價格', 'Precio', 'Prix'],
  status: ['상태', 'Status', '状態', '状态', '狀態', 'Estado', 'État'],
  rule: ['규칙', 'Rule', 'ルール', '规则', '規則', 'Regla', 'Règle'],
  date: ['일자', 'Date', '日付', '日期', '日期', 'Fecha', 'Date'],
  fee: ['수수료', 'Fee', '手数料', '手续费', '手續費', 'Comisión', 'Frais'],
  exit: ['청산가', 'Exit price', '決済価格', '平仓价', '平倉價', 'Precio de salida', 'Prix de sortie'],
  holding: ['보유', 'Holding period', '保有期間', '持有时间', '持有時間', 'Periodo de tenencia', 'Durée de détention'],
  realized: ['실현 손익', 'Realized P&L', '実現損益', '已实现盈亏', '已實現損益', 'Resultado realizado', 'Résultat réalisé'],
  equity: ['Equity', 'Equity', '純資産', '净值', '淨值', 'Patrimonio', 'Fonds propres'],
  available: ['Available', 'Available', '利用可能', '可用', '可用', 'Disponible', 'Disponible'],
  used: ['Used', 'Used', '使用中', '已使用', '已使用', 'Utilizado', 'Utilisé'],
  message: ['TETH에게 말해보세요… 예: 손절 기준 설명', 'Ask TETH… e.g. explain the stop rule', 'TETHに質問…例：損切りルールの説明', '询问TETH…例如解释止损规则', '詢問TETH…例如解釋停損規則', 'Pregunta a TETH… p. ej., explica la regla de stop', 'Demandez à TETH… ex. : expliquer la règle stop'],
  send: ['보내기', 'Send', '送信', '发送', '傳送', 'Enviar', 'Envoyer'],
  accountWide: ['계정 전체 범위', 'Account-wide scope', '口座全体', '整个账户', '整個帳戶', 'Toda la cuenta', 'Ensemble du compte'],
} as const satisfies Record<string, Translations>
export function nativeAccountText(language: ClientLanguage, key: keyof typeof copy) { return copy[key][column[language]] }
