import type { ClientLanguage } from '../client-preferences'

// Interface copy only. Producer-authored findings and financial values are never translated here.
const labels = {
  unavailable: ['아직 공급된 문서 데이터가 없습니다.', 'Document data is not available yet.', '文書データはまだ提供されていません。', '尚未提供文档数据。', '尚未提供文件資料。', 'Los datos del documento aún no están disponibles.', 'Les données du document ne sont pas encore disponibles.'],
  loading: ['문서를 불러오는 중', 'Loading document', '文書を読み込み中', '正在加载文档', '正在載入文件', 'Cargando documento', 'Chargement du document'],
  error: ['요청을 완료하지 못했습니다. 다시 시도해주세요.', 'The request could not be completed. Please try again.', 'リクエストを完了できませんでした。再試行してください。', '未能完成请求，请重试。', '未能完成請求，請重試。', 'No se pudo completar la solicitud. Inténtalo de nuevo.', 'La demande n’a pas abouti. Réessayez.'],
  pending: ['처리 중', 'Processing', '処理中', '处理中', '處理中', 'Procesando', 'Traitement en cours'],
  hypothesis: ['Investment Hypothesis', 'Investment Hypothesis', '投資仮説', '投资假设', '投資假設', 'Hipótesis de inversión', 'Hypothèse d’investissement'],
  plain: ['쉽게 말하면', 'In plain language', 'わかりやすく言うと', '简单来说', '簡單來說', 'En pocas palabras', 'En termes simples'],
  criteria: ['검증 기준', 'Validation criteria', '検証基準', '验证标准', '驗證標準', 'Criterios de validación', 'Critères de validation'],
  strategy: ['Strategy', 'Strategy', '戦略', '策略', '策略', 'Estrategia', 'Stratégie'],
  entry: ['진입', 'Entry', 'エントリー', '入场', '進場', 'Entrada', 'Entrée'],
  stopLoss: ['손절', 'Stop loss', '損切り', '止损', '停損', 'Límite de pérdidas', 'Seuil de perte'],
  takeProfit: ['익절', 'Take profit', '利確', '止盈', '停利', 'Toma de ganancias', 'Prise de bénéfices'],
  holding: ['최대 보유', 'Maximum holding', '最大保有期間', '最长持有', '最長持有', 'Tenencia máxima', 'Durée maximale'],
  costs: ['비용', 'Costs', 'コスト', '费用', '費用', 'Costes', 'Coûts'],
  edit: ['수정 요청', 'Request changes', '修正依頼', '请求修改', '請求修改', 'Solicitar cambios', 'Demander une modification'],
  comment: ['코멘트', 'Comment', 'コメント', '备注', '備註', 'Comentario', 'Commentaire'],
  commentHint: ['수정 요청, 예: -2%로', 'Request a change, e.g. to −2%', '修正依頼、例：−2%に', '修改请求，例如改为 −2%', '修改請求，例如改為 −2%', 'Cambio solicitado, p. ej. a −2%', 'Modification souhaitée, p. ex. à −2 %'],
  apply: ['적용', 'Apply', '適用', '应用', '套用', 'Aplicar', 'Appliquer'],
  cancel: ['취소', 'Cancel', 'キャンセル', '取消', '取消', 'Cancelar', 'Annuler'],
  backtest: ['Backtest', 'Backtest', 'バックテスト', '回测', '回測', 'Backtest', 'Backtest'],
  return: ['수익률', 'Return', 'リターン', '收益率', '報酬率', 'Rentabilidad', 'Rendement'],
  drawdown: ['최대 낙폭', 'Maximum drawdown', '最大ドローダウン', '最大回撤', '最大回撤', 'Caída máxima', 'Repli maximal'],
  winRate: ['승률', 'Win rate', '勝率', '胜率', '勝率', 'Tasa de acierto', 'Taux de réussite'],
  trades: ['거래', 'Trades', '取引', '交易', '交易', 'Operaciones', 'Transactions'],
  profitFactor: ['수익 팩터', 'Profit factor', 'プロフィットファクター', '盈利因子', '獲利因子', 'Factor de beneficio', 'Facteur de profit'],
  price: ['가격, 거래 시점, Holdout 봉인 구간', 'Price, trades and sealed holdout period', '価格・取引時点・封印されたホールドアウト期間', '价格、交易时点和封存留出区间', '價格、交易時點與封存保留區間', 'Precio, operaciones y periodo holdout sellado', 'Prix, transactions et période de réserve scellée'],
  equity: ['자산 곡선', 'Equity curve', '資産曲線', '资产曲线', '資產曲線', 'Curva de capital', 'Courbe de capital'],
  analysis: ['전문 차트 열기', 'Open professional chart', '詳細チャートを開く', '打开专业图表', '開啟專業圖表', 'Abrir gráfico profesional', 'Ouvrir le graphique professionnel'],
  byYear: ['연도별', 'By year', '年別', '按年', '按年', 'Por año', 'Par année'],
  year: ['연도', 'Year', '年', '年份', '年份', 'Año', 'Année'],
  pnl: ['손익', 'Profit / loss', '損益', '盈亏', '損益', 'Ganancia / pérdida', 'Gain / perte'],
  critic: ['Critic Review', 'Critic Review', '批判的レビュー', '批判性审查', '批判性審查', 'Revisión crítica', 'Revue critique'],
  criticFlow: ['Builder 주장 → Critic 반박 → 데이터', 'Builder claim → Critic challenge → Data', '構築担当の主張 → 批評担当の反論 → データ', '构建者主张 → 审查者质疑 → 数据', '建構者主張 → 審查者質疑 → 資料', 'Propuesta del constructor → Objeción del revisor → Datos', 'Proposition du concepteur → Objection critique → Données'],
  stress: ['Stress Test', 'Stress Test', 'ストレステスト', '压力测试', '壓力測試', 'Prueba de estrés', 'Test de résistance'],
  stressHint: ['일부러 불리한 조건에서 재검증', 'Revalidation under deliberately adverse conditions', '意図的に不利な条件で再検証', '在刻意不利的条件下重新验证', '在刻意不利的條件下重新驗證', 'Revalidación en condiciones adversas', 'Nouvelle validation en conditions défavorables'],
  scenario: ['시나리오', 'Scenario', 'シナリオ', '场景', '情境', 'Escenario', 'Scénario'],
  result: ['결과', 'Result', '結果', '结果', '結果', 'Resultado', 'Résultat'],
  verdict: ['판정', 'Verdict', '判定', '判定', '判定', 'Dictamen', 'Verdict'],
  builderRole: ['Builder', 'Builder', '構築担当', '构建者', '建構者', 'Constructor', 'Concepteur'],
  criticRole: ['Critic', 'Critic', '批評担当', '审查者', '審查者', 'Revisor crítico', 'Examinateur critique'],
  verdictRole: ['Verdict', 'Verdict', '判定', '结论', '結論', 'Dictamen', 'Conclusion'],
  holdout: ['Holdout Test', 'Holdout Test', 'ホールドアウトテスト', '留出测试', '保留資料測試', 'Prueba holdout', 'Test sur réserve'],
  annualized: ['수익 (연환산)', 'Return (annualized)', 'リターン（年率換算）', '收益（年化）', '報酬（年化）', 'Rentabilidad (anualizada)', 'Rendement (annualisé)'],
  decline: ['낙폭', 'Drawdown', 'ドローダウン', '回撤', '回撤', 'Caída', 'Repli'],
  meaning: ['의미', 'Meaning', '意味', '含义', '意義', 'Significado', 'Signification'],
  next: ['다음 행동', 'Next action', '次の対応', '下一步', '下一步', 'Siguiente acción', 'Prochaine action'],
  report: ['Final Report', 'Final Report', '最終レポート', '最终报告', '最終報告', 'Informe final', 'Rapport final'],
  researchReturn: ['연구 수익', 'Research return', '研究区間リターン', '研究区间收益', '研究區間報酬', 'Rendimiento de investigación', 'Rendement de recherche'],
  holdoutReturn: ['봉인 구간 수익', 'Holdout return', 'ホールドアウト区間リターン', '留出区间收益', '保留區間報酬', 'Rendimiento holdout', 'Rendement sur réserve'],
  evidence: ['근거', 'Evidence', '根拠', '依据', '依據', 'Evidencia', 'Éléments probants'],
  disagreement: ['의견 불일치', 'Disagreement', '見解の相違', '意见分歧', '意見分歧', 'Desacuerdo', 'Désaccord'],
  integrity: ['검증 무결성', 'Validation integrity', '検証の完全性', '验证完整性', '驗證完整性', 'Integridad de validación', 'Intégrité de la validation'],
  unknowns: ['아직 모르는 것', 'What remains unknown', 'まだ不明な点', '尚未知晓的事项', '尚未知曉的事項', 'Lo que aún no sabemos', 'Ce qui reste inconnu'],
  whatIf: ['만약에', 'What if', 'もしも', '如果', '如果', '¿Y si…?', 'Et si…'],
  fee2: ['수수료 2배', 'Double fees', '手数料2倍', '手续费翻倍', '手續費加倍', 'Comisiones dobles', 'Frais doublés'],
  delay: ['진입 1캔들 지연', 'Entry delayed by one candle', 'エントリーを1本遅延', '入场延迟一根K线', '進場延遲一根K線', 'Entrada retrasada una vela', 'Entrée retardée d’une bougie'],
  sl2: ['손절 -2%', 'Stop loss −2%', '損切り −2%', '止损 −2%', '停損 −2%', 'Límite de pérdidas −2%', 'Seuil de perte −2 %'],
  connect: ['거래소 연결', 'Connect exchange', '取引所接続', '连接交易所', '連接交易所', 'Conectar plataforma de intercambio', 'Connecter une plateforme'],
  activity: ['연구 과정 보기', 'View research activity', '研究過程を見る', '查看研究过程', '查看研究過程', 'Ver actividad de investigación', 'Voir l’activité de recherche'],
  primaryConnect: ['거래소로 간편 연결', 'Connect through exchange', '取引所から簡単接続', '通过交易所快速连接', '透過交易所快速連接', 'Conectar mediante exchange', 'Connexion via la plateforme'],
  partner: ['파트너 거래소로 시작', 'Start with partner exchange', '提携取引所で始める', '从合作交易所开始', '從合作交易所開始', 'Empezar con un exchange asociado', 'Commencer avec une plateforme partenaire'],
  balances: ['잔고, 시세 조회', 'Balances and quotes', '残高・価格の参照', '余额和行情查询', '餘額與行情查詢', 'Saldos y cotizaciones', 'Soldes et cotations'],
  orders: ['주문 실행', 'Order execution', '注文実行', '订单执行', '訂單執行', 'Ejecución de órdenes', 'Exécution d’ordres'],
  withdrawals: ['출금', 'Withdrawals', '出金', '提现', '提領', 'Retiros', 'Retraits'],
  requested: ['요청함', 'Requested', '要求する', '已请求', '已請求', 'Solicitado', 'Demandé'],
  notRequested: ['요청 안 함', 'Not requested', '要求しない', '不请求', '不請求', 'No solicitado', 'Non demandé'],
  run: ['실행 확인', 'Confirm execution', '実行確認', '确认执行', '確認執行', 'Confirmar ejecución', 'Confirmer l’exécution'],
  conditions: ['조건', 'Conditions', '条件', '条件', '條件', 'Condiciones', 'Conditions'],
  stopAndTarget: ['손절 / 익절', 'Stop loss / take profit', '損切り・利確', '止损与止盈', '停損與停利', 'Stop loss / toma de ganancias', 'Stop loss / prise de bénéfices'],
  capital: ['투자금', 'Capital', '投資金額', '投资金额', '投資金額', 'Capital', 'Capital'],
  verification: ['검증', 'Verification', '検証', '验证', '驗證', 'Verificación', 'Vérification'],
  paper: ['가상 검증으로 시작', 'Start paper validation', '仮想検証を開始', '开始模拟验证', '開始模擬驗證', 'Iniciar validación simulada', 'Démarrer la validation simulée'],
  liveStart: ['실전 시작', 'Start live', '実取引を開始', '开始实盘', '開始實盤', 'Iniciar en real', 'Démarrer en réel'],
  live: ['Live', 'Live', '運用', '运行', '運行', 'En curso', 'En cours'],
  openTrading: ['AI 트레이딩에서 열기', 'Open in AI trading', 'AIトレーディングで開く', '在AI交易中打开', '在AI交易中開啟', 'Abrir en Trading con IA', 'Ouvrir dans Trading IA'],
  recent: ['최근 활동', 'Recent activity', '最近のアクティビティ', '最近活动', '最近活動', 'Actividad reciente', 'Activité récente'],
  time: ['시각', 'Time', '時刻', '时间', '時間', 'Hora', 'Heure'],
  type: ['유형', 'Type', '種類', '类型', '類型', 'Tipo', 'Type'],
  quantity: ['수량', 'Quantity', '数量', '数量', '數量', 'Cantidad', 'Quantité'],
  reality: ['현실 점검', 'Reality check', '現実との比較', '现实检验', '現實檢驗', 'Comprobación real', 'Contrôle des conditions réelles'],
  check: ['항목', 'Check', '項目', '项目', '項目', 'Comprobación', 'Contrôle'],
  comparison: ['가정 → 관측', 'Assumed → observed', '想定 → 観測', '假设 → 观测', '假設 → 觀測', 'Supuesto → observado', 'Hypothèse → observation'],
  pause: ['일시 정지', 'Pause', '一時停止', '暂停', '暫停', 'Pausar', 'Mettre en pause'],
  resume: ['재개', 'Resume', '再開', '恢复', '繼續', 'Reanudar', 'Reprendre'],
  stop: ['전략 종료', 'Stop strategy', '戦略を終了', '结束策略', '結束策略', 'Detener estrategia', 'Arrêter la stratégie'],
  confirmStop: ['정말 종료할까요?', 'Confirm stop?', '本当に終了しますか？', '确定结束？', '確定結束？', '¿Confirmar detención?', 'Confirmer l’arrêt ?'],
} as const
export type ResearchDocumentCopyKey = keyof typeof labels
export const researchDocumentCopyRows = labels
const languages: readonly ClientLanguage[] = ['ko', 'en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr']
export function researchDocumentCopy(key: ResearchDocumentCopyKey, language: ClientLanguage): string {
  const index = languages.indexOf(language)
  return labels[key][index < 0 ? 0 : index]
}
