import type { ClientLanguage } from '../client-preferences'

const ko = {
  revision: '대화 revision {0} · 초안 revision {1}', draftRevision: '초안 revision {0} → {1}',
  proposed: '전략 변경 제안 확인', proposals: '제안 {0}개 · 기준 초안 revision {1}',
  proposalOnly: '제안은 적용이나 검증 완료를 뜻하지 않습니다.', missingMerge: '서버가 초안 적용 결과를 제공하지 않았습니다.',
  proposal: '제안 {0}: ', evidence: '사용자 근거: ', question: '추가 확인 질문', target: '대상: ', reason: '사유: ',
  scope: '지원 범위 확인', applied: '초안 반영 {0}개 확인', rejected: '초안 반영 거절', count: '서버 보고 적용 수: {0}개', path: '경로: ',
  rejectedLabel: '초안 변경 적용 거절', unsupportedLabel: '미지원 조건 확인', questionLabel: '추가 확인 필요', appliedLabel: '전략 초안 반영 확인',
  issued: '발급: ', expires: '만료: ', receipt: '검증 영수증: ', valid: '전략 검증 완료', invalid: '전략 검증 확인 필요',
  passed: '서버 초안 검증 통과', failed: '서버 초안 검증 실패',
  validNote: '해당 초안의 서버 검증을 확인했습니다. 사용자 승인이나 실행 완료를 뜻하지 않습니다.',
  invalidNote: '서버가 초안 검증 문제를 반환했습니다. 문제를 확인하고 초안을 수정한 뒤 다시 검증해주세요.',
  readyReply: '전략 조건을 정리했습니다. 초안과 변경 항목을 확인한 뒤 검증할 수 있습니다.', draftReply: '서버가 반환한 초안을 확인해주세요.',
  previousLabel: '이전 대화 탐색', previousAction: '이전 대화 서버에서 다시 확인',
  previousNote: '이 브라우저의 같은 세션에서 나간 대화 1개만 기억합니다. 현재 초안만 다시 읽으며 승인·결과는 실행 이력에서 별도로 확인합니다. 서버 작업은 취소하거나 삭제하지 않습니다.',
}
export type ObservationCopyKey = keyof typeof ko
export type ObservationNavigationError = 'read' | 'rollback' | 'write'
export const nativeObservationNavigationErrors: Record<ClientLanguage, Record<ObservationNavigationError, string>> = {
  ko: {
    read: '이전 대화 위치 저장소를 읽지 못했습니다. 현재 대화는 유지하며 자동으로 이전 대화를 조회하지 않습니다.',
    rollback: '저장소 복구를 확인하지 못해 화면 전환을 중단했습니다. 현재 화면은 유지하지만 새로고침 후 대화 위치 보존은 확인할 수 없습니다. 서버 전략은 삭제하지 않았습니다.',
    write: '대화 위치를 저장하지 못해 전환하지 않았습니다. 현재 화면과 이전 대화 위치를 유지합니다. 저장소를 확인한 뒤 다시 시도해주세요.',
  },
  en: {
    read: 'Could not read the previous conversation location from storage. The current conversation is retained; the previous one will not be fetched automatically.',
    rollback: 'Navigation stopped because storage recovery could not be confirmed. The current screen is retained, but whether the conversation location will be preserved after refresh is unconfirmed. No server strategy was deleted.',
    write: 'Navigation stopped because the conversation location could not be saved. The current screen and previous location are retained. Check browser storage and try again.',
  },
  ja: {
    read: '保存先から前の会話の場所を読み取れませんでした。現在の会話を維持し、前の会話を自動取得しません。',
    rollback: '保存先の復元を確認できないため画面の切り替えを中止しました。現在の画面は維持しますが、再読み込み後に会話の場所が保持されるかは確認できません。サーバーの戦略は削除していません。',
    write: '会話の場所を保存できないため切り替えませんでした。現在の画面と前の会話の場所を維持します。ブラウザーの保存先を確認して再試行してください。',
  },
  'zh-CN': {
    read: '无法从存储中读取上一段对话的位置。保留当前对话，不会自动获取上一段对话。',
    rollback: '无法确认存储恢复，已停止切换页面。当前页面保留，但无法确认刷新后是否保留对话位置。未删除服务器上的策略。',
    write: '无法保存对话位置，未进行切换。保留当前页面和上一段对话的位置。请检查浏览器存储后重试。',
  },
  'zh-TW': {
    read: '無法從儲存空間讀取上一段對話的位置。保留目前對話，不會自動取得上一段對話。',
    rollback: '無法確認儲存空間復原，已停止切換畫面。目前畫面保留，但無法確認重新整理後是否保留對話位置。未刪除伺服器上的策略。',
    write: '無法儲存對話位置，未進行切換。保留目前畫面和上一段對話的位置。請檢查瀏覽器儲存空間後重試。',
  },
  es: {
    read: 'No se pudo leer la ubicación de la conversación anterior del almacenamiento. Se conserva la conversación actual y no se consultará la anterior automáticamente.',
    rollback: 'Se detuvo la navegación porque no se pudo confirmar la recuperación del almacenamiento. Se conserva la pantalla actual, pero no se puede confirmar si se conservará la ubicación de la conversación tras recargar. No se eliminó ninguna estrategia del servidor.',
    write: 'No se cambió de pantalla porque no se pudo guardar la ubicación de la conversación. Se conservan la pantalla actual y la ubicación anterior. Revise el almacenamiento del navegador y vuelva a intentarlo.',
  },
  fr: {
    read: 'Impossible de lire l’emplacement de la conversation précédente dans le stockage. La conversation actuelle est conservée ; la précédente ne sera pas chargée automatiquement.',
    rollback: 'La navigation a été arrêtée car la restauration du stockage n’a pas pu être confirmée. L’écran actuel est conservé, mais la conservation de l’emplacement de la conversation après actualisation reste incertaine. Aucune stratégie du serveur n’a été supprimée.',
    write: 'La navigation a été arrêtée car l’emplacement de la conversation n’a pas pu être enregistré. L’écran actuel et l’emplacement précédent sont conservés. Vérifiez le stockage du navigateur et réessayez.',
  },
}
type Copy = Record<ObservationCopyKey, string>
export const nativeObservationCopy: Record<ClientLanguage, Copy> = {
  ko,
  en: {
    revision: 'Conversation revision {0} · Draft revision {1}', draftRevision: 'Draft revision {0} → {1}',
    proposed: 'Strategy change proposals reviewed', proposals: 'Proposals: {0} · Base draft revision {1}',
    proposalOnly: 'A proposal does not mean it has been applied or validated.', missingMerge: 'The server did not provide a draft application result.',
    proposal: 'Proposal {0}: ', evidence: 'User evidence: ', question: 'Clarification question', target: 'Target: ', reason: 'Reason: ',
    scope: 'Supported scope checked', applied: 'Draft updates confirmed: {0}', rejected: 'Draft update rejected', count: 'Server-reported applied count: {0}', path: 'Path: ',
    rejectedLabel: 'Draft changes rejected', unsupportedLabel: 'Unsupported conditions identified', questionLabel: 'Clarification needed', appliedLabel: 'Strategy draft update confirmed',
    issued: 'Issued: ', expires: 'Expires: ', receipt: 'Validation receipt: ', valid: 'Strategy validation complete', invalid: 'Strategy validation needs attention',
    passed: 'Server draft validation passed', failed: 'Server draft validation failed',
    validNote: 'Server validation for this draft has been confirmed. This does not mean user approval or completed execution.',
    invalidNote: 'The server returned draft validation issues. Review the issues, update the draft, and validate again.',
    readyReply: 'The strategy conditions are organized. You can validate after reviewing the draft and changes.', draftReply: 'Please review the draft returned by the server.',
    previousLabel: 'Previous conversation navigation', previousAction: 'Recheck the previous conversation on the server',
    previousNote: 'Only one conversation left in this browser session is remembered. This reloads the current draft only; check approvals and results separately in execution history. Server jobs are not cancelled or deleted.',
  },
  ja: {
    revision: '会話 revision {0} · 下書き revision {1}', draftRevision: '下書き revision {0} → {1}',
    proposed: '戦略の変更提案を確認', proposals: '提案 {0}件 · 基準下書き revision {1}',
    proposalOnly: '提案は適用や検証の完了を意味しません。', missingMerge: 'サーバーから下書きの適用結果が提供されていません。',
    proposal: '提案 {0}: ', evidence: 'ユーザーの根拠: ', question: '追加確認の質問', target: '対象: ', reason: '理由: ',
    scope: '対応範囲を確認', applied: '下書きの反映 {0}件を確認', rejected: '下書きの反映を拒否', count: 'サーバー報告の適用数: {0}件', path: 'パス: ',
    rejectedLabel: '下書き変更の適用を拒否', unsupportedLabel: '未対応の条件を確認', questionLabel: '追加確認が必要', appliedLabel: '戦略下書きの反映を確認',
    issued: '発行: ', expires: '有効期限: ', receipt: '検証レシート: ', valid: '戦略の検証完了', invalid: '戦略の検証に確認が必要',
    passed: 'サーバーの下書き検証に合格', failed: 'サーバーの下書き検証に失敗',
    validNote: '該当の下書きに対するサーバー検証を確認しました。ユーザーによる承認や実行の完了を意味するものではありません。',
    invalidNote: 'サーバーが下書きの検証問題を返しました。問題を確認して下書きを修正した上で、再度検証してください。',
    readyReply: '戦略条件を整理しました。下書きと変更項目を確認してから検証できます。', draftReply: 'サーバーから返された下書きを確認してください。',
    previousLabel: '前の会話のナビゲーション', previousAction: '前の会話をサーバーで再確認',
    previousNote: 'このブラウザーの同じセッションで離れた会話を1件だけ記憶します。現在の下書きのみを再取得し、承認と結果は実行履歴で別途確認します。サーバーの処理は取消・削除しません。',
  },
  'zh-CN': {
    revision: '对话 revision {0} · 草案 revision {1}', draftRevision: '草案 revision {0} → {1}',
    proposed: '已检查策略修改建议', proposals: '建议 {0}项 · 基础草案 revision {1}',
    proposalOnly: '建议不代表已应用或已完成校验。', missingMerge: '服务器未提供草案应用结果。',
    proposal: '建议 {0}: ', evidence: '用户依据: ', question: '补充确认问题', target: '目标: ', reason: '原因: ',
    scope: '已检查支持范围', applied: '已确认草案更新 {0}项', rejected: '草案更新被拒绝', count: '服务器报告的应用数量: {0}', path: '路径: ',
    rejectedLabel: '草案修改被拒绝', unsupportedLabel: '已识别不支持的条件', questionLabel: '需要补充确认', appliedLabel: '已确认策略草案更新',
    issued: '签发: ', expires: '到期: ', receipt: '校验收据: ', valid: '策略校验完成', invalid: '策略校验需要检查',
    passed: '服务器草案校验通过', failed: '服务器草案校验失败',
    validNote: '已确认该草案的服务器校验。这不代表用户已批准或已执行完毕。',
    invalidNote: '服务器返回了草案校验问题。请检查问题并修改草案后，重新进行校验。',
    readyReply: '策略条件已整理。检查草案和修改项后，即可进行校验。', draftReply: '请检查服务器返回的草案。',
    previousLabel: '浏览上一段对话', previousAction: '从服务器重新确认上一段对话',
    previousNote: '仅记住在此浏览器同一会话中离开的一段对话。只重新读取当前草案；批准和结果请在执行记录中单独查看。不会取消或删除服务器任务。',
  },
  'zh-TW': {
    revision: '對話 revision {0} · 草稿 revision {1}', draftRevision: '草稿 revision {0} → {1}',
    proposed: '已檢查策略修改建議', proposals: '建議 {0}項 · 基礎草稿 revision {1}',
    proposalOnly: '建議不代表已套用或已完成校驗。', missingMerge: '伺服器未提供草稿套用結果。',
    proposal: '建議 {0}: ', evidence: '使用者依據: ', question: '補充確認問題', target: '目標: ', reason: '原因: ',
    scope: '已檢查支援範圍', applied: '已確認草稿更新 {0}項', rejected: '草稿更新遭拒絕', count: '伺服器回報的套用數量: {0}', path: '路徑: ',
    rejectedLabel: '草稿修改遭拒絕', unsupportedLabel: '已識別不支援的條件', questionLabel: '需要補充確認', appliedLabel: '已確認策略草稿更新',
    issued: '簽發: ', expires: '到期: ', receipt: '校驗憑證: ', valid: '策略校驗完成', invalid: '策略校驗需要檢查',
    passed: '伺服器草稿校驗通過', failed: '伺服器草稿校驗失敗',
    validNote: '已確認該草稿的伺服器校驗。這不代表使用者已核准或已執行完成。',
    invalidNote: '伺服器回傳了草稿校驗問題。請檢查問題並修改草稿後，重新進行校驗。',
    readyReply: '策略條件已整理。檢查草稿和修改項後，即可進行校驗。', draftReply: '請檢查伺服器回傳的草稿。',
    previousLabel: '瀏覽上一段對話', previousAction: '從伺服器重新確認上一段對話',
    previousNote: '僅記住在此瀏覽器同一工作階段中離開的一段對話。只重新讀取目前草稿；核准和結果請在執行紀錄中另外查看。不會取消或刪除伺服器任務。',
  },
  es: {
    revision: 'Conversación revision {0} · Borrador revision {1}', draftRevision: 'Borrador revision {0} → {1}',
    proposed: 'Propuestas de cambio revisadas', proposals: 'Propuestas: {0} · Borrador base revision {1}',
    proposalOnly: 'Una propuesta no significa que se haya aplicado o validado.', missingMerge: 'El servidor no proporcionó el resultado de aplicación del borrador.',
    proposal: 'Propuesta {0}: ', evidence: 'Evidencia del usuario: ', question: 'Pregunta de aclaración', target: 'Destino: ', reason: 'Motivo: ',
    scope: 'Ámbito compatible comprobado', applied: 'Actualizaciones del borrador confirmadas: {0}', rejected: 'Actualización del borrador rechazada', count: 'Cantidad aplicada según el servidor: {0}', path: 'Ruta: ',
    rejectedLabel: 'Cambios del borrador rechazados', unsupportedLabel: 'Condiciones no compatibles identificadas', questionLabel: 'Se requiere aclaración', appliedLabel: 'Actualización del borrador confirmada',
    issued: 'Emitido: ', expires: 'Vence: ', receipt: 'Comprobante de validación: ', valid: 'Validación de estrategia completada', invalid: 'La validación requiere revisión',
    passed: 'Validación del borrador aprobada por el servidor', failed: 'Validación del borrador fallida en el servidor',
    validNote: 'Se ha confirmado la validación del borrador en el servidor. Esto no implica la aprobación del usuario ni la finalización de la ejecución.',
    invalidNote: 'El servidor devolvió problemas en la validación del borrador. Revise los problemas, modifique el borrador y vuelva a validar.',
    readyReply: 'Las condiciones de la estrategia están organizadas. Puede validar después de revisar el borrador y los cambios.', draftReply: 'Revise el borrador devuelto por el servidor.',
    previousLabel: 'Navegación a la conversación anterior', previousAction: 'Volver a consultar la conversación anterior en el servidor',
    previousNote: 'Solo se recuerda una conversación abandonada en esta sesión del navegador. Se recarga únicamente el borrador actual; consulte las aprobaciones y resultados por separado en el historial de ejecución. No se cancelan ni eliminan tareas del servidor.',
  },
  fr: {
    revision: 'Conversation revision {0} · Brouillon revision {1}', draftRevision: 'Brouillon revision {0} → {1}',
    proposed: 'Propositions de modification examinées', proposals: 'Propositions : {0} · Brouillon de référence revision {1}',
    proposalOnly: 'Une proposition ne signifie pas que son application ou sa validation est terminée.', missingMerge: "Le serveur n’a pas fourni le résultat d’application du brouillon.",
    proposal: 'Proposition {0} : ', evidence: 'Éléments fournis par l’utilisateur : ', question: 'Question de clarification', target: 'Cible : ', reason: 'Motif : ',
    scope: 'Périmètre pris en charge vérifié', applied: 'Mises à jour du brouillon confirmées : {0}', rejected: 'Mise à jour du brouillon rejetée', count: 'Nombre appliqué selon le serveur : {0}', path: 'Chemin : ',
    rejectedLabel: 'Modifications du brouillon rejetées', unsupportedLabel: 'Conditions non prises en charge identifiées', questionLabel: 'Clarification nécessaire', appliedLabel: 'Mise à jour du brouillon confirmée',
    issued: 'Émis le : ', expires: 'Expire le : ', receipt: 'Reçu de validation : ', valid: 'Validation de la stratégie terminée', invalid: 'Validation de la stratégie à vérifier',
    passed: 'Validation du brouillon réussie sur le serveur', failed: 'Échec de validation du brouillon sur le serveur',
    validNote: 'La validation de ce brouillon par le serveur a été confirmée. Cela ne constitue ni une approbation de l’utilisateur ni la fin de l’exécution.',
    invalidNote: 'Le serveur a renvoyé des erreurs de validation du brouillon. Veuillez examiner les problèmes, modifier le brouillon et relancer la validation.',
    readyReply: 'Les conditions de la stratégie sont organisées. Vous pouvez lancer la validation après avoir vérifié le brouillon et les modifications.', draftReply: 'Veuillez vérifier le brouillon renvoyé par le serveur.',
    previousLabel: 'Navigation vers la conversation précédente', previousAction: 'Vérifier à nouveau la conversation précédente sur le serveur',
    previousNote: 'Une seule conversation quittée dans cette session du navigateur est mémorisée. Seul le brouillon actuel est rechargé ; consultez les approbations et résultats séparément dans l’historique d’exécution. Aucune tâche du serveur n’est annulée ni supprimée.',
  },
}
