import {
  assertPaperSessionSnapshot,
  type PaperExecutionSummary,
  type PaperRestartSummary,
  type PaperSessionAdapter,
  type PaperSessionMarketArtifactBinding,
  type PaperSessionSnapshot,
  type PaperStrategyBinding,
  OWNER_RECORDED_PAPER_PROVENANCE,
  RECORDED_PAPER_PROVENANCE,
  RECORDED_PAPER_UNEVALUATED_EXIT_RULE_IDS,
  samePaperStrategyBinding,
} from './paper-session'

const CONTRACT = 'owner-local-paper-api/0.1'
const RESULT_VERSION = 'owner-local-paper-result/1'
const REPORT_VERSION = 'owner-local-paper-session-report/1'
const POINTER_KEY = 'tesia-internal-poc-active-paper-pointer-v2'
const PENDING_KEY = 'tesia-internal-poc-pending-paper-request-v2'
const HASH = /^[0-9a-f]{64}$/
const RESOURCE = /^[a-z][a-z0-9_]{1,30}_[A-Za-z0-9_-]{8,80}$/
const FIXTURE = /^paper_fixture_[a-z0-9_]{8,80}$/
const UINT = /^(?:0|[1-9][0-9]*)$/
const TIME = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/
const API_PATH = /^\/internal\/poc\/paper-sessions(?:\/[a-z][a-z0-9_]{1,30}_[A-Za-z0-9_-]{8,80}(?:\/result)?)?$/
type Rec = Record<string, unknown>
type Api = Readonly<{ data: Rec; revision: string | null }>
type Hashes = Readonly<{ reportHash: string; replayHash: string; ledgerHash: string; fixtureFileSha256: string; artifactContentHash?: string; provenanceHash?: string; policyHash?: string; manifestSha256?: string }>
type Status = Readonly<{ paperSessionId: string; strategyVersionId: string; semanticHash: string; fixtureId: string; state: 'QUEUED'|'RUNNING'|'COMPLETED'|'FAILED'; revision: string; attempt: string; resultAvailable: boolean; artifact: PaperSessionMarketArtifactBinding; failureCode?: string; resultHashes?: Hashes }>
type Pointer = Readonly<{ version: 'active-paper-pointer/2'; paperSessionId: string; strategy: PaperStrategyBinding; artifact: PaperSessionMarketArtifactBinding }>
type Pending = Readonly<{ version: 'pending-paper-request/2'; idempotencyKey: string; strategy: PaperStrategyBinding; artifact: PaperSessionMarketArtifactBinding; requestDigest: string }>

const rec = (v: unknown, code: string): Rec => { if (typeof v !== 'object' || v === null || Array.isArray(v)) throw new Error(code); return v as Rec }
const keys = (v: Rec, wanted: readonly string[], code: string) => { const a=Object.keys(v).sort(); const b=[...wanted].sort(); if(a.length!==b.length||a.some((x,i)=>x!==b[i])) throw new Error(code) }
const txt = (v: unknown, code: string): string => { if(typeof v!=='string'||v.length===0||v.normalize('NFC')!==v) throw new Error(code); return v }
const hex = (v: unknown, code: string): string => { const x=txt(v,code); if(!HASH.test(x)) throw new Error(code); return x }
const num = (v: unknown, code: string): number => { if(!Number.isSafeInteger(v)||Number(v)<0) throw new Error(code); return Number(v) }
const dec = (v: unknown, code: string): string => { const x=txt(v,code); if(!/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?$/.test(x)) throw new Error(code); return x }
const sameArtifact = (a: PaperSessionMarketArtifactBinding, b: PaperSessionMarketArtifactBinding) => (
  a.artifactId === b.artifactId
  && a.source === b.source
  && a.fileSha256 === b.fileSha256
  && a.contentHash === b.contentHash
  && a.provenanceHash === b.provenanceHash
  && a.policyHash === b.policyHash
  && a.manifestSha256 === b.manifestSha256
  && a.verificationStatus === b.verificationStatus
)
const artifact = (v: unknown, code='PAPER_API_ARTIFACT_BINDING_INVALID'): PaperSessionMarketArtifactBinding => {
  const x=rec(v,code); keys(x,['artifactId','source','fileSha256','contentHash','provenanceHash','policyHash','manifestSha256','verificationStatus'],code)
  const owner=x.source==='OWNER_RECORDED_LOCAL_ARTIFACT'
  if(!FIXTURE.test(txt(x.artifactId,code))||!HASH.test(String(x.fileSha256))||!HASH.test(String(x.contentHash))||!HASH.test(String(x.provenanceHash))||!HASH.test(String(x.policyHash))||(owner?(x.verificationStatus!=='UNVERIFIED_FOR_TRADING'||!HASH.test(String(x.manifestSha256))):(x.source!=='PACKAGED_SYNTHETIC'||x.verificationStatus!=='SYNTHETIC_ONLY'||x.manifestSha256!==null))) throw new Error(code)
  return x as PaperSessionMarketArtifactBinding
}
const canonical = (v: unknown): string => {
  if(v===null||typeof v==='boolean') return JSON.stringify(v)
  if(typeof v==='string'){if(v.normalize('NFC')!==v)throw new Error('PAPER_API_CANONICAL_VALUE_INVALID');return JSON.stringify(v)}
  if(typeof v==='number'&&Number.isSafeInteger(v)) return String(v)
  if(Array.isArray(v)) return `[${v.map(canonical).join(',')}]`
  const x=rec(v,'PAPER_API_CANONICAL_VALUE_INVALID');const objectKeys=Object.keys(x);if(objectKeys.some(k=>k.normalize('NFC')!==k))throw new Error('PAPER_API_CANONICAL_VALUE_INVALID');return `{${objectKeys.sort().map(k=>`${JSON.stringify(k)}:${canonical(x[k])}`).join(',')}}`
}
const sha = async (v:string) => [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))].map(b=>b.toString(16).padStart(2,'0')).join('')
export const runtimeContentHashV04 = async (v: Readonly<Record<string,unknown>>) => sha(`tesia.runtime.content.v0.4.0\n${canonical(Object.fromEntries(Object.entries(v).filter(([k])=>k!=='contentHash'&&k!=='runHash')))}`)
const readJson=async(response:Response):Promise<unknown>=>{if(response.headers.get('content-type')?.split(';',1)[0]?.trim().toLowerCase()!=='application/json')throw new Error('PAPER_API_JSON_RESPONSE_REQUIRED');const raw=await response.text();if(new TextEncoder().encode(raw).byteLength>2*1024*1024)throw new Error('PAPER_API_RESPONSE_TOO_LARGE');try{return JSON.parse(raw) as unknown}catch(e){throw new Error('PAPER_API_JSON_INVALID',{cause:e})}}
const request=async(path:string,init?:RequestInit,status=200):Promise<Api>=>{
  const url=new URL(path,window.location.origin);if(url.origin!==window.location.origin||!API_PATH.test(url.pathname)||url.search||url.hash)throw new Error('PAPER_API_SAME_ORIGIN_REQUIRED')
  const response=await fetch(url.pathname,{...init,credentials:'same-origin',redirect:'manual',cache:'no-store',headers:{Accept:'application/json',...init?.headers}})
  const envelope=rec(await readJson(response),'PAPER_API_ENVELOPE_INVALID');const meta=rec(envelope.meta,'PAPER_API_META_INVALID');keys(meta,['internalContractVersion','requestId','traceId','resourceRevision'],'PAPER_API_META_INVALID')
  if(meta.internalContractVersion!==CONTRACT||typeof meta.requestId!=='string'||!meta.requestId||typeof meta.traceId!=='string'||!meta.traceId||(meta.resourceRevision!==null&&(typeof meta.resourceRevision!=='string'||!UINT.test(meta.resourceRevision))))throw new Error('PAPER_API_META_INVALID')
  if(!response.ok){keys(envelope,['meta','error'],'PAPER_API_ERROR_ENVELOPE_INVALID');const e=rec(envelope.error,'PAPER_API_ERROR_ENVELOPE_INVALID');keys(e,['code','message'],'PAPER_API_ERROR_ENVELOPE_INVALID');throw new Error(txt(e.code,'PAPER_API_ERROR_ENVELOPE_INVALID'))}
  if(response.status!==status)throw new Error('PAPER_API_HTTP_STATUS_INVALID');keys(envelope,['meta','data'],'PAPER_API_ENVELOPE_INVALID');return{data:rec(envelope.data,'PAPER_API_DATA_INVALID'),revision:meta.resourceRevision as string|null}
}
const parseStatus=(response:Api,strategy:PaperStrategyBinding,a:PaperSessionMarketArtifactBinding):Status=>{
  const d=response.data;const state=d.state;if(!['QUEUED','RUNNING','COMPLETED','FAILED'].includes(String(state)))throw new Error('PAPER_API_STATUS_INVALID')
  const terminal=state==='COMPLETED'?'resultHashes':state==='FAILED'?'failureCode':null;keys(d,['paperSessionId','strategyVersionId','semanticHash','fixtureId','state','revision','attempt','createdAt','updatedAt','resultAvailable','provenance',...(terminal?[terminal]:[])],'PAPER_API_STATUS_INVALID')
  if(typeof d.resultAvailable!=='boolean')throw new Error('PAPER_API_RESULT_AVAILABLE_INVALID')
  const p=rec(d.provenance,'PAPER_API_PROVENANCE_INVALID');const owner=a.source==='OWNER_RECORDED_LOCAL_ARTIFACT';keys(p,owner?['dataClass','verified','privateOnly','verificationStatus']:['dataClass','verified','privateOnly'],'PAPER_API_PROVENANCE_INVALID')
  if(p.dataClass!==(owner?'OWNER_LOCAL_RECORDED_MARKET_ARTIFACT':'SYNTHETIC_RECORDED_MARKET_FIXTURE')||p.verified!==false||p.privateOnly!==true||(owner&&p.verificationStatus!=='UNVERIFIED_FOR_TRADING'))throw new Error('PAPER_API_PROVENANCE_INVALID')
  const out:Status={paperSessionId:txt(d.paperSessionId,'PAPER_API_STATUS_INVALID'),strategyVersionId:txt(d.strategyVersionId,'PAPER_API_STATUS_INVALID'),semanticHash:hex(d.semanticHash,'PAPER_API_STATUS_INVALID'),fixtureId:txt(d.fixtureId,'PAPER_API_STATUS_INVALID'),state:state as Status['state'],revision:txt(d.revision,'PAPER_API_STATUS_INVALID'),attempt:txt(d.attempt,'PAPER_API_STATUS_INVALID'),resultAvailable:d.resultAvailable,artifact:a,...(state==='FAILED'?{failureCode:txt(d.failureCode,'PAPER_API_STATUS_INVALID')}:{})}
  if(!RESOURCE.test(out.paperSessionId)||out.fixtureId!==a.artifactId||!UINT.test(out.revision)||!UINT.test(out.attempt)||response.revision!==out.revision||typeof d.createdAt!=='string'||!TIME.test(d.createdAt)||typeof d.updatedAt!=='string'||!TIME.test(d.updatedAt)||!samePaperStrategyBinding(strategy,out)||out.resultAvailable!==(state==='COMPLETED'))throw new Error('PAPER_API_STATUS_BINDING_INVALID')
  if(state!=='COMPLETED')return out
  const h=rec(d.resultHashes,'PAPER_API_RESULT_HASHES_INVALID');keys(h,owner?['reportHash','replayHash','ledgerHash','fixtureFileSha256','artifactContentHash','provenanceHash','policyHash','manifestSha256']:['reportHash','replayHash','ledgerHash','fixtureFileSha256'],'PAPER_API_RESULT_HASHES_INVALID')
  const hs:Hashes={reportHash:hex(h.reportHash,'PAPER_API_RESULT_HASHES_INVALID'),replayHash:hex(h.replayHash,'PAPER_API_RESULT_HASHES_INVALID'),ledgerHash:hex(h.ledgerHash,'PAPER_API_RESULT_HASHES_INVALID'),fixtureFileSha256:hex(h.fixtureFileSha256,'PAPER_API_RESULT_HASHES_INVALID'),...(owner?{artifactContentHash:hex(h.artifactContentHash,'PAPER_API_RESULT_HASHES_INVALID'),provenanceHash:hex(h.provenanceHash,'PAPER_API_RESULT_HASHES_INVALID'),policyHash:hex(h.policyHash,'PAPER_API_RESULT_HASHES_INVALID'),manifestSha256:hex(h.manifestSha256,'PAPER_API_RESULT_HASHES_INVALID')}:{})}
  if(hs.fixtureFileSha256!==a.fileSha256||(owner&&(hs.artifactContentHash!==a.contentHash||hs.provenanceHash!==a.provenanceHash||hs.policyHash!==a.policyHash||hs.manifestSha256!==a.manifestSha256)))throw new Error('PAPER_API_ARTIFACT_AUTHORITY_MISMATCH')
  return{...out,resultHashes:hs}
}
const parseLedger=(v:unknown):PaperExecutionSummary['ledger']=>{const x=rec(v,'PAPER_API_LEDGER_INVALID');const ks=['initialWallet','markPrice','wallet','equity','quantity','averageEntry','realizedPnl','unrealizedPnl','fees','funding'] as const;keys(x,ks,'PAPER_API_LEDGER_INVALID');return Object.fromEntries(ks.map(k=>[k,dec(x[k],'PAPER_API_LEDGER_INVALID')])) as PaperExecutionSummary['ledger']}
const parseExecution=(v:unknown):PaperExecutionSummary=>{const x=rec(v,'PAPER_API_EXECUTION_INVALID');keys(x,['evaluationCandleCount','recordedMarketEventCount','signalCount','intentCount','fillCount','positionQuantity','signalHash','orderIntentHash','fillHashes','ledger'],'PAPER_API_EXECUTION_INVALID');if(!Array.isArray(x.fillHashes))throw new Error('PAPER_API_EXECUTION_INVALID');dec(x.positionQuantity,'PAPER_API_EXECUTION_INVALID');return{evaluationCandleCount:num(x.evaluationCandleCount,'PAPER_API_EXECUTION_INVALID'),recordedMarketEventCount:num(x.recordedMarketEventCount,'PAPER_API_EXECUTION_INVALID'),signalCount:num(x.signalCount,'PAPER_API_EXECUTION_INVALID'),intentCount:num(x.intentCount,'PAPER_API_EXECUTION_INVALID'),fillCount:num(x.fillCount,'PAPER_API_EXECUTION_INVALID'),signalHash:hex(x.signalHash,'PAPER_API_EXECUTION_INVALID'),orderIntentHash:hex(x.orderIntentHash,'PAPER_API_EXECUTION_INVALID'),fillHashes:x.fillHashes.map(i=>hex(i,'PAPER_API_EXECUTION_INVALID')),ledger:parseLedger(x.ledger)}}
const parseRestart=(v:unknown):PaperRestartSummary=>{const x=rec(v,'PAPER_API_RESTART_INVALID');const ks=['firstCheckpointRevision','terminalCheckpointRevision','fencingToken','duplicateIntentCount','duplicateEventCount','newFillCountAfterDuplicateReplay'] as const;keys(x,ks,'PAPER_API_RESTART_INVALID');return Object.fromEntries(ks.map(k=>[k,num(x[k],'PAPER_API_RESTART_INVALID')])) as PaperRestartSummary}
const projection=(a:PaperSessionMarketArtifactBinding):Rec=>({dataClass:'OWNER_LOCAL_RECORDED_MARKET_ARTIFACT',verificationStatus:'UNVERIFIED_FOR_TRADING',fixtureFileSha256:a.fileSha256,artifactContentHash:a.contentHash,provenanceHash:a.provenanceHash,executionProfileHash:a.policyHash})
const full=(a:PaperSessionMarketArtifactBinding):Rec=>({...projection(a),fixtureId:a.artifactId,manifestSha256:a.manifestSha256})
const completed=async(response:Api,status:Status,strategy:PaperStrategyBinding):Promise<PaperSessionSnapshot>=>{
  const d=response.data,a=status.artifact,owner=a.source==='OWNER_RECORDED_LOCAL_ARTIFACT';keys(d,owner?['artifactVersion','paperSessionId','strategyVersionId','semanticHash','fixtureId','fixtureFileSha256','reportHash','replayHash','ledgerHash','report','marketArtifactAuthority']:['artifactVersion','paperSessionId','strategyVersionId','semanticHash','fixtureId','fixtureFileSha256','reportHash','replayHash','ledgerHash','report'],'PAPER_API_RESULT_INVALID')
  const binding={strategyVersionId:txt(d.strategyVersionId,'PAPER_API_RESULT_INVALID'),semanticHash:hex(d.semanticHash,'PAPER_API_RESULT_INVALID')};const report=rec(d.report,'PAPER_API_REPORT_INVALID');keys(report,['artifactVersion','status','provenance','externalEffects','strategy','fixture','strategyCoverage','execution','restart','replayPreimage','replayHash','replayEqual','reportHash'],'PAPER_API_REPORT_INVALID')
  const rs=rec(report.strategy,'PAPER_API_REPORT_BINDING_INVALID');keys(rs,['strategyVersionId','semanticHash','strategyVersionContentHash','strategyVersionFileSha256','approvalAuthority','approvalRecordFileSha256'],'PAPER_API_REPORT_BINDING_INVALID');hex(rs.strategyVersionContentHash,'PAPER_API_REPORT_BINDING_INVALID');hex(rs.strategyVersionFileSha256,'PAPER_API_REPORT_BINDING_INVALID');hex(rs.approvalRecordFileSha256,'PAPER_API_REPORT_BINDING_INVALID')
  const rf=rec(report.fixture,'PAPER_API_REPORT_BINDING_INVALID'),expectedFixture=owner?full(a):{fixtureFileSha256:a.fileSha256};keys(rf,owner?['dataClass','verificationStatus','fixtureId','fixtureFileSha256','artifactContentHash','provenanceHash','executionProfileHash','manifestSha256']:['fixtureFileSha256'],'PAPER_API_REPORT_BINDING_INVALID')
  const h=status.resultHashes;if(!h)throw new Error('PAPER_API_RESULT_HASHES_MISSING');const reportHash=hex(d.reportHash,'PAPER_API_RESULT_INVALID'),replayHash=hex(d.replayHash,'PAPER_API_RESULT_INVALID'),ledgerHash=hex(d.ledgerHash,'PAPER_API_RESULT_INVALID'),file=hex(d.fixtureFileSha256,'PAPER_API_RESULT_INVALID')
  if(d.artifactVersion!==RESULT_VERSION||d.paperSessionId!==status.paperSessionId||!samePaperStrategyBinding(strategy,binding)||!samePaperStrategyBinding(status,binding)||d.fixtureId!==a.artifactId||file!==a.fileSha256||report.artifactVersion!==REPORT_VERSION||report.status!==(owner?'COMPLETED_OWNER_LOCAL_MARKET_ARTIFACT_ONLY':'COMPLETED_LOCAL_FIXTURE_ONLY')||report.replayEqual!==true||rs.strategyVersionId!==strategy.strategyVersionId||rs.semanticHash!==strategy.semanticHash||rs.approvalAuthority!=='OWNER_LOCAL_SQLITE_APPROVAL_RECORD'||canonical(rf)!==canonical(expectedFixture)||report.reportHash!==reportHash||report.replayHash!==replayHash||h.reportHash!==reportHash||h.replayHash!==replayHash||h.ledgerHash!==ledgerHash||h.fixtureFileSha256!==file||response.revision!==status.revision||(owner&&canonical(rec(d.marketArtifactAuthority,'PAPER_API_ARTIFACT_AUTHORITY_INVALID'))!==canonical(full(a))))throw new Error('PAPER_API_CROSS_RESOURCE_BINDING_MISMATCH')
  const p=rec(report.provenance,'PAPER_API_REPORT_PROVENANCE_INVALID');keys(p,owner?['dataClass','verified','privateOnly','verificationStatus','label']:['dataClass','verified','privateOnly','label'],'PAPER_API_REPORT_PROVENANCE_INVALID');if(p.dataClass!==(owner?'OWNER_LOCAL_RECORDED_MARKET_ARTIFACT':'SYNTHETIC_RECORDED_MARKET_FIXTURE')||p.verified!==false||p.privateOnly!==true||(owner&&p.verificationStatus!=='UNVERIFIED_FOR_TRADING')||p.label!==(owner?OWNER_RECORDED_PAPER_PROVENANCE.label:RECORDED_PAPER_PROVENANCE.label))throw new Error('PAPER_API_REPORT_PROVENANCE_INVALID')
  const e=rec(report.externalEffects,'PAPER_API_EXTERNAL_EFFECTS_INVALID');keys(e,['evidenceKind','networkCalls','exchangeCalls','credentialReads','orders'],'PAPER_API_EXTERNAL_EFFECTS_INVALID');const effects={evidenceKind:e.evidenceKind,networkCalls:e.networkCalls,exchangeCalls:e.exchangeCalls,credentialReads:e.credentialReads,orders:e.orders}
  const c=rec(report.strategyCoverage,'PAPER_API_COVERAGE_INVALID');keys(c,['entryRuleEvaluated','riskLimitsApplied','exitRulesEvaluated','unevaluatedExitRuleIds'],'PAPER_API_COVERAGE_INVALID');if(!Array.isArray(c.unevaluatedExitRuleIds))throw new Error('PAPER_API_COVERAGE_INVALID');const coverage={entryRuleEvaluated:c.entryRuleEvaluated,riskLimitsApplied:c.riskLimitsApplied,exitRulesEvaluated:c.exitRulesEvaluated,unevaluatedExitRuleIds:c.unevaluatedExitRuleIds}
  const execution=parseExecution(report.execution),restart=parseRestart(report.restart),pre=rec(report.replayPreimage,'PAPER_API_REPLAY_PREIMAGE_INVALID');keys(pre,owner?['artifactVersion','strategySemanticHash','signalHash','orderIntentHash','terminalCheckpoint','terminalLedger','marketArtifactAuthority']:['artifactVersion','strategySemanticHash','signalHash','orderIntentHash','terminalCheckpoint','terminalLedger'],'PAPER_API_REPLAY_PREIMAGE_INVALID');rec(pre.terminalCheckpoint,'PAPER_API_REPLAY_PREIMAGE_INVALID');const replayLedger=rec(pre.terminalLedger,'PAPER_API_REPLAY_PREIMAGE_INVALID'),wanted=[...RECORDED_PAPER_UNEVALUATED_EXIT_RULE_IDS].sort(),actual=coverage.unevaluatedExitRuleIds.every(i=>typeof i==='string')?[...coverage.unevaluatedExitRuleIds].sort():[]
  if(effects.evidenceKind!=='STATIC_OFFLINE_CAPABILITY_BOUNDARY'||effects.networkCalls!==0||effects.exchangeCalls!==0||effects.credentialReads!==0||effects.orders!==0||coverage.entryRuleEvaluated!==true||coverage.riskLimitsApplied!==true||coverage.exitRulesEvaluated!==false||actual.length!==wanted.length||actual.some((x,i)=>x!==wanted[i])||pre.artifactVersion!=='local-paper-replay/1'||pre.strategySemanticHash!==strategy.semanticHash||pre.signalHash!==execution.signalHash||pre.orderIntentHash!==execution.orderIntentHash||canonical(replayLedger)!==canonical(execution.ledger)||(owner&&canonical(rec(pre.marketArtifactAuthority,'PAPER_API_REPLAY_PREIMAGE_INVALID'))!==canonical(expectedFixture))||await runtimeContentHashV04(pre)!==replayHash||await runtimeContentHashV04(execution.ledger)!==ledgerHash||await runtimeContentHashV04(Object.fromEntries(Object.entries(report).filter(([k])=>k!=='reportHash')))!==reportHash)throw new Error('PAPER_API_RESULT_INTEGRITY_INVALID')
  return assertPaperSessionSnapshot({artifactVersion:'paper-session-view/1',sessionId:status.paperSessionId,stage:owner?'COMPLETED_OWNER_LOCAL_MARKET_ARTIFACT_ONLY':'COMPLETED_LOCAL_FIXTURE_ONLY',viewSource:'OWNER_LOCAL_API',requestedStrategy:strategy,recordedStrategy:binding,fixtureId:a.artifactId,provenance:owner?OWNER_RECORDED_PAPER_PROVENANCE:RECORDED_PAPER_PROVENANCE,revision:status.revision,attempt:status.attempt,strategyCoverage:coverage,externalEffects:effects,restart,execution,fixtureFileSha256:file,ledgerHash,replayEqual:true,replayHash,reportHash,marketArtifact:a})
}
const snapshot=(s:Status,strategy:PaperStrategyBinding)=>assertPaperSessionSnapshot({artifactVersion:'paper-session-view/1',sessionId:s.paperSessionId,stage:s.state,viewSource:'OWNER_LOCAL_API',requestedStrategy:strategy,recordedStrategy:{strategyVersionId:s.strategyVersionId,semanticHash:s.semanticHash},fixtureId:s.fixtureId,provenance:s.artifact.source==='OWNER_RECORDED_LOCAL_ARTIFACT'?OWNER_RECORDED_PAPER_PROVENANCE:RECORDED_PAPER_PROVENANCE,revision:s.revision,attempt:s.attempt,marketArtifact:s.artifact,...(s.failureCode?{failureCode:s.failureCode}:{})})
const stored=(key:string,code:string):Rec|null=>{const raw=sessionStorage.getItem(key);if(raw===null)return null;try{return rec(JSON.parse(raw) as unknown,code)}catch(e){throw new Error(code,{cause:e})}}
const strategy=(v:unknown,code:string):PaperStrategyBinding=>{const x=rec(v,code);keys(x,['strategyVersionId','semanticHash'],code);if(!RESOURCE.test(txt(x.strategyVersionId,code))||!HASH.test(String(x.semanticHash)))throw new Error(code);return x as PaperStrategyBinding}
const pointer=():Pointer|null=>{const x=stored(POINTER_KEY,'PAPER_API_POINTER_INVALID');if(!x)return null;keys(x,['version','paperSessionId','strategy','artifact'],'PAPER_API_POINTER_INVALID');if(x.version!=='active-paper-pointer/2'||!RESOURCE.test(String(x.paperSessionId)))throw new Error('PAPER_API_POINTER_INVALID');return{version:'active-paper-pointer/2',paperSessionId:String(x.paperSessionId),strategy:strategy(x.strategy,'PAPER_API_POINTER_INVALID'),artifact:artifact(x.artifact,'PAPER_API_POINTER_INVALID')}}
const pending=():Pending|null=>{const x=stored(PENDING_KEY,'PAPER_API_PENDING_REQUEST_INVALID');if(!x)return null;keys(x,['version','idempotencyKey','strategy','artifact','requestDigest'],'PAPER_API_PENDING_REQUEST_INVALID');if(x.version!=='pending-paper-request/2'||typeof x.idempotencyKey!=='string'||!/^paper_[0-9a-f_]{36}$/.test(x.idempotencyKey)||!HASH.test(String(x.requestDigest)))throw new Error('PAPER_API_PENDING_REQUEST_INVALID');return{version:'pending-paper-request/2',idempotencyKey:x.idempotencyKey,strategy:strategy(x.strategy,'PAPER_API_PENDING_REQUEST_INVALID'),artifact:artifact(x.artifact,'PAPER_API_PENDING_REQUEST_INVALID'),requestDigest:String(x.requestDigest)}}
const prepare=async(s:PaperStrategyBinding,a:PaperSessionMarketArtifactBinding,body:Rec):Promise<Pending>=>{const digest=await sha(`tesia.owner-local.start-paper.v1\0${canonical(body)}`),old=pending();if(old){if(!samePaperStrategyBinding(old.strategy,s)||!sameArtifact(old.artifact,a)||old.requestDigest!==digest)throw new Error('PAPER_API_PENDING_REQUEST_BINDING_MISMATCH');return old}const next:Pending={version:'pending-paper-request/2',idempotencyKey:`paper_${crypto.randomUUID().replaceAll('-','_')}`,strategy:s,artifact:a,requestDigest:digest};sessionStorage.setItem(PENDING_KEY,JSON.stringify(next));const check=pending();if(!check||check.idempotencyKey!==next.idempotencyKey||!sameArtifact(check.artifact,a))throw new Error('PAPER_API_PENDING_REQUEST_PERSIST_FAILED');return next}
const read=async(id:string,s:PaperStrategyBinding,a:PaperSessionMarketArtifactBinding):Promise<PaperSessionSnapshot>=>{const st=parseStatus(await request(`/internal/poc/paper-sessions/${id}`),s,a);if(st.paperSessionId!==id)throw new Error('PAPER_API_SESSION_BINDING_MISMATCH');return st.state==='COMPLETED'?completed(await request(`/internal/poc/paper-sessions/${id}/result`),st,s):snapshot(st,s)}

export const createLocalPaperApiAdapter=async():Promise<PaperSessionAdapter>=>({kind:'owner-local-api',label:'OWNER_LOCAL_API',async readActive(s){const p=pointer();if(!p)return{snapshot:null,recoverySource:'NONE'};if(!samePaperStrategyBinding(p.strategy,s))throw new Error('PAPER_API_ACTIVE_STRATEGY_BINDING_MISMATCH');return{snapshot:await read(p.paperSessionId,s,p.artifact),recoverySource:'ACTIVE_PAPER'}},async startSession(){throw new Error('PAPER_MARKET_ARTIFACT_SELECTION_REQUIRED')},async startSessionForArtifact(s,context,raw){const a=artifact(raw);if(pointer()!==null)throw new Error('PAPER_API_ACTIVE_SESSION_DISCARD_REQUIRED');if(!RESOURCE.test(s.strategyVersionId)||!HASH.test(s.semanticHash))throw new Error('PAPER_API_REQUESTED_STRATEGY_INVALID');if(typeof context.csrfToken!=='string'||context.csrfToken.length<16)throw new Error('PAPER_API_CSRF_MISSING');const body={strategyVersionId:s.strategyVersionId,expectedSemanticHash:s.semanticHash,fixtureId:a.artifactId},pending=await prepare(s,a,body),response=await request('/internal/poc/paper-sessions',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':context.csrfToken,'Idempotency-Key':pending.idempotencyKey},body:JSON.stringify(body)},201),st=parseStatus(response,s,a);sessionStorage.setItem(POINTER_KEY,JSON.stringify({version:'active-paper-pointer/2',paperSessionId:st.paperSessionId,strategy:{strategyVersionId:st.strategyVersionId,semanticHash:st.semanticHash},artifact:a} satisfies Pointer));sessionStorage.removeItem(PENDING_KEY);return{snapshot:snapshot(st,s),recoverySource:'NONE'}},async refreshSession(id,s){const p=pointer();if(!p||p.paperSessionId!==id||!samePaperStrategyBinding(p.strategy,s))throw new Error('PAPER_API_ACTIVE_SESSION_BINDING_MISMATCH');return{snapshot:await read(id,s,p.artifact),recoverySource:'ACTIVE_PAPER'}},hasPendingRequest(){return pending()!==null},invalidateArtifactBinding(artifactId){const p=pointer(),q=pending();if(p?.artifact.artifactId===artifactId)sessionStorage.removeItem(POINTER_KEY);if(q?.artifact.artifactId===artifactId)sessionStorage.removeItem(PENDING_KEY)},resetLocalView(){sessionStorage.removeItem(POINTER_KEY);sessionStorage.removeItem(PENDING_KEY)}})
export const LOCAL_PAPER_ACTIVE_POINTER_KEY=POINTER_KEY
export const LOCAL_PAPER_PENDING_REQUEST_KEY=PENDING_KEY
