import {expect,test} from '@playwright/test'
import words from '../src/client-catalogue-copy-setup-copy.json' with {type:'json'}

for(const language of ['ko','en','ja','zh-CN','zh-TW','es','fr'] as const) for(const viewport of [{width:320,height:600},{width:844,height:480},{width:844,height:600}]) test(`${language} ${viewport.width}×${viewport.height} 복사 상세 본문만 스크롤하고 하단 실행 버튼은 고정된다`,async({page},info)=>{
  await page.setViewportSize(viewport)
  await page.addInitScript(language=>localStorage.setItem('tethLang',language),language)
  await page.goto('/')
  await page.evaluate(async()=>{const path='/tests/fixtures/catalogue-copy-setup-harness.tsx';Object.assign(window,{copySetupHarness:(await import(path)).mountCatalogueCopy()})})
  await expect(page.locator('.ss3-dtitle')).toBeVisible()
  const trigger=page.locator('.shared-detail-actions .wbtn')
  await trigger.evaluate(el=>el.addEventListener('click',()=>Reflect.set(window,'copyBackgroundAtOpen',{x:scrollX,y:scrollY}),{capture:true,once:true}))
  await trigger.click()
  const sheet=page.locator('.catalogue-copy-sheet'),body=sheet.locator('.ccs-body'),copy=words[language]
  await sheet.getByRole('button',{name:copy.details,exact:true}).click()
  await expect.poll(()=>sheet.evaluate(el=>({fallback:el.classList.contains('is-content-scroll'),bodyScrolls:(b=>b.scrollHeight>b.clientHeight)(el.querySelector('.ccs-body')!)}))).toEqual({fallback:false,bodyScrolls:true})
  const footer=sheet.locator('footer'),start=sheet.getByRole('button',{name:copy.start,exact:true})
  const footerBefore=await footer.boundingBox()
  expect(footerBefore).not.toBeNull()
  const bounds=await body.boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.move(bounds!.x+bounds!.width/2,bounds!.y+bounds!.height/2)
  await page.mouse.wheel(0,1600)
  await expect.poll(()=>body.evaluate(el=>el.scrollTop)).toBeGreaterThan(0)
  await expect.poll(()=>footer.boundingBox()).toEqual(footerBefore)
  const visibleAction=await start.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth&&el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})
  expect(visibleAction).toBe(true)
  expect(await sheet.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  expect(await page.evaluate(()=>({x:scrollX,y:scrollY}))).toEqual(await page.evaluate(()=>Reflect.get(window,'copyBackgroundAtOpen')))
  await sheet.getByLabel(copy.budget,{exact:true}).fill('500')
  await expect(start).toBeEnabled()
  await start.click()
  expect((await page.evaluate(()=>Reflect.get(window,'copySetupHarness').snapshot())).calls).toHaveLength(1)
  await page.evaluate(()=>Reflect.get(window,'copySetupHarness').settle(0,false))
  await expect(footer.getByRole('alert')).toHaveText(copy.failed)
  // The extra source error row still leaves a readable body at these normal
  // heights; the previous short/enlarged fallback matrix covers the other mode.
  await expect.poll(()=>sheet.evaluate(el=>el.classList.contains('is-content-scroll'))).toBe(false)
  const afterFailure=await footer.boundingBox()
  expect(afterFailure).not.toBeNull()
  await body.evaluate(el=>{el.scrollTop=0})
  await expect.poll(()=>body.evaluate(el=>el.scrollTop)).toBe(0)
  await expect.poll(()=>footer.boundingBox()).toEqual(afterFailure)
  expect((await page.evaluate(()=>Reflect.get(window,'copySetupHarness').snapshot())).calls).toHaveLength(1)
  if(language==='fr'&&viewport.width===844&&viewport.height===600)await page.screenshot({path:info.outputPath('copy-fixed-footer-source.png')})
  await page.keyboard.press('Escape')
  await expect(sheet).toHaveCount(0)
  await expect(trigger).toBeFocused()
})

for(const width of [320,844]) test(`ko ${width}×240 실패 안내의 가용높이 전환에도 복사 동작 초점을 보존한다`,async({page})=>{
  await page.setViewportSize({width,height:240})
  await page.goto('/')
  await page.evaluate(async()=>{const path='/tests/fixtures/catalogue-copy-setup-harness.tsx';Object.assign(window,{copySetupHarness:(await import(path)).mountCatalogueCopy()})})
  await expect(page.locator('.ss3-dtitle')).toBeVisible()
  const trigger=page.locator('.shared-detail-actions .wbtn')
  await trigger.click()
  const sheet=page.locator('.catalogue-copy-sheet'),start=sheet.getByRole('button',{name:words.ko.start,exact:true})
  await expect.poll(()=>sheet.evaluate(el=>el.classList.contains('is-content-scroll'))).toBe(false)
  await sheet.getByLabel(words.ko.budget,{exact:true}).fill('500')
  await start.click()
  await page.evaluate(()=>Reflect.get(window,'copySetupHarness').settle(0,false))
  await expect(sheet.locator('footer [role="alert"]')).toHaveText(words.ko.failed)
  await expect.poll(()=>sheet.evaluate(el=>el.classList.contains('is-content-scroll'))).toBe(true)
  await expect(start).toBeFocused()
  expect(await start.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})).toBe(true)
  await expect(sheet.getByLabel(words.ko.budget,{exact:true})).toHaveValue('500')
  await start.press('Enter')
  await expect(sheet.locator('footer [role="alert"]')).toHaveCount(0)
  await expect.poll(()=>sheet.evaluate(el=>el.classList.contains('is-content-scroll'))).toBe(false)
  const pending=sheet.getByRole('button',{name:words.ko.starting,exact:true})
  await expect(pending).toBeFocused()
  expect((await page.evaluate(()=>Reflect.get(window,'copySetupHarness').snapshot())).calls).toHaveLength(2)
  await page.evaluate(()=>Reflect.get(window,'copySetupHarness').settle(1,true))
  await expect(sheet).toHaveCount(0)
  await expect(trigger).toBeFocused()
})
