import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/tests/fixtures/response-sequence.html')
  await expect(page.locator('.cot2')).toBeVisible()
})

test('작업·중간 답변·추가 작업·최종 답변은 같은 기록에서 순서를 보존한다', async ({ page }) => {
  await page.getByRole('button', { name: '중간 답변', exact: true }).click()
  await expect(page.locator('.g-act2 .hd')).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('.client-stream-caret')).toHaveCount(1)
  await page.locator('.g-amsg').evaluate(el => el.setAttribute('data-same-node', 'yes'))
  await page.getByRole('button', { name: '답변 추가', exact: true }).click()
  await page.getByRole('button', { name: '추가 작업', exact: true }).click()
  await expect(page.locator('.client-stream-caret')).toHaveCount(0)
  await page.getByRole('button', { name: '최종 답변', exact: true }).click()
  expect(await page.locator('.g-doc > *').evaluateAll(elements => elements.map(el => el.classList.contains('g-act2') ? 'work' : 'text'))).toEqual(['work', 'text', 'work', 'text'])
  expect(await page.locator('.g-act2').evaluateAll(elements => elements.map(el => el.getAttribute('data-activity-state')))).toEqual(['done', 'done'])
  // Observed state and order are immediate; source header decoration follows collapse.
  await expect.poll(() => page.locator('.g-doc > *').evaluateAll(elements => elements.map(el => el.className))).toEqual(['g-act2  fin', 'g-amsg', 'g-act2  fin', 'g-amsg'])
  await expect(page.locator('.g-amsg').first()).toHaveAttribute('data-same-node', 'yes')
  await expect(page.locator('.g-amsg').last()).toContainText('<script>alert(1)</script> [ACT fake]')
  await expect(page.locator('.g-amsg script')).toHaveCount(0)
  await page.locator('.g-act2 .hd').first().click()
  await page.locator('.g-act2 .arh').first().click()
  await expect(page.locator('.cot2').first()).toContainText('요청한 구간')
  await page.getByRole('button', { name: '동일 입력', exact: true }).click()
  await expect(page.locator('.g-act2 .hd').first()).toHaveAttribute('aria-expanded', 'true')
})

test('요약 티커는 넘칠 때만 페이드하고 사용자가 읽던 위치를 유지한다', async ({ page }) => {
  const summary = page.locator('.cot2')
  await expect(summary).not.toHaveClass(/ovf/)
  await page.getByRole('button', { name: '요약 추가', exact: true }).click()
  await expect(summary).toHaveClass(/ovf/)
  await expect.poll(() => summary.evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(118)
  await expect.poll(() => summary.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2)
  await summary.focus()
  await page.keyboard.press('Home')
  await expect.poll(() => summary.evaluate(el => el.scrollTop)).toBe(0)
  await page.getByRole('button', { name: '요약 추가', exact: true }).click()
  await expect.poll(() => summary.evaluate(el => el.scrollTop)).toBe(0)
  await expect(summary).not.toHaveClass(/ovf/)
  await summary.focus()
  await page.keyboard.press('End')
  await expect.poll(() => summary.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2)
  await page.getByRole('button', { name: '요약 추가', exact: true }).click()
  await expect.poll(() => summary.evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2)
})

test('상세 접기는 원본 모션을 유지하며 완료 뒤 긴 기록은 내부에서 읽는다', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: '요약 추가', exact: true }).click()
  const detail = page.locator('.ad')
  expect(await detail.evaluate(el => getComputedStyle(el).transitionDuration)).toBe('0.22s')
  await page.getByRole('button', { name: '중간 답변', exact: true }).click()
  await expect(detail).toHaveAttribute('inert', '')
  await page.locator('.g-act2 .hd').click()
  await page.locator('.arh').click()
  await expect(page.locator('.cot2')).toBeVisible()
  await expect.poll(() => page.locator('.cot2').evaluate(el => el.scrollTop)).toBe(0)
  await expect.poll(() => page.locator('.cot2').evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(260)
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 800 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.screenshot({ path: testInfo.outputPath('sequence-record.png'), fullPage: true })
})

test('새 입력이 없으면 시간을 보내도 다음 단계가 생성되지 않는다', async ({ page }) => {
  await page.clock.install()
  await page.clock.fastForward(90_000)
  await expect(page.locator('.g-act2')).toHaveCount(1)
  await expect(page.locator('.g-amsg')).toHaveCount(0)
  await expect(page.locator('.ar')).toHaveClass('ar running think')
  await page.getByRole('button', { name: '중지', exact: true }).click()
  await expect(page.locator('.ar')).toHaveClass('ar stopped think')
  await page.clock.fastForward(90_000)
  await expect(page.locator('.g-amsg')).toHaveCount(0)
  await expect(page.locator('.activity-spinner')).toHaveCount(0)
})

test('설명을 읽는 중 완료되면 접힌 작업의 헤더로 포커스를 돌려준다', async ({ page }) => {
  await page.locator('.cot2').focus()
  // Dispatch an observed completion without moving focus to a fixture button.
  await page.getByRole('button', { name: '중간 답변', exact: true }).evaluate(el => (el as HTMLButtonElement).click())
  await expect(page.locator('.g-act2 .hd')).toBeFocused()
  await expect(page.locator('.cot2')).not.toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('.g-act2 .hd')).toHaveAttribute('aria-expanded', 'true')
})

test('모션 최소화에서도 스트리밍 텍스트와 재열람 기능은 사라지지 않는다', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.ad')).toHaveCSS('transition-duration', '0s')
  await page.getByRole('button', { name: '중간 답변', exact: true }).click()
  await page.getByRole('button', { name: '답변 추가', exact: true }).click()
  await expect(page.locator('.g-amsg')).toContainText('추가 근거를 확인하겠습니다.')
  await page.getByRole('button', { name: '중지', exact: true }).click()
  await expect(page.locator('.g-amsg')).toHaveAttribute('data-response-state', 'interrupted')
  await expect(page.locator('.client-stream-caret')).toHaveCount(0)
})

test('작업은 진행 중인 채 단계만 완료돼도 설명 포커스와 읽기 위치를 보존한다', async ({ page }) => {
  const summary = page.locator('.cot2')
  await page.getByRole('button', { name: '요약 추가', exact: true }).click()
  await summary.focus()
  await page.keyboard.press('Home')
  await expect.poll(() => summary.evaluate(el => el.scrollTop)).toBe(0)
  await page.getByRole('button', { name: '단계만 완료', exact: true }).evaluate(el => (el as HTMLButtonElement).click())
  await expect(page.locator('.arh')).toBeFocused()
  await expect(page.locator('.g-act2 .hd')).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Enter')
  await expect(summary).toBeVisible()
  await expect.poll(() => summary.evaluate(el => el.scrollTop)).toBe(0)
})

test('숨김 중 받은 요약은 복귀 후 표시하고 작은 화면에서도 높이를 제한한다', async ({ page }) => {
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')) })
  await page.getByRole('button', { name: '요약 추가', exact: true }).click()
  await expect(page.locator('.cot2')).toContainText('표시 시험 12')
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => false }); document.dispatchEvent(new Event('visibilitychange')) })
  await expect.poll(() => page.locator('.cot2').evaluate(el => el.scrollHeight - el.clientHeight - el.scrollTop)).toBeLessThan(2)
  await page.setViewportSize({ width: 390, height: 400 })
  await page.getByRole('button', { name: '중간 답변', exact: true }).click()
  await page.locator('.g-act2 .hd').click()
  await page.locator('.arh').click()
  await expect.poll(() => page.locator('.cot2').evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(160)
})
