import { expect, test, type Page } from '@playwright/test'
import { seedOwnedStrategyEdit } from './fixtures/client-main-owned-strategy-edit'

type Request = { id: string; scope: string; identity: string; aborted: boolean }
type Fixture = { patch: (patch: { scope?: string; identity?: string; missing?: boolean }) => void; requests: () => Request[]; resolve: (index: number, wrong?: boolean) => void }
async function open(page: Page, missing = false) {
  const writes: string[] = []
  page.on('request', r => { if (!['GET', 'HEAD'].includes(r.method()) || new URL(r.url()).pathname.startsWith('/api/')) writes.push(r.url()) })
  const seed = await seedOwnedStrategyEdit(page)
  await page.addInitScript(missing => Reflect.set(window, 'mainTerminalMarketMissing', missing), missing)
  // Acquire the real compiled bootstrap once before Main can load or reload.
  // Fail on transport/status/MIME/seam errors; never retry or invent a module.
  const response = await page.request.get('/src/client-bootstrap.tsx', { maxRetries: 0 })
  if (response.status() !== 200) throw Error('TEST_ACTUAL_MAIN_BOOTSTRAP_REQUIRED:HTTP_' + response.status())
  if (!/^(?:application|text)\/(?:javascript|ecmascript)(?:\s*;|$)/i.test(response.headers()['content-type'] ?? '')) {
    throw Error('TEST_ACTUAL_MAIN_BOOTSTRAP_REQUIRED:JAVASCRIPT_MIME')
  }
  const body = await response.text()
  const original = /(["'])\/src\/components\/ClientMainExperience\.tsx(?:\?[^"']*)?\1/g
  if ([...body.matchAll(original)].length !== 1) throw Error('TEST_ACTUAL_MAIN_BOOTSTRAP_REQUIRED')
  const compiledBody = body.replace(original, '"/tests/fixtures/client-main-terminal-market-source.tsx"')
  const headers = { ...response.headers(), 'content-length': String(Buffer.byteLength(compiledBody)) }
  await page.route('**/src/client-bootstrap.tsx*', route => route.fulfill({ response, headers, body: compiledBody }))
  await page.goto('/#/trade')
  await expect(page.locator('.client-account-terminal')).toBeVisible()
  await expect.poll(() => page.evaluate(() => !!Reflect.get(window, 'mainTerminalMarketFixture'))).toBe(true)
  return { ...seed, writes }
}
const requests = (page: Page) => page.evaluate(() => (Reflect.get(window, 'mainTerminalMarketFixture') as Fixture).requests())
const patch = (page: Page, value: Parameters<Fixture['patch']>[0]) => page.evaluate(value => (Reflect.get(window, 'mainTerminalMarketFixture') as Fixture).patch(value), value)
const settle = (page: Page, index: number, wrong = false) => page.evaluate(({ index, wrong }) => (Reflect.get(window, 'mainTerminalMarketFixture') as Fixture).resolve(index, wrong), { index, wrong })
const inspection = (page: Page) => page.locator('[data-market-inspection]')
async function choose(page: Page, asset: string) {
  await page.locator('.cmp-trigger').click()
  const dialog = page.getByRole('dialog', { name: '종목 선택', exact: true })
  await dialog.getByRole('searchbox', { name: '종목 검색' }).fill(asset)
  await expect(dialog.locator('.cmp-select')).toHaveCount(1)
  await dialog.locator('.cmp-select').click()
  await expect(dialog).toHaveCount(0)
}

test('실제 Main: 명시 owner Mock 종목 검색·조회와 3탭/9기간/8지표는 원래 전략 bytes를 보존한다', async ({ page }) => {
  const { key, raw, writes } = await open(page)
  expect(await requests(page)).toEqual([])
  const selected = await page.locator('.client-account-terminal').getAttribute('data-selected-strategy')
  await choose(page, 'ETH'); await expect.poll(async () => (await requests(page)).length).toBe(1)
  expect((await requests(page))[0]).toMatchObject({ id: 'ETH', scope: 'main-owned-edit@example.test', identity: 'explicit-mock-market-1' })
  await settle(page, 0)
  await expect(inspection(page).locator('canvas').first()).toBeVisible()
  await expect(inspection(page)).toContainText('EXPLICIT TEST MOCK explicit-mock-market-1 ETH #0')
  await expect(page.locator('.ctm-tabs [role=tab]')).toHaveText(['차트', '정보', '데이터'])
  await page.getByRole('tab', { name: '정보', exact: true }).click()
  await expect(page.locator('.ctm-pane:visible')).toContainText('Explicit Mock ETH')
  await page.getByRole('tab', { name: '데이터', exact: true }).click()
  const periods = page.locator('.ctm-periods button')
  await expect(periods).toHaveCount(9)
  for (let i = 0; i < 9; i++) {
    await periods.nth(i).click(); await expect(periods.nth(i)).toHaveAttribute('aria-pressed', 'true')
    await expect(page.locator('.ctm-data-card')).toHaveCount(8)
    await expect(page.locator('.ctm-data-card .ctm-values')).toHaveCount(8)
  }
  await page.getByRole('tab', { name: '차트', exact: true }).click()
  expect((await requests(page)).length).toBe(1)
  expect(await page.locator('.client-account-terminal').getAttribute('data-selected-strategy')).toBe(selected)
  expect(await page.evaluate(key => sessionStorage.getItem(key), key)).toBe(raw)
  expect(writes).toEqual([])
})

test('실제 Main: 기본 미공급과 foreign owner 포트는 readonly 3탭을 유지하고 검색·요청을 만들지 않는다', async ({ page }) => {
  const { key, raw, writes } = await open(page, true)
  await expect(page.locator('.cmp-trigger')).toHaveCount(0)
  await expect(page.locator('.ctm-tabs [role=tab]')).toHaveCount(3)
  await page.getByRole('tab', { name: '정보', exact: true }).click()
  await expect(page.locator('.ctm-pane:visible')).toContainText('아직 제공된 자료가 없습니다.')
  await page.getByRole('tab', { name: '데이터', exact: true }).click()
  await expect(page.locator('.ctm-data-card')).toHaveCount(8)
  await patch(page, { missing: false, scope: 'foreign-owner@example.test' })
  await expect(page.locator('.cmp-trigger')).toHaveCount(0)
  expect(await requests(page)).toEqual([])
  await patch(page, { scope: 'main-owned-edit@example.test' })
  await expect(page.locator('.cmp-trigger')).toBeVisible()
  expect(await requests(page)).toEqual([])
  expect(await page.evaluate(key => sessionStorage.getItem(key), key)).toBe(raw)
  expect(writes).toEqual([])
})

test('실제 Main: 선택/identity 교체는 이전 요청을 abort하고 역순 응답·틀린 종목은 차트를 덮지 않는다', async ({ page }) => {
  const { key, raw, writes } = await open(page)
  await choose(page, 'ETH'); await expect.poll(async () => (await requests(page)).length).toBe(1)
  await choose(page, 'SOL'); await expect.poll(async () => (await requests(page)).length).toBe(2)
  expect((await requests(page))[0].aborted).toBe(true)
  await settle(page, 0); await expect(inspection(page).locator('canvas')).toHaveCount(0)
  await settle(page, 1, true)
  await expect(inspection(page)).toContainText('자료를 불러오지 못했습니다.')
  await expect(inspection(page).locator('canvas')).toHaveCount(0)
  await inspection(page).getByRole('button', { name: '다시 시도', exact: true }).click()
  await expect.poll(async () => (await requests(page)).length).toBe(3)
  await patch(page, { identity: 'explicit-mock-market-2' })
  await expect(page.locator('.cmp-trigger')).toBeVisible()
  await expect.poll(async () => (await requests(page))[2].aborted).toBe(true)
  await settle(page, 2); await expect(inspection(page)).toHaveCount(0)
  await choose(page, 'BTC'); await expect.poll(async () => (await requests(page)).length).toBe(4)
  await settle(page, 3)
  await expect(inspection(page)).toContainText('EXPLICIT TEST MOCK explicit-mock-market-2 BTC #3')
  expect(await page.evaluate(key => sessionStorage.getItem(key), key)).toBe(raw)
  expect(writes).toEqual([])
})

test('실제 Main: 공급자 제거·재공급은 취소 응답을 버리고 실제 사용자 로그아웃 뒤 늦은 자료를 노출하지 않는다', async ({ page }) => {
  const { key, raw, writes } = await open(page)
  await choose(page, 'ETH'); await expect.poll(async () => (await requests(page)).length).toBe(1)
  await patch(page, { missing: true })
  await expect(page.locator('.cmp-trigger')).toHaveCount(0)
  await expect.poll(async () => (await requests(page))[0].aborted).toBe(true)
  await settle(page, 0); await expect(inspection(page)).toHaveCount(0)
  await patch(page, { missing: false }); await expect.poll(async () => (await requests(page)).length).toBe(2)
  const hamburger = page.locator('.client-hamburger')
  if (await hamburger.isVisible()) { await hamburger.focus(); await hamburger.click() }
  else await page.locator('.client-rail-logo-row button').click()
  await page.locator('[data-sidebar-action=profile-settings]:visible').click()
  await page.locator('[data-account-action=logout]').click()
  expect(await page.evaluate(() => sessionStorage.getItem('teth-client-profile-preview'))).toBeNull()
  await expect.poll(async () => (await requests(page))[1].aborted).toBe(true)
  await settle(page, 1)
  await expect(page.locator('.cmp-trigger')).toHaveCount(0)
  await expect(inspection(page)).toHaveCount(0)
  expect((await requests(page)).length).toBe(2)
  expect(await page.evaluate(key => sessionStorage.getItem(key), key)).toBe(raw)
  expect(writes).toEqual([])
})

test('실제 Main: 포트 identity 재렌더와 검색 취소·탭 왕복은 별도 자료를 합성하지 않고 선택만 유지한다', async ({ page }) => {
  const { key, raw, writes } = await open(page)
  await page.locator('.cmp-trigger').click()
  await page.getByRole('searchbox', { name: '종목 검색' }).fill('SOL')
  await page.getByRole('dialog', { name: '종목 선택', exact: true }).getByRole('button', { name: '닫기', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await requests(page)).toEqual([])
  await choose(page, 'SOL'); await expect.poll(async () => (await requests(page)).length).toBe(1)
  await settle(page, 0)
  await expect(inspection(page).locator('canvas').first()).toBeVisible()
  const canvas = await inspection(page).locator('canvas').first().elementHandle()
  await patch(page, {})
  expect((await requests(page)).length).toBe(1)
  expect(await inspection(page).locator('canvas').first().evaluate((node, original) => node === original, canvas)).toBe(true)
  await page.getByRole('tab', { name: '정보', exact: true }).click()
  await page.getByRole('tab', { name: '차트', exact: true }).click()
  expect((await requests(page)).length).toBe(1)
  expect(await page.evaluate(key => sessionStorage.getItem(key), key)).toBe(raw)
  expect(writes).toEqual([])
})

test('실제 Main: 검색어가 있어도 첫 Escape는 picker를 닫고 원 trigger·차트·선택·조회 횟수를 보존한다', async ({ page }) => {
  const { key, raw, writes } = await open(page)
  await choose(page, 'ETH'); await expect.poll(async () => (await requests(page)).length).toBe(1)
  await settle(page, 0)
  await expect(inspection(page).locator('canvas').first()).toBeVisible()
  const canvas = await inspection(page).locator('canvas').first().elementHandle()
  const selected = await page.locator('.client-account-terminal').getAttribute('data-selected-strategy')
  const trigger = page.locator('.cmp-trigger')
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: '종목 선택', exact: true })
  const search = dialog.getByRole('searchbox', { name: '종목 검색' })
  await search.fill('SOL'); await expect(search).toHaveValue('SOL')
  await search.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  expect(await inspection(page).locator('canvas').first().evaluate((node, original) => node === original, canvas)).toBe(true)
  expect(await page.locator('.client-account-terminal').getAttribute('data-selected-strategy')).toBe(selected)
  await expect(page.locator('.ctm-symbol b')).toHaveText('ETH/USDT')
  expect((await requests(page)).length).toBe(1)
  expect(await page.evaluate(key => sessionStorage.getItem(key), key)).toBe(raw)
  expect(writes).toEqual([])
})
