import { finishSourceOfflineResearchPlan } from './fixtures/source-offline-research-entry'
import { expect, test, type Page } from '@playwright/test'

async function openPlan(page: Page) {
  await page.clock.install()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const input = page.locator('.client-home-content textarea')
  await input.fill('비트코인 과매도 반등 전략을 검증하고 싶어요')
  await input.press('Enter')
  await page.clock.fastForward(12_000)
  await finishSourceOfflineResearchPlan(page)
  await expect(page.getByRole('heading', { name: '연구 계획', exact: true })).toBeVisible()
}
async function artifact(page: Page, title: string) {
  const trigger = page.getByRole('button', { name: '연구 문서 열기', exact: true })
  if (await trigger.isVisible()) await trigger.click()
  await page.locator('.rw-artifact').filter({ hasText: new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(검토 필요)?$`) }).click()
}

test('Critic 질문은 필터 미적용·적용 상태에 맞는 원문을 표시한다', async ({ page }) => {
  await openPlan(page)
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(39_000)
  await artifact(page, '가설')
  await expect(page.locator('.g-adoc')).toContainText('이 패턴이 Research 구간과 Holdout 구간 모두에서 확인되어야 가설이 유지됩니다. 결과는 Backtest, Holdout artifact에서 확인하십시오.')
  await artifact(page, '비판 검토 기록')
  await expect(page.locator('.research-critic-document')).toHaveAttribute('data-version', '1')
  await page.getByLabel('비판 검토 기록에 질문').fill('필터는 적용됐나요?')
  await page.getByRole('button', { name: '문서 질문 보내기', exact: true }).click()
  await expect(page.locator('.rw-answer').last()).toHaveText('저변동성 구간에 손실 71% 집중 (v1 기준). 상위 3개 거래가 수익의 42%.')
  await expect(page.locator('.rw-answer').last()).not.toContainText('필터로 수정됨')
  await page.clock.fastForward(15_000)
  await expect(page.locator('.research-critic-document')).toHaveAttribute('data-version', '2')
  await page.getByLabel('비판 검토 기록에 질문').fill('지금 필터 상태는 어떤가요?')
  await page.getByRole('button', { name: '문서 질문 보내기', exact: true }).click()
  await expect(page.locator('.rw-answer')).toHaveText([
    '저변동성 구간에 손실 71% 집중 (v1 기준). 상위 3개 거래가 수익의 42%.',
    '저변동성 구간에 손실 71% 집중 (v1 기준), 필터로 수정됨. 상위 3개 거래가 수익의 72%, 소수 거래 의존.',
  ])
})

test('95초 연구에서 문서가 순차 생성되고 완료 후 최종 보고서로 이어진다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openPlan(page)
  await expect(page.locator('.rw-artifact')).toHaveCount(1)
  await expect(page.locator('.rw-team')).toHaveCount(7)
  await expect(page.locator('.rw-team small')).toHaveText(Array(7).fill('대기'))
  await expect(page.locator('.rw-artifact svg path').first()).toHaveAttribute('d', 'M6 3h8l5 5v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await expect(page.locator('.rw-title')).toContainText('연구 진행 중')
  await expect(page.locator('.rw-composer')).toHaveCount(0)
  await page.clock.fastForward(39_000)
  await expect(page.locator('.g-finding > div')).toHaveCount(5)
  await expect(page.locator('.g-finding')).toContainText('저변동성 구간 과잉 거래')
  await expect(page.locator('.g-finding')).toContainText('시장이 거의 움직이지 않을 때도 거래해 손실의 71%가 그 구간에서 발생했습니다.')
  await expect(page.locator('.rw-artifact')).toHaveCount(5)
  await artifact(page, '비판 검토 기록')
  await expect(page.locator('.research-critic-document')).toHaveAttribute('data-version', '1')
  await expect(page.locator('.research-critic-document')).not.toContainText('필터로 수정됨')
  await expect(page.locator('.research-critic-blocks p').nth(1)).toHaveText('저변동성 구간에 손실 71% 집중 (v1 기준). 상위 3개 거래가 수익의 42%.')
  await page.clock.fastForward(15_000)
  await expect(page.locator('.research-critic-document')).toHaveAttribute('data-version', '2')
  await expect(page.locator('.research-critic-document')).toContainText('수익의 72%')
  await expect(page.locator('.research-critic-blocks p').nth(1)).toHaveText('저변동성 구간에 손실 71% 집중 (v1 기준), 필터로 수정됨. 상위 3개 거래가 수익의 72%, 소수 거래 의존.')
  await expect(page.locator('.research-critic-blocks p').nth(2)).toHaveText('수익성 확인. 일관성은 Holdout, Forward에서 계속 확인 필요.')
  await page.getByRole('tab', { name: '연구 과정', exact: true }).click()
  await page.clock.fastForward(41_000)
  await expect(page.getByRole('button', { name: '최종 보고서 열기', exact: true })).toBeVisible()
  await expect(page.locator('.rw-complete .g-note')).toHaveText('검증 7단계 완료, 전략 수정 1회, 백테스트 11회, Holdout 통과')
  await page.clock.fastForward(1_300)
  await expect(page.getByRole('heading', { name: '검증 무결성' })).toBeVisible()
  await expect(page.locator('.rw-artifact')).toHaveCount(10)
  // The latest client report itself includes this provenance, without a new banner.
  await expect(page.locator('.rw-workspace .meta')).toContainText('데모: 표준 샘플 데이터로 검증 과정을 시연 중')
  await expect(page.locator('.rw-workspace')).not.toContainText(/MOCK|95초/)
  await expect(page.locator('.rw-preview-tools')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('인라인 코멘트·문서별 초안·질문 맥락과 최대 5개 열린 탭을 보존한다', async ({ page }) => {
  await openPlan(page)
  await page.getByRole('button', { name: '손절 수정 요청', exact: true }).click()
  await page.getByLabel('손절 코멘트').fill('-2%로')
  await page.getByRole('button', { name: '적용', exact: true }).click()
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^손절$/ }) })).toContainText('−2%')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(96_000)
  await artifact(page, '비판 검토 기록')
  await page.getByLabel('비판 검토 기록에 질문').fill('집중도와 손절의 관계를 알고 싶어요')
  await artifact(page, '백테스트 v2')
  await page.getByLabel('백테스트 v2에 질문').fill('2025년 손익은 왜 약해졌나요?')
  await artifact(page, '비판 검토 기록')
  await expect(page.getByLabel('비판 검토 기록에 질문')).toHaveValue('집중도와 손절의 관계를 알고 싶어요')
  for (const title of ['가설', '전략 v1', '전략 v2', '스트레스 테스트', '봉인 구간 검증', '검증 결과']) await artifact(page, title)
  await expect(page.getByRole('tab')).toHaveCount(5)
  await expect(page.getByRole('tab').first()).toHaveText('연구 과정')
  await artifact(page, '백테스트 v2')
  await expect(page.getByLabel('백테스트 v2에 질문')).toHaveValue('2025년 손익은 왜 약해졌나요?')
  await page.getByRole('button', { name: '문서 질문 보내기', exact: true }).click()
  await expect(page.locator('.rw-user-message')).toHaveText('2025년 손익은 왜 약해졌나요?')
  await expect(page.locator('.rw-answer')).toContainText('v2는 10회 거래')
  await expect(page.getByRole('slider', { name: '백테스트 v2 가격과 매수·매도 시점' })).toBeVisible()
  await expect(page.locator('.rw-price svg title')).toHaveCount(20)
  await page.reload()
  await expect(page.getByRole('heading', { name: '백테스트 v2', exact: true })).toBeVisible()
  await expect(page.locator('.rw-user-message')).toHaveText('2025년 손익은 왜 약해졌나요?')
})

test('320~1440px에서 문서·차트와 모바일 탐색을 유지하고 미공급 계획 결과를 Paper로 등록하지 않는다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openPlan(page)
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(96_000)
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 820 })
    await artifact(page, '백테스트 v2')
    await expect(page.locator('.rw-price')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await artifact(page, '스트레스 테스트')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 820 })
  await page.getByRole('button', { name: '연구 문서 열기' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '연구 문서 열기' })).toBeFocused()
  await expect(page.getByRole('button', { name: '연구 문서 열기' })).toHaveAttribute('aria-expanded', 'false')
  await artifact(page, '검증 결과')
  await page.getByRole('button', { name: '거래소 연결', exact: true }).click()
  await page.getByRole('button', { name: 'Binance로 간편 연결', exact: true }).click()
  await expect(page.locator('.rw-notice')).toContainText('계정 연결이나 권한 요청을 실행하지 않았습니다')
  await page.getByRole('button', { name: '실행 확인 화면 보기', exact: true }).click()
  await page.getByRole('button', { name: '실전 시작 (데모 잠금)', exact: true }).click()
  await expect(page.locator('.rw-notice')).toContainText('실제 자금 실행은 데모에서 잠겨 있어요')
  const url = page.url()
  await page.getByRole('button', { name: '가상 검증으로 시작', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '선택한 계획의 연구 결과가 아직 연결되지 않았어요.' })).toBeVisible()
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await expect(page.locator('.client-account-terminal')).toHaveCount(0)
  expect(page.url()).toBe(url)
  expect(await page.evaluate(() => Object.keys(sessionStorage).filter(key => key.startsWith('teth-client-user-strategies:')))).toEqual([])
  await expect(page.getByLabel('실행 확인에 질문')).toBeVisible()
  expect(errors).toEqual([])
})

test('저장된 ETH 문서의 RSI·추세필터·1시간·손절·익절 없음은 기존 계획에서 복원하고 고정 결과와 구분한다', async ({ page }) => {
  await page.clock.install()
  await page.goto('/?ui-debug=1')
  const input = page.locator('.client-home-content textarea')
  await input.fill('이더리움 추세 전략을 만들고 싶어요')
  await input.press('Enter')
  await page.clock.fastForward(12_000)
  await expect(page.getByRole('button', { name: /연구 계획.*(?:확인|크게 보기)/ })).toHaveCount(0)
  for (const choice of ['1시간마다', '-2%', '익절 없이 진행']) {
    await page.getByRole('button', { name: choice, exact: true }).click()
    await page.clock.fastForward(12_000)
  }
  // This fresh no-TP result does not pass. Restoring an explicitly supplied
  // previous base document is a compatibility consumer, never fresh approval.
  await expect(page.getByRole('button', { name: /연구 계획.*(?:확인|크게 보기)/ })).toHaveCount(0)
  await page.addInitScript(() => {
    if (sessionStorage.getItem('explicit-eth-archived-document')) return
    sessionStorage.setItem('explicit-eth-archived-document', 'true')
    const saved = JSON.parse(sessionStorage.getItem('teth-client-experience')!)
    const session = saved.sessions.find((s: { id: string }) => s.id === saved.currentId)
    session.workspace = 'research'
    const turnId = session.inlineResults.at(-1).turnId
    session.researchPlanTurnId = turnId
    session.researchPlanTurnIds = [turnId]
    const scope = `inline-plan:${JSON.stringify([session.id, turnId])}`
    sessionStorage.setItem(`teth-client-research-documents:${scope}`, JSON.stringify({active:'plan',tabs:['plan'],drafts:{plan:''},positions:{},replies:[],edits:{}}))
    sessionStorage.setItem('teth-client-experience', JSON.stringify(saved))
  })
  await page.reload()
  await expect(page.locator('article .meta')).toContainText('ETH/USDT, 1시간봉')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^진입$/ }) })).toContainText('전봉 RSI 44 이하 + 당일 +0.5% 반등 + 추세 필터(20/60 이평)')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^손절$/ }) })).toContainText('−2%')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^익절$/ }) })).toContainText('없음')
  await page.locator('.rw-preview-tools summary').click()
  await expect(page.locator('.rw-preview-tools')).toContainText('선택한 계획: ETH/USDT · 1시간봉 · 추세 추종 · 손절 −2% · 익절 없음')
  await expect(page.locator('.rw-preview-tools')).toContainText('고정 원본 재생 사례: BTC/USDT · 1일봉 · RSI 40 반등 · 손절 −3% · 익절 +8%')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(2_000)
  await artifact(page, '가설')
  await expect(page.locator('article')).toContainText('Momentum continuation following volume-confirmed breakouts within established uptrends.')
  await expect(page.locator('article')).toContainText('거래가 몰리며 상승 흐름이 확인될 때')
  await page.getByRole('button', { name: '샘플 재생 완료', exact: true }).click()
  await artifact(page, '전략 v2')
  await expect(page.locator('article')).toContainText('RSI(14) < 40')
  await expect(page.locator('.g-row').filter({ has: page.locator('.k', { hasText: /^손절$/ }) })).toContainText('−3%')
})
