import { findCatalogueStrategy } from '../src/client-catalogue'
import { readSharedLocation } from '../src/client-shared-navigation'
import { finishSourceOfflineResearchPlan, revealSourceNavigation } from './fixtures/source-offline-research-entry'
import { expect, test, type Page } from '@playwright/test'

async function menu(page: Page) {
  await page.locator((page.viewportSize()?.width ?? 0) <= 860 ? '.client-hamburger' : '.client-rail-logo-row button').click()
}
async function healthy(page: Page) {
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  expect(await page.evaluate(() => {
    const ids = Array.from(document.querySelectorAll('[id]')).map(el => el.id)
    return ids.filter((id, i) => ids.indexOf(id) !== i)
  })).toEqual([])
  expect(await page.evaluate(() => Boolean(document.activeElement?.closest('[inert],[hidden]')))).toBe(false)
}
async function document(page: Page, title: string) {
  if (title === '연구 과정') { await page.getByRole('tab', { name: '연구 과정', exact: true }).click(); return }
  const trigger = page.getByRole('button', { name: '연구 문서 열기', exact: true })
  if (await trigger.isVisible()) await trigger.click()
  await page.locator('.rw-artifact').filter({ has: page.locator('span', { hasText: new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`) }) }).click()
}

test('빈 계정에서 두 대화·연구·공개 페이지·문서·랭킹을 왕복해도 상태가 섞이지 않는다', async ({ page }) => {
  const openSourceMenu = async () => { await revealSourceNavigation(page); await menu(page) }
  page.setDefaultTimeout(15_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.install()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.clock.pauseAt(await page.evaluate(() => Date.now() + 1000))
  await page.locator('.client-home-content textarea').fill('비트코인 하락 후 반등 전략 🔍')
  await page.getByRole('button', { name: '대화 시작', exact: true }).click()
  await page.locator('.g-composer textarea').fill('첫 대화에 보존할 초안')
  await page.locator('.g-composer textarea').press('Enter')
  await expect(page.locator('.g-urow')).toHaveCount(1)
  await expect(page.locator('.g-composer textarea')).toHaveValue('첫 대화에 보존할 초안')
  await page.clock.resume()
  // Local presentation-only login, no OAuth or network authentication.
  await openSourceMenu()
  await page.locator('[data-sidebar-action="account"]').click()
  await page.locator('.au-btns button').first().click()
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await openSourceMenu()
  await page.locator('.client-new-strategy').click()
  await page.locator('.client-home-content textarea').fill('이더리움 추세 전략')
  await page.getByRole('button', { name: '대화 시작', exact: true }).click()
  await page.getByRole('button', { name: '대화 제목 수정', exact: true }).click()
  await page.getByRole('textbox', { name: '대화 제목 수정', exact: true }).fill('두 번째 연구 🔍')
  await page.getByRole('textbox', { name: '대화 제목 수정', exact: true }).press('Enter')
  await page.locator('.g-composer textarea').fill('두 번째 독립 초안')
  await openSourceMenu()
  await page.locator('.client-session').nth(1).click()
  await page.clock.fastForward(15_000)
  await expect(page.locator('.g-composer textarea')).toHaveValue('첫 대화에 보존할 초안')
  // Fresh source ASK hides the composer; close it through its real action before editing the preserved draft.
  await page.getByRole('button', { name: '질문 카드 닫기', exact: true }).click()
  await expect(page.locator('.g-composer textarea')).toBeVisible()
  await page.locator('.g-composer textarea').fill('')
  await page.getByRole('button', { name: /^전략 맡기기/ }).click()
  // Fresh source needs a calculated passing inline result before its plan.
  await finishSourceOfflineResearchPlan(page)
  const firstTitle = await page.evaluate(() => { const state = JSON.parse(sessionStorage.getItem('teth-client-experience')!); return state.sessions.find((session: { id: string }) => session.id === state.currentId).title })
  await page.locator('.rw-composer textarea').fill('계획 문서의 독립 초안')
  await page.getByRole('button', { name: '연구 시작', exact: true }).click()
  await page.clock.fastForward(18_000)
  await openSourceMenu()
  await page.locator('.client-sidebar .client-drawer-links').getByRole('link', { name: 'TETH 앱 다운로드', exact: true }).click()
  await expect(page.locator('.client-info-download')).toBeVisible()
  await page.clock.fastForward(90_000)
  await page.getByRole('link', { name: '웹에서 바로 시작하기', exact: true }).click()
  await document(page, '연구 과정')
  await expect(page.locator('.g-act-row')).toHaveCount(19)
  await document(page, '연구 계획')
  await expect(page.locator('.rw-composer textarea')).toHaveValue('계획 문서의 독립 초안')
  const labels = await page.locator('.rw-artifact > span').allTextContents()
  expect(labels.length).toBeGreaterThanOrEqual(10)
  for (let i = 0; i < labels.length; i++) {
    await page.setViewportSize({ width: [320, 768, 1440][i % 3], height: 900 })
    await document(page, labels[i])
    await expect(page.locator('.rw-scroll article')).toHaveAttribute('aria-label', `${labels[i]} 문서`)
    await expect(page.locator('.rw-tabs [aria-selected="true"]')).toHaveCount(1)
    expect(await page.locator('.rw-tabs button').count()).toBeLessThanOrEqual(5)
    expect(await page.locator('.rw-scroll svg').evaluateAll(elements => elements.some(el => /NaN|Infinity/.test(el.outerHTML)))).toBe(false)
    await healthy(page)
  }
  await document(page, '검증 결과')
  await page.getByRole('button', { name: '거래소 연결', exact: true }).click()
  await page.getByRole('button', { name: 'Binance로 간편 연결', exact: true }).click()
  await page.getByRole('button', { name: '실행 확인 화면 보기', exact: true }).click()
  await page.getByRole('button', { name: '실전 시작 (데모 잠금)', exact: true }).click()
  await expect(page.locator('.rw-notice')).toContainText('실제 자금 실행은 데모에서 잠겨 있어요')
  const researchUrl = page.url()
  await page.getByLabel('실행 확인에 질문').fill('결과 연결 전에도 보존할 실행 질문')
  await page.getByRole('button', { name: '가상 검증으로 시작', exact: true }).click()
  // An inline plan has no supplied result producer yet. Do not register the
  // unrelated legacy BTC fixture as this plan's result just to reach a chart.
  // Supplied-result registration and terminal controls remain covered by
  // client-research-terminal.spec.ts and the registration-boundary tests.
  await expect(page.getByRole('status').filter({ hasText: '선택한 계획의 연구 결과가 아직 연결되지 않았어요.' })).toBeVisible()
  await expect(page.locator('.client-account-terminal')).toHaveCount(0)
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  expect(page.url()).toBe(researchUrl)
  expect(await page.evaluate(() => Object.keys(sessionStorage).filter(key => key.startsWith('teth-client-user-strategies:')))).toEqual([])
  await expect(page.getByLabel('실행 확인에 질문')).toHaveValue('결과 연결 전에도 보존할 실행 질문')
  await openSourceMenu()
  await page.locator('.client-sidebar').getByRole('button', { name: '연구 기록', exact: true }).click()
  await page.locator('.g-hist-row').filter({ hasText: firstTitle }).click()
  await expect(page.getByRole('button', { name: '내 트레이딩에서 열기', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('실행 확인에 질문')).toHaveValue('결과 연결 전에도 보존할 실행 질문')
  const resultNotice = page.locator('.client-global-notice').filter({ hasText: '선택한 계획의 연구 결과가 아직 연결되지 않았어요.' })
  for (const width of [320, 768, 1100, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(resultNotice).toBeVisible()
    const openDocuments = page.getByRole('button', { name: '연구 문서 열기', exact: true })
    if (width <= 1100) {
      await openDocuments.click()
      await expect(resultNotice).toBeHidden()
      await page.getByRole('button', { name: '연구 문서 닫기', exact: true }).click()
      await expect(openDocuments).toBeFocused()
      await expect(resultNotice).toBeVisible()
    } else {
      await expect(openDocuments).toBeHidden()
      await expect(page.locator('.rw-aux')).toBeVisible()
    }
  }
  await page.setViewportSize({ width: 320, height: 900 })
  await document(page, '연구 계획')
  await expect(resultNotice).toBeVisible()
  await expect(page.locator('.rw-composer textarea')).toHaveValue('계획 문서의 독립 초안')
  await openSourceMenu()
  await page.locator('.client-sidebar').getByRole('button', { name: '연구 기록', exact: true }).click()
  await expect(page.locator('.g-hist-list li')).toHaveCount(2)
  // bd22156 history displays title/date, not the old status-table columns.
  // The underlying research state must still survive the new presentation.
  expect(await page.evaluate(title => JSON.parse(sessionStorage.getItem('teth-client-experience')!).sessions.find((session: { title: string }) => session.title === title).researchStatus, firstTitle)).toBe('검토 필요')
  await page.locator('.g-hist-row').filter({ hasText: '두 번째 연구 🔍' }).click()
  await expect(page.locator('.g-composer textarea')).toHaveValue('두 번째 독립 초안')
  await expect(page.locator('.g-title')).toContainText('두 번째 연구 🔍')
  await expect(page.locator('.g-urow')).toHaveCount(1)
  await openSourceMenu()
  await page.locator('.client-sidebar').getByRole('button', { name: '전략 복사', exact: true }).click()
  // Latest source ranking opens the shared catalogue. Analysis starts a new
  // conversation while the selected conversation and its draft remain intact.
  await page.locator('.strategy-list-card a').first().click()
  const analysedStrategy = findCatalogueStrategy(readSharedLocation(new URL(page.url()).hash)?.nick ?? '')
  expect(analysedStrategy).toBeDefined()
  await page.getByRole('button', { name: '더 보기', exact: true }).click()
  await page.getByRole('menuitem', { name: 'TETH에게 분석시키기', exact: true }).click()
  await expect(page.locator('.g-composer textarea')).toHaveValue('')
  await expect(page.locator('.g-urow')).toHaveCount(1)
  await expect(page.locator('.g-urow')).toContainText('공유 전략 분석 요청:')
  await expect(page.locator('.g-urow')).toContainText(`원본 전략 ID: ${analysedStrategy!.id}`)
  await expect(page.locator('.g-urow')).toContainText(`규칙: ${JSON.stringify(analysedStrategy)}`)
  await page.reload()
  await expect(page.locator('.g-composer textarea')).toHaveValue('')
  await expect(page.locator('.g-urow')).toContainText('공유 전략 분석 요청:')
  await openSourceMenu()
  await expect(page.locator('.client-session')).toHaveCount(3)
  await page.locator('.client-session').filter({ hasText: '두 번째 연구 🔍' }).click()
  await expect(page.locator('.g-composer textarea')).toHaveValue('두 번째 독립 초안')
  await expect(page.locator('.g-title')).toContainText('두 번째 연구 🔍')
  await healthy(page)
  expect(errors).toEqual([])
})

test('공개 페이지 언어·정책·설정·피드백을 교차 사용해도 입력과 조작이 유지된다', async ({ page }) => {
  page.setDefaultTimeout(15_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const draft = '줄바꿈 보존\n<script>테스트 문자열</script> 🔍'.repeat(5)
  await page.locator('.client-home-content textarea').fill(draft)
  await menu(page)
  await page.locator('.client-sidebar .client-drawer-links').getByRole('link', { name: 'TETH 정보', exact: true }).click()
  await page.locator('.public-language-trigger').click()
  await page.getByRole('button', { name: 'Français', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'fr')
  await healthy(page)
  await page.locator('.public-language-trigger').click()
  await page.getByRole('button', { name: '한국어', exact: true }).click()
  await page.locator('.client-site-footer').getByRole('link', { name: '앱 다운로드', exact: true }).click()
  await page.locator('.download-tabs').getByRole('tab', { name: '검증', exact: true }).click()
  await expect(page.locator('.download-tabs').getByRole('tab', { name: '검증', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('.phone-preview [data-screen=report]')).toBeVisible()
  await expect(page.locator('.phone-preview [data-screen=chat]')).toHaveAttribute('inert', '')
  await page.locator('.client-site-footer').getByRole('button', { name: '도움말', exact: true }).click()
  await page.locator('.site-help-pop a[href="/policies/#overview"]').click()
  await page.locator('.tabs').getByRole('link', { name: '서비스 약관', exact: true }).click()
  await page.locator('#v-terms .lnk').filter({ hasText: '투자 위험 고지' }).click()
  await expect(page.locator('#t-risk')).toBeInViewport()
  await healthy(page)
  await page.goBack()
  await page.goBack()
  await page.goBack()
  await expect(page.locator('.client-info-download')).toBeVisible()
  await page.getByRole('link', { name: '웹에서 바로 시작하기', exact: true }).click()
  await expect(page.locator('.client-home-content textarea')).toHaveValue(draft)
  await menu(page)
  await page.locator('[data-sidebar-action="settings"]').click()
  await page.locator('.ca-settings').getByRole('button', { name: '의견 보내기', exact: true }).click()
  await page.locator('.fb-send').click()
  await expect(page.locator('.ca-feedback textarea')).toBeFocused()
  await expect(page.locator('.ca-feedback [role="alert"]')).toBeVisible()
  await page.locator('.ca-feedback textarea').fill('검수용 의견입니다. 외부 전송 없음.')
  await page.locator('.fb-send').click()
  await expect(page.locator('.fb-done')).toBeVisible()
  await page.locator('.fb-done button').click()
  await expect(page.locator('.client-home-content textarea')).toHaveValue(draft)
  await healthy(page)
  expect(errors).toEqual([])
})
