import { expect, test, type Page } from '@playwright/test'
import { securityText } from '../src/client-settings-security-copy'
import settings from '../src/client-settings-copy.json' with { type: 'json' }
const path = '/tests/fixtures/client-settings-security-source-actions.html'
const device = '[data-security-row="device:remote/device"]', exchange = '[data-security-row="permission:permission-read"]'
const fixture = (page: Page, method: string, value?: unknown) => page.evaluate(({ method, value }) => Reflect.get(window, 'securitySourceFixture')[method](value), { method, value })
async function open(page: Page, kind: 'logoutDevice' | 'disconnectExchange') {
  await page.locator(kind === 'logoutDevice' ? device : exchange).getByRole('button').click()
  const dialog = page.getByRole('dialog'); await expect(dialog).toBeVisible(); return dialog
}
test('source actions require observed identities and capabilities; unknown is not empty', async ({ page }) => {
  await page.goto(`${path}?unknown&unavailable#/settings/security`)
  await expect(page.locator('[data-security-row=connectExchange]')).toHaveCount(0)
  await fixture(page, 'setData', { sourceLabel: 'CONFIRMED EMPTY', devices: [], permissions: [] })
  const connect = page.locator('[data-security-row=connectExchange]')
  await expect(connect).toContainText('연결된 거래소가 없습니다')
  await expect(connect.getByRole('button')).toHaveText('거래소 연결')
  await expect(connect.getByRole('button')).toBeDisabled()
  await expect(connect).toContainText(settings.actionUnavailable.ko)
  await fixture(page, 'setData', { sourceLabel: 'SUPPLIED', devices: [{id:'current',label:'Current',current:true},{id:'remote/device',label:'Remote device',current:false}], permissions: [{id:'permission-read',label:'Observed exchange',value:'READ',exchangeConnection:{id:'exchange/one'}},{id:'generic-permission',label:'Not a connection',value:'READ'}] })
  await expect(page.locator('[data-security-row="device:current"] button')).toHaveCount(0)
  for (const selector of [device, exchange]) { await expect(page.locator(selector).getByRole('button')).toBeDisabled(); await expect(page.locator(selector)).toContainText(settings.actionUnavailable.ko) }
  await expect(page.locator('[data-security-row="permission:generic-permission"] button')).toHaveCount(0)
  expect(await fixture(page, 'calls')).toEqual([])
})
for (const kind of ['logoutDevice','disconnectExchange'] as const) test(`${kind} exact source ID is submitted once and acceptance does not change observed state`, async ({ page }) => {
  await page.goto(`${path}#/settings/security`)
  const row = page.locator(kind === 'logoutDevice' ? device : exchange), trigger = row.getByRole('button')
  const dialog = await open(page,kind)
  await expect(dialog.getByRole('button',{name:'취소',exact:true})).toBeFocused()
  expect(await fixture(page,'calls')).toEqual([])
  await dialog.locator('button[type=submit]').evaluate(node => { (node as HTMLButtonElement).click(); (node as HTMLButtonElement).click() })
  await expect(dialog.locator('button[type=submit]')).toBeDisabled()
  expect(await fixture(page,'calls')).toEqual([{kind:`${kind}:0`,id:kind==='logoutDevice'?'remote/device':'exchange/one',aborted:false}])
  await fixture(page,'resolve'); await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('status')).toBeVisible()
  await expect(row).toBeVisible(); await expect(trigger).toBeFocused()
  await expect(page.locator('.stg-security')).not.toContainText('연결을 끊었습니다')
})
test('failure is redacted, remains retryable, and cancellation aborts the pending retry', async ({page}) => {
  await page.goto(`${path}#/settings/security`); const dialog=await open(page,'disconnectExchange')
  await dialog.locator('button[type=submit]').click(); await fixture(page,'reject')
  await expect(dialog.getByRole('alert')).toHaveText(securityText('ko','failed'))
  await expect(page.locator('body')).not.toContainText('PRIVATE_SOURCE_ACTION_ERROR')
  await dialog.locator('button[type=submit]').click()
  await dialog.getByRole('button',{name:'취소',exact:true}).click()
  expect(await fixture(page,'calls')).toEqual([{kind:'disconnectExchange:0',id:'exchange/one',aborted:false},{kind:'disconnectExchange:0',id:'exchange/one',aborted:true}])
  await fixture(page,'resolve',1); await expect(page.getByRole('status')).toHaveCount(0)
})
for (const boundary of ['cancel','owner','dataset','callback','removed-id','unmount','route'] as const) test(`${boundary} retires a pending source action and ignores late completion`, async ({page}) => {
  await page.goto(`${path}#/settings/security`);const dialog=await open(page,'logoutDevice')
  await dialog.locator('button[type=submit]').click()
  if(boundary==='cancel') await page.keyboard.press('Escape')
  else if(boundary==='owner') await fixture(page,'setOwner','owner-b')
  else if(boundary==='dataset') await fixture(page,'setDataset','dataset-b')
  else if(boundary==='callback') await fixture(page,'replaceCallback')
  else if(boundary==='removed-id') await fixture(page,'setData',{sourceLabel:'NEW OBSERVATION',devices:[],permissions:[]})
  else if(boundary==='unmount') await fixture(page,'setMounted',false)
  else await page.evaluate(()=>{location.hash='#/settings/general'})
  await expect(dialog).toHaveCount(0)
  expect(await fixture(page,'calls')).toEqual([{kind:'logoutDevice:0',id:'remote/device',aborted:true}])
  await fixture(page,'resolve');await expect(page.getByRole('status')).toHaveCount(0)
})
test('only confirmed empty connections offer direct connect and callback replacement retires it',async({page})=>{
  await page.goto(`${path}#/settings/security`);await fixture(page,'setData',{sourceLabel:'EMPTY',devices:[],permissions:[]})
  const button=page.locator('[data-security-row=connectExchange] button')
  await button.evaluate(node=>{(node as HTMLButtonElement).click();(node as HTMLButtonElement).click()})
  await expect(button).toBeDisabled();expect(await fixture(page,'calls')).toEqual([{kind:'connectExchange:0',aborted:false}])
  await fixture(page,'replaceCallback');await expect(button).toBeEnabled()
  expect(await fixture(page,'calls')).toEqual([{kind:'connectExchange:0',aborted:true}])
  await fixture(page,'resolve');await expect(page.getByRole('status')).toHaveCount(0)
  await button.click();await fixture(page,'resolve',1);await expect(page.getByRole('status')).toBeVisible()
  await expect(page.locator('[data-security-row=connectExchange]')).toBeVisible()
})
test('malformed IDs and unconfirmed current markers are never submitted',async({page})=>{
  await page.goto(`${path}#/settings/security`);await fixture(page,'setData',{sourceLabel:'BOUNDED',devices:[{id:' bad ',label:'Invalid device',current:false},{id:'unknown-current',label:'Unknown current'}],permissions:[{id:'permission-read',label:'Invalid exchange',value:'READ',exchangeConnection:{id:''}}]})
  await expect(page.locator('[data-security-row="device: bad "] button')).toBeDisabled()
  await expect(page.locator('[data-security-row="device:unknown-current"] button')).toHaveCount(0)
  await expect(page.locator(exchange+' button')).toBeDisabled();expect(await fixture(page,'calls')).toEqual([])
})
for(const language of ['ko','en','ja','zh-CN','zh-TW','es','fr'] as const)test(`${language} source buttons, confirmation and focus remain readable at 320px and 200%`,async({page})=>{
  await page.setViewportSize({width:320,height:900});await page.addInitScript(language=>localStorage.setItem('tethLang',language),language)
  await page.goto(`${path}#/settings/security`)
  await expect(page.getByRole('heading',{name:securityText(language,'devicesTitle'),exact:true})).toBeVisible()
  await expect(page.getByRole('heading',{name:securityText(language,'exchangesTitle'),exact:true})).toBeVisible()
  const dialog=await open(page,'disconnectExchange')
  await expect(dialog.getByRole('heading')).toHaveText(securityText(language,'disconnectTitle').replace('{label}','Observed exchange'))
  await expect(dialog.getByRole('button',{name:settings.cancel[language],exact:true})).toBeFocused()
  await dialog.evaluate(node=>{for(const el of node.querySelectorAll<HTMLElement>('h2,p,button'))el.style.fontSize=`${parseFloat(getComputedStyle(el).fontSize)*2}px`})
  for(const el of await dialog.locator('h2,p,button').all())expect(await el.evaluate(node=>node.scrollWidth<=node.clientWidth+1)).toBe(true)
  await page.keyboard.press('Escape');await expect(page.locator(exchange+' button')).toBeFocused()
})
