import { expect, test } from '@playwright/test'

test('원본P0: 템플릿은 해석에만 쓰고 입력 원문을 말풍선·편집·새로고침에 보존한다', async ({ page }) => {
  test.setTimeout(30_000)
  await page.clock.install()
  await page.addInitScript(() => sessionStorage.setItem('teth-client-profile-preview', JSON.stringify({ name: '검색 검수자', email: 'intake@example.test' })))
  await page.goto('/')
  await page.locator('.g-tpl[data-id="auto"]').click()
  await page.locator('.g-tpl[data-id="btc"]').click()
  const raw = '하락 뒤 반등할 때 살래요\n조건은 같이 정해주세요'
  await page.locator('#strategy-idea').fill(raw)
  await page.locator('#strategy-idea').press('Enter')
  await expect(page.locator('.g-umsg')).toHaveText(raw)
  await page.clock.fastForward(15_000)
  const session = await page.evaluate(() => JSON.parse(sessionStorage.getItem('teth-client-experience')!).sessions[0])
  expect(session.pair).toBe('BTC/USDT')
  expect(session.turns[0].question).toBe(raw)
  expect(session.turns[0].requestText).toContain('BTC')
  await page.reload()
  await expect(page.locator('.g-umsg')).toHaveText(raw)
  await page.locator('.g-uacts button').first().click()
  await expect(page.locator('.g-composer textarea')).toHaveValue(raw)
  const historyButton = page.locator('.client-research-navigation nav button').first()
  if (!await historyButton.isVisible()) await page.locator((page.viewportSize()?.width ?? 0) <= 860 ? '.client-hamburger' : '.client-rail-logo-row button').click()
  await historyButton.click()
  const templateWords = session.turns[0].requestText.replace('. ' + raw, '')
  expect(raw).not.toContain(templateWords)
  await page.getByRole('searchbox', { name: '연구 기록 검색', exact: true }).fill(templateWords)
  // 원본 final gHistText는 해석 명령이 아닌 제목·가시 대화만 검색합니다.
  await expect(page.locator('.g-hist-row')).toHaveCount(0)
  await page.getByRole('searchbox', { name: '연구 기록 검색', exact: true }).fill('하락 반등')
  await expect(page.locator('.g-hist-row')).toHaveCount(1)
  await page.evaluate(() => {
    const value = JSON.parse(sessionStorage.getItem('teth-client-experience')!)
    value.sessions[0].turns[0].requestText = { damaged: true }
    sessionStorage.setItem('teth-client-experience', JSON.stringify(value))
  })
  await page.reload()
  await expect(page.locator('.g-umsg')).toHaveText(raw)
})

test('템플릿만 선택해 전송하고 같은 대화에서 이어 쓴다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.locator('.g-tpl[data-id="auto"]').click()
  await page.locator('.g-tpl[data-id="btc"]').click()
  await expect(page.locator('#strategy-idea')).toHaveValue('')
  await expect(page.locator('.client-home-send')).toBeVisible()
  await page.locator('#strategy-idea').press('Enter')
  await expect(page.locator('.g-urow')).toHaveCount(1)
  await expect(page.locator('.g-urow')).toContainText('BTC')
  await expect(page.locator('.g-composer textarea')).toBeVisible()
  await expect(page.locator('.client-home-gallery')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('로그인 취소는 입력과 선택을 유지하고 완료 후 정확히 한 번 전송한다', async ({ page }) => {
  await page.goto('/')
  await page.locator('.g-tpl[data-id="anal"]').click()
  await page.locator('#strategy-idea').fill('금리와 함께 살펴봐 주세요')
  await page.locator('.client-free-row button').click()
  await expect(page.locator('.ca-auth')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('#strategy-idea')).toHaveValue('금리와 함께 살펴봐 주세요')
  await expect(page.locator('.g-tpl[data-id="anal"]')).toHaveAttribute('aria-pressed','true')
  await page.locator('.client-free-row button').click()
  await page.locator('.au-btns button').first().click()
  await page.getByRole('textbox', { name: '연령', exact: true }).fill('30')
  await page.getByRole('button', { name: '시장에 입장하기', exact: true }).click()
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await expect(page.locator('.g-urow')).toHaveCount(1)
  await expect(page.locator('.g-urow')).toContainText('금리와 함께 살펴봐 주세요')
  await expect(page.locator('.g-umsg')).toHaveText('금리와 함께 살펴봐 주세요')
  await page.waitForTimeout(500)
  await expect(page.locator('.g-urow')).toHaveCount(1)
})

test('한글 조합 Enter는 보내지 않으며 전체화면에서도 선택과 초안을 유지한다', async ({ page }) => {
  await page.goto('/')
  await page.locator('.g-tpl[data-id="auto"]').click()
  const input = page.locator('#strategy-idea')
  await input.fill('첫째 조건\n둘째 조건')
  await input.dispatchEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true })
  await expect(page.locator('.g-urow')).toHaveCount(0)
  await page.locator('.client-expand').click()
  await expect(page.getByRole('dialog', { name: '전체 화면 입력' })).toBeVisible()
  await expect(page.locator('.client-template-selection')).toContainText('AI가 대신 거래')
  await expect(input).toHaveValue('첫째 조건\n둘째 조건')
  await page.keyboard.press('Escape')
  await expect(input).toHaveValue('첫째 조건\n둘째 조건')
  await expect(input).toBeFocused()
})

test('반응형 하단 밴드에서 선택칩·입력·약관이 겹치지 않는다', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  for (const [width, height] of [[320,568],[390,844],[844,390],[1024,768],[1440,1000]]) {
    await page.setViewportSize({ width, height })
    await page.locator('.g-tpl[data-id="auto"]').click()
    await page.locator('#strategy-idea').fill('비트코인\n손절 기준도 정리해 주세요')
    const band = page.locator('.client-home-band')
    await expect(band).toBeVisible()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
    const parts = await band.evaluate(el => {
      const input = el.querySelector('textarea')!.getBoundingClientRect()
      const terms = el.querySelector('.client-home-terms')!.getBoundingClientRect()
      const chips = el.querySelector('.client-template-selection')!.getBoundingClientRect()
      return { separate: chips.bottom <= input.top + 1 && input.bottom <= terms.top + 1 }
    })
    expect(parts.separate).toBe(true)
    await page.screenshot({ path: info.outputPath(`gallery-band-${width}.png`) })
    await page.getByRole('button', { name: 'AI가 대신 거래 선택 해제' }).click()
  }
})
