import { expect,test } from '@playwright/test'
import copy from '../src/client-trading-intro-copy.json' with {type:'json'}

test('guest trading route is a complete source introduction, not an implicit login or synthetic terminal',async({page},info)=>{
  const errors:string[]=[],mutations:string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  page.on('request',request=>{if(request.url().includes('/api/')&&request.method()!=='GET')mutations.push(request.method())})
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#/trade')
  const root=page.locator('.txh')
  await expect(root.getByRole('heading',{level:1})).toHaveText('AI가 스스로 판단해 거래합니다')
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await expect(page.locator('.client-account-terminal')).toHaveCount(0)
  await expect(root.locator('.txh-ai-cols li')).toHaveCount(9)
  await expect(root.locator('.txh-card')).toHaveCount(2)
  await expect(root.locator('.txh-step')).toHaveCount(3)
  await expect(root.locator('.txh-safe li')).toHaveCount(4)
  await expect(root.locator('.txh-note').first()).toHaveText('영원히 무료, 카드 등록 필요없음')
  await expect(root.locator('.txh-card').first()).toContainText('12,480')
  await expect(root.locator('.txh-example-note')).toContainText('실제 거래 기록이 아닙니다')
  await expect(page.locator('.client-site-footer')).toHaveCount(1)
  await expect(root.locator('video')).toHaveCount(0)
  await root.locator('.txh-safe').scrollIntoViewIfNeeded()
  await expect(root.locator('.txh-safe button')).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
  await root.locator('.txh-hero').scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath('trading-intro.png'),fullPage:true})
  expect(errors).toEqual([]);expect(mutations).toEqual([])
})

test('explicit guest start opens source signup in place; cancellation and completion preserve the introduction',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#/trade')
  const start=page.locator('.txh-hero .txh-cta')
  await start.click();await expect(page.locator('.ca-auth')).toBeVisible()
  await expect(page.getByTestId('connection-plan')).toHaveCount(0)
  await expect(page).toHaveURL(/#\/trade$/)
  await page.keyboard.press('Escape');await expect(page.locator('.ca-auth')).toHaveCount(0)
  await expect(page).toHaveURL(/#\/trade$/);await expect(start).toBeFocused()
  await start.click();await page.getByRole('button',{name:/Google/}).click()
  await expect(page.getByRole('heading',{name:'연령을 알려주세요'})).toBeVisible()
  await page.getByLabel('연령',{exact:true}).fill('28')
  await page.getByRole('button',{name:'시장에 입장하기',exact:true}).click()
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await expect(page.getByTestId('connection-plan')).toHaveCount(0)
  await expect(page.locator('.client-account-terminal')).toHaveCount(0)
  await expect(page.locator('.txh')).toBeVisible()
  await expect(page).toHaveURL(/#\/trade$/)
  // The next explicit action belongs to the now signed-in member.
  await start.click();await expect(page.getByTestId('connection-plan')).toHaveAttribute('data-step','plan')
})

test('member without owned strategies gets intro and source connection plan without losing draft',async({page})=>{
  await page.addInitScript(()=>sessionStorage.setItem('teth-client-profile-preview',JSON.stringify({name:'소개 검수',email:'intro@example.test'})))
  await page.goto('/');await page.locator('#strategy-idea').fill('소개를 보고 와도 남아야 하는 질문')
  await page.locator('.client-site-footer').getByRole('button',{name:'AI 트레이딩',exact:true}).click()
  await expect(page.locator('.txh')).toBeVisible()
  await expect(page.locator('.client-account-terminal')).toHaveCount(0)
  await page.locator('.txh-hero .txh-cta').click()
  await expect(page.getByTestId('connection-plan')).toBeVisible()
  // Keep the original plan styling check on the member path that owns it.
  await expect(page.getByTestId('connection-plan')).toHaveCSS('background-color','rgb(0, 0, 0)')
  // The original first plan has no back control; use its browser-history path.
  await expect(page.getByTestId('connection-plan').getByRole('button',{name:'뒤로',exact:true})).toBeHidden()
  await page.goBack();await expect(page.locator('.txh')).toBeVisible()
  await page.goBack()
  await expect(page.locator('#strategy-idea')).toHaveValue('소개를 보고 와도 남아야 하는 질문')
})

for(const width of [320,390,760,761,1440])test(`${width}px latest source introduction retains copy, four sections and neutral card hierarchy`,async({page},info)=>{
  await page.setViewportSize({width,height:800});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#/trade')
  const root=page.locator('.txh'),card=root.locator('.txh-card').last()
  await expect(root.locator('h2')).toHaveText(['TETH가 쓰는 AI','지금 TETH가 하는 일','시작 방법','실행 설정'])
  await expect(root.locator('.txh-ai-col h3')).toHaveText(['뉴스 확인','시장 분석','판단 정리'])
  await expect(root.locator('.txh-step b')).toHaveText(['대화로 정하기','과거 시장에서 확인','거래소 연결'])
  await expect(root.locator('.txh-safe li b')).toHaveText(['연결 권한','전략 예산','손실 한도','거래 중지'])
  await expect(root.locator('.txh-sub')).toHaveText('거래소 계정을 한 번 승인으로 연결하면 전략이 그 계정에서 직접 주문합니다.')
  await expect(root.locator('.txh-sub br,.txh-step .n,.txh-kick,.txh-term,link')).toHaveCount(0)
  await expect(root.locator('.txh-name')).toHaveText(['워렌 버핏 AI 버전 13','RSI 반등 규칙 버전 2'])
  await expect(card.locator('.txh-body')).toHaveText('비트코인이 내려 RSI가 28입니다. 반등할 수 있지만, 규칙상 30을 다시 넘을 때만 삽니다. 그래서 지금은 기다립니다. 산 뒤 5% 내리면 팔고, 12% 오르면 절반을 정리합니다.')
  await expect(card.locator('dd')).toHaveText(['$1,000','+3.1%','+$31'])
  await expect(card).toHaveCSS('background-color','rgb(48, 48, 48)')
  await expect(card).toHaveCSS('border-radius',width<=760?'20px':'26px')
  await expect(card.locator('dd').first()).toHaveCSS('font-weight','400')
  await expect(root.locator('h2').first()).toHaveCSS('font-weight','400')
  await expect(root.locator('h2').first()).toHaveCSS('font-size',width<=760?'26px':'28px')
  expect(await root.locator('h2').first().evaluate(el=>getComputedStyle(el).fontFamily)).not.toMatch(/Myeongjo|Serif|Batang/)
  await card.scrollIntoViewIfNeeded()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
  await page.screenshot({path:info.outputPath('source-intro-cards.png')})
  const cta=root.locator('.txh-safe .txh-cta')
  await cta.scrollIntoViewIfNeeded();await expect(cta).toHaveCSS('background-color','rgb(255, 255, 255)')
  await cta.click();await expect(page.locator('.ca-auth')).toBeVisible()
  await expect(page.getByTestId('connection-plan')).toHaveCount(0)
  await expect(page).toHaveURL(/#\/trade$/)
})

// User-approved localization supplements the source's missing foreign copy;
// the Korean source and all existing signup/member behavior remain unchanged.
const localizedHeadlines={ko:'AI가 스스로 판단해 거래합니다',en:'AI makes its own trading decisions',ja:'AIが自ら判断して取引します','zh-CN':'AI 自主判断并交易','zh-TW':'AI 自主判斷並交易',es:'La IA decide y opera por sí misma',fr:'L’IA décide et négocie de façon autonome'}
for(const language of ['ko','en','ja','zh-CN','zh-TW','es','fr'] as const)test(`${language} entry controls and editorial meaning localize with Korean source preserved`,async({page},info)=>{
  info.annotations.push({type:'localization-supplement',description:'Korean final-source parity; six foreign translations approved by the full-localization request.'})
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#/trade')
  await page.evaluate(async language=>{const path='/src/client-preferences.ts';const {setClientPreference}=await import(path);setClientPreference('language',language)},language)
  await expect(page.locator('.txh-hero .txh-cta')).toHaveText(copy.start[language])
  await expect(page.locator('.txh-example-note')).toHaveText(copy.example[language])
  await expect(page.locator('.txh')).toHaveAttribute('lang',language)
  await expect(page.locator('.txh h1')).toHaveText(localizedHeadlines[language])
})

test('video ending restores the poster while the video fades and never loops',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/#/trade')
  const floor=page.locator('.txh-floor'),video=floor.locator('video')
  await expect(video).toHaveCount(1)
  await expect.poll(()=>video.evaluate((el:HTMLVideoElement)=>Number.isFinite(el.duration))).toBe(true)
  await expect(floor).toHaveClass(/playing/)
  expect(await video.evaluate((el:HTMLVideoElement)=>{el.currentTime=el.duration-.5;el.dispatchEvent(new Event('timeupdate'));return el.parentElement!.classList.contains('playing')})).toBe(false)
  await expect(floor).not.toHaveClass(/playing/)
  await expect(video).not.toHaveClass(/on/)
  await expect(floor.locator('img')).toHaveCSS('opacity','1')
  await expect(video).toHaveJSProperty('ended',true)
  await page.locator('.txh-safe').scrollIntoViewIfNeeded()
  await page.locator('.txh-hero').scrollIntoViewIfNeeded()
  await expect(video).toHaveJSProperty('paused',true)
})

test('mobile source headline retains its intentional two-line break',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/#/trade')
  await expect(page.locator('.txh h1')).toBeVisible()
  expect(await page.locator('.txh h1').evaluate(el=>{
    const first=document.createRange(),last=document.createRange()
    first.selectNodeContents(el.firstChild!);last.selectNodeContents(el.lastChild!)
    return last.getBoundingClientRect().top>first.getBoundingClientRect().top+10
  })).toBe(true)
})

test('decorative video respects offscreen, reduced motion and route cleanup',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/#/trade')
  const video=page.locator('.txh-floor video')
  await expect(video).toHaveCount(1)
  await expect(video).toHaveJSProperty('loop',false)
  await expect(video).toHaveJSProperty('muted',true)
  await expect.poll(()=>video.evaluate((el:HTMLVideoElement)=>el.readyState)).toBeGreaterThanOrEqual(1)
  await page.locator('.txh-safe').scrollIntoViewIfNeeded()
  await expect(video).toHaveJSProperty('paused',true)
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.locator('.txh-hero').scrollIntoViewIfNeeded()
  await expect(video).toHaveJSProperty('paused',true)
  const element=await video.elementHandle()
  await page.locator('.client-site-footer').getByRole('button',{name:'새 전략 만들기',exact:true}).click()
  await expect(video).toHaveCount(0)
  expect(await element!.evaluate((el:HTMLVideoElement)=>({paused:el.paused,source:el.getAttribute('src')}))).toEqual({paused:true,source:null})
})

for(const width of [320,1440])test(`${width}px enlarged introduction has readable cards and reachable actions`,async({page},info)=>{
  await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#/trade')
  await page.locator('.txh').evaluate(el=>(el as HTMLElement).style.zoom='2')
  const card=page.locator('.txh-card').last()
  expect(await card.locator('dd').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(12)
  await expect(card.getByRole('button')).toHaveCount(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true)
  await card.locator('.txh-stats').scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath('enlarged-card.png')})
  await page.locator('.txh-safe .txh-cta').scrollIntoViewIfNeeded()
  await expect(page.locator('.txh-safe .txh-cta')).toBeInViewport()
})

test('leaving guest signup closes its overlay and history restores the introduction without a plan entry',async({page})=>{
  await page.goto('/')
  await page.locator('#strategy-idea').fill('가입 경로 왕복에도 보존')
  await page.locator('.client-site-footer').getByRole('button',{name:'AI 트레이딩',exact:true}).click()
  await page.locator('.txh-hero .txh-cta').click()
  await expect(page.locator('.ca-auth')).toBeVisible()
  await expect(page.getByTestId('connection-plan')).toHaveCount(0)
  await expect(page).toHaveURL(/#\/trade$/)
  await page.goBack()
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await expect(page.locator('#root')).not.toHaveAttribute('inert')
  await expect(page.locator('#strategy-idea')).toHaveValue('가입 경로 왕복에도 보존')
  await page.goForward()
  await expect(page.locator('.txh')).toBeVisible()
  await expect(page).toHaveURL(/#\/trade$/)
  await expect(page.getByTestId('connection-plan')).toHaveCount(0)
  await expect(page.locator('.ca-auth')).toHaveCount(0)
  await expect(page.locator('.client-account-terminal')).toHaveCount(0)
  await page.goBack()
  await expect(page.locator('#strategy-idea')).toHaveValue('가입 경로 왕복에도 보존')
})

test('enlarged desktop uses actual introduction width for AI and setup reading columns',async({page},info)=>{
  await page.setViewportSize({width:1200,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#/trade')
  await page.locator('.txh').evaluate(el=>(el as HTMLElement).style.zoom='2')
  await expect.poll(()=>page.locator('.txh').evaluate(el=>el.clientWidth)).toBeLessThanOrEqual(600)
  for(const selector of ['.txh-ai-cols','.txh-steps']){
    const grid=page.locator(selector)
    await expect.poll(()=>grid.evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length)).toBe(1)
    expect(await grid.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  }
  // Capture only after lazy assets have entered the viewport and decoded.
  for(const img of await page.locator('.txh-ai-cols img').all()){
    await img.scrollIntoViewIfNeeded()
    await expect.poll(()=>img.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true)
  }
  await page.locator('.txh-ai-col').nth(1).scrollIntoViewIfNeeded()
  await page.screenshot({path:info.outputPath('enlarged-ai-columns.png')})
})
