import { expect, test, type Page } from '@playwright/test'
import { connectedMyExchanges, effectiveMyExchange, matchesMyExchange, myExchangeIds, selectedMyExchanges } from '../src/client-my-exchanges'
import { CLIENT_BROKERS } from '../src/client-broker-fixtures'
import { createClientSharingPreferencesStore } from '../src/client-sharing-preferences'
import { catalogueStrategies } from '../src/client-catalogue'
import copy from '../src/client-my-exchanges-copy.json' with { type: 'json' }
import type { MyExchangeFixture } from './fixtures/my-exchanges-harness'
import { sourceSidebarNavigationLabel } from '../src/client-shell-copy'

const cards = (page: Page) => page.locator('#myex-test-root .strategy-list-card h3')
const pill = (page: Page) => page.locator('.myex-w>button,.myex-w .tfbk-drop')
async function mount(page: Page, fixture: MyExchangeFixture, language = 'ko') {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(language => localStorage.setItem('tethLang', language), language)
  await page.goto('/')
  await page.evaluate(async fixture => {
    const path = '/tests/fixtures/my-exchanges-harness.tsx'
    const { mountMyExchanges } = await import(/* @vite-ignore */ path)
    Reflect.set(window, 'myExchangeHarness', mountMyExchanges(fixture))
  }, fixture)
  await expect(page.locator(fixture.shell ? '#myex-test-root .client-service-app' : '#myex-test-root .client-strategy-sharing')).toBeVisible()
}
async function update(page: Page, fixture: MyExchangeFixture) {
  await page.evaluate(fixture => Reflect.get(window, 'myExchangeHarness').update(fixture), fixture)
}
test('연결 지원이나 로그인만으로 연결을 생성하지 않고 동일 owner의 CONNECTED만 선택한다', () => {
  const presentation = { scope: 'owner', identity: 'dataset', catalog: [
    { broker: CLIENT_BROKERS[0], connectionState: 'NEEDS_LINK' as const },
    { broker: { ...CLIENT_BROKERS[0], id: 'okx' }, connectionState: 'CONNECTED' as const },
    { broker: { ...CLIENT_BROKERS[0], id: 'okx' }, connectionState: 'CONNECTED' as const },
    { broker: { ...CLIENT_BROKERS[0], id: 'unknown' }, connectionState: 'CONNECTED' as const },
  ] }
  expect(connectedMyExchanges(presentation, 'owner', true).map(item => item.id)).toEqual(['okx'])
  for (const [owner, signedIn] of [['other', true], ['owner', false], [null, true]] as const) expect(connectedMyExchanges(presentation, owner, signedIn)).toEqual([])
  expect(connectedMyExchanges(undefined, 'owner', true)).toEqual([])
  const connected = connectedMyExchanges(presentation, 'owner', true)
  expect(effectiveMyExchange('binance', connected)).toBe('all')
  expect(effectiveMyExchange('all', [])).toBe('')
  expect(effectiveMyExchange('', connected)).toBe('')
  expect(selectedMyExchanges('okx', connected)).toEqual(connected)
  expect(matchesMyExchange({ venue: { name: 'OKX' } }, connected)).toBe(true)
  expect(matchesMyExchange({ me: true, venue: { name: 'OKX' } }, connected)).toBe(false)
  expect(matchesMyExchange({}, connected)).toBe(false)
  expect(matchesMyExchange({}, [])).toBe(true)
})
test('선택 저장은 계정별이며 legacy 기본값과 실패 후 복구를 유지한다', () => {
  const values = new Map<string, string>(); let fail = false
  const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { if (fail) throw Error('blocked'); values.set(key, value) }, removeItem: (key: string) => { values.delete(key) } }
  const store = createClientSharingPreferencesStore('owner', storage)
  expect(store.getSnapshot().preferences.myExchange).toBeUndefined()
  for (const myExchange of ['', 'all', ...myExchangeIds] as const) {
    expect(store.update({ myExchange })).toBe(true)
    expect(createClientSharingPreferencesStore('owner', storage).getSnapshot().preferences.myExchange).toBe(myExchange)
  }
  expect(createClientSharingPreferencesStore('other', storage).getSnapshot().preferences.myExchange).toBeUndefined()
  fail = true; expect(store.update({ myExchange: 'binance' })).toBe(false)
  expect(store.getSnapshot().preferences.myExchange).toBe('binance')
  fail = false; expect(store.retrySave()).toBe(true)
  expect(createClientSharingPreferencesStore('owner', storage).getSnapshot().preferences.myExchange).toBe('binance')
  expect(store.clear()).toBe(true)
  expect(store.getSnapshot().preferences.myExchange).toBeUndefined()
})
test('연결 1개 토글은 원본 조건과 교집합이며 전체 보기는 검색을 지우지 않는다', async ({ page }) => {
  await mount(page, { ids: ['binance'] })
  await expect(cards(page)).toHaveCount(5)
  await expect(pill(page)).not.toHaveAttribute('aria-haspopup')
  await pill(page).click()
  await expect(pill(page)).toHaveAttribute('aria-pressed', 'true')
  await expect(cards(page)).toHaveText(['Bitcoin rule'])
  await expect(page.locator('.myex-note')).toHaveText('Binance에서 바로 실행할 수 있는 전략 1개입니다.')
  await page.getByRole('searchbox', { name: '전략 검색' }).fill('Mixed')
  await expect(page.locator('.myex-empty')).toContainText('Binance에서 실행할 수 있는 전략이 아직 없습니다.')
  await page.getByRole('button', { name: '전체 보기', exact: true }).click()
  await expect(cards(page)).toHaveText(['Mixed markets'])
  await expect(page.getByRole('searchbox')).toHaveValue('Mixed')
  await expect(pill(page)).toHaveAttribute('aria-pressed', 'false')
})
test('여러 거래소 선택·서로 배타적인 메뉴·키보드·연결해제·계정교체', async ({ page }) => {
  await mount(page, { ids: ['binance', 'okx', 'bitget'] })
  await pill(page).click()
  await expect(page.getByRole('listbox', { name: '내 거래소' })).toBeVisible()
  await page.getByRole('option', { name: 'OKX만', exact: true }).click()
  await expect(cards(page)).toHaveText(['Stock AI'])
  await pill(page).press('ArrowDown')
  await expect(page.getByRole('option', { name: 'OKX만', exact: true })).toBeFocused()
  await page.keyboard.press('Home')
  await page.keyboard.press('Enter')
  await expect(cards(page)).toHaveText(['Bitcoin rule', 'Stock AI', 'Mixed markets'])
  await pill(page).click()
  await page.keyboard.press('Escape')
  await expect(pill(page)).toBeFocused()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await pill(page).click()
  await page.locator('.strategy-filter-row>.tfbk-dropwrap button').click()
  await expect(page.getByRole('listbox', { name: '내 거래소' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await pill(page).click()
  await page.getByRole('option', { name: 'OKX만', exact: true }).click()
  await update(page, { ids: ['binance', 'bitget'] })
  await expect(cards(page)).toHaveText(['Bitcoin rule', 'Mixed markets'])
  await update(page, { ids: ['binance', 'okx'] })
  await expect(cards(page)).toHaveText(['Stock AI'])
  await update(page, { ids: ['binance'], owner: 'other', scope: 'myex-fixture-owner' })
  await expect(pill(page)).toHaveCount(0)
  await expect(cards(page)).toHaveCount(5)
  await update(page, { ids: ['binance'], owner: 'other' })
  await expect(pill(page)).toHaveAttribute('aria-pressed', 'false')
})
test('미연결·로그아웃은 필터를 숨기고 기존 목록을 보존한다', async ({ page }) => {
  await mount(page, { ids: ['binance'], disconnected: true })
  await expect(pill(page)).toHaveCount(0)
  await update(page, { ids: ['binance'], signedIn: false })
  await expect(pill(page)).toHaveCount(0)
  await expect(cards(page)).toHaveCount(5)
})
test('서비스 shell이 공급한 연결을 소비하고 대화 왕복 뒤 필터와 입력을 유지한다', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await mount(page, { ids: ['binance', 'okx'], shell: true })
  const navigate = async () => {
    const hamburger = page.locator('.client-hamburger')
    if (await hamburger.isVisible()) await hamburger.click()
    await page.locator('.client-sidebar').getByRole('button', { name: sourceSidebarNavigationLabel('ko', 'sharing'), exact: true }).click()
    await expect(page.locator('.native-strategies')).toBeVisible()
  }
  const input = page.locator('.g-composer textarea')
  await expect(input).toHaveValue('작성 중이던 대화')
  await input.evaluate(node => Reflect.set(window, 'originalMyExchangeInput', node))
  await navigate()
  await pill(page).click()
  await page.getByRole('option', { name: 'OKX만', exact: true }).click()
  await expect(cards(page)).toHaveText(['Stock AI'])
  await page.screenshot({ path: info.outputPath('myex-shell-selected.png') })
  expect((await pill(page).boundingBox())!.height).toBeLessThanOrEqual(48)
  const iconBox = await pill(page).locator('img').boundingBox()
  const labelBox = await pill(page).locator('.myex-content>span:last-child').boundingBox()
  expect(Math.abs(iconBox!.y + iconBox!.height / 2 - labelBox!.y - labelBox!.height / 2)).toBeLessThan(2)
  await page.locator('.native-strategies .hub-header button').click()
  await expect(input).toHaveValue('작성 중이던 대화')
  expect(await input.evaluate(node => node === Reflect.get(window, 'originalMyExchangeInput'))).toBe(true)
  await navigate()
  await expect(pill(page)).toContainText('OKX만')
  await expect(cards(page)).toHaveText(['Stock AI'])
  await update(page, { ids: ['binance', 'okx'], shell: true, scope: 'wrong-owner' })
  await expect(pill(page)).toHaveCount(0)
  expect(errors).toEqual([])
})
test('공개 원본31종도 동일 venue 필터를 사용하며 브라우저 선택을 복구한다', async ({ page }) => {
  await mount(page, { ids: ['binance', 'bitget'], preview: true })
  await expect(cards(page)).toHaveCount(10)
  await pill(page).click()
  await page.getByRole('option', { name: 'Binance만', exact: true }).click()
  await expect(cards(page)).toHaveText(catalogueStrategies.filter(row => row.ex === 'binance').map(row => row.name))
  await page.reload()
  await page.evaluate(async () => {
    const path = '/tests/fixtures/my-exchanges-harness.tsx'
    const { mountMyExchanges } = await import(/* @vite-ignore */ path)
    mountMyExchanges({ ids: ['binance', 'bitget'], preview: true })
  })
  await expect(pill(page)).toContainText('Binance만')
  await expect(cards(page)).toHaveText(catalogueStrategies.filter(row => row.ex === 'binance').map(row => row.name))
})
test('시장·판단방식·정렬과 거래소 필터가 함께 적용되고 거래소 해제는 다른 선택을 유지한다', async ({ page }) => {
  await mount(page, { ids: ['binance', 'okx', 'bitget'] })
  await pill(page).click()
  await page.getByRole('option', { name: '연결한 거래소 전체', exact: true }).click()
  await page.getByRole('group', { name: '판단 방식' }).getByRole('button', { name: 'AI 판단', exact: true }).click()
  await page.getByRole('combobox', { name: '정렬 기준' }).selectOption('fw')
  await expect(cards(page)).toHaveText(['Stock AI'])
  await page.locator('.strategy-filter-row>.tfbk-dropwrap button').click()
  await page.getByRole('option', { name: '가상자산', exact: true }).click()
  await expect(page.locator('.myex-empty')).toBeVisible()
  await page.getByRole('button', { name: '전체 보기', exact: true }).click()
  await expect(page.getByRole('group', { name: '판단 방식' }).getByRole('button', { name: 'AI 판단', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('combobox', { name: '정렬 기준' })).toHaveValue('fw')
  await expect(page.locator('.strategy-filter-row>.tfbk-dropwrap button')).toContainText('가상자산')
  await expect(cards(page)).toHaveCount(0)
  await page.getByRole('button', { name: '필터 초기화', exact: true }).click()
  await expect(cards(page)).toHaveCount(5)
  await expect(pill(page)).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('combobox', { name: '정렬 기준' })).toHaveValue('fw')
})
for (const language of Object.keys(copy) as (keyof typeof copy)[]) test(`${language} 320px 글자2배에서 알약·목록·검색 가독성`, async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await mount(page, { ids: ['binance', 'okx', 'bitget', 'bybit', 'mexc', 'woox', 'gate'] }, language)
  await page.addStyleTag({ content: '.myex-w button,.myex-w .tfbk-menu .mi,.myex-note,.myex-empty{font-size:28px!important;line-height:1.5!important}' })
  expect((await pill(page).boundingBox())!.height).toBeLessThan(200)
  await pill(page).click()
  const list = page.getByRole('listbox', { name: copy[language].label })
  await expect(list).toBeVisible()
  await page.keyboard.press('End')
  await expect(list.getByRole('option').last()).toBeFocused()
  await expect(list.getByRole('option').last()).toBeInViewport()
  const bounds = await list.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  await page.screenshot({ path: info.outputPath(`myex-${language}-expanded.png`) })
  await page.keyboard.press('Escape')
  await expect(pill(page)).toBeFocused()
  await expect(page.getByRole('searchbox')).toBeVisible()
  await page.screenshot({ path: info.outputPath(`myex-${language}-closed.png`) })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
