import { expect, test, type Page } from '@playwright/test'
import { createMarketSelectionStore } from '../src/client-market-selection-store'
import { boundTerminalMarketSource, validMarketObservation } from '../src/client-terminal-market-source'
import { fixture as chart } from '../src/dev/chart-workspace-fixture'
import type { InspectionFixture } from './fixtures/market-inspection-harness'

async function mount(page: Page, fixture: InspectionFixture = {}) {
  await page.goto('/')
  await page.evaluate(async fixture => { const path = '/tests/fixtures/market-inspection-harness.tsx'; const { mountMarketInspection } = await import(/* @vite-ignore */ path); Reflect.set(window, 'inspectionHarness', mountMarketInspection(fixture)) }, fixture)
  await expect(page.locator('#inspection-test-root .client-account-terminal')).toBeVisible()
}
const requestCount = (page: Page) => page.evaluate(() => Reflect.get(window, 'inspectionHarness').requests().length)
const resolve = (page: Page, index: number, wrong = false) => page.evaluate(({ index, wrong }) => Reflect.get(window, 'inspectionHarness').resolve(index, wrong), { index, wrong })
const update = (page: Page, fixture: InspectionFixture) => page.evaluate(fixture => Reflect.get(window, 'inspectionHarness').update(fixture), fixture)
async function choose(page: Page, symbol: string) { await page.locator('.cmp-trigger').click(); await page.locator('.cmp-select').filter({ hasText: `${symbol}/USDT` }).click() }
const inspection = (page: Page) => page.locator('[data-market-inspection]')

test('선호는 owner별로 격리하고 미저장 상태를 유지하며 새 lifetime은 전략 추종으로 복원한다', () => {
  const values = new Map<string, string>(); let fail = false
  const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { if (fail) throw Error('blocked'); values.set(key, value) } }
  const store = createMarketSelectionStore('a', 'market', storage)
  store.favorite('BTC', true); store.select('ETH')
  expect(store.getSnapshot()).toMatchObject({ manualId: 'ETH', lastId: 'ETH', favorites: ['BTC'], storageError: false })
  const second = createMarketSelectionStore('a', 'market', storage)
  expect(second.getSnapshot()).toMatchObject({ manualId: null, lastId: 'ETH', favorites: ['BTC'] })
  expect(createMarketSelectionStore('b', 'market', storage).getSnapshot().favorites).toEqual([])
  second.favorite('SOL', true); store.favorite('ETH', true)
  expect(store.getSnapshot().favorites).toEqual(['BTC', 'SOL', 'ETH'])
  fail = true; expect(store.select('SOL')).toBe(false)
  expect(store.getSnapshot()).toMatchObject({ manualId: 'SOL', storageError: true })
  fail = false; expect(store.retry()).toBe(true)
  store.follow(); expect(store.getSnapshot()).toMatchObject({ manualId: null, lastId: 'SOL' })
})
test('저장 재시도는 다른 탭의 변경을 보존하며 미저장 즐겨찾기만 합친다', () => {
  const values = new Map<string, string>(); let fail = false
  const storage = { getItem: (key: string) => values.get(key) ?? null, setItem: (key: string, value: string) => { if (fail) throw Error('blocked'); values.set(key, value) } }
  const first = createMarketSelectionStore('a', 'market', storage)
  first.favorite('BTC', true); first.select('BTC')
  const second = createMarketSelectionStore('a', 'market', storage)
  fail = true; first.favorite('BTC', false); first.favorite('ETH', true)
  fail = false; second.favorite('SOL', true); second.select('SOL')
  expect(first.retry()).toBe(true)
  expect(first.getSnapshot()).toMatchObject({ favorites: ['SOL', 'ETH'], lastId: 'SOL', manualId: 'BTC', storageError: false })
  expect(createMarketSelectionStore('a', 'market', storage).getSnapshot()).toMatchObject({ favorites: ['SOL', 'ETH'], lastId: 'SOL' })
})
test('독립 조회는 owner·source·종목·차트 심볼을 결속하며 다른 전략 체결을 가져오지 않는다', () => {
  const preferences = createMarketSelectionStore('a', 'market', { getItem: () => null, setItem: () => {} })
  const source = { scope: 'a', identity: 'market', preferences, catalog: { state: 'unavailable' as const }, load: async () => { throw Error('unused') } }
  expect(boundTerminalMarketSource(source, 'b')).toBeUndefined()
  expect(boundTerminalMarketSource({ ...source, identity: 'other' }, 'a')).toBeUndefined()
  const instrument = { id: 'BTC', symbol: 'BTC/USDT', exchangeId: 'fixture', market: 'TEST', categories: [], price: null, change: null, volume: null }
  const value = { scope: 'a', identity: 'market', instrumentId: 'BTC', chart: { ...chart, market: 'BTC/USDT', fills: [] } }
  expect(validMarketObservation(value, source, instrument)).toBe(true)
  for (const value2 of [{ ...value, instrumentId: 'ETH' }, { ...value, scope: 'b' }, { ...value, chart }, { ...value, chart: { ...value.chart, fills: chart.fills } }]) expect(validMarketObservation(value2, source, instrument)).toBe(false)
})
test('종목 조회는 실제 전문차트만 바꾸고 전략·초안·원장·원래 canvas를 보존한다', async ({ page }, info) => {
  await mount(page)
  await expect.poll(() => requestCount(page)).toBe(1)
  const original = await page.locator('[data-strategy-price-chart] canvas').first().elementHandle()
  await resolve(page, 0)
  await expect(inspection(page).locator('canvas').first()).toBeVisible()
  await choose(page, 'ETH')
  await expect.poll(() => requestCount(page)).toBe(2)
  await expect(inspection(page).locator('canvas')).toHaveCount(0)
  await resolve(page, 1)
  await expect(inspection(page)).toContainText('TEST ONLY ETH #1')
  await expect(page.locator('.client-account-terminal')).toHaveAttribute('data-selected-strategy', 'strategy-BTC')
  await expect(page.getByTestId('ledger')).toHaveText('strategy-BTC:current')
  await expect(page.getByRole('textbox', { name: 'BTC draft' })).toHaveValue('draft-BTC')
  expect(await page.locator('[data-strategy-price-chart] canvas').first().evaluate((node, old) => node === old, original)).toBe(true)
  await page.screenshot({ path: info.outputPath('market-inspection.png'), fullPage: true })
  await page.evaluate(() => Reflect.get(window, 'inspectionHarness').selectStrategy('BTC'))
  await expect.poll(() => requestCount(page)).toBe(3)
  await expect(page.locator('.ctm-symbol b')).toHaveText('BTC/USDT')
  await resolve(page, 2)
  await expect(inspection(page)).toContainText('TEST ONLY BTC #2')
})
test('응답 역전·A→B→A·계정교체·조회불가에서 이전 응답이 차트를 덮지 못한다', async ({ page }) => {
  await mount(page); await expect.poll(() => requestCount(page)).toBe(1)
  await choose(page, 'ETH'); await expect.poll(() => requestCount(page)).toBe(2)
  await choose(page, 'BTC'); await expect.poll(() => requestCount(page)).toBe(3)
  await resolve(page, 0); await resolve(page, 1)
  await expect(inspection(page).locator('canvas')).toHaveCount(0)
  await resolve(page, 2); await expect(inspection(page)).toContainText('TEST ONLY BTC #2')
  await choose(page, 'SOL'); await expect.poll(() => requestCount(page)).toBe(4)
  await update(page, { owner: 'other' }); await expect.poll(() => requestCount(page)).toBe(5)
  await resolve(page, 3); await expect(inspection(page).locator('canvas')).toHaveCount(0)
  await resolve(page, 4); await expect(inspection(page)).toContainText('TEST ONLY BTC #4')
  await update(page, { owner: 'other', missing: true })
  await expect(inspection(page)).toHaveCount(0)
  await expect(page.locator('.cmp-trigger')).toHaveCount(0)
  const requests = await page.evaluate(() => Reflect.get(window, 'inspectionHarness').requests())
  expect(requests.slice(0, 4).every((request: { aborted: boolean }) => request.aborted)).toBe(true)
})
test('틀린 binding과 실패는 재시도하고 locale·일반 렌더·같은 데이터에서는 재요청하지 않는다', async ({ page }) => {
  await mount(page); await expect.poll(() => requestCount(page)).toBe(1)
  await resolve(page, 0, true)
  await expect(inspection(page)).toContainText('자료를 불러오지 못했습니다.')
  await inspection(page).getByRole('button', { name: '다시 시도' }).click()
  await expect.poll(() => requestCount(page)).toBe(2)
  await resolve(page, 1); await expect(inspection(page).locator('canvas').first()).toBeVisible()
  const canvas = await inspection(page).locator('canvas').first().elementHandle()
  await update(page, {})
  for (const language of ['en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr', 'ko']) await page.evaluate(async language => { const p = '/src/client-preferences.ts'; const { setClientPreference } = await import(/* @vite-ignore */ p); setClientPreference('language', language) }, language)
  expect(await requestCount(page)).toBe(2)
  expect(await inspection(page).locator('canvas').first().evaluate((node, old) => node === old, canvas)).toBe(true)
  await update(page, { wrongScope: true })
  await expect(inspection(page)).toHaveCount(0)
  await expect(page.locator('.cmp-trigger')).toHaveCount(0)
})
test('전략 없는 계정은 최근 종목으로 복귀하며 수동 선택은 같은 store의 화면 왕복에 남는다', async ({ page }) => {
  await mount(page, { empty: true }); expect(await requestCount(page)).toBe(0)
  await choose(page, 'SOL'); await expect.poll(() => requestCount(page)).toBe(1)
  await resolve(page, 0); await expect(inspection(page)).toContainText('TEST ONLY SOL #0')
  await update(page, { empty: true, missing: true }); await expect(inspection(page)).toHaveCount(0)
  await update(page, { empty: true }); await expect.poll(() => requestCount(page)).toBe(2)
  await resolve(page, 1); await expect(page.locator('.ctm-symbol b')).toHaveText('SOL/USDT')
})
test('시장 표시명 번역만 바뀌면 요청과 기존 차트는 유지한다', async ({ page }) => {
  await mount(page); await expect.poll(() => requestCount(page)).toBe(1)
  await resolve(page, 0); await expect(inspection(page).locator('canvas').first()).toBeVisible()
  const canvas = await inspection(page).locator('canvas').first().elementHandle()
  await update(page, { marketLabel: '번역된 시장 이름' })
  await expect(page.locator('.ctm-symbol')).toContainText('번역된 시장 이름')
  expect(await requestCount(page)).toBe(1)
  expect(await inspection(page).locator('canvas').first().evaluate((node, old) => node === old, canvas)).toBe(true)
})
test('native 실제 소비 경로에서 번역 표시명과 무관하게 명시 종목을 따르고 수동 조회를 연결한다', async ({ page }, info) => {
  await mount(page, { native: true, translated: true }); await expect.poll(() => requestCount(page)).toBe(1)
  await resolve(page, 0); await expect(inspection(page).locator('canvas').first()).toBeVisible()
  await choose(page, 'SOL'); await expect.poll(() => requestCount(page)).toBe(2)
  await resolve(page, 1); await expect(inspection(page)).toContainText('TEST ONLY SOL #1')
  await expect(page.locator('.client-account-terminal')).toHaveAttribute('data-selected-strategy', 'strategy-BTC')
  await expect(page.locator('.cat-context')).toContainText('언어에 따른 표시 이름')
  await page.screenshot({ path: info.outputPath('native-market.png'), fullPage: true })
})
for (const width of [320, 844, 1440]) test(`${width}px 세로 배치에서 질문 입력이 판단 기록을 가리지 않는다`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 760 })
  await mount(page, { native: true }); await expect.poll(() => requestCount(page)).toBe(1)
  await resolve(page, 0); await expect(inspection(page).locator('canvas').first()).toBeVisible()
  const feed = page.locator('.teth-agent-feed'), composer = page.locator('.cst-composer')
  for (const scrolled of [false, true]) {
    if (scrolled) await composer.scrollIntoViewIfNeeded()
    const feedBox = await feed.boundingBox(), composerBox = await composer.boundingBox()
    expect(feedBox).not.toBeNull(); expect(composerBox).not.toBeNull()
    expect(composerBox!.y).toBeGreaterThanOrEqual(feedBox!.y + feedBox!.height - 1)
  }
  await page.screenshot({ path: info.outputPath('composer-flow.png'), fullPage: true })
})
test('브라우저 저장 실패를 알리고 재시도해도 차트 선택과 초안을 보존한다', async ({ page }) => {
  await mount(page); await expect.poll(() => requestCount(page)).toBe(1)
  await resolve(page, 0)
  await page.evaluate(() => { Reflect.set(window, 'originalStorageSet', Storage.prototype.setItem); Storage.prototype.setItem = () => { throw Error('TEST BLOCKED') } })
  await choose(page, 'ETH'); await expect.poll(() => requestCount(page)).toBe(2)
  await resolve(page, 1)
  const alert = page.locator('.ctm-state[role="alert"]')
  await expect(alert).toBeVisible()
  await alert.getByRole('button', { name: '다시 시도' }).click()
  await expect(alert).toBeVisible()
  await page.evaluate(() => { Storage.prototype.setItem = Reflect.get(window, 'originalStorageSet') })
  await alert.getByRole('button', { name: '다시 시도' }).click()
  await expect(alert).toHaveCount(0)
  expect(await requestCount(page)).toBe(2)
  await expect(page.locator('.ctm-symbol b')).toHaveText('ETH/USDT')
  await expect(page.getByRole('textbox', { name: 'BTC draft' })).toHaveValue('draft-BTC')
})
