import { expect, test, type Page } from '@playwright/test'
import { filterMarketPickerRows, marketCategories, marketPickerIcon, marketPickerText, validMarketPickerRows, type MarketPickerRow } from '../src/client-market-picker'
import type { PickerFixture } from './fixtures/market-picker-harness'

const rows: MarketPickerRow[] = [
  { id: 'nvidia', symbol: 'NVDAUSDT', name: '엔비디아', searchAliases: ['NVIDIA'], categories: ['us', 'ai'], price: 5, change: -3, volume: 100 },
  { id: 'btc', symbol: 'BTCUSDT', categories: ['l1'], price: 10, change: 2, volume: 1000 },
  { id: 'unknown', symbol: 'NULLUSDT', categories: [], price: null, change: null, volume: null },
]
async function mount(page: Page, fixture: PickerFixture = {}, language = 'ko') {
  await page.addInitScript(language => localStorage.setItem('tethLang', language), language)
  await page.goto('/')
  await page.evaluate(async fixture => { const path = '/tests/fixtures/market-picker-harness.tsx'; const { mountMarketPicker } = await import(/* @vite-ignore */ path); Reflect.set(window, 'pickerHarness', mountMarketPicker(fixture)) }, fixture)
  await expect(page.locator('#picker-test-root .ctm-header')).toBeVisible()
}
async function update(page: Page, fixture: PickerFixture) { await page.evaluate(fixture => Reflect.get(window, 'pickerHarness').update(fixture), fixture) }
const selections = (page: Page) => page.locator('.cmp-select')
const open = (page: Page) => page.locator('.cmp-trigger').click()

test('목록과 시장 헤더가 같은 로컬 종목 아이콘을 사용하고 실패·오래된 선택은 첫 글자로 대체한다', async ({ page }) => {
  await mount(page)
  const icon = page.locator('.ctm-symbol-icon')
  await expect(icon.locator('img')).toHaveAttribute('src', '/client-template-assets/btc.svg')
  await open(page)
  await page.getByRole('searchbox').fill('엔비디아')
  await selections(page).click()
  await expect(icon).toHaveText('N')
  await expect(icon.locator('img')).toHaveCount(0)
  await page.route('**/client-market-assets/NVDA.png', route => route.fulfill({ status: 404 }))
  await update(page, { selectedIcon: '/client-market-assets/NVDA.png' })
  await expect(icon.locator('img')).toBeHidden()
  await expect(icon).toHaveText('N')
  await update(page, { selectedIcon: '/client-template-assets/eth.svg' })
  await expect(icon.locator('img')).toBeVisible()
  await expect(icon.locator('img')).toHaveAttribute('src', '/client-template-assets/eth.svg')
  for (const fixture of [
    { selectedIcon: 'https://example.com/tracking.svg' },
    { selectedIcon: '/client-template-assets/eth.svg', selectedId: 'btc' },
    { selectedIcon: '/client-template-assets/eth.svg', duplicate: true },
  ]) {
    await update(page, fixture)
    await expect(icon.locator('img')).toHaveCount(0)
    await expect(icon).toHaveText('N')
  }
})

test('원본 11분류와 별칭 검색·교집합·숫자 정렬·결측 마지막 순서를 보존한다', () => {
  expect(marketCategories).toHaveLength(11)
  expect(validMarketPickerRows(rows)).toBe(true)
  expect(validMarketPickerRows([...rows, rows[0]])).toBe(false)
  expect(validMarketPickerRows([{ ...rows[0], price: NaN }])).toBe(false)
  for (const q of ['엔비디아', 'nvidia', 'ＮＶＤＡ', ' nvda ']) expect(filterMarketPickerRows(rows, q, 'us', ['nvidia'], true, 'volume', true).map(row => row.id)).toEqual(['nvidia'])
  expect(filterMarketPickerRows(rows, 'nvda', 'kr', [], false, 'volume', true)).toEqual([])
  expect(filterMarketPickerRows(rows, '', 'all', [], false, 'price', true).map(row => row.id)).toEqual(['btc', 'nvidia', 'unknown'])
  expect(filterMarketPickerRows(rows, '', 'all', [], false, 'price', false).map(row => row.id)).toEqual(['nvidia', 'btc', 'unknown'])
  expect(rows[0].id).toBe('nvidia')
  expect(marketPickerIcon('/client-template-assets/btc.svg')).toBe('/client-template-assets/btc.svg')
  expect(marketPickerIcon('/client-market-assets/币安人生.png')).toBe('/client-market-assets/币安人生.png')
  for (const path of ['https://example.com/a.svg', '//example.com/a.svg', '/client-market-assets/../secret.svg', '/client-market-assets/%2e%2e/secret.svg', '/client-market-assets/a.svg?url=remote', 'javascript:alert(1)']) expect(marketPickerIcon(path)).toBeUndefined()
})
test('실제 헤더에서 검색·분류·정렬·별 선택과 종목 선택을 구별하고 초점을 복원한다', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await mount(page); await open(page)
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(selections(page)).toHaveCount(4)
  await page.getByRole('searchbox').fill('엔비디아')
  await expect(selections(page)).toHaveCount(1)
  await page.getByRole('button', { name: 'NVDAUSDT 즐겨찾기', exact: true }).click()
  await expect(page.getByTestId('count')).toHaveText('0')
  await page.getByRole('button', { name: '즐겨찾기', exact: true }).click()
  await expect(selections(page)).toHaveCount(1)
  await page.getByRole('searchbox').fill('')
  await expect(selections(page)).toHaveCount(3)
  await page.getByRole('button', { name: 'AI', exact: true }).click()
  await expect(selections(page)).toHaveCount(1)
  await page.getByRole('button', { name: '전체', exact: true }).click()
  await page.locator('.cmp-columns .cmp-price').click()
  await expect(selections(page).first()).toContainText('BTCUSDT')
  await page.locator('.cmp-columns .cmp-price').click()
  await expect(selections(page).first()).toContainText('NVDAUSDT')
  await page.screenshot({ path: info.outputPath('picker.png') })
  await selections(page).first().click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByTestId('selection')).toHaveText('nvda')
  await expect(page.getByTestId('count')).toHaveText('1')
  await expect(page.locator('.cmp-trigger')).toBeFocused()
  await expect(page.locator('.ctm-price>b')).toHaveText('—')
  expect(errors).toEqual([])
})
test('원본처럼 검색어가 있는 입력의 첫 Escape는 선택 없이 닫고 종목 버튼 초점을 복원한다', async ({ page }) => {
  await mount(page); await open(page)
  const search = page.getByRole('searchbox')
  await search.fill('엔비디아')
  await expect(search).toBeFocused()
  await expect(search).toHaveValue('엔비디아')
  await expect(selections(page)).toHaveCount(1)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.cmp-trigger')).toBeFocused()
  await expect(page.getByTestId('count')).toHaveText('0')
  await expect(page.getByTestId('selection')).toHaveText('btc')
})
test('고정높이·키보드 초점 순환·Escape·IME·동일 owner 갱신과 owner 교체', async ({ page }) => {
  await mount(page); await open(page)
  const before = await page.getByRole('dialog').boundingBox()
  await page.getByRole('searchbox').fill('not found')
  await expect(page.locator('.cmp-state')).toHaveText('찾는 종목이 없습니다.')
  expect((await page.getByRole('dialog').boundingBox())?.height).toBe(before?.height)
  await page.getByRole('searchbox').dispatchEvent('keydown', { key: 'Escape', isComposing: true, keyCode: 229 })
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '닫기', exact: true }).focus()
  await page.keyboard.press('Shift+Tab')
  await expect(page.locator('.cmp-columns button:visible').last()).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: '닫기', exact: true })).toBeFocused()
  await update(page, { state: 'loading' })
  await expect(page.getByRole('searchbox')).toHaveValue('not found')
  await expect(page.locator('.cmp-state')).toHaveText('불러오는 중')
  await page.keyboard.press('Escape')
  await expect(page.locator('.cmp-trigger')).toBeFocused()
  await open(page); await update(page, { identity: 'owner-b' })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await open(page); await expect(page.getByRole('searchbox')).toHaveValue('')
})
for (const state of ['loading', 'error', 'unavailable', 'duplicate'] as const) test(`${state} 자료에서 가격·선택을 합성하지 않는다`, async ({ page }) => {
  await mount(page, state === 'duplicate' ? { duplicate: true } : { state }); await open(page)
  await expect(selections(page)).toHaveCount(0)
  await expect(page.locator('.cmp-state')).toHaveText(marketPickerText('ko', state === 'duplicate' ? 'error' : state))
  await expect(page.getByTestId('count')).toHaveText('0')
  await update(page, {})
  await expect(selections(page)).toHaveCount(4)
})
test('미공급 선택기는 클릭 유도를 만들지 않으며 기존 헤더를 보존한다', async ({ page }) => {
  await mount(page, { missing: true })
  await expect(page.locator('.cmp-trigger')).toHaveCount(0)
  await expect(page.locator('.ctm-symbol')).toContainText('BTCUSDT')
})
test('선택 종목·정렬 방향 낭독과 목록·분류 방향키를 지원한다', async ({ page }) => {
  await mount(page)
  await expect(page.locator('.cmp-trigger')).toHaveAccessibleName('종목 선택: BTCUSDT')
  await open(page)
  await page.locator('.cmp-columns .cmp-price').click()
  await expect(page.locator('.cmp-columns .cmp-price')).toHaveAccessibleName('최근가: 내림차순')
  await page.locator('.cmp-columns .cmp-price').click()
  await expect(page.locator('.cmp-columns .cmp-price')).toHaveAccessibleName('최근가: 오름차순')
  await selections(page).first().focus()
  await page.keyboard.press('End'); await expect(selections(page).last()).toBeFocused()
  await page.keyboard.press('ArrowUp'); await expect(selections(page).nth(2)).toBeFocused()
  await page.keyboard.press('Home'); await expect(selections(page).first()).toBeFocused()
  await page.locator('.cmp-star').first().focus()
  await page.keyboard.press('ArrowDown'); await expect(page.locator('.cmp-star').nth(1)).toBeFocused()
  await page.locator('.cmp-categories button').first().focus()
  await page.keyboard.press('ArrowLeft'); await expect(page.locator('.cmp-categories button').last()).toBeFocused()
  await page.keyboard.press('Home'); await expect(page.locator('.cmp-categories button').first()).toBeFocused()
  await expect(page.getByTestId('count')).toHaveText('0')
  for (const node of await page.locator('.cmp-number').all()) await expect(node).toHaveCSS('white-space', 'nowrap')
})
test('배경 클릭은 닫고 내부에서 바깥으로 드래그하면 닫지 않으며 scroll lock을 복원한다', async ({ page }) => {
  await mount(page); await page.evaluate(() => document.body.style.overflow = 'clip')
  await open(page)
  const bounds = (await page.getByRole('dialog').boundingBox())!
  await page.mouse.move(bounds.x + 10, bounds.y + 10); await page.mouse.down(); await page.mouse.move(2, 2); await page.mouse.up()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.mouse.click(2, 2)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('clip')
  await expect(page.locator('.cmp-trigger')).toBeFocused()
})
test('즐겨찾기 해제로 행이 사라질 때 다음 별 또는 필터에 초점을 유지한다', async ({ page }) => {
  await mount(page); await open(page)
  const favorites = page.getByRole('button', { name: '즐겨찾기', exact: true })
  await favorites.click()
  await page.getByRole('button', { name: 'BTCUSDT 즐겨찾기', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.cmp-star')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'ETHUSDT 즐겨찾기', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('.cmp-star')).toHaveCount(0)
  await expect(favorites).toBeFocused()
  await expect(page.locator('.cmp-state')).toHaveText('즐겨찾기한 종목이 없습니다. 별을 눌러 추가합니다.')
  await expect(page.getByTestId('count')).toHaveText('0')
})
test('전체740개를 잘라내지 않고 검색하며 백그라운드 polling과 외부 아이콘 요청이 없다', async ({ page }) => {
  await mount(page, { many: true })
  const network: string[] = []; page.on('request', request => { if (!request.url().includes('127.0.0.1')) network.push(request.url()) })
  await open(page)
  await expect(selections(page)).toHaveCount(740)
  await page.getByRole('searchbox').fill('SYMBOL0739')
  await expect(selections(page)).toHaveCount(1)
  await selections(page).click()
  await expect(page.getByTestId('selection')).toHaveText('row-739')
  expect(network).toEqual([])
})
for (const language of ['ko', 'en', 'ja', 'zh-CN', 'zh-TW', 'es', 'fr']) test(`${language} 320px·200% 글자·짧은 화면에서 조작과 문구가 남는다`, async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 760 }); await mount(page, {}, language); await open(page)
  await expect(page.getByRole('dialog')).toHaveAccessibleName(marketPickerText(language, 'title'))
  await page.evaluate(() => {
    document.querySelectorAll<HTMLElement>('.cmp-dialog h2,.cmp-dialog p,.cmp-dialog button,.cmp-dialog input,.cmp-dialog small').forEach(node => node.style.setProperty('font-size', `${parseFloat(getComputedStyle(node).fontSize) * 2}px`, 'important'))
  })
  expect(await page.getByRole('dialog').evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  for (const button of await page.locator('.cmp-segment:not(.cmp-categories)>button').all()) {
    expect(await button.evaluate(node => node.getBoundingClientRect().height <= parseFloat(getComputedStyle(node).fontSize) * 1.5 + 20)).toBe(true)
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath(`${language}-320-expanded.png`) })
  await page.getByRole('button', { name: marketPickerText(language, 'favorites'), exact: true }).click()
  await expect(selections(page)).toHaveCount(2)
  await page.setViewportSize({ width: 640, height: 320 })
  await selections(page).last().click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.cmp-trigger')).toBeFocused()
})
