import { expect, test, type Page } from '@playwright/test'
import { delegationRecommendedParameters, evaluateDelegation } from '../src/client-delegation-engine'
import { restoreLegacyDelegationEntry } from './fixtures/legacy-source-entry'
test.describe('저장된 위임 consumer 복원: 현재 fresh source 동선과 별도', () => {
const recommended = evaluateDelegation(delegationRecommendedParameters(), 5000000).result

async function openDelegation(page: Page) {
  // Saved five-question compatibility consumer, not a fresh-source entry.
  // Current fresh offline/source proposal paths have their own integration tests.
  await restoreLegacyDelegationEntry(page)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '어떤 자산으로 할까요?' })).toBeVisible()
}

async function report(page: Page) {
  await openDelegation(page)
  for (const name of ['비트코인', '중립적으로', '500만원', '최근 2년', '-5%까지']) await page.getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('heading', { name: '전략 계약서' })).toBeVisible()
  await page.getByRole('button', { name: '전략 검증 시작', exact: true }).click()
  await expect(page.getByRole('heading', { name: '검증 진행' })).toBeVisible()
  await page.getByRole('button', { name: '추천 설정으로 다시 검증', exact: true }).click()
  await page.getByRole('button', { name: '리포트 보기', exact: true }).click()
}

async function expectNoSensitiveStorage(page: Page) {
  const values = await page.evaluate(() => Object.values({ ...localStorage, ...sessionStorage }).join('\n'))
  expect(values).not.toMatch(/SAFE_FAKE|BAD_FAKE|42424242|1212345678|1234567890|테스트카드/)
  const records = await page.evaluate(() => Object.entries(sessionStorage).filter(([key]) => key.startsWith('teth:client-delegation:')).map(([, value]) => JSON.parse(value)))
  for (const record of records) expect(Object.keys(record).sort()).toEqual(['answers', 'attempt', 'chartInterval', 'expert', 'page', 'parameters', 'questionIndex', 'workStartedAt', 'workStep'])
}

for (const width of [320, 1440]) test(`${width}px 체결 가정은 종가 판정과 규칙가 체결을 구분하고 원본 동선을 보존한다`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 900 })
  await openDelegation(page)
  for (const name of ['비트코인', '중립적으로', '500만원', '최근 2년', '-5%까지']) await page.getByRole('button', { name, exact: true }).click()
  const assumption = page.locator('.tf-assumptions').filter({ hasText: '데이터: 원본 공통 합성 일봉 시뮬레이션' })
  await expect(assumption).toContainText('모든 판정은 봉 종가 기준이에요')
  await expect(assumption).toContainText('진입과 기간 청산은 그 봉 종가로')
  await expect(assumption).toContainText('손절·익절은 진입가 대비 설정 비율(규칙가)에 체결됐다고 가정해요')
  await expect(assumption).toContainText('일중 변동·갭·슬리피지는 반영하지 않아요')
  await expect(assumption).toContainText('완료 거래당 수수료 0.2% 반영')
  await expect(assumption).not.toContainText('지정가')
  expect(await assumption.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await assumption.screenshot({ path: testInfo.outputPath(`fill-assumptions-intake-${width}.png`) })
  const verifyButton = page.getByRole('button', { name: '전략 검증 시작', exact: true })
  const paragraphBox = await assumption.boundingBox(), buttonBox = await verifyButton.boundingBox()
  expect(paragraphBox).not.toBeNull()
  expect(buttonBox).not.toBeNull()
  expect(buttonBox!.y).toBeGreaterThanOrEqual(paragraphBox!.y + paragraphBox!.height)
  await page.screenshot({ path: testInfo.outputPath(`fill-page-intake-${width}.png`), fullPage: true })
  await verifyButton.click()
  await expect(page.getByRole('heading', { name: '검증 진행' })).toBeVisible()
  await expect(assumption).toContainText('판정·진입·기간 청산은 봉 종가, 손절·익절은 규칙가 가정')
  await expect(assumption).toContainText('일중·갭·슬리피지 미반영')
  await expect(assumption).toContainText('완료 거래당 0.2% 반영')
  await expect(assumption).not.toContainText('지정가')
  expect(await assumption.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await assumption.screenshot({ path: testInfo.outputPath(`fill-assumptions-workspace-${width}.png`) })
  await page.screenshot({ path: testInfo.outputPath(`fill-page-workspace-${width}.png`), fullPage: true })
  await page.getByRole('button', { name: '추천 설정으로 다시 검증', exact: true }).click()
  await expect(page.getByRole('button', { name: '리포트 보기', exact: true })).toBeEnabled()
})

test('보존된 전략 위임은 원본 5문항과 계약서, 개선 결과, 리포트로 이어진다', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await report(page)
  await expect(page.locator('.tf-scorebox')).toHaveCount(0)
  await expect(page.locator('.client-delegation')).toContainText('완료 거래의 손익은 거래당 수수료 0.2%를 반영한 값이며')
  await expect(page.locator('.client-delegation')).not.toContainText('모든 수치는 거래당 수수료')
  await expect(page.locator('.tf-ez').first()).toContainText(`100번 중 ${Math.round(recommended.winRate)}번`)
  await page.getByRole('button', { name: '전문가 보기', exact: true }).click()
  await expect(page.locator('.tf-ez').first()).toContainText(`Profit Factor ${recommended.pf.toFixed(2)}`)
  await page.reload()
  await expect(page.getByRole('button', { name: '쉬운 말 보기', exact: true })).toBeVisible()
  await expect(page.locator('.tf-ez').first()).toContainText(`Profit Factor ${recommended.pf.toFixed(2)}`)
  await page.locator('.client-delegation .bk').click()
  const daily = Number(await page.locator('.tf-source-price').getAttribute('data-points'))
  await page.getByRole('button', { name: '1W', exact: true }).click()
  expect(Number(await page.locator('.tf-source-price').getAttribute('data-points'))).toBeLessThan(daily)
  await page.getByRole('button', { name: '1M', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '1M', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.client-delegation')).toHaveAttribute('data-source', 'client-ui-fixture')
  expect(errors).toEqual([])
})

test('질문 선택은 세션별 복원되고 다시 답하기는 계약서 전체를 초기화한다', async ({ page }) => {
  await openDelegation(page)
  await page.getByRole('button', { name: '이더리움', exact: true }).click()
  await page.getByRole('button', { name: '안전하게', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: '어느 정도 예산으로 시작할까요?' })).toBeVisible()
  await expect(page.locator('.tf-intake-done')).toHaveCount(2)
  await expect(page.locator('.tf-intake-done').first()).toContainText('이더리움')
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: '잘 모르겠어요, AI가 추천해주세요' }).click()
  await page.getByRole('button', { name: '다시 답하기', exact: true }).click()
  await expect(page.locator('.tf-intake-done')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '어떤 자산으로 할까요?' })).toBeVisible()
})

test('무료 연결은 UID 오류와 가이드, API 오류 재시도를 지원하고 민감값은 저장하지 않는다', async ({ page }) => {
  await report(page)
  await page.getByRole('button', { name: '이 전략 실행하기' }).click()
  await page.getByRole('button', { name: '무료로 시작' }).click()
  await page.getByRole('button', { name: '추천 Binance', exact: true }).click()
  await page.getByRole('button', { name: '가입 완료했어요' }).click()
  await page.getByRole('button', { name: '연동 확인하기' }).click()
  await expect(page.getByLabel('Binance UID')).toBeFocused()
  await page.getByLabel('Binance UID').fill('000000')
  await page.getByRole('button', { name: '연동 확인하기' }).click()
  await expect(page.getByRole('alert')).toContainText('가입 내역을 찾지 못했어요')
  await page.getByLabel('Binance UID').fill('1212345678')
  await page.getByRole('button', { name: 'UID가 어디 있어요?' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('.tf-guide .g')).toHaveCount(3)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'UID가 어디 있어요?' })).toBeFocused()
  await expect(page.getByLabel('Binance UID')).toHaveValue('1212345678')
  await page.getByRole('button', { name: '연동 확인하기' }).click()
  await page.getByLabel('API Key', { exact: true }).fill('BAD_FAKE_KEY')
  await page.getByLabel('Secret Key', { exact: true }).fill('SAFE_FAKE_SECRET')
  await page.getByRole('button', { name: '권한 확인하고 연결하기' }).click()
  await expect(page.getByRole('alert')).toContainText('API Key 권한 확인에 실패')
  await expect(page.getByRole('alert')).toBeFocused()
  await page.getByLabel('API Key', { exact: true }).fill('SAFE_FAKE_KEY')
  await page.getByRole('button', { name: '권한 확인하고 연결하기' }).click()
  await page.getByRole('button', { name: '전략 시작', exact: true }).click()
  await expect(page.locator('.ca-auth')).toBeVisible()
  await page.locator('.au-btns button').first().click()
  await expect(page).toHaveURL(/#\/trade\/bot\/\d+$/)
  await page.getByRole('button', { name: '실행 일시정지', exact: true }).click()
  await expect(page.locator('.nfxb-st')).toHaveText('중지됨')
  await expectNoSensitiveStorage(page)
})

test('유료 결제는 검증·거절·재시도를 지원하고 새로고침 시 민감 입력 단계로 복귀하지 않는다', async ({ page }) => {
  await report(page)
  await page.getByRole('button', { name: '이 전략 실행하기' }).click()
  await page.getByRole('button', { name: '기존 계정 연결' }).click()
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await expect(page.getByLabel('카드 번호', { exact: true })).toBeFocused()
  await page.getByLabel('카드 번호', { exact: true }).fill('0000000000000000')
  await page.getByLabel('유효기간').fill('12/29')
  await page.getByLabel('CVC').fill('123')
  await page.getByLabel('카드 소유자 이름').fill('테스트카드')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('button', { name: '₩5,000,000 결제하기' }).click()
  await expect(page.getByRole('alert')).toContainText('카드사 승인이 거절')
  await page.getByLabel('카드 번호', { exact: true }).fill('4242424242424242')
  await page.getByRole('button', { name: '계속', exact: true }).click()
  await page.getByRole('button', { name: '₩5,000,000 결제하기' }).click()
  await page.getByRole('button', { name: 'OKX', exact: true }).click()
  await page.getByLabel('API Key', { exact: true }).fill('SAFE_FAKE_KEY')
  await page.getByLabel('Secret Key', { exact: true }).fill('SAFE_FAKE_SECRET')
  await expectNoSensitiveStorage(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: '어떻게 실행할까요?' })).toBeVisible()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveCount(0)
  await expectNoSensitiveStorage(page)
})

test('위임 리포트의 모바일 축과 단계, 드로어가 화면 폭을 넘지 않는다', async ({ page }) => {
  await report(page)
  // The preserved report now presents the source upgrade prompt after 700ms.
  // Dismiss it through its actual control before exercising the report layout.
  await page.getByRole('dialog').getByRole('button', { name: '나중에 하기', exact: true }).click()
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect.poll(() => page.locator('.tf-chart svg').evaluate(el => Math.abs(el.viewBox.baseVal.width - el.getBoundingClientRect().width))).toBeLessThan(2)
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
    await expect(page.getByRole('button', { name: '이 전략 실행하기' })).toBeVisible()
  }
  await page.setViewportSize({ width: 320, height: 740 })
  await page.getByRole('button', { name: '이 전략 실행하기' }).click()
  await page.getByRole('button', { name: '무료로 시작' }).click()
  await page.getByRole('button', { name: '추천 Binance', exact: true }).click()
  await page.getByRole('button', { name: '가입 완료했어요' }).click()
  await page.getByRole('button', { name: 'UID가 어디 있어요?' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
})
})
