import { newPage, closePage, goto, evala, viewport, shot, sleep } from './cdp.mjs';
import fs from 'fs';
const OUT='C:/Users/hyun1/OneDrive/바탕 화면/tesia-lab fork 1/qa/gpt-skin/mkt/r/'; fs.mkdirSync(OUT,{recursive:true});
const p=await newPage();
const errs=async()=>JSON.parse(await evala(p,`JSON.stringify(window.__errs||[])`));
for(const [W,M] of [[1440,false],[390,true]]){ const sx=M?'-m':'';
  await viewport(p,W,900,{mobile:M}); await goto(p,'http://127.0.0.1:8765/index.html?v='+Date.now(),1200); await evala(p,`localStorage.clear()`); await goto(p,'http://127.0.0.1:8765/index.html?v='+Date.now(),3500);
  await evala(p,`window.__errs=[]; window.addEventListener('error',function(e){ __errs.push(String(e.message)+' @'+e.lineno); }); var s=document.createElement('style'); s.textContent='#tf-devbtn,#tf-devpanel,#teth-help{display:none!important}'; document.head.appendChild(s);`);
  await evala(p,`qaRun(3,2)`); await sleep(6500);
  await shot(p,OUT+'M1-empty'+sx+'.png',{full:false});
  console.log(W,'empty',await evala(p,`JSON.stringify({mkh:!!document.getElementById('mkh'),px:(document.querySelector('.mkh-px b')||{}).textContent,kv:[].map.call(document.querySelectorAll('.mkh-kv dd'),function(d){ return d.textContent; }),tabs:document.querySelectorAll('.mkt-tabs button').length,iframe:!!document.querySelector('#nfxh-tv iframe')})`), JSON.stringify(await errs()));
  await evala(p,`mktPick()`); await sleep(2500);
  await shot(p,OUT+'M2-picker'+sx+'.png',{full:false});
  console.log(W,'picker rows',await evala(p,`document.querySelectorAll('.mkp-r').length`));
  await evala(p,`(function(){ var b=[].filter.call(document.querySelectorAll('#mkp-cat button'),function(x){ return x.dataset.v==='meme'; })[0]; b&&b.click(); })()`); await sleep(500);
  console.log(W,'meme rows',await evala(p,`document.querySelectorAll('.mkp-r').length`));
  await evala(p,`mktSet('ETHUSDT')`); await sleep(3500);
  console.log(W,'eth',await evala(p,`JSON.stringify({sym:(document.querySelector('.mkh-sym b')||{}).textContent,px:(document.querySelector('.mkh-px b')||{}).textContent})`));
  await evala(p,`mktTab('info')`); await sleep(4500); await shot(p,OUT+'M3-info'+sx+'.png',{full:false});
  await evala(p,`mktTab('data')`); await sleep(4500); await shot(p,OUT+'M4-data'+sx+'.png',{full:false});
  console.log(W,'data cards with svg',await evala(p,`document.querySelectorAll('.mkx-card .mkx-svg').length`));
  await evala(p,`mktTab('chart')`); await sleep(500);
  await evala(p,`qaRun(3,4)`); await sleep(7000);
  await shot(p,OUT+'M5-strat'+sx+'.png',{full:false});
  console.log(W,'strat',await evala(p,`JSON.stringify({sel:!!document.querySelector('.mks-btn'),sym:(document.querySelector('.mkh-sym b')||{}).textContent,rail:getComputedStyle(document.querySelector('.tft-rail')).display})`));
  await evala(p,`mktRailTgl(true)`); await sleep(500); await shot(p,OUT+'M6-rail'+sx+'.png',{full:false});
  console.log(W,'rail',await evala(p,`getComputedStyle(document.querySelector('.tft-rail')).display`), JSON.stringify(await errs()));
  await evala(p,`qaRun(3,8)`); await sleep(7000); await shot(p,OUT+'M7-copy'+sx+'.png',{full:false});
  console.log(W,'copy',await evala(p,`JSON.stringify({mode:G.mode,txt:(document.querySelector('.tft-page')||{innerText:''}).innerText.replace(/\\s+/g,' ').slice(0,300)})`), JSON.stringify(await errs()));
}
await closePage(p);
