import { test, expect } from '@playwright/test'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import fixtures from './fixtures/native-service-contracts.json' with { type: 'json' }
import type { NativeJob, NativeReport, NativeChartManifest, NativeChartWindow } from '../../src/internal-poc/native-service-api'

test('result pagination keeps confirmed page after failure and allows the same cursor retry', async ({ page }) => {
  await page.evaluate(async data => {
    const refreshPath = '/@react-refresh'
    const runtime = (await import(/* @vite-ignore */ refreshPath)).default
    runtime.injectIntoGlobalHook(window)
    Object.assign(window, { $RefreshReg$: () => {}, $RefreshSig$: () => (type: unknown) => type, __vite_plugin_react_preamble_installed__: true })
    const reactPath = '/@id/react', domPath = '/@id/react-dom/client', panelPath = '/src/internal-poc/NativeServiceResult.tsx'
    const react = await import(/* @vite-ignore */ reactPath), dom = await import(/* @vite-ignore */ domPath)
    const { NativeServiceResult } = await import(/* @vite-ignore */ panelPath)
    const report = (data.sources[1].fixture as unknown as { response: { data: NativeReport } }).response.data
    let attempts = 0
    const api = { report: async () => report, trades: async (_report: unknown, _segment: unknown, cursor?: string) => {
      if (cursor !== undefined) {
        if (cursor !== 'synthetic_ui_cursor') throw new Error('WRONG_CURSOR')
        if (++attempts === 1) throw new Error('SYNTHETIC_RESPONSE_LOSS')
      }
      return { trades: [], nextCursor: cursor === undefined ? 'synthetic_ui_cursor' : null }
    }, chart: async () => { throw new Error('SYNTHETIC_CHART_UNAVAILABLE') } }
    const root = document.createElement('div'); document.body.append(root)
    // Isolated display fixture, not a substitute for generated SDK/API verification.
    ;(dom.createRoot ?? dom.default.createRoot)(root).render((react.createElement ?? react.default.createElement)(NativeServiceResult, { api, job: { backtestId: report.binding.backtestId } }))
  }, fixtures)
  const result = page.getByRole('region', { name: '백테스트 결과' })
  await expect(result).toContainText('1페이지 · 현재 0건')
  await result.getByRole('button', { name: '다음 거래 페이지' }).click()
  await expect(result).toContainText('마지막으로 확인한 페이지를 유지합니다.')
  await expect(result).toContainText('1페이지 · 현재 0건')
  await result.getByRole('button', { name: '다음 거래 페이지' }).click()
  await expect(result).toContainText('2페이지 · 현재 0건')
  await expect(result).not.toContainText('마지막으로 확인한 페이지를 유지합니다.')
  await expect(result.getByRole('button', { name: '다음 거래 페이지' })).toHaveCount(0)
})

test('vendored native SDK retains published generated bytes', () => {
  for (const version of ['0.5', '0.6', '0.7', '0.8']) {
    const root = new URL(`../../src/internal-poc/contracts/generated/api-v${version}/`, import.meta.url)
    const manifest = JSON.parse(readFileSync(new URL('generation-manifest.json', root), 'utf8'))
    for (const file of ['client.ts', 'types.ts', 'validator.ts', 'index.ts', 'operation-manifest.json']) {
      expect(createHash('sha256').update(readFileSync(new URL(file, root))).digest('hex')).toBe(manifest.generatedSha256[file])
    }
  }
})

test.beforeEach(async ({ page }) => {
  await page.route('**/native-api-test.html', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><html><body>오프라인 계약 fixture 시험</body></html>' }))
  await page.goto('/native-api-test.html')
})

test('정착된 report 결속 불일치는 표시 controller에 도착하기 전에 기존 SDK adapter가 거절한다', async ({ page }) => {
  const result = await page.evaluate(async data => {
    const path = '/src/internal-poc/native-service-api.ts'
    const { createNativeServiceApi } = await import(/* @vite-ignore */ path)
    const report = data.sources[1].fixture as unknown as { response: { data: NativeReport } }
    const job = { ...(data.sources[3].fixture as unknown as { cases: { response: { data: NativeJob } }[] }).cases[0].response.data,
      state: 'COMPLETED', resultAvailable: true, nativeReportBinding: report.response.data.binding } as NativeJob
    let reads = 0
    const api = createNativeServiceApi({ async request() {
      reads++
      return { status: 200, headers: { 'cache-control': 'no-store', etag: '"synthetic_etag_1234567890"' }, body: JSON.stringify(report.response) }
    } })
    const valid = await api.report(job)
    let rejected: string | null = null
    try { await api.report({ ...job, splitGroupId: 'split_group_wrong_0001' } as NativeJob) }
    catch (error) { rejected = (error as Error).message }
    return { valid: valid.binding.backtestId === job.backtestId, rejected, reads }
  }, fixtures)
  expect(result).toEqual({ valid: true, rejected: 'NATIVE_RESULT_BINDING_CONFLICT', reads: 2 })
})

test('same-origin bounded transport rejects outbound and unrecognized operations before fetch', async ({ page }) => {
  const results = await page.evaluate(async () => {
    const path = '/src/internal-poc/native-service-api.ts'
    const { NativeServiceTransport } = await import(/* @vite-ignore */ path)
    const transport = new NativeServiceTransport()
    const base = { method: 'GET', headers: { Accept: 'application/json' }, credentials: 'include', redirect: 'manual', cache: 'no-store' }
    const requests = [
      { ...base, path: 'https://example.com/api/v7/backtests/a' },
      { ...base, path: '/api/v7/other/../backtests/a' },
      { ...base, path: '/api/v7/backtests/a#token' },
      { ...base, path: '/api/v7/backtests/a', headers: { Authorization: 'synthetic_forbidden' } },
      { ...base, method: 'POST', path: '/api/v7/backtests/a' },
      { ...base, method: 'DELETE', path: '/api/v7/backtests' },
      { ...base, path: '/api/v7/backtests/a', redirect: 'follow' },
    ]
    const values = []
    for (const request of requests) { try { await transport.request(request); values.push('UNEXPECTED') } catch (error) { values.push((error as Error).message) } }
    return values
  })
  expect(results).toHaveLength(7)
  expect(results.every(value => /NATIVE_(SAME_ORIGIN_OPERATION_REQUIRED|REQUEST_HEADER_REJECTED)/.test(value))).toBe(true)
})

test('동시 GET의 프로토콜 거절·통신 실패는 서로 섞이지 않고 정상 SDK 응답은 그대로 통과한다', async ({ page }) => {
  const sample = fixtures.sources[3].fixture.cases![0].response
  const ids = ['protocol', 'network', 'healthy'].map(kind => `backtest_native_${kind}_0001`)
  const methods: string[] = []
  await page.route(/\/api\/v7\/backtests\/backtest_native_(protocol|network|healthy)_0001$/, route => {
    methods.push(route.request().method())
    const id = new URL(route.request().url()).pathname.split('/').at(-1)!
    if (id.includes('network')) return route.abort('failed')
    return route.fulfill({ status: 200, contentType: 'application/json',
      headers: { ETag: '"native_protocol_fixture_0001"', 'cache-control': id.includes('protocol') ? 'public' : 'no-store' },
      body: JSON.stringify({ ...sample, data: { ...sample.data, backtestId: id } }) })
  })
  const result = await page.evaluate(async ids => {
    const path = '/src/internal-poc/native-service-api.ts'
    const { createNativeServiceApi } = await import(/* @vite-ignore */ path)
    const api = createNativeServiceApi()
    const get = async (id: string) => {
      try { const response = await api.jobs.call('getNativeBacktestV7', { backtestId: id }); return response.data.backtestId }
      catch (failure) { return (failure as { code: string }).code }
    }
    return { concurrent: await Promise.all(ids.map(get)), next: await get(ids[2]) }
  }, ids)
  expect(result).toEqual({ concurrent: ['INVALID_RESPONSE', 'TRANSPORT_FAILED', ids[2]], next: ids[2] })
  expect(methods).toEqual(['GET', 'GET', 'GET', 'GET'])
})

for (const responseCase of ['valid', 'redirect', 'cache', 'invalid-utf8', 'oversize'] as const) {
  test(`native browser fetch: ${responseCase}`, async ({ page }) => {
    const payload = JSON.stringify({ fixture: true })
    await page.route('**/api/v7/backtests/job_test', route => route.fulfill({
      status: responseCase === 'redirect' ? 302 : 200,
      contentType: 'application/json', headers: { 'cache-control': responseCase === 'cache' ? 'public' : 'no-store', ...(responseCase === 'redirect' ? { location: '/never-follow' } : {}) },
      body: responseCase === 'invalid-utf8' ? Buffer.from([0xc3, 0x28]) : responseCase === 'oversize' ? 'x'.repeat(4 * 1024 * 1024 + 1) : payload,
    }))
    const result = await page.evaluate(async () => {
      const modulePath = '/src/internal-poc/native-service-api.ts'
      const { NativeServiceTransport } = await import(/* @vite-ignore */ modulePath)
      try { const reply = await new NativeServiceTransport().request({ method: 'GET', path: '/api/v7/backtests/job_test', headers: { Accept: 'application/json' }, credentials: 'include', redirect: 'manual', cache: 'no-store' }); return { okay: true, body: reply.body } }
      catch { return { okay: false } }
    })
    expect(result.okay).toBe(responseCase === 'valid')
    if (responseCase === 'valid') expect(result.body).toBe(payload)
  })
}

test('v5 chart parses raw JSON separately; v6 report preserves native binding and MMR limitation', async ({ page }) => {
  const result = await page.evaluate(async data => {
    const modulePath = '/src/internal-poc/native-service-api.ts'
    const { createNativeServiceApi } = await import(/* @vite-ignore */ modulePath)
    const chart = data.sources[0].fixture as unknown as { binding: NativeChartManifest['binding']; sourcePolicy: NativeChartManifest['sourcePolicy']; meta: unknown; manifest: Omit<NativeChartManifest, 'binding' | 'sourcePolicy'>; window: Omit<NativeChartWindow, 'binding' | 'sourcePolicy'> }
    const report = data.sources[1].fixture as unknown as { response: { data: NativeReport } }
    const job = { ...(data.sources[3].fixture as unknown as { cases: { response: { data: NativeJob } }[] }).cases[0].response.data,
      state: 'COMPLETED', resultAvailable: true, nativeReportBinding: report.response.data.binding }
    const segment = report.response.data.nativeEnvelope.projection.segments[0]
    const binding = { ...chart.binding, backtestId: job.backtestId, splitGroupId: job.splitGroupId,
      strategyVersionId: job.strategyVersionId, semanticHash: job.semanticHash, resultContentHash: segment.resultContentHash }
    const segmentBounds = { fromInclusive: segment.evaluationStartInclusive, toExclusive: segment.evaluationEndExclusive }
    const manifest = { ...chart.manifest, binding, sourcePolicy: chart.sourcePolicy, segmentBounds,
      series: chart.manifest.series.map(series => ({ ...series, availableRange: segmentBounds })) }
    const requests: string[] = []
    const api = createNativeServiceApi({ request: async (request: { path: string }) => {
      requests.push(request.path)
      let body
      if (request.path.includes('native-report')) body = report.response
      else if (request.path.includes('chart-manifest')) body = { meta: chart.meta, data: manifest }
      else {
        const url = new URL(request.path, location.origin)
        const requestedRange = { fromInclusive: url.searchParams.get('fromInclusive'), toExclusive: url.searchParams.get('toExclusive') }
        body = { meta: chart.meta, data: { ...chart.window, binding, sourcePolicy: chart.sourcePolicy, resolution: url.searchParams.get('resolution'), aggregationPolicy: 'UTC_EPOCH_COMPLETE_OHLCV', requestedRange,
          bars: [], coverage: { status: 'UNAVAILABLE', coveredRanges: [], missingRanges: [requestedRange] } } }
      }
      return { status: 200, headers: { 'cache-control': 'no-store', etag: '"synthetic_etag_1234567890"' }, body: JSON.stringify(body) }
    } })
    const actualReport = await api.report(job)
    const actualChart = await api.chart(job, actualReport, 'IS')
    manifest.series = manifest.series.map(series => ({ ...series, supportedResolutions: ['1m', '15m', '1h'],
      availableRange: { ...segmentBounds, fromInclusive: '2024-01-01T00:15:00Z' } }))
    const hourlyChart = await api.chart(job, actualReport, 'IS')
    const hourBuckets = Math.floor((Date.parse(hourlyChart.window.requestedRange.toExclusive) - 1) / 3600000)
      - Math.floor(Date.parse(hourlyChart.window.requestedRange.fromInclusive) / 3600000) + 1
    manifest.segmentBounds = { ...segmentBounds, fromInclusive: '2024-01-01T00:01:00Z' }
    let wrongBoundsRejected = false
    try { await api.chart(job, actualReport, 'IS') } catch { wrongBoundsRejected = true }
    let rejected = false
    try { await api.report({ ...job, nativeReportBinding: { ...job.nativeReportBinding, terminalSealContentHash: 'a'.repeat(64) } }) } catch { rejected = true }
    return { requests, source: actualReport.binding.evidenceClass, limitation: actualReport.binding.liquidationCheckStatus,
      chartStatus: actualChart.window.coverage.status, bars: actualChart.view.bars.length, rejected, hourBuckets, wrongBoundsRejected }
  }, fixtures)
  expect(result.source).toBe('SYNTHETIC_CONTRACT_FIXTURE')
  expect(result.limitation).toBe('UNAVAILABLE')
  expect(result.chartStatus).toBe('UNAVAILABLE')
  expect(result.bars).toBe(0)
  expect(result.rejected).toBe(true)
  expect(result.hourBuckets).toBe(1000)
  expect(result.wrongBoundsRejected).toBe(true)
  expect(result.requests.some(path => path.includes('/api/v5/') && path.includes('chart-window'))).toBe(true)
})
