// 거래소 연결 플랜: 상태 모델 변경 (결제 먼저, 본인 확인 단계, 구독 거래소 2곳, 가입 안내 2단계)
const fs=require('fs');
function ed(f,L){ let s=fs.readFileSync(f,'utf8'); for(const [a,b] of L){ const n=s.split(a).length-1; if(n!==1) throw new Error(f+' anchor '+n+' :: '+a.slice(0,70)); s=s.replace(a,()=>b); } fs.writeFileSync(f,s); }
ed('ac.js',[
 // 상태: 본인 확인
 ["  var a=t.ac; a.conn=a.conn||{}; a.pay=a.pay||{st:'none'}; a.auth=a.auth||{st:'idle'}; a.uid=a.uid||{st:'none'}; a.cards=a.cards||[]; a.bill=a.bill||[];",
  "  var a=t.ac; a.conn=a.conn||{}; a.pay=a.pay||{st:'none'}; a.auth=a.auth||{st:'idle'}; a.uid=a.uid||{st:'none'}; a.kyc=a.kyc||{st:'none'}; a.cards=a.cards||[]; a.bill=a.bill||[];"],
 // 구독은 거래소 2곳까지
 ["function acReady(ex){","var AC_PAID_MAX=2; /* 구독 하나로 연결할 수 있는 거래소 수 */\nfunction acPaidCount(){ var a=acS(), n=0; for(var k in a.conn) if(a.conn[k].via==='paid'&&acEx(k)) n++; return n; }\nfunction acPaidFull(){ return acSubOn()&&acPaidCount()>=AC_PAID_MAX*((acS().sub&&acS().sub.n)||1); }\nfunction acKycOk(ex){ var a=acS(); return a.kyc.st==='ok'&&a.kyc.ex===ex; }\nfunction acReady(ex){"],
 // 단계 순서: 구독은 결제 → 거래소 → 승인 → 본인 확인. 초대는 거래소 → 계정 → 승인 → 초대 확인 → 본인 확인
 ["  var r=acRouteNow();\n  if(!r) return 'route';\n  if(!ex) return 'ex';\n  if(r==='partner'){ if(!a.has) return 'acct'; if(a.has==='no'&&a.g<3) return 'guide'; if(!acAuthOk(ex)) return 'auth'; if(a.uid.st!=='ok'||a.uid.ex!==ex) return 'uid'; }\n  else if(r==='paid'){ if(!acSubOn()) return 'pay'; if(!acAuthOk(ex)) return 'auth'; }\n  return 'commit';",
  "  var r=acRouteNow();\n  if(!r) return 'route';\n  if(r==='paid'){ if(!acSubOn()) return 'pay'; if(!ex) return 'ex'; if(!a.conn[ex]&&acPaidFull()) return 'limit'; if(!acAuthOk(ex)) return 'auth'; if(!acKycOk(ex)) return 'kyc'; }\n  else { if(!ex) return 'ex'; if(!a.has) return 'acct'; if(a.has==='no'&&a.g<2) return 'guide'; if(!acAuthOk(ex)) return 'auth'; if(a.uid.st!=='ok'||a.uid.ex!==ex) return 'uid'; if(!acKycOk(ex)) return 'kyc'; }\n  return 'commit';"],
 ["  if(acc==='none'||(!acSubOn()&&a.route==='paid')) L.push(['route','이용 방식']);\n  L.push(['ex','거래소']);\n  if(r==='partner'){ L.push(['acct','거래소 계정']); L.push(['auth','연결 승인']); L.push(['uid','초대 계정 확인']); }\n  else { /* 결제는 아직 안 했거나 방금 이 흐름에서 마쳤을 때만 보인다 */ if(!acSubOn()||(a.pay.st==='ok'&&!acConnList().some(function(k){ return a.conn[k].via==='paid'; }))) L.push(['pay','결제']); L.push(['auth','연결 승인']); }\n  return L;",
  "  if(acc==='none'||(!acSubOn()&&a.route==='paid')) L.push(['route','이용 방식']);\n  if(r==='partner'){ L.push(['ex','거래소']); L.push(['acct','거래소 계정']); L.push(['auth','연결 승인']); L.push(['uid','초대 계정 확인']); L.push(['kyc','본인 확인']); }\n  else { /* 결제가 먼저. 이미 구독 중이면 결제 단계는 보이지 않는다 */ if(!acSubOn()||(a.pay.st==='ok'&&!acConnList().some(function(k){ return a.conn[k].via==='paid'; }))) L.push(['pay','결제']); L.push(['ex','거래소']); L.push(['auth','연결 승인']); L.push(['kyc','본인 확인']); }\n  return L;"],
 ["  if(k==='acct') return a.has==='no'?'새 계정, 가입과 본인 확인 완료':'계정 있음';","  if(k==='acct') return a.has==='no'?'새 계정, 가입 완료':'계정 있음';\n  if(k==='kyc') return acName(a.ex)+' 본인 확인 완료';"],
 ["k==='acct'?(!!a.has&&(a.has!=='no'||a.g>=3)):","k==='acct'?(!!a.has&&(a.has!=='no'||a.g>=2)):k==='kyc'?acKycOk(ex):"],
 // 그리기 표에 본인 확인과 한도 안내
 ["body={route:acBRoute,ex:acBEx,acct:acBAcct,guide:acBGuide,pay:acBPay,auth:acBAuth,uid:acBUid};","body={route:acBRoute,ex:acBEx,acct:acBAcct,guide:acBGuide,pay:acBPay,auth:acBAuth,uid:acBUid,kyc:acBKyc,limit:acBLimit};"],
 ["  var seen=false, sub=cur==='guide'; if(sub) cur='acct';","  var seen=false, sub=cur==='guide'; if(sub) cur='acct'; var lim=cur==='limit'; if(lim) cur='ex';"],
 ["+(on?'<div class=\"sb\" id=\"ac-sb\">'+body[sub?'guide':x[0]]()+'</div>':'')+'</li>'; }).join('')","+(on?'<div class=\"sb\" id=\"ac-sb\">'+body[sub?'guide':lim?'limit':x[0]]()+'</div>':'')+'</li>'; }).join('')"],
 // 계정 있음 화면: 승인 뒤 초대 계정 확인을 미리 알린다
 ["  return '<p class=\"btg-p\">'+n+' 계정이 있습니까? TETH 초대로 가입한 계정이면 이용료 없이 씁니다.</p>'","  return '<p class=\"btg-p\">'+n+' 계정이 있습니까? TETH 초대로 가입한 계정이면 이용료 없이 씁니다. 승인 뒤에 TETH 초대로 가입한 계정인지 확인합니다.</p>'"],
 // 가입 안내: 가입, 본인 확인 두 단계. 입금은 실행 준비에서
 ["  var a=acS(), n=acName(a.ex), g=a.g||0, T=[['계정 만들기','TETH 초대 주소로 '+n+' 가입 화면이 새 창에 열립니다. 이메일이나 전화번호로 가입합니다.'],['본인 확인',n+' 앱이나 웹에서 신분증으로 본인 확인을 마칩니다. 보통 몇 분이면 끝납니다.'],['입금','전략이 쓸 금액을 '+n+' 계정에 넣습니다. 지금 건너뛰고 나중에 넣어도 연결은 할 수 있습니다.']];\n  return '<ol class=\"acx-g\">'+T.map(function(x,i){ return '<li class=\"'+(i<g?'ok':i===g?'on':'')+'\"><span class=\"n num\">'+(i<g?AC_CK:(i+1))+'</span><div><b>'+x[0]+'</b>'+(i===g?'<p>'+x[1]+'</p>':'')+'</div></li>'; }).join('')+'<li><span class=\"n num\">4</span><div><b>TETH 연결</b></div></li></ol>'\n    +(g===0?'<a class=\"bt-cta acx-a\" href=\"'+gEsc(acRef(a.ex))+'\" target=\"_blank\" rel=\"noopener\" onclick=\"acGuideOpen()\">'+n+' 가입 화면 열기'+AC_OUT+'</a><button type=\"button\" class=\"bt-sec\" onclick=\"acGuide(1)\">가입 완료</button>'\n      :g===1?'<button type=\"button\" class=\"bt-cta\" onclick=\"acGuide(2)\">본인 확인 완료</button>'\n      :'<button type=\"button\" class=\"bt-cta\" onclick=\"acGuide(3)\">입금 완료</button><button type=\"button\" class=\"bt-sec\" onclick=\"acGuide(3)\">나중에 입금</button>');",
  "  var a=acS(), n=acName(a.ex), g=a.g||0, T=[['계정 만들기','TETH 초대 주소로 '+n+' 가입 화면이 새 창에 열립니다. 이메일이나 전화번호로 가입합니다.'],['본인 확인',n+' 앱이나 웹에서 신분증으로 본인 확인을 마칩니다. 보통 몇 분이면 끝납니다. 입금은 나중에 전략을 시작할 때 안내합니다.']];\n  return '<ol class=\"acx-g\">'+T.map(function(x,i){ return '<li class=\"'+(i<g?'ok':i===g?'on':'')+'\"><span class=\"n num\">'+(i<g?AC_CK:(i+1))+'</span><div><b>'+x[0]+'</b>'+(i===g?'<p>'+x[1]+'</p>':'')+'</div></li>'; }).join('')+'<li><span class=\"n num\">3</span><div><b>TETH 연결</b></div></li></ol>'\n    +(g===0?'<a class=\"bt-cta acx-a\" href=\"'+gEsc(acRef(a.ex))+'\" target=\"_blank\" rel=\"noopener\" onclick=\"acGuideOpen()\">'+n+' 가입 화면 열기'+AC_OUT+'</a><button type=\"button\" class=\"bt-sec\" onclick=\"acGuide(1)\">가입 완료</button>'\n      :'<button type=\"button\" class=\"bt-cta\" onclick=\"acGuide(2)\">본인 확인 완료</button>');"],
 // 본인 확인 단계와 한도 안내
 ["function acUidAlt(k){","/* 본인 확인(KYC): 거래소에서 마쳤는지 조회한다. 완료, 미완료, 심사 중, 조회 실패 */\nfunction acBKyc(){\n  var a=acS(), n=acName(a.ex), k=a.kyc.ex===a.ex?a.kyc:{st:'none'};\n  if(k.st==='fail') return '<p class=\"acx-fail\" role=\"alert\"><b>'+n+'에서 본인 확인을 완료해 주십시오</b><br>계정 승인은 완료되었습니다. '+n+'에서 본인 확인을 마치면 이어서 진행합니다.</p><a class=\"bt-cta acx-a\" href=\"'+gEsc(acRef(a.ex))+'\" target=\"_blank\" rel=\"noopener\">본인 확인하러 가기'+AC_OUT+'</a><button type=\"button\" class=\"bt-sec\" onclick=\"acKycRun()\">다시 확인하기</button>';\n  if(k.st==='review') return '<p class=\"acx-note\" role=\"status\"><b>'+n+'에서 본인 확인을 검토하고 있습니다</b><br>보통 몇 분에서 하루 안에 끝납니다. 끝나면 이어서 진행합니다.</p><button type=\"button\" class=\"bt-cta\" onclick=\"acKycRun()\">다시 확인하기</button>';\n  if(k.st==='err') return '<p class=\"acx-note\" role=\"status\">본인 확인 상태를 불러오지 못했습니다. 잠시 뒤 다시 확인해 주십시오.</p><button type=\"button\" class=\"bt-cta\" onclick=\"acKycRun()\">다시 확인하기</button>';\n  return '<ul class=\"btg-chk acx-chk\" id=\"ac-kchk\"><li class=\"run\" id=\"ac-k0\"><span class=\"ic\"><i></i></span><b>본인 확인 상태</b><span>'+n+'에서 확인하는 중</span></li></ul>';\n}\nfunction acKycRun(){ var a=acS(), my=++AC_RUN; a.kyc={st:'run',ex:a.ex}; acRe();\n  setTimeout(function(){ if(my!==AC_RUN) return; var q=(window.AC_QA&&AC_QA.kyc)||'ok'; a.kyc={st:(q==='fail'||q==='review'||q==='err')?q:'ok',ex:a.ex}; acSave(); acRe(); },1100); }\nfunction acBLimit(){ var a=acS(), n=acName(a.ex);\n  return '<p class=\"acx-note\" role=\"status\"><b>구독으로는 거래소 '+AC_PAID_MAX+'곳까지 연결합니다</b><br>지금 구독에는 이미 '+acPaidCount()+'곳이 연결되어 있습니다. '+n+'는 TETH 초대 계정으로 연결하거나 구독을 하나 더 시작할 수 있습니다.</p>'\n    +'<div class=\"acx-col\"><button type=\"button\" class=\"acx-ch\" onclick=\"acLimitAlt(\\'partner\\')\"><b>TETH 초대 계정으로 연결</b><span>이용료 없이 씁니다. 초대 계정이 아니면 새로 만듭니다</span></button><button type=\"button\" class=\"acx-ch\" onclick=\"acLimitAlt(\\'more\\')\"><b>구독 하나 더 시작</b><span>월 '+acUsd(AC_CFG.price)+' 추가, 거래소 '+AC_PAID_MAX+'곳 더</span></button><button type=\"button\" class=\"acx-ch\" onclick=\"acLimitAlt(\\'ex\\')\"><b>다른 거래소 고르기</b><span></span></button></div>'; }\nfunction acLimitAlt(k){ var a=acS(); if(k==='partner'){ a.route='partner'; a.has=null; a.g=0; a.uid={st:'none'}; a.kyc={st:'none'}; } else if(k==='more'){ a.more=1; a.pay={st:'none'}; a.newCard=0; } else { a.ex=null; } acSave(); acRe(); }\nfunction acUidAlt(k){"],
 // 결제 성공: 구독 수 증가(구독 하나 더)
 ["    a.pay={st:'ok',at:Date.now()}; a.sub={st:'active',since:Date.now(),next:Date.now()+30*864e5,price:AC_CFG.price}; t.payDone=true; t.cardOn=true; t.plan='paid'; acBillAdd('paid',card,AC_CFG.price);",
  "    a.pay={st:'ok',at:Date.now()}; var nS=(a.more&&a.sub&&a.sub.st==='active')?((a.sub.n||1)+1):1; a.more=0; a.sub={st:'active',since:(a.sub&&a.sub.since)||Date.now(),next:Date.now()+30*864e5,price:AC_CFG.price,n:nS}; t.payDone=true; t.cardOn=true; t.plan='paid'; acBillAdd('paid',card,AC_CFG.price);"],
 ["    a.pay={st:'ok',at:Date.now()}; a.sub={st:'active',since:(a.sub&&a.sub.since)||Date.now(),next:Date.now()+30*864e5,price:AC_CFG.price}; t.payDone=true; t.cardOn=true; t.plan='paid'; acBillAdd('paid',sv,AC_CFG.price); acSave(); acRe(); },1500);",
  "    a.pay={st:'ok',at:Date.now()}; var nS=(a.more&&a.sub&&a.sub.st==='active')?((a.sub.n||1)+1):1; a.more=0; a.sub={st:'active',since:(a.sub&&a.sub.since)||Date.now(),next:Date.now()+30*864e5,price:AC_CFG.price,n:nS}; t.payDone=true; t.cardOn=true; t.plan='paid'; acBillAdd('paid',sv,AC_CFG.price); acSave(); acRe(); },1500);"],
 // 구독 상태에서 '결제' 단계는 more 요청 때만 다시
 ["function acRouteNow(){ var a=acS(); return acSubOn()?'paid':(a.route||(acAccess()==='partner'?'partner':null)); }","function acRouteNow(){ var a=acS(); if(a.route==='partner'&&acSubOn()&&a.ex&&!a.conn[a.ex]) return 'partner'; /* 구독 회원이 한도 뒤 초대 계정으로 고른 경우 */ return acSubOn()?'paid':(a.route||(acAccess()==='partner'?'partner':null)); }"],
 ["  if(r==='paid'){ if(!acSubOn()) return 'pay'; if(!ex) return 'ex';","  if(r==='paid'){ if(!acSubOn()||a.more) return 'pay'; if(!ex) return 'ex';"],
 // 다른 거래소를 시작할 때 본인 확인 상태도 초기화
 ["function acExGo(){ var a=acS(), id=a.exSel||a.ex||(AC_CTX&&AC_CTX.ex); if(!id) return; if(a.ex!==id){ a.has=null; a.g=0; a.auth={st:'idle'}; a.uid={st:'none'};","function acExGo(){ var a=acS(), id=a.exSel||a.ex||(AC_CTX&&AC_CTX.ex); if(!id) return; if(a.ex!==id){ a.has=null; a.g=0; a.auth={st:'idle'}; a.uid={st:'none'}; a.kyc={st:'none'};"],
 // 승인 뒤 초대 확인, 그 뒤 본인 확인이 자동으로 이어진다
 ["    acSave(); acRe(); if(!bad&&acStep()==='uid') acUidRun(); },1300);","    acSave(); acRe(); if(!bad&&acStep()==='uid') acUidRun(); else if(!bad&&acStep()==='kyc') acKycRun(); },1300);"],
 ["      a.uid=bad?{st:'fail',ex:a.ex,v:a.auth.uid}:{st:'ok',ex:a.ex,v:a.auth.uid}; acSave(); acRe(); },900); },800);","      a.uid=bad?{st:'fail',ex:a.ex,v:a.auth.uid}:{st:'ok',ex:a.ex,v:a.auth.uid}; acSave(); acRe(); if(!bad&&acStep()==='kyc') acKycRun(); },900); },800);"],
 ["  TF_RENDERING=false; if(acStep()==='uid') acUidRun();\n}\nfunction acAddMore(){","  TF_RENDERING=false; if(acStep()==='uid') acUidRun(); else if(acStep()==='kyc'&&acS().kyc.st!=='fail'&&acS().kyc.st!=='review'&&acS().kyc.st!=='err') acKycRun();\n}\nfunction acAddMore(){"],
 ["function acAddMore(){ var a=acS(); a.ex=null; a.adding=1; a.has=null; a.auth={st:'idle'}; a.uid={st:'none'};","function acAddMore(){ var a=acS(); a.ex=null; a.adding=1; a.has=null; a.auth={st:'idle'}; a.uid={st:'none'}; a.kyc={st:'none'};"],
]);
console.log('ok');
