const fs=require('fs');
function ed(f,L){ let s=fs.readFileSync(f,'utf8'); for(const [a,b] of L){ const n=s.split(a).length-1; if(n!==1) throw new Error(f+' anchor '+n+' :: '+a.slice(0,70)); s=s.replace(a,()=>b); } fs.writeFileSync(f,s); }
ed('ac.js',[
 ["  a.conn[ex]={via:r==='paid'?'paid':'partner',at:Date.now(),uid:a.uid.ex===ex?(a.uid.v||''):'',kyc:'run'};","  a.conn[ex]={via:r==='paid'?'paid':'partner',at:Date.now(),uid:a.uid.ex===ex?(a.uid.v||''):'',kyc:'none'};"],
 ["  a.doneAt=Date.now(); a.edit=null; acSave(); try{ tfTrack('ac_connected',{ex:ex,via:a.conn[ex].via}); tfSideSync&&tfSideSync(); }catch(e){}\n  setTimeout(function(){ acKycRun(ex); },50);","  a.doneAt=Date.now(); a.edit=null; acSave(); try{ tfTrack('ac_connected',{ex:ex,via:a.conn[ex].via}); tfSideSync&&tfSideSync(); }catch(e){}"],
 ["    +acKycHtml(ex)\n    +(ctx.doneHtml?ctx.doneHtml():","    +(ctx.doneHtml?ctx.doneHtml():"],
 // 실행 직전 관문: 본인 확인이 끝나야 주문을 낸다
 ["function acRunOk(ex){ var a=acS(); return !!(a.conn[ex]&&a.conn[ex].kyc==='ok'); }",
  "function acRunOk(ex){ var a=acS(); return !!(a.conn[ex]&&a.conn[ex].kyc==='ok'); }\n/* 전략을 시작하기 직전에만 본인 확인을 본다. 연결 자체는 막지 않는다 */\nfunction acRunGate(ex,cb){ var a=acS(); ex=ex||acConnList()[0]; if(!ex||!a.conn[ex]){ cb(); return; } if(acRunOk(ex)){ cb(); return; }\n  var open=function(){ var w=document.getElementById('ac-cf'); if(w) w.remove(); var d=document.createElement('div'); d.id='ac-cf'; d.className='acx-cf'; d.setAttribute('role','dialog'); d.setAttribute('aria-modal','true'); d.innerHTML='<div class=\"bx\"><h3>전략을 시작하기 전에 본인 확인이 필요합니다</h3>'+acKycHtml(ex)+'<div class=\"bts\"><button type=\"button\" onclick=\"acConfirmClose()\">닫기</button><button type=\"button\" class=\"ok\" id=\"ac-kyc-go\" onclick=\"acRunGateGo()\"'+(acRunOk(ex)?'':' disabled')+'>전략 시작</button></div></div>'; document.body.appendChild(d); };\n  AC_GATE={ex:ex,cb:cb}; open();\n  var my=++AC_RUN; a.conn[ex].kyc='run'; acSave(); try{ var el=document.getElementById('ac-kyc'); if(el) el.outerHTML=acKycHtml(ex); }catch(e){}\n  setTimeout(function(){ if(my!==AC_RUN) return; var q=(window.AC_QA&&AC_QA.kyc)||'ok'; var st=(q==='fail'||q==='review'||q==='err')?q:'ok'; a.conn[ex].kyc=st; acSave(); try{ var el=document.getElementById('ac-kyc'); if(el) el.outerHTML=acKycHtml(ex); var g=document.getElementById('ac-kyc-go'); if(g) g.disabled=st!=='ok'; }catch(e){} if(st==='ok'){ setTimeout(function(){ acConfirmClose(); var c=AC_GATE&&AC_GATE.cb; AC_GATE=null; if(c) c(); },500); } },1100); }\nvar AC_GATE=null;\nfunction acRunGateGo(){ var g=AC_GATE; AC_GATE=null; acConfirmClose(); if(g&&g.cb&&acRunOk(g.ex)) g.cb(); }"],
 // 다시 확인하기(대화 상자 안)도 같은 조회를 쓴다
 ["function acKycRun(ex){ var a=acS(); ex=ex||a.ex; var c=a.conn[ex]; if(!c) return; var my=++AC_RUN; c.kyc='run'; a.kyc={st:'run',ex:ex}; acSave(); acRe();\n  setTimeout(function(){ if(my!==AC_RUN) return; var q=(window.AC_QA&&AC_QA.kyc)||'ok'; var st=(q==='fail'||q==='review'||q==='err')?q:'ok'; if(a.conn[ex]) a.conn[ex].kyc=st; a.kyc={st:st,ex:ex}; acSave(); acRe(); try{ var el=document.getElementById('ac-kyc'); if(el) el.outerHTML=acKycHtml(ex); }catch(e){} },1100); }",
  "function acKycRun(ex){ var a=acS(); ex=ex||a.ex; var c=a.conn[ex]; if(!c) return; var my=++AC_RUN; c.kyc='run'; acSave(); try{ var el=document.getElementById('ac-kyc'); if(el) el.outerHTML=acKycHtml(ex); }catch(e){}\n  setTimeout(function(){ if(my!==AC_RUN) return; var q=(window.AC_QA&&AC_QA.kyc)||'ok'; var st=(q==='fail'||q==='review'||q==='err')?q:'ok'; if(a.conn[ex]) a.conn[ex].kyc=st; acSave(); try{ var el=document.getElementById('ac-kyc'); if(el) el.outerHTML=acKycHtml(ex); var g=document.getElementById('ac-kyc-go'); if(g) g.disabled=st!=='ok'; }catch(e){} if(st==='ok'&&AC_GATE&&AC_GATE.ex===ex){ setTimeout(function(){ acConfirmClose(); var c=AC_GATE&&AC_GATE.cb; AC_GATE=null; if(c) c(); },500); } },1100); }"],
]);
// 실행 시작점에 관문을 건다
ed('p16.js',[["  /* 팝업 메뉴는 예전 그대로 둔다.","  /* 전략 시작 직전의 본인 확인 관문 */\n  if(typeof btMineStart==='function'&&!btMineStart.kyc){ var bm0=btMineStart; btMineStart=function(m){ var args=arguments, self=this; if(m==='live'){ acRunGate(acS().ex||acConnList()[0],function(){ bm0.apply(self,args); }); return; } return bm0.apply(self,args); }; btMineStart.kyc=1; }\n  if(typeof cpStart==='function'&&!cpStart.kyc){ var cs0=cpStart; cpStart=function(ne){ var args=arguments, self=this, s=null; try{ s=tfSSFind(decodeURIComponent(ne)); }catch(e){} var ex=s&&s.ex&&acEx(s.ex)&&acS().conn[s.ex]?s.ex:(acConnList()[0]||null); acRunGate(ex,function(){ cs0.apply(self,args); }); }; cpStart.kyc=1; }\n  /* 팝업 메뉴는 예전 그대로 둔다."]]);
console.log('ok');
