import type { ClientLanguage } from '../client-preferences'

const ko = {
  group: '차트 그리기', cursor: '선택', trend: '추세선', ray: '반직선', horizontal: '수평선', vertical: '수직선', rectangle: '사각형', fibonacci: '피보나치 되돌림', measure: '가격 범위',
  undo: '되돌리기', redo: '다시 실행', hide: '도형 숨기기', show: '도형 표시', remove: '선택 도형 삭제', list: '분석 도형', start: '시작점 변경', end: '끝점 변경',
  first: '차트에서 시작점을 선택하세요. 방향키와 Enter로도 그릴 수 있습니다.', second: '끝점을 선택하세요. Esc로 취소합니다.', edit: '새 위치를 선택하세요. Esc로 취소합니다.',
  local: '현재 차트에서만 유지되며 거래에는 영향을 주지 않습니다.', limit: '도형은 최대 100개까지 그릴 수 있습니다.', paused: '재생이 끝나면 그리기 도구를 사용할 수 있습니다.',
}
type Copy = Record<keyof typeof ko, string>
const copy: Record<ClientLanguage, Copy> = {
  ko,
  en: { group: 'Chart drawings', cursor: 'Select', trend: 'Trend line', ray: 'Ray', horizontal: 'Horizontal line', vertical: 'Vertical line', rectangle: 'Rectangle', fibonacci: 'Fibonacci retracement', measure: 'Price range', undo: 'Undo', redo: 'Redo', hide: 'Hide drawings', show: 'Show drawings', remove: 'Delete selected drawing', list: 'Analysis drawings', start: 'Move start point', end: 'Move end point', first: 'Choose a start point on the chart. Arrow keys and Enter also work.', second: 'Choose the end point. Press Esc to cancel.', edit: 'Choose the new position. Press Esc to cancel.', local: 'Kept only in this chart and never used for trading.', limit: 'You can draw up to 100 objects.', paused: 'Drawing tools are available after replay.' },
  ja: { group: 'チャート描画', cursor: '選択', trend: 'トレンドライン', ray: 'レイ', horizontal: '水平線', vertical: '垂直線', rectangle: '長方形', fibonacci: 'フィボナッチ・リトレースメント', measure: '価格範囲', undo: '元に戻す', redo: 'やり直す', hide: '描画を非表示', show: '描画を表示', remove: '選択した描画を削除', list: '分析用の描画', start: '始点を変更', end: '終点を変更', first: 'チャートで始点を選択してください。矢印キーとEnterでも操作できます。', second: '終点を選択してください。Escでキャンセルできます。', edit: '新しい位置を選択してください。Escでキャンセルできます。', local: 'このチャート内だけで保持され、取引には影響しません。', limit: '描画は100個まで追加できます。', paused: '再生終了後に描画ツールを利用できます。' },
  'zh-CN': { group: '图表绘图', cursor: '选择', trend: '趋势线', ray: '射线', horizontal: '水平线', vertical: '垂直线', rectangle: '矩形', fibonacci: '斐波那契回撤', measure: '价格范围', undo: '撤销', redo: '重做', hide: '隐藏绘图', show: '显示绘图', remove: '删除所选绘图', list: '分析绘图', start: '修改起点', end: '修改终点', first: '在图表上选择起点。也可使用方向键和Enter。', second: '选择终点，按Esc取消。', edit: '选择新位置，按Esc取消。', local: '仅保留在当前图表中，不影响交易。', limit: '最多可添加100个绘图。', paused: '回放结束后可使用绘图工具。' },
  'zh-TW': { group: '圖表繪圖', cursor: '選取', trend: '趨勢線', ray: '射線', horizontal: '水平線', vertical: '垂直線', rectangle: '矩形', fibonacci: '費波那契回撤', measure: '價格範圍', undo: '復原', redo: '重做', hide: '隱藏繪圖', show: '顯示繪圖', remove: '刪除所選繪圖', list: '分析繪圖', start: '修改起點', end: '修改終點', first: '在圖表上選取起點。也可使用方向鍵和Enter。', second: '選取終點，按Esc取消。', edit: '選取新位置，按Esc取消。', local: '僅保留在目前圖表中，不影響交易。', limit: '最多可新增100個繪圖。', paused: '回放結束後可使用繪圖工具。' },
  es: { group: 'Dibujos del gráfico', cursor: 'Seleccionar', trend: 'Línea de tendencia', ray: 'Semirrecta', horizontal: 'Línea horizontal', vertical: 'Línea vertical', rectangle: 'Rectángulo', fibonacci: 'Retroceso de Fibonacci', measure: 'Rango de precios', undo: 'Deshacer', redo: 'Rehacer', hide: 'Ocultar dibujos', show: 'Mostrar dibujos', remove: 'Eliminar dibujo seleccionado', list: 'Dibujos de análisis', start: 'Mover punto inicial', end: 'Mover punto final', first: 'Elige el punto inicial. También puedes usar las flechas y Enter.', second: 'Elige el punto final. Esc para cancelar.', edit: 'Elige la nueva posición. Esc para cancelar.', local: 'Solo se mantienen en este gráfico y no afectan a las operaciones.', limit: 'Puedes añadir hasta 100 dibujos.', paused: 'Las herramientas estarán disponibles tras la reproducción.' },
  fr: { group: 'Dessins du graphique', cursor: 'Sélectionner', trend: 'Ligne de tendance', ray: 'Demi-droite', horizontal: 'Ligne horizontale', vertical: 'Ligne verticale', rectangle: 'Rectangle', fibonacci: 'Retracement de Fibonacci', measure: 'Plage de prix', undo: 'Annuler', redo: 'Rétablir', hide: 'Masquer les dessins', show: 'Afficher les dessins', remove: 'Supprimer le dessin sélectionné', list: 'Dessins d’analyse', start: 'Déplacer le début', end: 'Déplacer la fin', first: 'Choisissez le point de départ. Les flèches et Entrée fonctionnent aussi.', second: 'Choisissez le point final. Échap pour annuler.', edit: 'Choisissez la nouvelle position. Échap pour annuler.', local: 'Conservés uniquement dans ce graphique, sans effet sur les transactions.', limit: 'Vous pouvez ajouter jusqu’à 100 dessins.', paused: 'Les outils seront disponibles après la lecture.' },
}
export function priceDrawingCopy(language: ClientLanguage) { return copy[language] }
